Change endpoint that sends configuration id
mild-blue/txmatching pull request #1005
Opened 2022-10-01 16:18 UTC by kristinagalik

Closes #725

2022-10-04 14:47 UTC, kristinagalik commented
@kubantjan nakoniec to neni to iste ako ist na `matchings/{config_id}` , mozem to pripadne vyriesit v separatnej issue (nech tu neni vela zmien) ak treba

riesi to aj otazku toho ze ked je nieco nedopocitatelne, atd.. proste raisuje error, nijak to neovplyvnuje funkcionalitu configurationu, meaning - "show top X matches for config with id Y" je korektne, taktiez sa vie stale ta konfiguracia oznacit za default, atd...

2022-10-05 07:45 UTC, kubantjan requested changes

2022-10-05 07:45 UTC, kubantjan commented on txmatching/web/api/configuration_api.py
> +@configuration_api.route('/find-config-id', methods=['POST'])
v zadani je posilat cely configuration objekt a ne jen configuration ID ne?

2022-10-15 13:59 UTC, kristinagalik commented
@kubantjan znovu som otvorila tento pr lebo riesil problem takym sposobom akym sme sa nakoniec dohodli, teda:
* vytvoreny novy endpoint ktory bud ulozi novy config a vrati id, alebo ho najde a vrati id
* matching endpoint uz nepotrebuje dostavat cely config parameters objekt ale len config id
* vytvorila som novu issue na matching/txmeventid/configid url https://github.com/mild-blue/txmatching/issues/1031

2022-10-24 12:37 UTC, kubantjan commented
@NotLubo  muzes na to kouknout :)

2022-10-24 12:41 UTC, kubantjan requested changes
minor comments, v zasade dobre!

2022-10-24 12:41 UTC, kubantjan commented on txmatching/web/api/configuration_api.py
> +@configuration_api.route('/find-config-id', methods=['POST'])
tohle ho bud najde nebo ho ulozi, tak by  to  v nazvu melo byt

2022-10-24 12:41 UTC, kubantjan commented on txmatching/web/api/configuration_api.py
> +                                   description='Returns config id if config exists, else creates new config.')
Rozvedl bych, podle me to ted dela toto :vrati config id kdyz existuje odpovidajici v databazi, jinak ho ulozi jako novy. V kazdem pripade vraci id configu. 

coz ten text nerika

2022-10-25 16:25 UTC, NotLubo requested changes

2022-10-25 16:25 UTC, NotLubo commented on txmatching/web/frontend/src/app/pages/home/home.component.ts
> +    this.configurationId = await this._configService.findConfigurationId(this.defaultTxmEvent.id, this.configuration);
Obalit do try catch a přidat error hlášku do logování + vypadá to že pro error kdy neco katastrofálne zlyhalo využívame `errorMessage` :)

2022-10-25 16:25 UTC, NotLubo commented on txmatching/web/frontend/src/app/pages/home/home.component.ts
> +      this._eventService.setConfigId(this.configurationId.configId);
Po přidání try catch bude tohle potřeba opodmínkovat

2022-10-25 16:25 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/matching/matching.service.ts
> +  constructor(private _http: HttpClient, protected _configService: ConfigurationService) {}
`protected _configService: ConfigurationService` se nikde nepouživá

2022-10-25 16:25 UTC, NotLubo commented on txmatching/web/frontend/src/app/pages/home/home.component.ts
> +        this.configurationId.configId,
Je trochu divné že z `configurationId` taháme `configId` :D

Možná to udelat takto
```
const response = await this._configService.findConfigurationId(this.defaultTxmEvent.id, this.configuration);
this.configurationId = response.configId
```

2022-10-25 16:25 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/matching/matching.service.ts
> +  constructor(private _http: HttpClient, protected _configService: ConfigurationService) {}
plus moc jsem nikde nevidel `protocted` v constructoru angularu. nemělo by to nic měnit ale zvykne se používat private. jestli si o tom něco našla pošli link :)

2022-10-30 18:53 UTC, kristinagalik commented on txmatching/web/frontend/src/app/services/matching/matching.service.ts
> +  constructor(private _http: HttpClient, protected _configService: ConfigurationService) {}
nenasla, to som si len skusala stuff a zabudla som to odstranit pardon

2022-10-31 08:40 UTC, kubantjan commented
Za me je to ok, az to schvali @NotLubo

2022-10-31 08:44 UTC, kubantjan requested changes
Za me ok, jeste @NotLubo  jen prosim jeste @kristinagalik  shrn jak to ted presne funuje

tzn. jaky endpoint FE vola kdyz:

1) prijdu na matchings stranku poprve
2) kdyz kliknu na set values v konfiguraci a je to nova konfigurace
3) kdyz kliknu na set values v konfiguraci a je to uz znama konfigurace

4) kdyz otevru patients stranku rovnou zadanim url
5) kdyz otevru patients stranku tim ze prekliknu z matchings stranky: jaky se tam pak pouziva config? 

jeste nejaky case te napada?

2022-11-01 19:58 UTC, kristinagalik commented
jaky endpoint FE vola kdyz:

1. prijdu na matchings stranku poprve 
    a. get txm event
    b. get default txm event
    c. get patients
    d. get (init) config (vrati objekt config parametrov)
    e. get config id (novy endpoint co najde id)
    f. calculate for confid

2. kdyz kliknu na set values v konfiguraci a je to nova konfigurace
    a. get config id (novy endpoint co najde id)
    b. calculate for confid

3. kdyz kliknu na set values v konfiguraci a je to uz znama konfigurace
    a. get config id (novy endpoint co najde id)
    b. calculate for confid

4. kdyz otevru patients stranku rovnou zadanim url
   a. get patients 
   config co sa pouziva je automaticky default

5. kdyz otevru patients stranku tim ze prekliknu z matchings stranky: jaky se tam pak pouziva config?
    ten co je aktualne nastaveny ako current - tzn nie nutne default

preco sa deje 4 a 5 - lebo je nejaka premenna v event service co sa vola `_configId` a ta sa vzdy meni ad hoc - teda ak reloadnem stranku tak ta premenna ostane prazdna a preto ked rovno otvorim patients strianku z url tak sa event service inicializuje s undefined `_configId`. ale ak ju zmenim v matchings a potom prejdem do pacientov tak sa berie updatnuta hodnota

2022-11-03 09:03 UTC, NotLubo requested changes
Super :) V `home.component.html` ešte uprav zobrazování tej `errorMessage`, aby vždy když tam něco je byla zobrazena ona a obsah skrytý. 
   ```
     <h3 *ngIf="!loading && errorMessage">
        <mat-icon class="error-icon">error</mat-icon>
        {{ errorMessage }}
    </h3>
    <app-item-list
      *ngIf="!loading && !errorMessage"
      [items]="matchings"
      [configuration]="configuration"
      [patients]="patients"
      [defaultTxmEvent]="defaultTxmEvent"
    ></app-item-list>
```

Původní error hlášku `No matchings were found...` bych přidal do té `calculate` funkce. Checkni jestli `!matchings.length` může nastat i mimo BE error a podle toho ji umísti do `finally` nebo `catch` :)

2022-11-03 09:14 UTC, kubantjan commented
> @kubantjan jaky endpoint FE vola kdyz:
> 
> 1. prijdu na matchings stranku poprve
>    a. get txm event
>    b. get default txm event
>    c. get patients
>    d. get (init) config (vrati objekt config parametrov)
>    e. get config id (novy endpoint co najde id)
>    f. calculate for confid
> 2. kdyz kliknu na set values v konfiguraci a je to nova konfigurace
>    a. get config id (novy endpoint co najde id)
>    b. calculate for confid
> 3. kdyz kliknu na set values v konfiguraci a je to uz znama konfigurace
>    a. get config id (novy endpoint co najde id)
>    b. calculate for confid
> 4. kdyz otevru patients stranku rovnou zadanim url
>    a. get patients
>    config co sa pouziva je automaticky default
> 5. kdyz otevru patients stranku tim ze prekliknu z matchings stranky: jaky se tam pak pouziva config?
>    ten co je aktualne nastaveny ako current - tzn nie nutne default
> 
> preco sa deje 4 a 5 - lebo je premenna v event service co sa vola `_configId` a ta sa vzdy meni ad hoc - teda ak reloadnem stranku tak ta premenna ostane prazdna a preto ked rovno otvorim patients strianku z url tak sa event service inicializuje s undefined `_configId`. ale ak ju zmenim v matchings a potom prejdem do pacientov tak sa berie updatnuta hodnota

ok diky za doplneni. co me k tomu mate je to volani v cisle 1. proc se vola
1) a. a pak b.? 

2) co presne dela d? proc je to potreba?

2022-11-04 18:28 UTC, kristinagalik commented
@kubantjan 

**v cisle 1. proc se vola**

1. **a. a pak b.?** toto som mohla asi viac opisat lebo ten endpoint sa vola sice get txm event - ale returnuje list of all txm events co teda znamena ze este stale fe nevie ktory presne chce ukazat a tak musi getnut este ten default (co ma napada ze to vracia cely txm event a neviem ci nedava vacsi zmysel aby get all events rovno malo v return objekte atribut ze `db_id_of_default_event`. lebo asi chceme endpoint ktory vracia default event ale je to asi zbytocne volat v tomto pripade)

2. **co presne dela d? proc je to potreba?** inicializuje aktualny config - teda najde default config ktory patri default eventu. a potom e sa musi diat preto, lebo je to sucast `calculate` funkcie ktora sa vola tak ako pri inicializacii tak pri kazdom novom calculate. 

3. **mrknes proc se vola c.? myslim ze volani toho endpointu trva fakt dlouho a mam pocit, ze je to jen potreba kvuli takovym tem vecem jako vek a vyska pacienta, myslim si to spravne?** no celkovo kvoli tym hla kodom a tomuto vsetkemu, ze aj ten matchings page je heavily dependent od infa v pacientoch, potrebujes info o nich do configu (na required patients napr), potrebujes ich parametre a HLAs, krv na compatibility - je len malo veci co z nich netreba a tipujem ze to dlho trva hlavne kvoli tym HLAs

2022-11-07 07:52 UTC, kubantjan commented
> @kubantjan
> 
> **v cisle 1. proc se vola**
> 
> 1. **a. a pak b.?** toto som mohla asi viac opisat lebo ten endpoint sa vola sice get txm event - ale returnuje list of all txm events co teda znamena ze este stale fe nevie ktory presne chce ukazat a tak musi getnut este ten default (co ma napada ze to vracia cely txm event a neviem ci nedava vacsi zmysel aby get all events rovno malo v return objekte atribut ze `db_id_of_default_event`. lebo asi chceme endpoint ktory vracia default event ale je to asi zbytocne volat v tomto pripade)
> 2. **co presne dela d? proc je to potreba?** inicializuje aktualny config - teda najde default config ktory patri default eventu. a potom "e" sa musi diat preto, lebo je to sucast `calculate` funkcie ktora sa vola tak ako pri inicializacii tak pri kazdom novom calculate.
> 3. **mrknes proc se vola c.? myslim ze volani toho endpointu trva fakt dlouho a mam pocit, ze je to jen potreba kvuli takovym tem vecem jako vek a vyska pacienta, myslim si to spravne?** no celkovo kvoli tym hla kodom a tomuto vsetkemu, ze aj ten matchings page je heavily dependent od infa v pacientoch, potrebujes info o nich do configu (na required patients napr), potrebujes ich parametre a HLAs, krv na compatibility - je len malo veci co z nich netreba a tipujem ze to dlho trva hlavne kvoli tym HLAs


ok, diky

k te 3. jsi si jista ze HLA kody? Ja mam prave pocit, ze ty dostaneme z matchings endpointu. V detailed matching with score, ze tyhle veci posleme.

2022-11-07 07:53 UTC, kubantjan submitted a review, later dismissed
Jen jeste otazka jedna, ale to je spis kvuli dalsim issues, da se mergnout

2022-11-07 10:23 UTC, kristinagalik commented
@kubantjan sorry mas pravdu, bere sa to z matchings endpointu

2022-11-07 12:18 UTC, NotLubo requested changes

2022-11-07 12:29 UTC, NotLubo approved these changes

2022-11-15 20:26 UTC, kubantjan approved these changes

2022-11-18 09:12 UTC, NotLubo approved these changes

2022-11-18 10:33 UTC, merged