files for kepsoft
mild-blue/txmatching pull request #1009
Opened 2022-10-04 15:08 UTC by kristinagalik

2022-10-04 15:12 UTC, kristinagalik commented on temporary/optimizer_api.py
> +        main(INPUT_PATH, OUTPUT_PATH)
toto je kristofova funkcia ktore spolieha na daky input a output path tak som sa mu radsej nebrblala v kode, a nechala som to takto ze z payloadu vytvorim files a potom ich zmazem

2022-10-04 16:39 UTC, kubantjan requested changes
LGTM, klidne bych tam jeste hodil ten kod, ktery to zparsuje ty jsony na dataclassy, aspon se tim testne ze maji ty data spravny format a casem bude davat smysl stejne ten kristofuv kod prepsat tak, ze dataclassy vyuzivat bude.

2022-10-07 06:27 UTC, kubantjan commented
approve za me teda ok, pripadne se jeste ptej

2022-10-09 09:27 UTC, kristinagalik commented
@kubantjan este update nech to je threadsafe, je to takto ok? ci mam robit nieco jak meno_filu_timestamp

2022-10-11 09:58 UTC, kubantjan approved these changes

2022-10-11 09:58 UTC, kubantjan commented
dava smysl

2022-10-11 16:00 UTC, closed without merging