refactor: retrieve config id separately from pairing
mild-blue/txmatching pull request #1013
Opened 2022-10-05 21:11 UTC by kristinagalik

2022-10-07 08:30 UTC, kubantjan commented
Porad nechapu
Pridavas novy endpoint a pritom v zadani nic o novem endpointu neni

Chceme z compute matchings endpointu dát config id pryč a posílat ho místo toho v configuration endpointu. Configuration endpointy teď mohou kromě parametrů vracet i celý objekt Configuration, ve kterém je i ID.

2022-10-07 08:30 UTC, kubantjan requested changes

2022-10-07 08:30 UTC, kubantjan commented on txmatching/database/services/config_service.py
> +        raise ValueError(f'Configuration not found for db id {configuration_db_id}.')
tady teda nevracime default ale raisujeme error, takze ten koment uz neplati?

2022-10-09 18:46 UTC, kristinagalik commented
@kubantjan problem je ten ze ziaden endpoint nevracia id, lebo configuration sa sklada z id, txm event id, a config parameters. endpoint get config vracia len tie parametere, a nie id.

co sa na fe deje je:
zoberu sa hodnoty z config formu a urobi sa objekt. ten objekt sa potom passne endpointu na pocitanie matchingov. ten mimo ineho vytvori novy config v databaze, a na fe posle spat aj ten novy config id, a fe podla neho nastavi nejaky globalny config id na novy. 
co to znamena je, ze nemozeme vediet config id pred tym nez sa to dopocita, *unless* vytvorim novy endpoint ktory config vytvori (ak este nie je) a vrati nove id (alebo ak uz existuje tak ho len najde). cize config_id ako parameter uz v matching endpointe nieje, ale nejak nerozumiem ako inak mam zistit config id bez toho aby som bud dost prepisala jeden endpoint a mozno tam po ceste budu dalsie zadrhle, alebo urobit rovno novy.

2022-10-11 10:40 UTC, kubantjan commented
@kristinagalik  myslenka byla prave ze ten config co vraci jen ty parametry bude nove vracet i id.

2022-10-11 10:41 UTC, kubantjan requested changes
V tom poslednim komentari presne pises to co je v zadani issue, ted se v tom endpointu config id nevraci a tenhle task je o tom ho zacit vracet podle me

2022-10-15 13:47 UTC, closed without merging