Rewrite all_circuits to our custom function to find directly only cycles up to certain length
mild-blue/txmatching pull request #1039
Opened 2022-10-19 19:18 UTC by kristinagalik

Closes #1038

2022-10-20 21:57 UTC, kubantjan requested changes
par readability comments :). Ale vim ze ti jeste chybi 
- sequences
- testy

2022-10-20 21:57 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +    ndds = {donor_id for donor_id in original_donor_idx_to_recipient_idx.keys() if
ndds prosim ne, poradne slovo:)

2022-10-20 21:57 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +            _dfs_cycles(node, [], all_circuits, max_cycle_length, donor_to_compatible_donor_graph)
dfs_cycles taky zmenit

2022-10-20 21:57 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
>              len(circuit) <= config_parameters.max_cycle_length
len circuit uz nemusis checkovat ne?

2022-10-23 22:10 UTC, kristinagalik commented
mal si pravdu, dost hlupo sa checkuju tie mensie private funckie lebo kym sa k nim dostane proces tak sa vytvori vela objektov po ceste co by som si v testoch zas musela robit ale snad to je dobre ak to prechadza uz existujuce testy

2022-10-24 07:27 UTC, kubantjan requested changes
Ten test solver robust bych nemazal, ale spis zkontroloval, ze to uspesne projde a spocte se ne? Pokud se to spocte rychle :)

2022-10-24 07:42 UTC, kubantjan requested changes
Dobre! 
2 veci:
1) par komentaru na zlepseni citelnosti kodu a mozna male zrychleni (to nevim) akorat.
2) Ten test solver robust bych nemazal, ale spis zkontroloval, ze to uspesne projde a spocte se ne? Pokud se to spocte rychle :)

2022-10-24 07:42 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +    ndd_dict = nx.get_node_attributes(donor_to_compatible_donor_graph, 'ndd')
nevim co je ndd_dict prosim lepsi nazev

2022-10-24 07:42 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +    if len(set(maybe_cycle)) != len(maybe_cycle):
tohle bych spis prepsal jako is node in maybe cycle. to je lepsi. rychlejsi a citelnejsi. 

a pak az volat maybe_cycle.append(node)

2022-10-24 07:42 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +    if len(set(maybe_sequence)) == len(maybe_sequence):
zase lepsi pres append se ptat jeslit je node in sequence

2022-10-24 07:42 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +def country_count_in_path(path: List[int], donors: List[Donor]) -> int:
Path je list[int] akorat typealias,  tak pro co tady prepisujes?

2022-10-24 07:42 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +        if node < maybe_cycle[0]:
sem bych dal komentar, ze tohle zajistuje ze nebudou duplicity.

2022-10-24 10:40 UTC, kristinagalik commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +def country_count_in_path(path: List[int], donors: List[Donor]) -> int:
path je tuple[int] a na tuples sa to meni az napr v `find_all_cycles` v riadkoch
```
circuit_with_end = tuple(circuit + [circuit[0]])
circuits_to_return.append(circuit_with_end)
```
cize ta funkcia ma return type `-> List[Path]` ale z funkcie `_find_cycles_recursive` vychadza este len list[int] ktory sa potom passuje do `_circuit_valid` ktory kontroluje presne veci ako `country_count_in_path`

mam to tak nechat aj tak? alebo mam robit rovno z toho tuples? co je najlepsie riesenie?

2022-10-24 10:46 UTC, kristinagalik commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +def country_count_in_path(path: List[int], donors: List[Donor]) -> int:
mam aj squashnut commity asi ci?

2022-10-24 12:23 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +def country_count_in_path(path: List[int], donors: List[Donor]) -> int:
no proste obecne kdyz se neco nazvyva stejne (tzn path) tak by to mela byt stejna vec. Ne aby jednou to byl list, jindy tuple jindy neco jineho.

jako uvnitr v ty recursive fci mozna dava smysl kdyz mas ten prubezne vytvareny cyklus tak jeste nez je hotov aby to byl list, ale pak uz mi dava smysl aby to byl typ PATH a stejne tak je nestastny aby tam byl cycklus jednou s poslednim prvkem a jednou bez nej a jmenoval se stejne. To by chtelo mit jasne vymezeny.. 

Za me tak, ze cyklus uz rovnou ma i ten prvni prvek stejny jak posledni..

2022-10-24 12:31 UTC, kubantjan requested changes
jeste male poznamky

2022-10-24 12:31 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/compatibility_graph_utils.py
> +                           graph: nx.DiGraph, max_cycles_in_all_solutions_solver: int):
tady ti to intellij nepodtrhava? Me jo mas tu jedno graph: Digraph a jednou graph: Graph
![Screenshot from 2022-10-24 14-31-04](https://user-images.githubusercontent.com/24394374/197525992-038dbaa9-4192-403b-9b49-d6acad979659.png)

2022-10-24 13:39 UTC, kubantjan approved these changes

2022-10-24 13:39 UTC, merged