Optimization: replaced dacite.to_dict with my solution
mild-blue/txmatching pull request #1046
Opened 2022-10-25 12:52 UTC by krllstdn

solves #1045

2022-10-25 13:03 UTC, krllstdn commented
Before optimisation
![image](https://user-images.githubusercontent.com/50211831/197780016-722b76b9-a7ff-4363-9497-af9c840f02b2.png)
After optimisation
![image](https://user-images.githubusercontent.com/50211831/197780330-bce9458d-bec0-41f4-9127-08d93a52a1e0.png)

2022-10-26 07:28 UTC, kubantjan requested changes

2022-10-26 07:28 UTC, kubantjan commented on tests/utils/test_dict_to_dataclass.py
> +        self.assertGreater(dacite_time, dataclass_time)
tady bych treba doplnil, ze to ma byt 1.5 nasobek nebo tak neco

2022-10-26 07:28 UTC, kubantjan commented on tests/utils/test_dict_to_dataclass.py
> +        self.assertGreater(dacite_time, dataclass_time)
a zaroven porovnat, ze ty dva vznikle objekt jsou stejne

2022-10-26 09:45 UTC, kubantjan requested changes
Posledni koment

2022-10-26 09:45 UTC, kubantjan commented on tests/utils/test_dict_to_dataclass.py
> +        antibodies_dto_list_comprehension = HLAAntibodiesDTO([
Tady dava smysl vyuzit fu fci co mame v kodu rovnou a ne tady psat ten kod znovu.

2022-10-26 12:53 UTC, kubantjan requested changes
Nazev testu by mel odpovidat tomu, co testuje.

2022-10-26 12:53 UTC, kubantjan commented on tests/utils/test_dict_to_dataclass.py
> +    def test_dict_to_dataclass(self):
test bychom meli nazvat podle toho co testuje.

test_direct_conversion_to_dataclass_works_and_is_faster_than_dacite

2022-10-26 16:30 UTC, kubantjan approved these changes

2022-10-26 17:33 UTC, kubantjan approved these changes

2022-10-26 17:34 UTC, merged