Optimized dataclass creation
mild-blue/txmatching pull request #1051
Opened 2022-10-27 14:35 UTC by krllstdn

closes #1050

2022-10-27 14:47 UTC, krllstdn commented
![image](https://user-images.githubusercontent.com/50211831/198320954-8fb42d8d-bf56-47b1-bf67-e880211b29be.png)
trochu lip

2022-10-27 16:33 UTC, krllstdn commented on tests/database/services/test_patient_service.py
> +        # with self.assertRaises(dacite.exceptions.MissingValueError):
toto mi nici testy. kvuli tomu ze my uz tam nepouzivame dacite jsem toto zakomentoval. Rekny je-li toto v poradku. Pokud ano, tak to zmazu.

2022-10-27 17:09 UTC, kubantjan commented on tests/database/services/test_patient_service.py
> +        # with self.assertRaises(dacite.exceptions.MissingValueError):
No mělo by to být nahrazeno asi jiným errrorem ne?

2022-10-27 17:16 UTC, krllstdn commented on tests/database/services/test_patient_service.py
> +        # with self.assertRaises(dacite.exceptions.MissingValueError):
jasne, jdu hodit tam novy error

2022-10-31 08:36 UTC, kubantjan commented
> ![image](https://user-images.githubusercontent.com/50211831/198320954-8fb42d8d-bf56-47b1-bf67-e880211b29be.png) trochu lip

tady vzdy potrebuju videt predtim a potom, takhle trochu lip samo o sobe neda dobrou predstavu co se stalo :)

2022-10-31 08:39 UTC, kubantjan requested changes

2022-10-31 08:39 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +        raise ValueError("Recipient model has no antibodies")
to je naprosto normalni stav, ze recipient nema zadny protilatky!

2022-10-31 08:39 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +        raise ValueError("Patient has no hla typing")
tadytohle ze nema typing je reseny jinde, tady bys raisovat error nemel, to ani ten dacite nedelall

2022-10-31 08:39 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +        # hla_typing_raw = dacite.from_dict(data_class=HLATypingRawDTO, data=patient_model.hla_typing_raw)
tady zakomentovani asi nepatri

2022-10-31 09:41 UTC, krllstdn commented on txmatching/database/services/patient_service.py
> +        raise ValueError("Patient has no hla typing")
ale kdyz toto davam pryc pada ten test, o kterem jsem psal pred tim

2022-10-31 11:02 UTC, krllstdn commented on tests/database/services/test_patient_service.py
> +        with self.assertRaises(KeyError):
To je mozna trochu blbi, ale tam hazi KeyError kvuli tomu ze jsme tam v testu udelali prazdny dict. Ze za potreba to nejak lip zpracovat a pridat do `_get_hla_typing_dto_from_patient_model` treba value error s popsanim co se tam deje (ze nemame zparsovane hla) nebo to takhle staci?

2022-10-31 12:44 UTC, kubantjan requested changes

2022-10-31 12:44 UTC, kubantjan commented on tests/database/services/test_patient_service.py
> +        with self.assertRaises(KeyError):
jo asi bude fajn, kdyz chytnes ten key error a vratis nejaky error ktery rekne, ze je format antibodies nevalidni a ze se ma pustit recompute, ktery by to mel spravit.

2022-11-01 15:57 UTC, kubantjan approved these changes

2022-11-03 08:42 UTC, merged