Unify functions raising warning about number of antiboides and them being in high res above cutoff and function is type a
mild-blue/txmatching pull request #1052
Opened 2022-10-31 08:28 UTC by abragtim

Closes #1049

2022-11-04 19:37 UTC, abragtim commented on txmatching/patients/hla_functions.py
> +def parse_if_high_res_antibodies_in_sufficient_amount_and_some_below_cutoff(
@kubantjan , nejsem si jistý s použitím téhle funkce. Vychází mi pak hezky s ní dál pracovat v is_type_a a a v rozhodování o almost valid při parsingu, ale technicky dělám v ní několik věcí najednou. Je to tady v pořádku, nebo pořád je lépe rozdělit tu funkci na dvě a pak je společně používat v jiných částech kódu?

2022-11-07 08:27 UTC, kubantjan requested changes
hlavni poznamka je ze chceme pridat do ty unifikovany logiky i to poznavani jestli jsou all antibodies high res, ted v jednom miste mame i tu extra vec s if antibody.code.high_res is None and antibody.code.split not in MULTIPLE_SERO_CODES_LIS a ve druhem ne, ale ma to byt v obou.

2022-11-07 08:27 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    if not parse_if_high_res_antibodies_in_sufficient_amount_and_some_below_cutoff(
misto tadytech radku se da rovnou psat return parse_if... coz je vyrazne lepe citelny

2022-11-07 08:27 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        total_antibodies += antibodies_per_group.hla_antibody_list
total antibodies bylo predtim cislo, ted je to list, total antibodies mi zni spis jako to cislo prave prejmenoval bych tu promennou.

2022-11-07 08:27 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +def parse_if_high_res_antibodies_in_sufficient_amount_and_some_below_cutoff(
neni to uplne krasny no, ale asi ok.

2022-11-08 10:49 UTC, kubantjan requested changes
navrh na par prejmenovani a uprav logiky, jinak fajn

2022-11-08 10:49 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +def parse_if_high_res_antibodies_in_sufficient_amount_and_some_below_cutoff(
tady nic neparsujes, jen analyzujes jestli antibodies jsou vhodny pro typ a a pripadne vracis issues, proc ne.

takze bych to prejmenoval

analyze_if_high_res_antibodies_are_type_a nebo tak neco

2022-11-08 10:49 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +class IsSuccessfulParsingIssue:
zas jine jmeno bych dal.

HighResAntibodiesAnalysis

2022-11-08 10:49 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +    is_successful: bool
is_type_a_compliant

2022-11-08 10:49 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +    return IsSuccessfulParsingIssue(True,
tady bych nevracel success, ale None

2022-11-08 10:49 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +    return IsSuccessfulParsingIssue(True,
a pak mel maybe_parsing_issue)

2022-11-08 11:33 UTC, kubantjan commented
> > 
> 
> @kubantjan Podle mě, v obou místech teď máme i tu podmínku s MULTIPLE_SERO_CODES_LIST (je ve funkci is_all_antibodies_in_high_res, kterou používáme v obou místech). Nebo musím vrátit i tu TODO poznámku v místech, kde používám is_all_antibodies_in_high_res?

hmm asi jsem se prehlidl, ted to vypada ok, tak jak to je. Takto to muzes nechat.

2022-11-11 07:08 UTC, kubantjan approved these changes

2022-11-11 08:19 UTC, merged