TAke conversion to split also from assumed serology column in dna_hla_ser table
mild-blue/txmatching pull request #1064
Opened 2022-11-04 17:45 UTC by abragtim

Closes #1048

2022-11-16 22:00 UTC, kristinagalik submitted a review, later dismissed
treba este pridat migracie inak to nebude ukladat do db

2022-11-17 08:56 UTC, abragtim commented on txmatching/database/db_migrations/0035.add-new-parsing-issue-detail.sql
> +ALTER TYPE parsing_issue_detail ADD VALUE 'HIGH_RES_WITH_ASSUMED_SPLIT_CODE'
@kristinagalik , správně chápu, že je potřeba udělat migraci jen pro type parsing_issue_detail?

2022-11-17 17:59 UTC, kristinagalik commented on txmatching/database/db_migrations/0035.add-new-parsing-issue-detail.sql
> +ALTER TYPE parsing_issue_detail ADD VALUE 'HIGH_RES_WITH_ASSUMED_SPLIT_CODE'
hmm asi by som menila enum rovno a nie column? uz len pre konzistenciu (aj ked toto by asi tiez malo fungovat, ale wild guess ze to ze pridas type do columnu nemeni enum a teda keby sa prida do db dalsi column co ma pouzivat nejaky enum tak mozno nebude moct nadobudnut tuto value lebo si to zmenil len pre `parsing_issue_detail` - no idea ci to takto aj realne funguje ale)

2022-11-18 11:22 UTC, abragtim commented on txmatching/database/db_migrations/0035.add-new-parsing-issue-detail.sql
> +ALTER TYPE parsing_issue_detail ADD VALUE 'HIGH_RES_WITH_ASSUMED_SPLIT_CODE'
@kristinagalik 
<img width="463" alt="Snímek obrazovky 2022-11-18 v 12 17 36" src="https://user-images.githubusercontent.com/25512296/202693404-b4d3dd95-0e6e-4daf-80f2-b46225438cac.png">
IDE mi ukazuje (jako public -> object types), že se do toho enum přidává to value. O tom mluvíš, že to může nefungovat nebo se to může nepřidávat do něčeho jiného?

2022-11-18 12:46 UTC, kristinagalik commented on txmatching/database/db_migrations/0035.add-new-parsing-issue-detail.sql
> +ALTER TYPE parsing_issue_detail ADD VALUE 'HIGH_RES_WITH_ASSUMED_SPLIT_CODE'
![image](https://user-images.githubusercontent.com/56656359/202707563-78939e38-e3cc-4c61-9bbd-4d85c378d657.png)
toto je stara verzia toho ^ a co to znamena vlastne teraz je ze: column `parsing_issue_detail` has type enum `PARSING_ISSUE_DETAIL` lebo:
![image](https://user-images.githubusercontent.com/56656359/202707771-08a3b9e8-358a-4052-b20b-2fc968173ef0.png)

a doteraz sme teda v migraciach menili enum, priklad:
![image](https://user-images.githubusercontent.com/56656359/202707948-b3a5ab31-7957-4122-92cb-05dfa38ff25c.png)

2022-11-18 13:15 UTC, abragtim commented on txmatching/database/db_migrations/0035.add-new-parsing-issue-detail.sql
> +ALTER TYPE parsing_issue_detail ADD VALUE 'HIGH_RES_WITH_ASSUMED_SPLIT_CODE'
@kristinagalik , Jo. To sedí. Tak já taky měním jenom enum přes ALTER TYPE <type name> ADD VALUE '<new detail>';
(ALTER TYPE parsing_issue_detail ADD VALUE 'HIGH_RES_WITH_ASSUMED_SPLIT_CODE') 1:1 jako to děláme i s MFI_PROBLEM a OTHER_PROBLEM. Takže je to ok? Neměním column v parsing_issue_detail. 
Možná je matoucí, protože mají stejný název a napsal jsem to s lowercase (Ooops)

2022-11-21 08:14 UTC, kubantjan requested changes
Tak jeste to ocividne bylo z me strany spatne popsano a jsou tam veci o kterych jsem nevedel:
1) nevedel jsem ze jsou tam pripady s lomitkem.
o co mi tady slo je aby se spravne zpracovavaly ty veci co jsou ted v PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS

kde typicky to vypada nejak takto:

DQB1*;03:19:01:01;;;3;
DQB1*;03:19:02;;;3;
DQB1*;03:19:03;;;3;
DQB1*;03:19:04;;;3;

a to by se melo zpracovat na 3 s  tim warningem. 

pripad kdy je lomitko je zajimavy. pripady jako tento:

hmm tohle jsem ani netusil ze tam je to lomitko nekdy v te assumed serology.

o co mi tady slo je aby se spravne zpracovavaly ty veci co jsou ted v 

PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS

kde typicky to vypada nejak takto:

DQB1*;03:19:01:01;;;3;
DQB1*;03:19:01:02Q;;;0/3;
DQB1*;03:19:02;;;3;
DQB1*;03:19:03;;;3;
DQB1*;03:19:04;;;3;

bych zpracoval se stejnym warningem. 

tzn ty kde je lomitko 0/neco (protoze 0 je v podstate neco jako nic)

pripady kdy je nekde v assumed realne vic jak jedna moznost bych spis ted neresil. 

vyzkousel bych jestli to funguje na vsech tech vecech z toho hla_dna_ser_exeptions

2022-11-21 09:14 UTC, abragtim commented
> Tak jeste to ocividne bylo z me strany spatne popsano a jsou tam veci o kterych jsem nevedel:
> 
> 1. nevedel jsem ze jsou tam pripady s lomitkem.
>    o co mi tady slo je aby se spravne zpracovavaly ty veci co jsou ted v PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS
> 
> kde typicky to vypada nejak takto:
> 
> DQB1*;03:19:01:01;;;3; DQB1*;03:19:02;;;3; DQB1*;03:19:03;;;3; DQB1*;03:19:04;;;3;
> 
> a to by se melo zpracovat na 3 s tim warningem.
> 
> pripad kdy je lomitko je zajimavy. pripady jako tento:
> 
> hmm tohle jsem ani netusil ze tam je to lomitko nekdy v te assumed serology.
> 
> o co mi tady slo je aby se spravne zpracovavaly ty veci co jsou ted v
> 
> PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS
> 
> kde typicky to vypada nejak takto:
> 
> DQB1*;03:19:01:01;;;3; DQB1*;03:19:01:02Q;;;0/3; DQB1*;03:19:02;;;3; DQB1*;03:19:03;;;3; DQB1*;03:19:04;;;3;
> 
> bych zpracoval se stejnym warningem.
> 
> tzn ty kde je lomitko 0/neco (protoze 0 je v podstate neco jako nic)
> 
> pripady kdy je nekde v assumed realne vic jak jedna moznost bych spis ted neresil.
> 
> vyzkousel bych jestli to funguje na vsech tech vecech z toho hla_dna_ser_exeptions

@kubantjan ,
Tj. musím zkontrolovat, co je v PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS zůstalo validní (například, když už máme nějaký split code jako assumed a je zároveň v exceptions, tak v exceptions už ho mít nechceme. Ale když například máme DQB1*;03:19 z assumed jako DQ3 a z exceptions DQ7, tak prioritu má exceptions a zůstává ten kód v exceptions). Správně to chápu?
A lomítko v assumed řeším jen v případě 0/něco?

2022-11-21 11:09 UTC, abragtim commented
Jenom jedna kolize je v PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS pro DQB1*;03:19<br>
PARSE_HIGH_RES_HLA_CODE_EXCEPTIONS: DQ7<br>
rel_dna_ser.txt : DQ3.

2022-11-21 14:54 UTC, kubantjan commented
> DQB1*;03:19

tak uz jsme to dokonce historicky resili, pro zajimavost:

Pro DQB1*03:19 je strukturně nejbližší DQB1*03:01, což je serologická DQ7. DQ3 je zbytečně široká, ačkoliv je možné, že některé protilátky, které by byly proti DQ7 by nemuseli být konkrétně proti této alele.

takze je to spravne v kodu tak jak to je :)

2022-11-21 15:02 UTC, kubantjan commented on txmatching/utils/hla_system/rel_dna_ser_exceptions.py
> +    'DQB1*03:19': 'DQ7',  # TODO: according to rel_dna_ser.txt should be DQ3
tady bych prepsal anglicky ten text co napsal matej nam v mejlu. co jsem ti poslal v komentari

2022-11-21 15:04 UTC, kubantjan commented on txmatching/utils/hla_system/rel_dna_ser_parsing.py
> +            .replace('0/', '', regex=True)
tady bych to spis udelal tak, ze splitnes to na list pomoci /, pak zahodis 0 z toho listu a pak se podivas kolik tam tech prvku je. Tim to bude jisty, ze kdyz nahodou 0 nebude jako prvni furt to bude fungovat a bude to srozumitelnejsi co se deje

2022-11-23 11:52 UTC, kubantjan requested changes
uz se blizime :)

2022-11-23 11:52 UTC, kubantjan commented on tests/utils/hla_system/test_code_parser.py
> +    'A*68:06': (HLACode('A*68:06', 'A68', 'A28'), ParsingIssueDetail.HIGH_RES_WITH_ASSUMED_SPLIT_CODE),
timto nemame zadny, co by mely unknow transforamtion from high res v testech, tak bych nejaky pridal

2022-11-29 07:53 UTC, kubantjan commented
jeste bych chtel aby @kristinagalik nebo @krllstdn  vyzkouseli, ze na FE fakt tohle novy issue uvidi a pujde jim ho resolvnout, pokud ano, tak done a hotovo

2022-11-29 07:54 UTC, kubantjan requested changes
jen chci otestovat na FE od @kristinagalik  nebo @krllstdn pak approve

2022-12-01 20:54 UTC, krllstdn commented
yep, je to issue videt a da se ho resolvnout. funguje jak musi. ode me approve

2022-12-01 20:54 UTC, krllstdn approved these changes

2022-12-05 14:04 UTC, kubantjan approved these changes

2022-12-05 14:11 UTC, merged