Update conda.yml and cleanup README
mild-blue/txmatching pull request #1074
Opened 2022-11-15 05:56 UTC by krllstdn

Closes #1067

2022-11-17 19:02 UTC, abragtim commented
<h3>Notes</h3>
<img width="693" alt="Snímek obrazovky 2022-11-17 v 19 58 57" src="https://user-images.githubusercontent.com/25512296/202534607-d532a133-7770-409f-bdc7-c4268c623534.png">
Pro python 3.11 je nutně přejít na psycopg 2.9.5

2022-11-18 19:19 UTC, abragtim commented
@kubantjan , 
Obnovil jsem všechny možné knihovny. Jenom zbývá nam udělat update do python 3.11. Našel jsem web, který dává aktuální informaci o tom které knihovny explicitně fungují s novou verzi python. A 79% ještě neudělali update spojený s python 3.11 (jsou tam i hodně z těch, které používáme i my: flask, pandas, jinja2 atd.) https://pyreadiness.org/3.11/.

Ale spouštěl jsem a, podle mě, python 3.11 na první pohled problémy nedělá. Jenom bude potřeba změnit kód tak ve třech místech, protože .format() pro Enum s mixed-in types funguje trochu jinak (viz note 2 here https://github.com/mild-blue/txmatching/pull/1074#issuecomment-1319074695). Tak co si o tom myslíš, jestli už chceme přejít na python 3.11 nebo ještě pár měsíců počkáme, když developery knihoven zveřejní otestované verze s novém pythonem? + Nejspíš do konce roku už bude python 3.11.1 s bugfixes.

2022-11-20 18:48 UTC, krllstdn commented
Asi funguje (u me se lokalne rozbil wkhtmltopdf), ale testy nepadaji, takze snad ok

2022-11-21 10:30 UTC, kubantjan commented
s 3.11. bych pockal jeste

2022-11-21 10:33 UTC, kubantjan requested changes
jeste update pythonu

2022-11-21 13:23 UTC, kubantjan requested changes

2022-11-21 13:23 UTC, kubantjan commented on txmatching/utils/country_enum.py
> +        return f'{self.name}'
nez overridovat format bych spis v tech mistech kde se tohle vyuziva pouzil .name

2022-11-21 13:23 UTC, kubantjan commented on txmatching/utils/country_enum.py
> +        return f'{self.name}'
chceme zachovat to, jak to ted novej python zamysli a ne se drzet furt toho jak se choval 3.10.

2022-11-21 13:27 UTC, kubantjan commented
hmm tak jeste jsem poradneji ted prosel a promyslel ten python 3.11. a radeji bych byl opatrny. prosim udelejme to takto:
- vytvor prosim nove issue s python 3.11. k tomu rovnou dej tyhle upravy kolem pythonu 3.11. (tzn ten format) ale zatim to nech a nemerguj
- z tohohle pr nakonec prosim ten python odeber

2022-11-21 14:47 UTC, kubantjan approved these changes

2022-11-21 14:48 UTC, merged