Make optimiser module consistent with the Hungarian one
mild-blue/txmatching pull request #1081
Opened 2022-11-21 20:32 UTC by krllstdn

2022-11-21 20:33 UTC, krllstdn commented
I've pushed only to run tests. The PR is still a work in progress.

2022-11-24 18:00 UTC, krllstdn commented on txmatching/scorers/compatibility_graph.py
> +CompatibilityGraph = Dict[Tuple[int, int], Dict[str, int]]
nevim jestli se tak da delat, pokud ne, tak napiste prosim. na internetu jsem nic relevantniho nenasel a to nepada takze jsem predpokladal ze je fajn

2022-11-24 18:04 UTC, krllstdn commented on txmatching/database/services/report_service.py
> +        percentage = 100 * (score['score'] if isinstance(score, dict) else score) / max_score
to muze byt blbost, ale nekdy se tam stavalo ze tam byl int zamesto dict jak to musi byt. Proto jsem to pridal jsem. Navic nemuzu to lokalne otestovat kvuli problemu v lokalnim environmentu, ktery neumoznuje testovani reportu. Proto prosim o overeni

2022-11-24 18:06 UTC, krllstdn commented
@kubantjan nemuzu lokalne vygenerovat ten swagger, muzes prosim ho vygenerovat?

2022-11-29 07:57 UTC, kubantjan commented
@krllstdn  issues jdou podle me za tebou ne za swaggerem.

2022-11-29 07:58 UTC, kubantjan commented on txmatching/scorers/compatibility_graph.py
> +CompatibilityGraph = Dict[Tuple[int, int], Dict[str, int]]
jop, tohle by melo byt ok

2022-11-29 08:00 UTC, kubantjan commented on txmatching/database/services/report_service.py
> +        percentage = 100 * (score['score'] if isinstance(score, dict) else score) / max_score
muzes preci otestovat primo tuhle fci co tu mas (score['score'] if isinstance(score, dict) else score) tohle nekde si lokalne, jestli to funguje. prijde mi ze by melo, ale rozhodne pak mas v ty fci spatnej typ score: Optional[float] to preci neni pravda ted.

2022-11-29 08:00 UTC, kubantjan requested changes
viz komenty

2022-12-06 17:13 UTC, kristinagalik requested changes
len par drobnosti :)

2022-12-06 17:13 UTC, kristinagalik commented on txmatching/scorers/compatibility_graph.py
> +OptimizerCompatibilityGraph = List[Dict[str, any]]
neni toto list of CompGraphEntries?

2022-12-08 10:37 UTC, krllstdn commented on tests/web/test_optimizer_api.py
> +        self.assertEqual(len(compatibility_graph), len(res.json['compatibility_graph']))
trosku dementni uprava, souhlasim, ale nevim jak jinak lze jednoduse porovnat list dataclassu a list dictu (api zrejme vraci dict)

2022-12-13 14:56 UTC, kristinagalik submitted a review, later dismissed

2022-12-14 15:06 UTC, kubantjan requested changes
potrebuju vyjasnit to issue zadani

2022-12-15 15:26 UTC, kubantjan requested changes
Prvni komentare

2022-12-15 15:26 UTC, kubantjan commented on tests/database/services/test_file_upload.py
> +                    calculated_score = calculated_scores[(donor_enum, recipient_enum)]["score"]
proc se tady pridava score? to prece vubec nikde v zadani toho issue neni. Tomu nerozumim.

2022-12-15 19:16 UTC, kristinagalik commented on tests/database/services/test_file_upload.py
> +                    calculated_score = calculated_scores[(donor_enum, recipient_enum)]["score"]
myslim ze je to kvoli tomu ze `CompatibilityGraph = Dict[Tuple[int, int], Dict[str, int]]`... tym ze sme to chceli mat konzistentne s madarskym a oni to reprezentuju takto ^ (key je donor recipient id pair, a value je dict of weights) plus je to nice v tom ze potom ak sa naozaj bude napr prepisovat ilp solver na lexicographic alebo sa bude pridavat novy alebo co, tak sa toto bude lahko dat vyuzit...

mozno ale dobry point ze by to nemuselo byt `"score"` ale niekde by to bolo zadefinovane ako premenna co sa potom vsade pouzije na styl `SCORE="score"` lebo z tohto neni na prvu jasne ze to je (tipujem) `hla_compatibility_score` pre cloveka co toto vidi prvy krat

2022-12-15 22:30 UTC, krllstdn commented on tests/database/services/test_file_upload.py
> +                    calculated_score = calculated_scores[(donor_enum, recipient_enum)]["score"]
@kristinagalik dekuji za vysvetleni. Ted jsem si taky vsimnul, ze to neni tak uplne ihned srozumitelny. Takze prejmenovat na `hla_compatibility_score`?

2022-12-16 08:07 UTC, kubantjan commented on tests/database/services/test_file_upload.py
> +                    calculated_score = calculated_scores[(donor_enum, recipient_enum)]["score"]
@krllstdn jop to dava smysl

2022-12-16 08:11 UTC, kubantjan requested changes

2022-12-16 08:11 UTC, kubantjan commented on tests/web/test_optimizer_api.py
> +        self.assertEqual(len(compatibility_graph), len(res.json['compatibility_graph']))
Podivej se poradne na nazev toho testu a co ti vsechno dava smysl testovat a to testuj. Obecne si myslim ze len fakt neni test moc uzitecnej. 

pripadne muzes treba porovnavat konkretni prvky nebo napis fci co to nejak pretransformuje, na to druhe

2023-01-03 13:32 UTC, kristinagalik reviewed
len jedna otazka, inak imo ok :)

nebolo by mat dobre niekde nejaku premennu na styl HLA_SCORE = 'hla_compatibility_score' aby sa potom kod lahsie v buducnosti upravoval? ale je to len myslienka, ak myslis ze takto to je ok tak fajn

2023-01-04 09:52 UTC, krllstdn commented
@kristinagalik good point. Pridal jsem tam tu konstantu

2023-01-04 18:37 UTC, kristinagalik approved these changes

2023-01-11 22:18 UTC, kubantjan requested changes
Jak je to s migraci? Nerozbije se nahodou migrace? Ze historicky ukladame ten compatibility graf jinak, nebo je tohle poreseny? 

na to by bylo jeste fajn mrknout. pokud jsi to neresil a vyzkouset to pak.

Tzn vytvorit txm z mastra, nahrat tam nejaky paicenta aby to proste fungovalo (staci to non empty db) a pak checkout nove verze a jeji spusteni a kontrola ze vse beha.

2023-01-12 11:04 UTC, krllstdn commented
@kubantjan vyzkousel jsem,  beha na obou solverech na databazi s mastru bez problemu

2023-01-13 08:53 UTC, kubantjan commented
no ok, a jak to teda ted funguje? Uklada se do databaze furt stejny objekt nebo jiny? @krllstdn

2023-01-13 10:22 UTC, krllstdn commented
@kubantjan Uklada se ten samy object (dict: list of ints). 
Chces ten seznam zmenit na dict, kde bude primo napsano ze, to treti cislo je 'hla_compatibility_score', nebo je to takhle v pohode?

2023-01-16 11:33 UTC, kubantjan requested changes
ok, tak to nechcme v db tak jak to je, ale jeste jsem ti dal nejaky komentar

2023-01-16 11:33 UTC, kubantjan commented on txmatching/database/services/scorer_service.py
> +    return {"compatibility_graph_dto": [[int(pair[0]), int(pair[1]), weighths[HLA_SCORE]]
proc jsi tady dropnul vyuziti toho CompatibilityGraphDTO? to je k tomu abychom meli jistotu ze to ma spravny format.

2023-01-16 11:33 UTC, kubantjan commented on txmatching/database/services/scorer_service.py
> +    return {(pair[0], pair[1]): {HLA_SCORE: pair[2]} for pair in
to same tady, tohleto nechceme zahazovat!

2023-01-16 11:33 UTC, kubantjan commented on txmatching/database/services/scorer_service.py
> +    return {(pair[0], pair[1]): {HLA_SCORE: pair[2]} for pair in
to je prave kvuli konzsistenci tech modelu. Pohle prosim nepredelavaej.

2023-01-24 13:29 UTC, kubantjan approved these changes

2023-01-24 14:16 UTC, merged