add the option of forgiving HLA parsing
mild-blue/txmatching pull request #1099
Opened 2022-12-11 15:33 UTC by kristinagalik

Closes #1098 

Alternativne HLA parsovanie pre spanielske data - riesila som errory aj warningy, lebo tych warningov bolo napr aj 100 pre niektorych recipientov.

2022-12-12 13:52 UTC, kubantjan requested changes
Dopis jeste do readme co to znameni dela a znamena

2022-12-12 13:52 UTC, kubantjan commented on txmatching/configuration/app_configuration/application_configuration.py
> +class ApplicationHLAParsing(str, Enum):
JEste bych tady detailneji vysvetlil co znamena ta strictness

2022-12-13 11:09 UTC, kubantjan reviewed
Obecne si predstavuju, ze vetsina veci (hlavne tech treba s tema basic_hla_group_is_empty) by sla vyresit tak, ze v zavislosti na tom envu das veci do warningu vs erroru.  (sem tam budou potreba zmeny kodu, kde se ted misto kodu vraci none, ale bude to takovy ulizenejsi

2022-12-13 11:09 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        forgiving_hla_parsing = get_application_configuration() is not None and \
tohle by nemelo nastat nikdy, appliaction configuration nikdy by nemalo vracen none.

2022-12-13 11:09 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        forgiving_hla_parsing = get_application_configuration() is not None and \
tady muzes teoreticky vracet ty errory, to preci nevadi, tenhle error dalsi pocitani nezablokuje.

2022-12-13 11:09 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +            return process_parsing_result(standartized_high_res, exception_split_broad_code,
tady vracis v exception split_broad_code vzdycky none

2022-12-13 11:09 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +            return process_parsing_result(standartized_high_res, exception_split_broad_code,
coz takhle muze byt spatne citelny, dal bych tam rovnou none

2022-12-13 11:09 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +            return process_parsing_result(standartized_high_res, exception_split_broad_code,
pridal bych spesl typ asi na parsing kam bych daval tyhle casy

2022-12-13 11:09 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        forgiving_hla_parsing = get_application_configuration() is not None and \
tzn tady by ten kod vubec nemelo byt potreba menit ne?

2022-12-13 15:18 UTC, kristinagalik commented
@kubantjan cize ma to byt stale premenna v env alebo daky event atribut? lebo env premenna bude platit na vsetky eventy.

2022-12-14 14:54 UTC, kubantjan commented
> @kubantjan cize ma to byt stale premenna v env alebo daky event atribut? lebo env premenna bude platit na vsetky eventy.

no puvodne jsem si rikal, ze bych to nechal jen v ramci .env, ale ted kdyz nad tim premyslim vic, tak by to nemuselo byt tolik prace mit nejaky takovy setting per txm event, tak to prosim udelej tak :).

2022-12-20 07:59 UTC, closed without merging