feat: add forgiving option to HLA parsing
mild-blue/txmatching pull request #1102
Opened 2022-12-17 12:53 UTC by kristinagalik

2022-12-17 15:02 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        # TODO
@kubantjan tu si mi k predoslej issue pisal toto:
"tady muzes teoreticky vracet ty errory, to preci nevadi, tenhle error dalsi pocitani nezablokuje."
a ked tu nemam tu upravu tak to hadze warningy a su to sice len warningy ale niektori pacienti ich maju mrte vela

2022-12-19 10:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        # TODO
@kristinagalik  takze to je pak necitelny?

2022-12-19 10:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        # TODO
jestli to jinak funguje, klidne bych jim nechal mrte vela warningu

2022-12-19 13:24 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_transformations/hla_transformations.py
> +        # TODO
okej pozerala som to, nechavam tam teda warningy, pre tento konkretny je ich nastastie malo. problemove boli ine. cize to budu len musiet manualne odklikat. 

ale uz je kod updated

2022-12-19 13:34 UTC, kristinagalik commented
@kubantjan updated

2022-12-20 07:30 UTC, kubantjan requested changes
Maly komentar, jeste poprosim @abragtim at na to mrkne, jestli je mu vse jasne a zkusi tam najit nejakou vec co by sla vylepsit. Pak muzeme mergnout.

2022-12-20 07:30 UTC, kubantjan commented on tests/utils/test_matching.py
> +        self.assertEqual(1, result)
nasel jsem https://stackoverflow.com/questions/930995/assertequals-vs-assertequal-in-python ze tu upravu delas spravne, ze assertEqual je spravnejsi. Ale kdyz uz to delas, koukalas do kodu vsude, ze to jinde nemame?

2022-12-20 08:01 UTC, kristinagalik commented on tests/utils/test_matching.py
> +        self.assertEqual(1, result)
hej, je to iba v tomto file

2022-12-20 10:22 UTC, abragtim requested changes
Vypadá fajn. Jen jsem našel pár drobností

2022-12-20 10:22 UTC, abragtim commented on txmatching/patients/hla_functions.py
> +    if not is_some_antibody_below_cutoff and strictness_type == StrictnessType.STRICT:
Možná by hodilo po tomto bloku if-elif po prvním elif přidat ještě jeden
```
elif stricktness_type == StrictnessType.FORGIVING:
        return HighResAntibodiesAnalysis(True, ParsingIssueDetail.FORGIVING_HLA_PARSING)
```
Co si o tom myslíš?

2022-12-20 11:38 UTC, NotLubo commented
Mám tady něco dělat nebo se mohu unsubscribe?

2022-12-20 23:38 UTC, kristinagalik commented on tests/database/services/test_update_donor_recipient.py
> +        txm_event_base = get_txm_event_complete(txm_event_db_id)
opsi sorry to mi uslo

2022-12-21 00:00 UTC, kristinagalik commented
@kubantjan pozeram na to a teda rozpravali sme sa, ze ten strict mod ma byt taky ako doteraz, a ze pre forgiving ma vsetko byt na urovni infa. 

co ma napada ako najefektivnejsie riesenie je mozno upravit funkciu ktora filtruje pacientov podla validity, no tam je problem zas to ze sa musi prekopavat kod okolo `ERROR_PROCESSING_RESULTS` lebo potom stracame uplne info o tych HLAs (ked sa vracia error tak sa HLA discarduje). 

je nieco co ta napada ako lepsie riesenie?

2022-12-21 07:19 UTC, kubantjan commented
@kristinagalik priste prosim presne se odkaz na misto v kodu o kterem mluvis, takhle jsem to musel dohledavat, moc casu to nezabere, ale pomuze to :).

jinak ERROR_PROCESSING_RESULTS a WARNING_PROCESSING_RESULTS me napada, ze by mohly mozna byt proste vlastnosti txm eventu. Tzn. txm_event.get_error_processing_results() nebo tak neo.

a pak tohle pouzit na tech mistech kde to je relevantni mozna.

2023-01-01 23:04 UTC, closed without merging