Correct scoring of Other typing
mild-blue/txmatching pull request #1105
Opened 2022-12-19 20:48 UTC by kristinagalik

Closes #627

2023-01-06 00:24 UTC, kristinagalik commented on txmatching/utils/enums.py
>          max_count_per_patient=2
z popisu issue chapem ze ak mame napr DPA*01:01 a ine DPA uz nemam, tak by sa to jedno malo pocitat 2x. ale tu vidim ze jednotlive groups maju uz info o max count per patient. to stale znamena ze ked je len jedno tak sa to duplikuje?

2023-01-06 08:06 UTC, kubantjan commented on txmatching/utils/enums.py
>          max_count_per_patient=2
hmm tady je to zvlastni protoze vetsina je genu. Tzn je to ze je jich maximalne i minimalne 2. 
jedina vyjimka je DRB ktery je nekolik genu, ktery mezi sebou tak zvlastne jeste interagujou a tam je to divnejsi.

v zasade by asi krome parametru max count, ktery slouzi spis k overeni jestli jich tam neni moc by mel byt jeste count_per patient, ktery teda temer u vseho je presne 2 a kdyz je neco 1x tak se to bere ze to tam je 2x. V pripade DRB51,2,3 muze byt realny pocet cokoliv mezi 0 az 2 a tam se tahleta duplicita nedela. (jsou to realne 3 odlisny geny, ktery se chovaji divne.)

tak to bych zkusil nejak podchytit. Mozna ten parametr max_count_pre_patient neni uplne stastny nazev. 

Zkus se zamyslet jak to udelat hezky (a samozrejme to napis do readme :)

2023-01-06 08:06 UTC, kubantjan requested changes
na kod jsem nekoukal, zatim jen odpoved na dotaz, coz mozna bude znamenat jeste nejakou zmenu :)

2023-01-08 13:33 UTC, kristinagalik commented on txmatching/utils/enums.py
>          max_count_per_patient=2
aha tak ak to je max tak asi ok, to ze ak je nieco 1x tak sa to bere 2x uz sa riesi potom inde, toto je info cisto len pre scorer a bonusy pre jednotlive skupiny, tak som nechapala ze co s tym

2023-01-08 19:50 UTC, kristinagalik commented
@kubantjan jedna otazocka - na tie bonusy pre skupiny - ako to mam spravit? lebo takto to dost meni skore medzi ludmi.. mam to dat nejake desatinne? a ak to ma byt ine nez to je trz - od coho sa to ma odvijat?

2023-01-09 10:37 UTC, kubantjan commented
> @kubantjan jedna otazocka - na tie bonusy pre skupiny - ako to mam spravit? lebo takto to dost meni skore medzi ludmi.. mam to dat nejake desatinne? a ak to ma byt ine nez to je trz - od coho sa to ma odvijat? (mam namysli tie bonusy ako `EQUAL_BONUS_PER_GROUPS`)

@kristinagalik jako jak ted je bonus pro DR=9 B=3 a A=1? ty pro ty ostatni skupiny zatim 0, nez rekne IKEM jinak.

2023-01-09 10:37 UTC, kubantjan commented
chceme na to byt ready, aby se to dalo menit protoze jiny zeme to obcas zminuji co je pro ne podstatny, ale zatim se to nereklo a jak jsme na to nebyli ready, tak jsem to ani neresil.

2023-01-10 23:48 UTC, kristinagalik commented
done @kubantjan

2023-01-11 22:29 UTC, kubantjan requested changes
nejaky komets

2023-01-11 22:29 UTC, kubantjan commented on txmatching/utils/enums.py
> +GENE_HLA_GROUPS_WITH_OTHER = GENE_HLA_GROUPS + HLA_GROUPS_OTHER
tady uz tenhle nazev nedava smysl.


protoze gene hla groups jsou vlastne vsechny je to proste vzdy vlastne nazev genu. Jediny divny je OTHER_DR coz je nejaky mix genu. Ale vlastne ted uz je to jendo, klidne bych to vsechno dal do proste Hla_GROUPs listu a ohotov.

klidne bych nechal jen HLA_GROUPS ted a nic s other vlastne nerozlisovat.

2023-01-11 22:29 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +        if group.hla_group is not HLAGroup.OTHER_DR and group_exceedes_max_number_of_hla_types(group.hla_types):
tady by to melo fungovat pro vsechny, jen OTHER_DR ma to maximum jiny (3) a ostatni maji 2.

2023-01-11 22:29 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    if hla_per_group.hla_group in HLA_GROUPS_OTHER and hla_per_group.hla_types == []:
tady ten if na to hla groups other asi neni potreba uz, to muze jit proste pres vsechny

2023-01-11 22:29 UTC, kubantjan commented on txmatching/utils/hla_system/compatibility_index.py
> +    # TODO ktore mozu mat kolko teda non basic prazdne?
jou tady je to tak ze kdyz ma 1 nebo dva tak skorovat a kdyz nema nic tak neraisnout error ale tuhle skupinu pro ted neskorovat. a ta kontrola ktere skupiny jsou nebo nejsou pritomny se dejou jinde.

takze tady bude jste potreba trosku uprava.

2023-01-11 22:29 UTC, kubantjan commented on txmatching/utils/hla_system/compatibility_index.py
> +    # TODO ktore mozu mat kolko teda non basic prazdne?
rekl bych takto:
0 -> skip skorovani tenhle group (tzn skore 0, zadny match, neresim)

1 -> je to other dr -> ponechat, neni to other dr -> zdvojit pro ucely skorovani

2-> ponechat

2023-01-14 18:25 UTC, kristinagalik commented on txmatching/utils/hla_system/compatibility_index.py
> +    # TODO ktore mozu mat kolko teda non basic prazdne?
skip skorovani - to znamena ze aj pre A, B, DR?

2023-01-16 11:56 UTC, kubantjan requested changes
jeste vylepseni

2023-01-16 11:56 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +        if group.hla_group is not HLAGroup.OTHER_DR and group_exceedes_max_number_of_hla_types(group.hla_types, group.hla_group):
tady bych udelal teda nejakou skupinu SPECIAL_HLA_GROUPS kde ted bude jen to other DR aby bylo jasny co se tady deje.

2023-01-16 11:56 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +        if group.hla_group is not HLAGroup.OTHER_DR and group_exceedes_max_number_of_hla_types(group.hla_types, group.hla_group):
plus ten koment nad tim ted nesedi ne? ty uplne check toho OTHER_DR skipujes? ale tady pises ze max 3 kontrolujes, coz neni pravda?

2023-01-16 11:56 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +MAX_ANTIGENS_PER_OTHER_DR = 3
v enums.py mame max_count_per_patient pro kazdou hla group

2023-01-16 13:08 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +MAX_ANTIGENS_PER_OTHER_DR = 3
oki ale trz si niesom ista ze co zmenit. lebo v predoslych komentoch si teda pisal ze "tady by to melo fungovat pro vsechny, jen OTHER_DR ma to maximum jiny (3) a ostatni maji 2." cize mam zmenit max_count_per_patient pre other_dr na 3 a potom ten parameter pouzit tam kde sa pouziva teraz `MAX_ANTIGENS_PER_OTHER_DR` a `MAX_ANTIGENS_PER_GROUP`?

2023-01-16 13:32 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +MAX_ANTIGENS_PER_OTHER_DR = 3
@kristinagalik  tak sorry, spatne jsem to rekl.

od Mateje Rodera vime toto:

2) U DRB345 je to tak, že každý může mít 0 až 2 geny pro DRB3, 0 až 2 geny pro DRB4 a 0 až 2 geny pro DRB5. Zároveň však platí, že může mít pouze 0 až 2 jakékoliv geny DRB345. Čili neexistuje jedinec, který by měl například 1 funkční protein DRB3, DRB4 i DRB5, protože pak by jich měl dohromady 3, což není možné, rsp. to zatím u žádného člověka nebylo objeveno.

2023-01-16 13:35 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +MAX_ANTIGENS_PER_OTHER_DR = 3
je to na zaklade emailu od Mateje Rodera z 12.5.2020, to tam prosim dopis k tomu mistu kde je to max u other DR

2023-01-16 14:54 UTC, kristinagalik commented
kvoli testom (a aj normalnej logike) uz sa nebudu pridavat invalid codes do OTHER_DR ale do INVALID_CODES. Co to ale znamena je ze sa to potom vykresluje aj na FE (kvoli situacii ak je sctrictness type eventu FORGIVING). mam to riesit alebo to mozem nechat tak? @kubantjan

2023-01-16 18:41 UTC, kubantjan commented
> situacii ak je sctrictness type eventu FORGIVING). mam

Líbí dává smysl :)

2023-01-16 20:07 UTC, kristinagalik commented
oki tak je to ready na check :)

2023-01-16 20:14 UTC, kubantjan requested changes

2023-01-16 20:16 UTC, kubantjan requested changes
Jak to vypada na FE kdyz jsou nejaky ty groups prazdny, ukazujou se tam pak nebo ne? Aby to tam nevypadalo hnusne pri ruznych kombinacich (donor DQA ma, recipient ne atp)

2023-01-24 14:10 UTC, kubantjan requested changes
Jeste tam resim malou upravu tech skupin, vzi email na rodera, ale na zaklade toho jeho mailu udelam jeste novy issue a tohle ted mergneme.

tzn takto asi dobre, jeste poprosim @krllstdn  o to aby to prolitl jestli vsemu rozumi a mergujem

2023-01-24 14:12 UTC, kubantjan requested changes
plus prijej prosim screenshot jak to ted vypada na FE kdyz se pridaji ty novy skupiny

2023-01-25 00:45 UTC, kristinagalik commented
takto to vyzera:
![image](https://user-images.githubusercontent.com/56656359/214454361-08a6ab11-49ef-4d3e-8d69-8cc2529e1d27.png)

![Uploading image.png…]()

\+ dala som prec tie zmeny z fe, su to aj tak nezavisle drobnosti co sa vedia vyriesit vramci fe issue ak to budu naozaj relevant zmeny

2023-01-25 00:46 UTC, kristinagalik commented
takto to vyzera na fe:
![image](https://user-images.githubusercontent.com/56656359/214454582-c777272f-b9bd-4a21-a022-ce5c4bf08e8e.png)

![image](https://user-images.githubusercontent.com/56656359/214454521-93bc76fd-0dbe-4b5f-9207-a8d6047a32fb.png)

\+ zmazala som tie zmeny z fe, aj tak to nebolo relevant k tejto issue a da sa to vyriesit aj potom

2023-01-25 08:01 UTC, kubantjan commented
ok, dobre

2023-01-25 08:01 UTC, kubantjan submitted a review, later dismissed

2023-01-25 13:45 UTC, krllstdn commented on txmatching/utils/enums.py
> +    # Each DRB3,4,5 (DR51,52,53 in split) can have 0 to 2 genes for DRB3, 0 to 2 genes for DRB, and 0 to 2 genes for DRB5.
Line is too long :)

2023-01-25 13:45 UTC, krllstdn commented on txmatching/utils/enums.py
>      HLAGroup.OTHER_DR: HLAGroupProperties(
Vidim ze z DR grupy je oddelena podgrupa DRB1, ale DRB3,DRB4, DRB5 nejsou a jsou sjednocene v Other_DR. Jen pro jistotu: oni se nerozepisuji protoze kazda z nich muze byt a muze i nebyt podle toho, co je napsano v komentari? Pokud se mylim, tak prosim  rekni prosim proc se nerozdeluiji @kristinagalik

2023-01-26 00:17 UTC, kristinagalik commented on txmatching/utils/enums.py
>      HLAGroup.OTHER_DR: HLAGroupProperties(
not sure co presne sa asi pytas, ale myslim ze toto by to malo zodpovedat: https://github.com/mild-blue/txmatching/issues/1100#issue-1499931255

2023-01-26 06:46 UTC, kubantjan approved these changes

2023-01-27 19:01 UTC, krllstdn commented on txmatching/utils/enums.py
>      HLAGroup.OTHER_DR: HLAGroupProperties(
jo, sorac - spatne jsem zformuloval. Otazka by mohla znit tak: proc DRB1 ma svu vlastni skupinu, pres to, ze on patri k  skupine DR?

2023-01-28 10:57 UTC, kristinagalik commented on txmatching/utils/enums.py
>      HLAGroup.OTHER_DR: HLAGroupProperties(
jaj, pretoze drb3,4,5 sa spravaju oddly v tomto pripade, cize mozes mat 2 antigeny drb1, a potom este up to 2 antigens z drb3,4,5. tak to je rozdelene.

2023-01-29 14:59 UTC, merged