feat: add the forgiving attribute to a txm event
mild-blue/txmatching pull request #1113
Opened 2023-01-01 23:31 UTC by kristinagalik

zmenila som assertEquals na assertEqual, lebo to prve uz je deprecated

2023-01-02 20:08 UTC, kristinagalik commented on txmatching/patients/hla_functions.py
> +            hla_types_in_groups[HLAGroup.Other].append(hla_type)
@kubantjan tu mam otazku - okej cize chceme mat niekde ulozene tie codes ktore niesu OK, ale nechceme ich po novom mazat... mam urobit novu kategoriu alebo je ok zatial ich mat takto zatial v Other?

2023-01-03 07:46 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +            hla_types_in_groups[HLAGroup.Other].append(hla_type)
nechme je v other

2023-01-03 07:48 UTC, kubantjan requested changes
Jeste test testujici ten atribut forgiving nikde nevidim, jestli jsem to neprehlidl?

2023-01-03 07:57 UTC, kubantjan requested changes

2023-01-03 07:57 UTC, kubantjan commented on txmatching/patients/hla_code.py
> +            # TODO
smazat todo

2023-01-03 07:57 UTC, kubantjan commented on txmatching/patients/patient.py
> +            ) = _return_all_patients(all_donors, all_recipients)
jak se presne tohle chova na FE? tam se ukazou vsechny ty vykricniky a to vsechno akorat se s nima pocita? To bude dost matouci ne? Ja si predstavoval, ze vsechno bude mit bud level info aby se to ani nedalo confirmovat, nebo level warning ale pak budou muset fungovat konfirmace. Takhle se tam normalne posle level error, pacient se zaradi nakonec a tak vsechno a pritom se s nim bude pocitat.

Navic si furt dovedu predstavit nejaky veci kdy pacient je tak moc spatnej, ze ho zaradime s errorem i v pripade forgiving parsing.. (ted tam takovou kategorii asi nemame ale klidne bychom mohli).

2023-01-03 22:13 UTC, kristinagalik commented
oki je to vsetko info, test pridany

Navic si furt dovedu predstavit nejaky veci kdy pacient je tak moc spatnej, ze ho zaradime s errorem i v pripade forgiving parsing.. (ted tam takovou kategorii asi nemame ale klidne bychom mohli).
^ k tomuto ale prosim asi vysvetlenie ze pod akou podmienkou je pacient prilis spatny aj na forgiving verziu?

2023-01-04 07:24 UTC, kubantjan commented
> oki je to vsetko info, test pridany
> 
> Navic si furt dovedu predstavit nejaky veci kdy pacient je tak moc spatnej, ze ho zaradime s errorem i v pripade forgiving parsing.. (ted tam takovou kategorii asi nemame ale klidne bychom mohli). ^ k tomuto ale prosim asi vysvetlenie ze pod akou podmienkou je pacient prilis spatny aj na forgiving verziu?

no ted presne nevim. NEjaky absurdni kod? NEvim presne, ale radeji bych si tam tu moznost proste ponechal :)

2023-01-04 07:26 UTC, kubantjan requested changes
rebase a maly koment jinak ok

2023-01-04 07:26 UTC, kubantjan commented on txmatching/data_transfer_objects/patients/out_dtos/conversions.py
> +            'infos': [warning for warning in parsing_issues],
parsing_issue in parsing_issues, text warning me mate :P

2023-01-06 08:14 UTC, kubantjan approved these changes

2023-01-06 08:17 UTC, kubantjan approved these changes

2023-01-06 12:03 UTC, merged