Installation description in README doesn't have a lot of small details
mild-blue/txmatching pull request #1123
Opened 2023-01-04 10:04 UTC by krllstdn

Closes #1092

2023-01-06 13:56 UTC, abragtim requested changes
Několik drobných úprav a zadal jsem několik otázek. Ovšem nemůžu ale ověřit technickou část README specifickou pro ubuntu.
Taky v plánu issue je napsáno "swagger (openapi-generator) needs java 8 to work", ale podle issue #1091 asi chápu, že Java 8 už není potřeba, správně?

2023-01-06 13:56 UTC, abragtim commented on txmatching/web/frontend/README.md
> +(by some reason it is not possible to run `make` commands with superuser rights).
Nelze spouštět sudo uvnitř Makefile nebo "sudo make ...". U mě na macOs lze spouštět sudo make ... a poběží všechny příkazy z make se superuser právy. Pokud na Ubuntu taky lze použit "sudo make", tak to  bude jednodušší krok pro instalaci

2023-01-06 13:56 UTC, abragtim commented on txmatching/web/frontend/README.md
> +(at the time it is written) that is not very suitable us. Which shouldn't be a problem,
suitable for us?

2023-01-06 13:56 UTC, abragtim commented on txmatching/web/frontend/README.md
> +Here comes very interesting part: openapi generator from npm comes in quite old version
I think "In a quite old version" is correctly

2023-01-06 13:56 UTC, abragtim commented on txmatching/web/frontend/README.md
> +but at least in Ubuntu it cannot be updated without superuser rights, so `make` commands will not work
"can't" or "can not"

2023-01-11 20:59 UTC, krllstdn commented on txmatching/web/frontend/README.md
> +Here comes very interesting part: openapi generator from npm comes in quite old version
true

2023-01-11 20:59 UTC, krllstdn commented on txmatching/web/frontend/README.md
> +(at the time it is written) that is not very suitable us. Which shouldn't be a problem,
co s tim?

2023-01-11 21:04 UTC, krllstdn commented on txmatching/web/frontend/README.md
> +(by some reason it is not possible to run `make` commands with superuser rights).
ja mam takovy error (a myslim si ze na wsl to bylo stejne)
![image](https://user-images.githubusercontent.com/50211831/211917105-f64d9788-e5b1-41c6-8c91-cfa2bb14e1d9.png)
@kubantjan da se ti spoustet `make` commands s superuser rights? pripadne @kristinagalik

2023-01-11 21:08 UTC, krllstdn commented
@abragtim jo. nejak openapi-generator se nechtel spoustet bez java 8 a potom jsem ho preinstaloval  a  uz nejak to slo s modernejsimi verzemi. Jak to mas ty, jakou verzi javy mas nainstalovano? a mozna sis mel podobny problem?

2023-01-11 21:12 UTC, abragtim commented
> @abragtim jo. nejak openapi-generator se nechtel spoustet bez java 8 a potom jsem ho preinstaloval a uz nejak to slo s modernejsimi verzemi. Jak to mas ty, jakou verzi javy mas nainstalovano? a mozna sis mel podobny problem?
@krllstdn 
Podíval jsem se, že právě mám nainstalovanou Javu 8

2023-01-11 21:15 UTC, krllstdn commented on txmatching/web/frontend/README.md
> +(by some reason it is not possible to run `make` commands with superuser rights).
jop, pardon, to je muj env problem. zmenil jsem `python` na `python3` a pobezelo to (aspon swagger)

2023-01-11 21:22 UTC, krllstdn commented
@abragtim hmmmm, no oni tam v readme psali, ze pro MacOS fakt je potreba v jave 8, ale jak to je v linuxu?.. 

@kristinagalik jakou verzi javy mas nainstalovanou?

2023-01-11 21:28 UTC, kristinagalik reviewed
![image](https://user-images.githubusercontent.com/56656359/211921583-03092681-56c1-426e-8e68-f00a0dddb1bf.png)

2023-01-11 21:32 UTC, abragtim commented
> @abragtim hmmmm, no oni tam v readme psali, ze pro MacOS fakt je potreba v jave 8, ale jak to je v linuxu?..
> 
> @kristinagalik jakou verzi javy mas nainstalovanou?

Tak zítra zkusím to spustit u sebe na jiné verzi Java a tam vědět. Jestli opravdu musím mít Javu 8, tak by bylo dobré to propsat v README.

2023-01-11 21:50 UTC, krllstdn commented
@abragtim dik, tady je odkaz na jejich readme https://github.com/OpenAPITools/openapi-generator#1---installation zkus jeste prosim zbuildit ten jar

2023-01-16 07:14 UTC, abragtim commented
@krllstdn , podle mě Java 8 není třeba ani na mac. Zkusil jsem rozběhnout celý txm, generate-swagger-all, testy a nainstalovat ten .jar. Tady je výstup terminalu a asi problémy nejsou.
[Uložený výstup terminálu_jar.txt](https://github.com/mild-blue/txmatching/files/10423333/Ulozeny.vystup.terminalu_jar.txt)
[Uložený výstup terminálu.txt](https://github.com/mild-blue/txmatching/files/10423334/Ulozeny.vystup.terminalu.txt)

2023-02-02 07:53 UTC, kubantjan submitted a review, later dismissed

2023-02-03 06:07 UTC, abragtim submitted a review, later dismissed
Opravdu na mac s ARM condou nelze spustit. Padá to kvůli binarkům CBC (mip), které jsou jen pro Intel

2023-02-03 10:45 UTC, kubantjan approved these changes

2023-02-03 10:56 UTC, merged