Make medical id unique
mild-blue/txmatching pull request #1125
Opened 2023-01-06 09:39 UTC by krllstdn

Closes #615

2023-01-11 21:01 UTC, kristinagalik commented on txmatching/database/services/parsing_utils.py
> +    new_recipient_current_donor_ids = new_recipient_ids.intersection(current_donor_ids)
zatial sice tusim neni endpoint ktory by pridaval viac pairs naraz ale bolo by dobre toto mat poriesene do buducnosti (a zaroven si myslim ze je dobre mat aj endpoint na pridavanie viac pairs ale mozno je a len si nespominam teraz), ze pozerat aj navzajom ci v `new_recipient_ids` a `new_donor_ids` niesu duplikatne veci.. also mozno len myslienka ale nedali by sa tie riadky 24-34 nejak zmrsknut na styl ze 
```
all_ids = new_ids + old_ids
duplicate_ids = all_ids - set(all_ids)
```
a potom mat len info o otm ze aha tu su duplicate_ids: `duplicate_ids`? je az tak velmi podstatne povedat ci to je donor alebo recipient a ze v akej kombinacii? ak hej tak chapem preco je to takto - cize toto je skor otazka.

2023-01-11 21:05 UTC, kristinagalik commented on txmatching/database/services/parsing_utils.py
> +    new_recipient_current_donor_ids = new_recipient_ids.intersection(current_donor_ids)
pytam sa lebo ak to niekto pridava manualne cez stranku tak stare medical ids nezmeni ak nezmaze stareho pacienta, a pri novom mu staci ta info ze "zmen tohto medical id" a ak to niekto robi cez endpointy asi aj vie ako vyhladat rychlo v tom requeste pomocou ctrl f

2023-01-20 10:39 UTC, krllstdn commented on txmatching/database/services/parsing_utils.py
> +    new_recipient_current_donor_ids = new_recipient_ids.intersection(current_donor_ids)
Jo, asi mas pravdu - kdyz nekdo pridava pacienta s duplicitnim id tak on nechce vedet kde ta duplicita je, mu proste staci znat jake id je duplicitni. Tak to opravim.

2023-01-21 14:44 UTC, krllstdn commented
@kristinagalik Pridal jsem jeste jeden check pro case kdy v seznamu PatientUploadDTO dva a vice donoru nebo recipientu maji stejny medical id. Navic jsem zmensil pocet tech chybovych hlasek. 
Snazil jsem to udelat cojnejcitelnejsi a proto vyskytlo trochu vice promennych nez pylint pocita za normalni.  Rekni pokud je to spatne cist, pripadne co by se dalo zlepsit.

2023-01-21 22:12 UTC, kristinagalik requested changes
nevedela som sa dobre vyjadrit ale taketo nieco som mala namysli v tom `parsing_utils`:
```
def check_existing_ids_for_duplicates(txm_event: TxmEvent, donors: List[DonorUploadDTO], recipients: List[RecipientUploadDTO]):
    new_ids = [donor.medical_id for donor in donors] + [recipient.medical_id for recipient in recipients]
    old_ids = [donor.medical_id for donor in txm_event.all_donors] + [recipient.medical_id for recipient in txm_event.all_recipients]

    upload_duplicate_medical_ids = set(_find_duplicates_in_list(new_ids))
    db_duplicate_medical_ids = set(old_ids).intersection(set(new_ids))

    if upload_duplicate_medical_ids:
        raise InvalidArgumentException(f'Duplicate medical ids {upload_duplicate_medical_ids} in data for upload.')

    if db_duplicate_medical_ids:
        raise InvalidArgumentException(f'Medical ids {db_duplicate_medical_ids} are already in use in given txm event.')
```
s tym, ze teda ta helper funkcia uz tiez vlastne rovno moze vraciat set a nie list

2023-01-21 22:12 UTC, kristinagalik commented on txmatching/database/services/parsing_utils.py
>      new_donor_ids = {donor.medical_id for donor in donors}
resp neni to nespravne, ale je to nieco navyse co by sa dalo napisat na menej riadkov

2023-01-21 22:12 UTC, kristinagalik commented on txmatching/database/services/parsing_utils.py
> +    return [item for item in set(list_to_check) if list_to_check.count(item) > 1]
toto je tusim n**2 complexity kvoli `count`, cize keby pouzijes set na lookupovanie occurences to bude linear

2023-01-22 13:14 UTC, krllstdn commented
@kristinagalik Jaj, sorry, zkusil jsem udelat jak sis tam napsala, ale vono samozrejmne nefungovalo (takove operace mezi sety a listy neexistuji). Potom ale z nejakeho duvodu jsem zahodil napad udelat tak jak sis ty narvhla ted. Udelal jsem jak sis narvhla. Doufam ze uz to je lip. Dekuju za opravu.

2023-01-22 14:59 UTC, kristinagalik requested changes
len jeden maly koment inak imo ok :)

2023-01-22 14:59 UTC, kristinagalik commented on txmatching/database/services/parsing_utils.py
> +# pylint: disable=too-many-locals
toto tu uz neni treba ci?

2023-01-31 08:20 UTC, closed without merging