Prihodit do readme vysvetlivky o hla antigenech
mild-blue/txmatching pull request #1132
Opened 2023-01-21 22:19 UTC by kristinagalik

Closes #1100

2023-01-24 13:32 UTC, kubantjan approved these changes
Dobry, ale jeste bych pocka na @krllstdn  jestli to pro nej bude srozumitelny

2023-01-24 13:32 UTC, kubantjan commented on documentation/README.md
> +We are currently considering 6 groups of HLA antigens: A, B, C, DR, RP, and DQ. All of the other groups are not relevant to
RP->DP

2023-01-24 13:32 UTC, kubantjan requested changes
teda krome toho mini komentare na typo

2023-01-25 10:51 UTC, krllstdn commented
@kubantjan @kristinagalik Yep, to je srozumitelny

2023-01-25 10:53 UTC, krllstdn reviewed
@kubantjan @kristinagalik Yep, to je srozumitelny

2023-01-25 11:06 UTC, kubantjan approved these changes

2023-01-25 11:15 UTC, merged