Poor mans solution for multiple donors
mild-blue/txmatching pull request #1133
Opened 2023-01-23 11:18 UTC by krllstdn

Closes #1112

2023-01-30 14:45 UTC, krllstdn commented
@kubantjan Problem byl v `backref`, v definici toho vztahu. To je legacy definice, ve ktere se nerika co v tom vztahu je child, a co je parent - vono se urcuje automaticky. 
`back_populates` s explicitni definici child a parent  je lepsi volba. Je to popsano zde: https://docs.sqlalchemy.org/en/14/orm/backref.html

Moje spekulace: tam se nejak spletlo co je child a co je parent  - donor  byl parent a jsme tim padem menily parenta pro daneho recipienta a kvuli tomu ten recipient_id u donora se mazal.

2023-01-30 14:48 UTC, krllstdn commented on tests/web/test_patient_api.py
> +                ManualDonorRecipientScore(
Bez teto zmeny Idea neechtela delat commit

2023-02-01 20:23 UTC, kristinagalik requested changes

2023-02-03 10:50 UTC, krllstdn commented on tests/web/test_patient_api.py
> +                'country_code': 'CZE'
Podle me ty antibodies tu nejsou potreba, tady se testuje ta moznost pridani dvou donoru k tomu stejnemu recipientu

2023-02-13 16:14 UTC, kristinagalik requested changes
este ten bod 3 z issue nevidim - to sa ma robit uz tu?

2023-02-14 11:12 UTC, krllstdn commented on tests/web/test_patient_api.py
> +            json_data_puv = {
good point

2023-02-16 16:41 UTC, kristinagalik submitted a review, later dismissed
ak bol ten warning message mysleny zatial len na backend tak za mna ok @kubantjan

2023-02-17 08:13 UTC, kubantjan commented
@kristinagalik  @krllstdn nebyl melo by se to ukazat i na FE ale myslel jsem, ze nebude potreba psat nic na FE a ze staci kdyz Be spravne preda FE tu error hlasku, vzdyt na TXm uz spoustu be hlasek ukazujeme.

2023-02-20 11:37 UTC, krllstdn commented
@kubantjan adding FE message is moved to #1155

2023-02-20 14:03 UTC, kubantjan requested changes
Male komenty, jinak ok

2023-02-20 14:03 UTC, kubantjan commented on txmatching/database/services/patient_upload_service.py
> +    if donor_models_related_to_recipients_in_db:
tady ten if je zbytecny, jinak proste to bude prazdny list

2023-02-21 09:50 UTC, kubantjan approved these changes

2023-02-21 09:50 UTC, merged