Change hla groups a bit
mild-blue/txmatching pull request #1142
Opened 2023-01-29 15:34 UTC by kristinagalik

Closes #1135

2023-02-02 13:53 UTC, kristinagalik commented on txmatching/utils/enums.py
> +        # TODO 8?
ma ich tu byt teraz 8 stale dokopy hej

2023-02-02 13:53 UTC, kristinagalik commented on txmatching/utils/hla_system/compatibility_index.py
> +                # TODO: change this in he future, create issue
takto je to ok? mam urobit issue?

2023-02-02 13:54 UTC, kristinagalik commented
a teda este jedna otazka @kubantjan ze ked je skupina len o jednom HLA tak sa normalne len zdvoji hej? neni to take ze to zas treba pozerat ze ci je tam napr DPA a DPB a kazde zdvojit osamom

2023-02-02 14:40 UTC, kubantjan commented
@kristinagalik  no to bohuzel ne. je to tak ze kdyz budes mit 
ve skupine DP:
a)
DPB1*01:01 -> DPB1*01:01, DPB1*01:01

b) 
DPB1*01:01, DPA1*01:01 -> DPB1*01:01, DPB1*01:01, DPA1*01:01, DPA1*01:01

c) 
DPB1*01:01,DPB1*02:01, DPA1*01:01 -> DPB1*01:01, DPB2*01:01, DPA1*01:01, DPA1*01:01


tzn koukas na jednotlivy geny a zdvojujes ty. Rozhodne je dulezity ze ve skupine DP a DQ je max 4 veci a minimalne 2. jako kdyz opravdu mergnes to DPB a DPA

2023-02-03 12:20 UTC, kubantjan requested changes
odmtiam jen z testovacich duvodu

2023-02-05 11:26 UTC, kubantjan requested changes
male komentare, ale vypada ok

2023-02-05 11:26 UTC, kubantjan commented on txmatching/utils/enums.py
> +        # TODO 8?
nn 2 od dpa a 2 od dpb tzn 4

2023-02-05 11:26 UTC, kubantjan commented on txmatching/utils/enums.py
> +        # TODO 8?
jak jsi prisla na 8?

2023-02-05 11:26 UTC, kubantjan commented on txmatching/utils/hla_system/compatibility_index.py
>  def _hla_types_for_gene_hla_group(hla_typing: HLATyping, hla_group: HLAGroup) -> List[HLAType]:
tady to neni "gene_hla_group" ten pojem podle me ted nikde uz pouzity neni a je to proste hla group.

2023-02-05 11:49 UTC, kristinagalik commented
jak jsi prisla na 8? - predtym kazda s tych skupin mala o samom max 4, tak som to len spojila

2023-02-05 12:55 UTC, kubantjan commented
Tak to bylo blbě. DPA je gen a má max 2.

2023-02-07 08:46 UTC, kubantjan requested changes

2023-02-07 08:46 UTC, kubantjan commented on txmatching/utils/hla_system/compatibility_index.py
> +        dp_dq_bonuses = {
tohle bych dal do nejaky konstanty vedle hla_typing_bonus_per_groups. A z hla_typing_bonus_per_groups bych vypustil hodnoty pro dp dq kdyz ted k nicemu nejsou. a prejmenoval aby bylo jasny, ze to neobsahuje dp dq ze to se nastavuje jinde.

a sjednotil bych jak jsou tyhle hodnoty nastaveny v 
txmatching/scorers/split_hla_additive_scorer.py vs txmatching/scorers/high_res_hla_additive_scorer.py vzdyt to je divny..

2023-02-07 08:46 UTC, kubantjan commented on txmatching/utils/hla_system/compatibility_index.py
> +                # TODO: change this in he future, create issue
takto ok, nechal bych to asi tak pro ted a ani issue nedelal doku nas to nazacne stvat

2023-02-13 12:04 UTC, kristinagalik commented on txmatching/scorers/hla_additive_scorer.py
> +            self.ci_configuration.hla_typing_bonus_per_groups_without_dp_dq.items()) \
co s tymto? teraz to pocita len s grupami bez dp a dq

2023-02-13 12:18 UTC, kubantjan requested changes

2023-02-13 13:14 UTC, kubantjan requested changes
jen upravit text todo a mergujeme

2023-02-13 13:14 UTC, kubantjan commented on txmatching/utils/hla_system/compatibility_index.py
> +                # TODO: change this in he future, create issue
tady to todo je matouci formulace, napis tady ze to neni nejkrasneji udelany, ale funguje to, ze slo o to jak nejjednoduseji pridat dp dq takto rozpadly.

2023-02-13 13:21 UTC, kubantjan approved these changes

2023-02-13 14:42 UTC, merged