Add antibody theoretical type
mild-blue/txmatching pull request #1143
Opened 2023-01-30 19:48 UTC by krllstdn

Closes #1136

2023-02-01 14:33 UTC, krllstdn commented
- [ ] Pridat property type do tridy HLAAntibody
- [ ] Vytvorit nejaky enum s hodnotama 'NORMAL' a 'THEORETICAL'. Dat 'NORMAL' jako default.
- [ ] Pridat typ 'THEORETICAL' do AntibodyMatchTypes
- [ ] Pridat check na THEORETICAL crossmatch pro vsechny checky v hla_crossmatch.py to lze udelat tak: vytvorit funkci _add_theoretical_typization() podobnou _add_none_typization() a jen zmenit pridani NONE crossmatch typu na THEORETICAL
- [ ] A napsat test, ktery overi, ze parsovani typu crossmatche THEORETICAL pro THEORETICAL protilatky funguje

2023-02-13 16:52 UTC, kristinagalik requested changes
ponahlam sa cize toto je skor otazka ako tvrdenie ale pls pozries to? :  nebude nahodou problem ze stratis to info pri presuvani antibodies alebo pod? (aka kopcenie pacientov alebo tak, lebo nevidim ze by sa ta hodnota ukladala do databaze)

2023-02-15 07:44 UTC, kubantjan commented
> Jo, podle mě to teď se bude ztrácet. @kubantjan Je přidaní typu protilátky do databáze součásti tohoto issue? Mam myšlenku jak to udělat, ale to bude hrozný pain v testech

podle me se to ztracet nebude. @krllstdn napis na to test :)

2023-02-16 16:28 UTC, kristinagalik commented
> > Jo, podle mě to teď se bude ztrácet. @kubantjan Je přidaní typu protilátky do databáze součásti tohoto issue? Mam myšlenku jak to udělat, ale to bude hrozný pain v testech
> 
> podle me se to ztracet nebude. @krllstdn napis na to test :)

napada ma export eventu - tam to nesuvisi s databazou sice ale s DTO, ale tam sa to isto bude stracat

2023-02-16 16:30 UTC, krllstdn commented
@kristinagalik jo, přesně tak. Právě to debuguju

2023-02-19 11:01 UTC, krllstdn commented
Pridal jsem property type do HLAAntibodyRaw protoze jinak by se ten typ ztracel. Tohle je mozne uvidet na radku 68 v `export_txm_event.py` (antibodies se kopirujou z raw listu). 
Lze to udelat jinak (napr. brat protilatky z Recipient.hla_antibodies.hla_antibodies_per_groups), ale tohle jsem si vsimnul az po tomu jak jsem pridal ten typ do raw protilaky a nevim jestli dava smysl to predelat? @kristinagalik @kubantjan

2023-02-19 15:56 UTC, kristinagalik submitted a review, later dismissed
chyba migracia, pridaval si veci do db schemy

na ten typ v antibody raw ti asi neviem odpovedat, pozerala som do zvysku kodu a nema dovod sa to vyuzivat pri raw, ale mozno je dobre to tam mat anyway? mozno dobuducna? na druhu stranu sa to vie lahko prirobit... neviem

2023-02-19 15:56 UTC, kristinagalik commented on tests/test_utilities/hla_preparation_utils.py
> +def create_antibody(raw_code, mfi, cutoff, type:HLAAntibodyType = HLAAntibodyType.NORMAL) -> HLAAntibody:
toto neni resolved

2023-02-19 15:56 UTC, kristinagalik commented on tests/utils/hla_system/test_crossmatch.py
> +from txmatching.utils.enums import AntibodyMatchTypes, HLACrossmatchLevel, HLAAntibodyType
toto neni abecedne

2023-02-19 15:56 UTC, kristinagalik commented on tests/web/test_matching_api.py
> +                                    Solver, HLAAntibodyType)
asi pls pozri vsetky importy

2023-02-19 15:56 UTC, kristinagalik commented on txmatching/web/frontend/src/app/model/Hla.ts
> +  type: "NORMAL" | "THEORETICAL";
tu by boo lepsie mat asi enum

2023-02-24 11:59 UTC, kubantjan requested changes
Hlavni je viz koment, plus dalsi mensi je Kdyz je protilatka undecidable tak nechat udencidable, ostatni positivni prepsat na ten theoretical.

2023-02-24 11:59 UTC, kubantjan commented on tests/utils/hla_system/test_crossmatch.py
> +    def test_theoretical(self):
tohle je spatne, ma to by t tak, ze Theoretical bude prave tehdy kdyz je positive a zaroven je typ protilatky theoretical, ty to ted mas napsany tak, ze kdyz je crossmatch negative a typ protilatky je theoretical.

2023-02-24 15:12 UTC, kubantjan approved these changes

2023-02-24 15:13 UTC, merged