Add antibody that has two hla code
mild-blue/txmatching pull request #1150
Opened 2023-02-04 12:49 UTC by kristinagalik

Closes #1137

2023-02-04 14:23 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return antibodies_over_cutoff
chapem toto dobre ze to ma takto byt hej? @kubantjan

2023-02-05 13:31 UTC, kubantjan requested changes
zda se mi ze zadani asi neni vubec jasny?

2023-02-05 13:31 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return antibodies_over_cutoff
asi ne? Nevim uprimne co to tady ma delat? neni to podle me ono.

ma byt proste typ protilatky, ktera ma 2 kody a pak jediny kdy dojde ke crossmatchi tak musi byt shoda v obou dvou. 

to tady vubec nikde nekotrolujes a tady naopak nejak podivne koukas, jestli protilatky co to naslo jsou jak genu 'A' tak z genu 'B' coz ale vubec po tobe nechci.

2023-02-05 13:32 UTC, kubantjan requested changes

2023-02-05 13:32 UTC, kubantjan commented on txmatching/patients/hla_model.py
> +                self.secondary_raw_code == other.secondary_raw_code)
tady neni vubec nic jako secondary a primary, ta protilatka ma mit moznost mit dva kody co jsou na stejny urovni.

jako muze se to jmenovat firstr a second a ten second bejt nekdy none, jen zduraznuju jak to ma byt chapano.

2023-02-15 18:59 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +
cize pre crossmatch typu A sa skupiny dp a dq prefiltruju, a zistim ci teda ozaj obe chainy maju v sebe crossmatch a ak hej, tak sa vyberie (to este dorobim, len najprv chcem vediet ci tato myslienka je ok) to "nizsie" rozlisenie, a inak sa ten crossmatch vobec nepocita a setne sa na NONE @kubantjan

2023-02-16 07:25 UTC, kubantjan requested changes

2023-02-16 07:25 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +
Mam priklad:

pacient ma jen jedinou protilatku a to  proti kombinaci DPA1*01:01 + DPB1*02:02.

takze v protilatkach mam (cutoff 2000):
DPA1*01:01 + DPB1*02:02 s MFI 3000 a pak samotny DPA1*01:01 s cutoff 100 treba.

donor ma kombinaci DPA1*01:01 + DPB1*02:02, ale v ty tvy logice podle me vyjde:
ze protilatka DPA1*01:01 + DPB1*02:02 bude mit match none.

napis nejaky test, kde ti to bude fungovat tak jak chces, abych videl jak to zamyslis, prijde mi ze ted to proste nemuze fungovat.

2023-02-18 16:26 UTC, closed without merging