Improve loggin vol 2
mild-blue/txmatching pull request #1151
Opened 2023-02-08 17:40 UTC by abragtim

Closes #1144

2023-02-08 18:19 UTC, abragtim commented
TODO

- [ ] User email or id in logs
- [ ] Stacktrace for non json logger
- [ ] Create questionnaire which options are switched on forever/optional/delete
- [ ] ...

2023-02-14 11:22 UTC, abragtim commented on txmatching/web/web_utils/logging_config.py
> +            'arguments': record.values or None
@LukasForst , ahoj. V logech chceme vidět vstupní argumenty, které user posílá do endpointu. Teď jsem testoval logování a uviděl jsem, že vidíme v endpointu '/v1/user/login' email a hlavně password, který pošle user. Tj. jsem přidal možnost vidět rovnou nehashovaná hesla userů. Smrdí to nějak porušením bezpečnosti, ale moc toho neznám. 
Tak bys mohl s tím poradit? Možná je to ok? Jak bych mohl k tomu přestoupit? Určitě můžu zakázat posílat argumenty pro tento specifický endpoint, ale bojím se, aby to nebylo příliš specifické chování, že to bude vlastně na nás pro jaké endpointy zakážeme posílat argumenty, ale pro některé můžeme zapomenout to udělat v budoucnosti (například někdo udělá nový endpoint, který bere za vstup password).

2023-02-14 12:19 UTC, kubantjan commented on txmatching/web/web_utils/logging_config.py
> +            'arguments': record.values or None
neni to ok, ty hesla chceme nejak zahvezdickovat. Chtelo by to upravit to tak, aby se pridalo, ze nejaky argument je sensitive a mus se zamaskovat.

2023-02-14 12:21 UTC, kubantjan commented on txmatching/web/web_utils/logging_config.py
> +            'arguments': record.values or None
takze by to pak melo vypadat password: ***********

2023-02-14 12:30 UTC, abragtim commented on txmatching/web/web_utils/logging_config.py
> +            'arguments': record.values or None
Ok. Zkusím nějak vymyslet, jak to udělat nejlíp. Nejvíc se bojím nechat takovou zodpovědnost na nás. Pokud prostě někdo za rok bude vytvářet nový endpoint, který bere heslo od usera, tak je docela velká pravděpodobnost, že prostě zapomene to označit jako sensitive pro logování. Možná nějaká automatizace, která to bude kontrolovat, že pokud je key "password", tak nechceme žádný další symbol mimo *, ale to je prostě první, co jsem vymyslel. Ještě nevím, jak to udělat nejbezpečněji, tak abychom skoro úplně v tom vynechali lidský faktor.

2023-02-14 12:36 UTC, abragtim commented on txmatching/web/web_utils/logging_config.py
> +            'arguments': record.values or None
Nebo třeba to lze udělat opačně. Budeme označovat při tvorbě endpointu, že endpoint neobsahuje sensitive informaci, ale jako default bude sensitive za true. Tak když někdo z nás zapomene to nastavit v endpointu, tak v nejhorším prostě budeme mít nekorektní zápisy v logech, ale ne důvěrné údaje uživatelů v logech

2023-02-15 11:12 UTC, kubantjan commented
@abragtim jeste rebase :)

2023-02-15 13:53 UTC, kubantjan requested changes

2023-02-15 13:53 UTC, kubantjan commented on txmatching/web/web_utils/traceback_formatters.py
> +        if len(frames) > max_frames_amount:
proc je to timeout errror?

a co je spatnyho na tom ze ma traceback object vic jak 100 radku, to asi neni na timeout ale vypsani bacha to je prvnich 100 radku, zbytek uz se nevesel spsi ne?

vzdy tady premyslej co se stane kdyz nekdo ten error uvidi, co to znamena, co s tim udelat. Tohle chovani co tu mas fakt chteny neni.

2023-02-16 07:35 UTC, kubantjan requested changes

2023-02-16 07:35 UTC, kubantjan commented on txmatching/web/web_utils/traceback_formatters.py
> +            logger.info(f"There are too many frames in the traceback object. "
kde se tohle zobrazi? Pred tim vypsanim ty hlasky nebo po ni? asi by bylo idealni to normalne pridat mezi ty rasky ty hlasky a nemit to jako separatni logging hlasku, to bude podle me matouci ne?

2023-02-16 07:35 UTC, kubantjan commented on txmatching/web/web_utils/traceback_formatters.py
> +class ExcInfo:
zkratku exc na exception bych nepouzival, klidne nech plne jmeno.

2023-02-17 09:17 UTC, kubantjan commented
ok, hod to jeste prosim na @kristinagalik  nebo @krllstdn zda tomu rozumeji, co se tam deje a at se dyztak doptaji, pak k mergi

2023-02-17 10:47 UTC, kubantjan approved these changes

2023-02-18 13:45 UTC, krllstdn commented
@abragtim lze nejak zapnut lokalne to logovani v jsonu? (ted to mam v takovem formatu:
```
txmatching.solve_service.solve_from_configuration-77819::solve_from_configuration|36:: User IP: 127.0.0.1:: 1 matchings were found.
2023-02-18 13:27:07-INFO-txmatching.database.services.pairing_result_service-77819::pairing_result_service|64:: User IP: 127.0.0.1:: Pairing was solved from configuration 6 and saved as pairing result 5
2023-02-18 13:27:07-INFO-txmatching.web-77819::__init__|135:: Status code: 200:: User ID: 1. User e-mail: admin@example.com. User IP: 127.0.0.1:: Request e4eac7f2-f07b-4c0e-b1a7-bf22cf828925 took 266 ms.
```
)

2023-02-18 13:46 UTC, abragtim commented
> @abragtim lze nejak zapnut lokalne to logovani v jsonu? (ted to mam v takovem formatu:
> 
> ```
> txmatching.solve_service.solve_from_configuration-77819::solve_from_configuration|36:: User IP: 127.0.0.1:: 1 matchings were found.
> 2023-02-18 13:27:07-INFO-txmatching.database.services.pairing_result_service-77819::pairing_result_service|64:: User IP: 127.0.0.1:: Pairing was solved from configuration 6 and saved as pairing result 5
> 2023-02-18 13:27:07-INFO-txmatching.web-77819::__init__|135:: Status code: 200:: User ID: 1. User e-mail: admin@example.com. User IP: 127.0.0.1:: Request e4eac7f2-f07b-4c0e-b1a7-bf22cf828925 took 266 ms.
> ```
> 
> )

v .env.local PRODUCTION_LOGGER=true

2023-02-18 13:54 UTC, krllstdn commented
@abragtim Jo, sorac, to jsem mel zapnuty,  Idea mi neupdatla posledni 2 komity - uz to tam mam.
Za me fajn

2023-02-18 13:54 UTC, krllstdn approved these changes

2023-02-19 16:07 UTC, kristinagalik approved these changes

2023-02-20 09:50 UTC, merged