Add antibody that has two hla code
mild-blue/txmatching pull request #1153
Opened 2023-02-18 16:25 UTC by kristinagalik

2023-02-21 09:09 UTC, kubantjan reviewed
Viz komentar

2023-02-21 12:06 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.high_res is None:
@kubantjan toto je sucast povodneho kodu ktorej som sa nechytala tak som ani neriesila ci to je spravne alebo nie - ale ten test neprechadza asi kvoli tomuto a podla mna ked ten kod citam by tu malo byt `if hla_type.code.high_res is not None` ci?

2023-02-21 12:30 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.high_res is None:
Nevím? Moc se mi nezdá že bychom tam měli takový bug. Myslím že ten test fakt souvisí čistě s tím novým kódem co jsi napsala. 

Napiš test jde ukážeš že něco co má nějak fungovat vždycky fungovalo špatně

2023-02-21 12:35 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.high_res is None:
https://github.com/mild-blue/txmatching/pull/1156/files

urobila som novu branch

2023-02-21 12:36 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.high_res is None:
pada to tam a je to len branch z mastera, podla mna by to aj tam malo byt high res with split ale hlasi to len high res

2023-02-21 12:38 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.high_res is None:
plus to dava zmysel ze by to malo byt `not None` vzhladom k zvysku kodu ci 

```
                # HIGH_RES_3
                if hla_type.code.high_res is None:
                    if _add_all_tested_positive_antibodies(tested_antibodies_that_match,
                                                           positive_tested_antibodies,
                                                           AntibodyMatchTypes.HIGH_RES,
                                                           positive_matches):
                        continue

                # HIGH_RES_WITH_SPLIT_1
                if _add_positive_tested_antibodies(positive_tested_antibodies,
                                                   AntibodyMatchTypes.HIGH_RES_WITH_SPLIT,
                                                   positive_matches):
                    continue
```
^ takto to je teraz ale ono to asi chce byt skor ze ak *nemame* high res code tak padni do HIGH_RES_WITH_SPLIT

2023-02-21 14:41 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.high_res is None:
jaj pardon vidim

2023-02-22 11:00 UTC, kubantjan requested changes
Viz komentare dyzta se doptavej

2023-02-22 11:00 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +        second_raw_code: Optional[str] = None
tady to je opravdu secondary raw code! ne second, protoze tady se vyuziva jen pro to parsovani.

2023-02-22 11:00 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    # leave hla codes that recipient was not tested for to the end
tenhle komenatar mi nesedi na toto misto. Ten se vztahuje spsi k ty fci ktera tutu fci vola ne?

2023-02-22 11:00 UTC, kubantjan commented on txmatching/patients/hla_model.py
> +    second_raw_code: Optional[str] = None
v raw je to skutecne secondary.

2023-02-22 11:00 UTC, kubantjan commented on txmatching/database/sql_alchemy_schema.py
> +    second_raw_code = Column(TEXT, unique=False, nullable=True)
tady to podle me nema co delat (pripadne uz to tam melo byt z predchoziho PR, ted by tento task nijak s HLAAntibodyRawModel nemel interagovat.

2023-02-22 11:00 UTC, kubantjan commented on txmatching/database/db_migrations/0037.add-attribute-to-hla-antibody.sql
> +ALTER TABLE hla_antibody_raw ADD COLUMN second_raw_code TEXT;
Viz komentar jinde

tady to podle me nema co delat (pripadne uz to tam melo byt z predchoziho PR, ted by tento task nijak s HLAAntibodyRawModel nemel interagovat.

2023-02-22 11:00 UTC, kubantjan commented on txmatching/database/db_migrations/0037.add-attribute-to-hla-antibody.sql
> +ALTER TABLE hla_antibody_raw ADD COLUMN second_raw_code TEXT;
kazdopadne muzeme to tam dyztak mit, a ukladat, ale pak to ma byt urcite secondary code. PRoc jsi na to ted prisla?

2023-02-22 11:12 UTC, kubantjan requested changes
o jak moc je to pomalejsi ted nez predtim? Treba testy? Mam pocit, ze je tam spousta redundatnich checku.

2023-02-22 11:12 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        if use_high_resolution and hla_type.code.high_res is not None and not _recipient_was_tested_for_donor_antigen(antibodies, hla_type.code):
ten chcck _recipient_was_tested_for_donor_antigen(antibodies, hla_type.code) zbytecnej ne? Z nazvu fce plyne ze tam by mely jit jen ty hlas na ktery ten pacient testovanej nebyl ne?

2023-02-22 11:12 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +def check_selected_antibodies(hla_per_group: HLAPerGroup, antibodies: List[HLAAntibody],
nemas tady co ta fce vraci a ten nazev je pomerne nestastnej, vyjadri lepe co ta fce dela

2023-02-22 11:12 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            tested_antibodies_that_match = [antibody for antibody in antibodies_to_check
pouzivas tady to "to_check" a pak se to vytraci, tezko se sleduje vyznam tech jednotlivych promennych

2023-02-22 23:30 UTC, kristinagalik commented on txmatching/database/db_migrations/0037.add-attribute-to-hla-antibody.sql
> +ALTER TABLE hla_antibody_raw ADD COLUMN second_raw_code TEXT;
https://github.com/mild-blue/txmatching/pull/1140/files

ta predosla issue mala byt tusim len taka predpriprava, este sa tam nic nedialo s tym ze antibodies budu mat nejaky attribut pre druhy kod

2023-02-22 23:30 UTC, kristinagalik commented on txmatching/database/db_migrations/0037.add-attribute-to-hla-antibody.sql
> +ALTER TABLE hla_antibody_raw ADD COLUMN second_raw_code TEXT;
mozem to tam teda takto nechat tie zmeny k databazi?

2023-02-23 00:10 UTC, kristinagalik commented
+ testy sli z 6 na 6 a pol minuty co asi neni az take hrozne?

2023-02-23 11:42 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        if use_high_resolution and hla_type.code.high_res is not None and not _recipient_was_tested_for_donor_antigen(antibodies, hla_type.code):
skusila som to lepsie okomentovat nech je jasnejsie co sa v tej funkcii deje ale ak treba vybrat ten check niekde von alebo prefiltrovat tie hlas uz skor tak mozem

2023-02-23 12:43 UTC, kubantjan commented on txmatching/database/db_migrations/0037.add-attribute-to-hla-antibody.sql
> +ALTER TABLE hla_antibody_raw ADD COLUMN second_raw_code TEXT;
no fakt ta predchozi issue s touto skoro vubec nesouvisela. Je naprosto nezavisla. nebyla to lehka predpriprava na tohle. 

v tamty se resilo aby byl secondARY code probublany do parsingu.  

kdezto tady resime second code. 

ale jak rikam asi ok, ale nutne to pak musi byt secondary a hodne prisne rozlisuj second secondary.

2023-02-23 12:57 UTC, kubantjan commented
> + testy sli z 6 na 6 a pol minuty co asi neni az take hrozne?

to je ok

2023-02-23 13:01 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +def do_crossmatch_for_selected_antibodies(hla_per_group: HLAPerGroup, antibodies: List[HLAAntibody],
jinde zas pouzivas antibodies to check, to by bylo fajn sjednotit

2023-02-23 13:24 UTC, kubantjan commented on txmatching/database/db_migrations/0037.add-attribute-to-hla-antibody.sql
> +ALTER TABLE hla_antibody_raw ADD COLUMN second_raw_code TEXT;
tohle cely ted dropni, to nedava smysl ted resit jeste to mozna v tom dalsim issue budeme resit, ale v tomhle issue tohle se vubec resit nemelo

2023-02-23 13:24 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +    if hla_raw_code is None:
kdyz nove muze byt hla_raw code none, tak bys musela rovnou upravit typ parametru. Ale obecne tohle jsi tady vubec resit nemela, to nesouvisi s timto taskem.

2023-02-23 13:24 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +            second_antibody_parsing_issues, second_code = parse_hla_raw_code_and_return_parsing_issue_list(
tohle sem vubec nepatri, parsing jsi vubec resit nemela

2023-02-23 13:31 UTC, kubantjan requested changes
jeste je tam moc zmen, ktery s timhle vubec nesouvisi.

2023-02-23 13:31 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +        second_raw_codes = {hla_antibody.second_raw_code for hla_antibody in antibody_group_list}
tohle sem do toho issue vubec nepatri

2023-02-23 13:31 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +        second_raw_code = second_raw_codes.pop()
tohle sem vubec nepatri

2023-02-23 13:31 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +            mfi=mfi,
tohle sem vubec nepatri

2023-02-23 16:14 UTC, kristinagalik reviewed
- zjednotila som nazvy
- dala som prec interakciu s databazou a ukadanie druheho HLACode
- teraz to teda nefunguje (kvoli db) zatial v praxi ale v testoch ano - resp funkcie crossmatchu su pripravene na tu zmenu

2023-02-23 16:14 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                            second_antibody = maybe_second_antibody
toto je taka otazka/vyjasnenie - viem ze zatial moze pacient dostat viac krat antibody rovnakeho nazvu, a teda nevedela som ci moze dostat aj 2x tu istu dvojicku ale s inymi mfi a co, tak checkujem preistotu vsetko

2023-02-24 14:24 UTC, kubantjan requested changes
teda nevim, zas mi prijde ze je tam nekolik uprav, ktery znamenaji, ze jsi me nepochopila.  no viz komentare.

2023-02-24 14:24 UTC, kubantjan commented on txmatching/patients/hla_model.py
> -    second_code: Optional[HLACode] = None
ne tady jedine mel ten kod zustat!!!

2023-02-24 14:24 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                    second_antibody = None
tady vubec netusim co delas uprimne ted

2023-02-24 14:24 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                            second_antibody = maybe_second_antibody
a obecne tady nechapu co delas tohle mas proste predpokladat, ze v ty protilatce je uvedeny ten kod a hotovo.

2023-02-24 14:24 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> -                                second_code=None if antibody["second_code"] is None else HLACode(high_res=antibody["second_code"]["high_res"],
tadyto tady taky melo zustat.

2023-02-24 14:26 UTC, kubantjan commented
> secondary vs second je naprosto zasadni rozdil
> 
> ted je to asi dobre, ALE ted jsem to jeste promyslel a bude dava smysl v ramci toho dalsiho issue jeste tuhle logiku trosku poladit (mit tam asi jen second nakonec a na secondary se vykaslat, nemit tam to duplikovani protilatek). ale to ted nresme a nechcme to takto.

Me slo o ukladani toho secondary code a pridavani toho sloupecku do tabulky. Coz bylo neco, co tam do toho issue nepatrilo. Nikdy jsem nezminoval, ze v HLAAntibody nema byt second code. Vzdyt to byl celou dobu zaklad a podstata tohoto tasku.

2023-02-24 23:13 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                    second_antibody = None
snazim sa najst second antibody

2023-02-24 23:18 UTC, kristinagalik commented
> Me slo o ukladani toho secondary code a pridavani toho sloupecku do tabulky. Coz bylo neco, co tam do toho issue nepatrilo. Nikdy jsem nezminoval, ze v HLAAntibody nema byt second code. Vzdyt to byl celou dobu zaklad a podstata tohoto tasku.

okej zmeny podla komentov som urobila, ale potom teda nechapem ze ked HLAAntibody ma mat second_code teda naozaj (a nielen second_raw_code) ze preco sa to rovno nema aj vytvarat v parsovani?

2023-02-26 10:26 UTC, kubantjan reviewed
no jeste ti tam zbylo asi na 2 mistech neco. Jinak ok. 

a na tu tvou otazku. Parsing se bude resit v tom dalsim tasku a bude se uplne predelavat, takze tady nedava smysl v parsingu cokoliv delat..

2023-02-26 10:26 UTC, kubantjan commented on txmatching/patients/hla_functions.py
> +            mfi=mfi,
tahle carka tu uz byt nema

2023-02-26 10:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +                    second_raw_code=hla_antibody.secondary_raw_code
tohle tady byt nema

2023-02-26 10:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +                    second_raw_code=hla_antibody.secondary_raw_code
v parsing nema byt zadna zmena, na to je ten dalsi task

2023-02-27 06:19 UTC, kubantjan requested changes
OK, ale jeste chci dat trosku zamysleni tomu souboru hla_crossmatch od @abragtim  a @krllstdn  je to presprilis komplexni. uvidime s cim kluci prijdou, aby to bylo co nejsrozumitelnejsi.

2023-03-01 14:26 UTC, abragtim requested changes
Zadal jsem pár otázek o poznámek. Odpověď ode mě na to, jak udělat ten kód srozumitelnější, tak je to refactoring. Asi je to funkce, která je jedna z nejdůležitějších na celém TXM a už tak částo se měnila, že to je takový obrovský monstrum a trvá to docela dlohou začát chapat, co v jakém momentě dělá a za jakých podmínek. Tak by asi hodně vyplatilo udělat issue na refactoring hla_crossmatch.py (zmenšit ty funkce, udělat nové, dobře je popsat, udělat doc). A už potom řešit věci s tím, jak to zoptimalizovat (tak, jak to navrhuje Kristina na začátku PR). Ale v podstatě PR řeší issue (positive match je jen tehdy, když je positive pro oba antibodies)

2023-03-02 12:07 UTC, abragtim submitted a review, later dismissed
Pořád doporučuju udělat issue na refactoring hla_crossmatch.py, pokud takové ještě není. Hodně by to pomohlo v budoucnu :)

2023-03-02 17:10 UTC, kubantjan requested changes

2023-03-02 17:10 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                    assert second_antibody is not None
co je tady ten assert? Kdy muze tady spadnout? tohle je proste nebezpecny takhle raisovat asserty uprostred kodu. Kor jeste bez vysvetleni.

2023-03-08 08:34 UTC, kubantjan approved these changes

2023-03-08 08:42 UTC, merged