Pripravit API na vyhodnoceni crossmatche pacienta
mild-blue/txmatching pull request #1157
Opened 2023-02-24 09:12 UTC by krllstdn

Closes #1134

2023-03-02 20:36 UTC, krllstdn commented on txmatching/web/api/public_api.py
> +    @public_api.require_user_login()
Nevim jestli cheme aby ten user byl zalogovany, ale jinak  `test_server_not_logged_in` bude rvat 
![Screenshot 2023-03-02 at 20 24 27](https://user-images.githubusercontent.com/50211831/222539185-9e07a83f-43f9-43d7-9650-4227eac21f9e.png)
I kdyz dame do tech vyjimek. Pokud to nechceme tak dej prosim vedet @kubantjan

2023-03-02 20:36 UTC, krllstdn commented on txmatching/data_transfer_objects/external_patient_upload/swagger.py
> +HLACode = public_api.model('HlaCode', {
Nepodarilo se mi sprovoznit Swagger bez pridani techto duplikatnich modelu do `public_api`.  Pokud lze nejak pouzivat stejne modely pro ruzne api tak dej prosim vedet @kristinagalik

2023-03-09 13:31 UTC, abragtim commented on txmatching/data_transfer_objects/external_patient_upload/swagger.py
> +HLACode = public_api.model('HlaCode', {
Zkus

```python
import patient_api
HLACode = public_api.add_model(patient_api.HLACode.name,  # common model as for patiend_api
                               patient_api.HLACode) 
```

2023-03-09 20:28 UTC, krllstdn commented on txmatching/data_transfer_objects/external_patient_upload/swagger.py
> +HLACode = public_api.model('HlaCode', {
Dekuji, ale bohuzel toto nebude fungovat. Ackoliv, diky tomu jsem prisel na neco jineho

2023-03-09 20:34 UTC, krllstdn commented
@abragtim mas jeste neco k tomu nebo za tebe je to fajn?

2023-03-09 20:38 UTC, abragtim requested changes
Nevím, jestli se změnilo issue, ale podle mě tam je popsáno něco jiného, než tohle, co tady máš

2023-03-09 20:38 UTC, abragtim commented on txmatching/data_transfer_objects/external_patient_upload/do_crossmatch_dto.py
> +    crossmatched_antibodies: List[AntibodyMatch]
V issue je napsano, že chceme vracet typizaci, tj. HLA donora. Diskutovali jste o tom? Tady vrátíš antibodies recipienta

2023-03-09 20:38 UTC, abragtim commented on txmatching/data_transfer_objects/external_patient_upload/swagger.py
> +})
Podle mě tento model neodpovídá dataclassu HLAAntibody v hla_model.py (nejsou second_code, second_raw_code, ale v testech už je máš). Po PR Kristiny jsou tam nové změny v mastru

2023-03-11 13:56 UTC, krllstdn commented on txmatching/data_transfer_objects/external_patient_upload/do_crossmatch_dto.py
> +    crossmatched_antibodies: List[AntibodyMatch]
Tam neni napsano, ze chceme vracet cele HLA donora. Co tam napsano je, ze chceme ty typizace s crossmatchem, coz je videt na prikladu a je upresneno po nej. 
Pro jistotu jeste jsem se zeptal u @kubantjan

2023-03-11 14:08 UTC, abragtim commented on txmatching/data_transfer_objects/external_patient_upload/do_crossmatch_dto.py
> +    crossmatched_antibodies: List[AntibodyMatch]
Myslel jsem HLA typing jo. Jenom tady vrátíš HLA Antibodies, které jsou u recipienta, které obecně nejsou stejné s HLA typing donora při crossmatch

2023-03-11 14:23 UTC, krllstdn commented on txmatching/data_transfer_objects/external_patient_upload/do_crossmatch_dto.py
> +    crossmatched_antibodies: List[AntibodyMatch]
> ... zpet se poslou ty typizace doplneny MFI plus typ crossmatche ...

odkud u HLA typizace se vezme mfi? :) Ja to chapu tak, ze se museji vracet jen ty crossmatched antibodies

2023-03-11 14:54 UTC, abragtim commented on txmatching/data_transfer_objects/external_patient_upload/do_crossmatch_dto.py
> +    crossmatched_antibodies: List[AntibodyMatch]
Taky mi to zmátlo, ale možná právě v tomhle kontextu crossmatch vracet MFI s donorem není takový nesmysl. Prostě protilatka s takovým MFI působila proti HLA, kterou vrátíme. Navíc vracení crossmatch anitbodies je taky součásti tohoto issue. Není to tak, že nebudou na tom výstupu.

Prostě hlavně vidím problém v tom, že doktor chce se podívat, jak moc je kompatibilní donor pro určitého recipienta. Zadá donora s HLA "A", "B", "C" pro recipienta s antybodies "D", "E", "F". Na výstupu obdrží "E", "F".  To je hezké, ale co tou informaci má dělat. Nemusí pamatovat z hlavy jaké HLA typing vyvolali crossmatch s "E" a "F". Ideálně by možná chtěl některé vypnout u donora, protože ví  z nějakých nových studií, že možná nemusí tam být crossmatch, ale potřeboval by vědět, jaké HLA typing jsou pozitivní na crossmatch

2023-03-13 08:10 UTC, kubantjan commented
Udelat rebase nad https://github.com/mild-blue/txmatching/pull/1158 neresit dvojity zatim a asi proste potom co mam protilatky tak projekt antigeny donory a napriroazovat.

2023-03-14 12:35 UTC, krllstdn commented
Neresil jsem dvojite protilatky, proto pada swagger test kde se tomu endpointu predavaji dvojite protilatky

2023-03-15 21:36 UTC, abragtim requested changes
Pokud ještě neřešíme dvojité protilátky pro tento endpoint, tak bych přidal tady
https://github.com/mild-blue/txmatching/blob/95f768cde15a2fea50a1db7e4c5422efde86f000/tests/web/test_swagger_endpoint.py#L58-L80

výjimku pro tento endpoint + komentář s linkem na nové issue

```python
f'{API_VERSION[1:]}/{PUBLIC_NAMESPACE}/do-crossmatch': [500]  # TODO: issue
```

Navíc lze vytvořit nový exception (něco jako TxmNotImplementedFeatureException) a raisoval jej, pokud tento endpoint dostane dvojitou protilátku s message _"This functionality is not currently available for dual antibodies. We apologize and will try to change this in future versions."_

2023-03-15 21:36 UTC, abragtim commented on txmatching/web/api/public_api.py
> +        antigen_to_antibody = [HLAToAntibodyMatch(hla_code=hla, antibody_matches=[]) for hla in
Případně změnit podle nového názvu `HLAToAntibodyMatch`

2023-03-15 21:36 UTC, abragtim commented on txmatching/data_transfer_objects/external_patient_upload/swagger.py
> +HlaToAntibodyMatchJson = public_api.model('HlaToAntibodyMatch', {
```suggestion
HLAToAntibodyMatchJson = public_api.model('HlaToAntibodyMatch', {
```
+ Případně změnit podle nového názvu HLAToAntibodyMatch

2023-03-16 07:51 UTC, abragtim commented on txmatching/web/api/public_api.py
> +class TxmEventDoCrossmatch(Resource):
Ještě jsem zapomněl zeptat, proč je to pro konkrétní TxmEvent v názvu, kryž txm_event není ve vstupních argumentech? Je tam omezení, že všechno funguje v rámci určitého TXM eventu?

2023-03-16 08:04 UTC, kubantjan commented
- udelat ze kdyz nam prijde theoretical protilatka ci dvojita tak vyhodnotime ze to zatim zpracovavat neumime a vratime error
-  pridat test ktery testuje ze se tohle spravne stane
- udelat rebase nad #1158  a udelat PR do #1158 tenhle zavrit
- po rebase by swagger unittest nemel padat podle me (tzn zadny dvojity protilatky tam podle me by se nemely objevovavat)

2023-03-16 08:27 UTC, kubantjan commented on txmatching/web/api/public_api.py
> +class TxmEventDoCrossmatch(Resource):
good point, nemelo by to s TXM eventem vubec souviset. Tzn asi prosim presunout na uplne separatni path.

2023-03-16 08:54 UTC, krllstdn commented on txmatching/web/api/public_api.py
> +class TxmEventDoCrossmatch(Resource):
Nope, zadne omezeni neni. Mas pravdu to tam nedava smysl

2023-03-17 11:09 UTC, krllstdn commented
@kubantjan Jo mels pravdu, problem byl ne v swagger testeru. Tam byla malicka chyba, je jiz opravena. 
Ale jsem se zasek na presouvani na novy path. Delam vsechno podle navodu, ale neco mi porak unika - namespace se nepridava do swaggeru a tim padem endpoint taky. Mohl bys prosim mrknout co delam spatne?

2023-03-21 08:32 UTC, closed without merging