Alter the logic of parse_hla_antibodies_raw_and_return_parsing_issue_list
mild-blue/txmatching pull request #1158
Opened 2023-02-26 12:21 UTC by kristinagalik

Closes #1138

2023-03-08 08:40 UTC, kubantjan commented
tak odpovedi:
- je to tak, jen antibodies, ten prepis dava smysl
- cutoffy by mely byt stejny pro protilatku globalne, dokonce bych rekl ze mi tady asi dava smysl aby byl stejny cutoff pro celou hla group, jinak by to mohlo delat bordel. Tak mozna tak bych to checknul, ze cela hla group ma stejny cutoff, pak se vrati i ta parsing issue u toho DQA1*06:01
- ok
- odpovezeno vyse
- tomu poslednimu nerozumim, co znamena sprasovane chains?

2023-03-08 09:01 UTC, kubantjan requested changes
pouzivani toho "single_chain" je standartni? nebo to sis vymyslela? 

ma to znamenat single_chain = antibody co ma jen jeden kod jo?

2023-03-08 12:08 UTC, kristinagalik commented
* cutoffy: oki idem zmenit pozeranie cutoffov
* single_chain: jop to ma byt antibody s jednou chainou, mam to radsej prepisat na `single_chain_antibody` alebo nieco take?

2023-03-09 10:20 UTC, abragtim commented on txmatching/patients/hla_functions.py
> +                            double_antibody, get_average_mfi, mfi_dictionary))
```suggestion
_join_absolute_positive_unparsed_antibodies_with_average_mfi(...)
```

2023-03-09 10:20 UTC, abragtim commented on txmatching/patients/hla_functions.py
> +                                double_antibody, get_negative_average_mfi, mfi_dictionary))
Na to bych taky udělal zvláštní funcki, jen jsem nevymyslel název + možná by tato funkce mohla odstranit duplicitu v nasledujicím if. 
Taky asi by bylo dobré přidat vysvětlujicí komentář, proč pro mixed děláme average jen pro negative.

2023-03-09 10:20 UTC, abragtim commented on txmatching/patients/hla_functions.py
> +                            double_antibody, get_average_mfi, mfi_dictionary, HLAAntibodyType.THEORETICAL))
```suggestion
_join_as_theoretical_antibody(...)
```

2023-03-14 00:01 UTC, kristinagalik commented
@kubantjan otazka zo zvedavosti (ktorej odpoved potom pojde ako koment do kodu) - v issue je takato cast: 

"ta positive je jen tato jedna, nebo uz dalsi positive neni na rade, pak proste mfi je prumer tech negative"

a teda v kode to je podla algoritmu, ale len cisto z toho ako to funguje v praxi - preco sa pocita priemer *len* negative?

2023-03-15 10:49 UTC, kubantjan commented
no protoze se predpoklada, ze ty pozitivni jsou zpusobeny pozitivnosti tech druhych chainu, takze by ty hodnoty nemely vstupovat do toho prumeru. @kristinagalik jasne?

2023-03-15 11:16 UTC, abragtim requested changes

2023-03-15 11:16 UTC, abragtim commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +    if hla_raw_code is None:
Je to kvůli tomu, že můžeme sem poslat optional second_raw code? Podle mě tohle ověření by muselo být mimo tuto funkci. Prostě chceme, aby funkce parse_hla_raw_code_and_return_parsing_issue_list zparsovala ten raw code a vrátila parsing issue list. V případě nevalidního vstupu by měla raisovat error. Může to v budoucnosti způsobit bug

2023-03-15 11:16 UTC, abragtim commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +                hla_antibody.secondary_raw_code)
Asi by bylo dobré mít to sjednocené, ne? Všude máme `second_raw_code`

2023-03-16 13:33 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +    if hla_raw_code is None:
jaj no to nema byt check, ale skor na to, aby nemuselo byt X podmienok v kode v zmysle ze:

```
first_code_parsed = parse_hla_raw_code_and_return_parsing_issue_list(antibody.raw_code)
if antibody.second_raw_code is not None:
    second_code_parsed = ...

if second_code_parsed is not None:
...
```

lebo aj tak vlastne sa to bud len ulozi do dakeho objektu kde to ma byt None, alebo su z toho parsing issues a tie ked sa vratia len ako prazdny list tak sa nic nedeje

2023-03-16 15:28 UTC, abragtim commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +    if hla_raw_code is None:
Nebude to moc řádků navíc
```python
second_code_parsed = parse_hla_raw_code_and_return_parsing_issue_list(antibody.second_raw_code)[1] \
        if second_raw_code is not None else None
```

Jinak prostě, pokud nějakou náhodou nastane situace, že pošleme ne second_raw_code jako None, ale raw_code a chceme dostat jenom parsing issue, tak prostě uvidíme, že na staging nebo production vstup, který normálně by měl vyvolat parsing issue a možná i několik vrací prázdný seznam. Tak se prostě dostaneme do situace, kdy TXM pročítá špatně a navíc s žádným errorem v logech. Určitě je větší šance, že ERROR log uvidíme rychleji a napravíme bug, než 0 parsing issues na FE pro nějaký random HLAs

2023-03-16 15:54 UTC, abragtim commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> +                hla_antibody.secondary_raw_code) if hla_antibody.secondary_raw_code is not None else None
Bacha tady, že chceme antibody_parsing_issues_second_code jako prazdný list

2023-03-17 11:11 UTC, abragtim requested changes
Poslední věc :)

2023-03-17 11:11 UTC, abragtim commented on txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
> -
```python
if not isinstance(hla_raw_code, str):
    raise TypeError(f"expected hla_raw_code as a string, got {type(hla_raw_code)}")
```

Pokud to nespadne tady, tak spadne až v try_get_hla_high_res se stejným errorem, který stejně handlujeme s kodem 500. Tak ať už spadne tady, než někde dál. Bude jednodušší pro debug.

2023-03-19 08:22 UTC, abragtim approved these changes

2023-03-23 10:11 UTC, abragtim submitted a review, later dismissed
List of changes by @kubantjan 

1. generate_patients.py tvoří teď i recipienty s dvojitými protilátkami pro HLAGroups DP a DQ.
2. generate_antibodies() tvoří teď i recipienty s dvojitými protilátkami pro HLAGroups DP a DQ.
3. přidání parsing issue při tvorbě DB.
4. database s double protilátkami
5. Test AllSolutionSolver s double
6. create_antibody teď vrací HLAAntibodyRaw. Teď HLAAntibody vrací nová funkce create_antibody_parsed (s tím taky souvisí zjednodušení funkce create_antibodies.
7. ParsingIssueBase je teď immutable typ.
8. Dostáváme antibody type z DB (RecipientModel)
9. UNDECIDABLE je v MATCHING_TYPE_ORDER
10. Zaokrouhlení average MFI na celá čísla.
11. Fix testů pro double antibodies
12. V test_patient_api checkujeme teď nejen počet errorů, ale i jaké jsou.
13. Hodně reformat (nejpopulárnější je "" -> '') + refactoring
14. Další změny, ke kterém mám komentáře přímo v kódu

2023-03-23 10:11 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                                                  cutoff=antibody.cutoff)
Nemá tady být takhle? Alespoň jsme to kontrolovali předtím, pokud hledali tu second_antibody.
```python
second_antibody = HLAAntibody(raw_code=antibody.second_raw_code, code=antibody.second_code,
                              second_raw_code = antibody.raw_code, second_code = antibody.code,
                              mfi=antibody.mfi,
                              cutoff=antibody.cutoff)
```

2023-03-27 19:32 UTC, kristinagalik commented on local_testing_utilities/generate_patients.py
> +    confirm_all_parsing_issues(1)
tototu musi byt kvoli testom ktore pouzivaju explicitne len tuto funkciu, inak by padali

2023-03-27 19:38 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                                                  cutoff=antibody.cutoff)
uz nie, lebo tam neni potrebna info o tom ze su to "dvojite" antibodies, proste len potrebujes info ci kazda separatne ma crossmatch

2023-03-27 19:43 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
> +        return hash((self.hla_code_or_group, self.parsing_issue_detail.name, self.message))
hashing nehovori nic o mutability classy ci? `frozen=True` len hovori ze "urob objekty tejto classy immutable" a hash len vrati hash urobeny custom sposobom na lahsie ukladanie infa o classe

2023-03-27 19:54 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
> +        return hash((self.hla_code_or_group, self.parsing_issue_detail.name, self.message))
plus nechces to robit vlastne ani ako immutable classu, lebo `ParsingIssue` inherituje z `ParsingIssueBase` a `ParsingIssue` musi byt mutable (kvoli confirmations a pod.) a nejde urobit to, ze mutable classa inherituje z immutable

2023-03-27 20:02 UTC, kristinagalik commented on txmatching/patients/hla_functions.py
> +
ak je len jeden MFI (alebo teda lepsie povedane antibody, ktora ma jeden chain, a vyskytuje sa len raz), tak to je to co je po novom ocakavane. ale ak sa bude napr kod "DQA*01:01" vyskytovat 3x, tak sa to sparsuje starou logikou co tam bola doteraz, a ta je zavedena vo funkcii `get_mfi_from_multiple_hla_codes_single_chain` 

ale niesom si asi ista co presne sa pytas

2023-03-27 20:48 UTC, abragtim commented on txmatching/patients/hla_functions.py
> +
Myslel jsem si, že teď v případě, když code je jen jednou, nastavujeme MFI a cutoff přímo z antibody_group_list[0].mfi. Pokud se podíváme do funkce `get_mfi_from_multiple_hla_codes_single_chain`, tak vypořádá s jenom jednou hodnotou MFI obdobným způsobem, že ji prostě vrací bez parsing issues. Což vypadá jako duplicita logiky počítání MFI, pokud je jen jednou.
Pokud v budoucnu budeme chtít přidat nějaká Parsing Issues, pokud je jedno MFI nějaké krásné překrásné. Tak budeme muset tohle změnit jak v get_mfi_from_multiple_hla_codes_single_chain, tak i v _add_single_hla_antibodies. 

Když teď přemýšlím nad tím, tak tato logika pro jen jedno MFI možná se nikdy nezmění, ale pokud get_mfi_from_multiple_hla_codes_single_chain je jen pro historická data, tak asi je to opravdu dobrý, když tato deprecated HLAs budou řešené úplně separátně, abychom tuto funkci už nikdy nepožívali

2023-03-27 21:05 UTC, abragtim commented on local_testing_utilities/generate_patients.py
> +    confirm_all_parsing_issues(1)
Tak bych v tomto případě trochu víc uklidil kód, který je spojen s touto funkcí. Pokud používáme tuto funkci, tak nechceme dělat confirm po ní  (confirm dvakrát).
Ještě bych udělal, aby vracela None. V místech, kde berou return value (asi je jen jednou), brali bychom txm_exent pomocí get_txm_event_complete. 

+nahradit jedničku pomocí admin id.

2023-03-28 09:46 UTC, kubantjan commented on tests/database/services/test_update_donor_recipient.py
> +                                                   HLAAntibodyUpdateDTO(mfi=20, raw_code='DQ[01:03,      06:03]')
netusim to je nejaky sotek co se tam dostal, to muzeme revertnout

2023-03-28 09:47 UTC, kubantjan commented on local_testing_utilities/generate_patients.py
> -        if not undecidable:
to jsem asi rychleji kodil nez myslel, to tam asi muzeme nechat.

2023-03-28 09:47 UTC, kubantjan commented on local_testing_utilities/generate_patients.py
> +    # HLAGroup.CW: get_codes(HLAGroup.CW, used_as_antibody=True),
jo muzem

2023-03-28 09:47 UTC, kubantjan commented on local_testing_utilities/generate_patients.py
> +    blood_groups = [BloodGroup.ZERO, BloodGroup.A, BloodGroup.B, BloodGroup.AB]
asi mohlo zustat, uprimne nevim, revertneme

2023-03-28 09:48 UTC, kubantjan commented
@kristinagalik  doplneno ty komentare co zbyvaly, dotahnes to prosim? (jeste pada test)

2023-03-29 09:08 UTC, kubantjan approved these changes

2023-03-29 09:08 UTC, merged