Show cpra and compatible donors in patients list
mild-blue/txmatching pull request #1159
Opened 2023-02-28 15:52 UTC by jakubmonhart

Closes #1145

Zde zatím řeším pouze backend část.

Čas jsem zatím zkoušel na datech vytvořených přes `populate_large_db.py`. Zpomalení je tam z ~1.6s na ~2.9s (cca stejně pro oba txm eventy). Je potřeba otestovat i na větších datech?

GET endpoint v AllPatients je využíván i při načítání stránky matching. Pokud task chápu správně, tam ale není seznam kompatibilních donorů pro každého recipienta potřeba, posílání těchto údajů by tedy mohlo být optional?

Funkce `get_cpra_and_detailed_compatibility_of_recipient_with_donors` by asi dávala větší smysl někde v `patients/patient.py` u `calculate_cpra_and_get_compatible_donors_for_recipient` (a ideálně obě funkce spojit?), ale momentálně používám funkci `get_detailed_score`, kterou bych tak musel přesunout taky a dělat úpravy v `donor_to_donor_dto_out`, můžu to udělat v rámci tohoto issue?

2023-03-02 07:20 UTC, kubantjan requested changes
Par poznamek:

1) get_cpra_and_detailed_compatibility_of_recipient_with_donors a calculate_cpra_and_get_compatible_donors_for_recipient urcite spojit. ted tam duplikujes logiku kterou urcite duplikovat nechceme. presunout fci muzes, ale snaz se urcite delat upravy minimalni, jen co souvisi primo s timto issue.

2) Ano tam neni posilani zatim potreba, ale to bych pripadne resil az na zaver, kdyz bod 4) nepomuze. 

3) pridal jsi ted ze se vraci neco noveho v tom getAllpatients endpointu. Tak otestovat by to chtelo tam, ze to API fakt vrati ted ted cely objekt s timto. To jak jsi pridal ted testovani je takovy ze to snad kvuli bodu 1 prestane davat smysl. V zasade ted tema testama testujes ze jsi napsal fci co dela to samy co ta stara fce coz trosku i vede k tomu ze to neni napsany vhodne. 

4) Zpomaleni ktery to ted zpusobi je celkem signifikantni. Mrkni proc to beha pomalu co nejvic zdrzuje a zkus rict zda je to vsechno nutny. Zda by napriklad pomohlo pro zrychleni vyuzit napocteny compatibility graph, ktery pro pripady, kdy uz bude v databazi napocitany matching je spocteny. Na zaklade toho co zjistis, se pak dohodnem co tam udelat.

2023-03-03 12:37 UTC, jakubmonhart commented
Casove ted nejvíce zdrzuje error logging (zdroj velkeho mnozstvi logů viz nize). Loguji defaultne do console i .log souboru, v takovem pripade trva funkce `to_lists_for_fe` ~2.5s, pri logovani pouze do .log souboru klesne cas na ~1.5s, bez logovani je to ~1.1s . Na master branch pro porovnani stejny vypocet trva ~0.7s .

Velke mnozstvi error logu ma puvod ve funkci `compatibility_index.py:309(_check_if_correct_amount_of_hla_types)`. Pri volani `to_lists_for_fe' je tento check zavolan >7000x , z toho ~2000x se loguje error, ktery zaroven printi cely objekt `HLAPerGroup`, coz v kombinaci s vypisovanim do console evidentne vede k tomu velkemu zdrzeni. Check byl pridan v #1142 .

Commitnul jsem profile vysledky funkce `to_lists_for_fe` do `local_testing_utilities/profile_results`. Jsou tam i vysledky pro vypnute logovani.

Pokud tedy neuvazujeme logovani, je to zpomaleni podstatne mensi. Zbyvajici zpomaleni je zpusobeno prevazne volanim `get_crossmatched_antibodies` pro zjisteni zda jsou recipient-donor kompatibilni, `antibodies` ktere ta funkce vraci jsou ale potreba na vypocet pouze pokud je zjistena kompatibilita (coz je na datech z `populate_large_db.py` pouze v ~20%). Zde by tedy slo neco usetrit vyuzitim predpoctene kompatibility z matchingu.

Dale dost casu padne na `hla_additive_scorer.py:48(score_transplant_calculated)`, kde se pocita `get_detailed_compatibility_index` ktery uz ale pocitam drive. Ten scorer ziskavam na zaklade parametru z `scorer_from_configuration'. Zatim myslim existuje jenom ten  `HLAAdditiveScorer`, ktery je pouzivan, takze by bylo mozne mu predpoctene informace uz dat a dosahnout dalsiho zrychleni. Pokud by ale mel v budoucnu pribyt jiny scorer ktery pocita score jinak, bude to potreba osetrit.

2023-03-03 12:40 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +        antibodies = crossmatch_logic(
Zde se pocitaji antibodies pro kazdy donor-recipient par podle kterych je rozhodnuta kompatibilita. Antibodies jsou ale pouzita jenom v pripade kompatibility a vetsinou jsou proto zahozena.

2023-03-03 12:44 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +                    score=scorer.score_transplant(donor, recipient, None),
Pri vypoctu score je pouzivan uvnitr `scorer` znovu vypocet `get_detailed_compatibility_index`, ktery delam o par radku vyse. Vyuzitim predchoziho vyslekdu by tedy melo byt volani `get_detailed_compatibility_index` redukovano na polovinu.

2023-03-03 12:51 UTC, jakubmonhart commented on local_testing_utilities/profile_results/profile_high_res_with_logging.txt
> +     7260    0.047    0.000    1.199    0.000 compatibility_index.py:309(_check_if_correct_amount_of_hla_types)
Tady je ten check ktery zpusobuje hodne error logu (viz radek 14 nize).

2023-03-03 12:53 UTC, jakubmonhart commented on local_testing_utilities/profile_results/profile_high_res_without_logging.txt
> +     1478    0.007    0.000    0.322    0.000 hla_crossmatch.py:28(get_crossmatched_antibodies)
Zde je videt ze vypocet anitbodies bere dost casu i kdyz vysledek neni ve velkem poctu donor-recipient paru vyuzivan kvuli nekompatibilite.

2023-03-03 12:54 UTC, jakubmonhart commented on local_testing_utilities/profile_results/profile_high_res_without_logging.txt
> +      452    0.006    0.000    0.237    0.001 compatibility_index.py:99(get_detailed_compatibility_index)
Tohle by melo byt mozne redukovat posilanim predpocitanych dat do `scorer`.

2023-03-10 16:33 UTC, kubantjan commented
@jakubmonhart 
> Spatne jsem pochopil vztah donora a jeho related recipienta. Nemusi byt kompatibilni (muzou mit positivni hla crossmatch), je to tak? 

**ano je to tak**

> TestCPRACalculation proto ted neni validni, protoze calculate_cpra_and_get_compatible_donors_for_recipient nevraci detail kompatibility donora a related recipienta pokud jsou kompatibilni. Stejne tak kvuli tomu musim opravit test_get_patients, podivam se na to. Na tom reseni zpomaleni by to ale nic menit nemelo.

 **OK**

> Mam jeste doplnujici dotaz k tomu co je v tomto issue chapano jako kompatibilni par. Staci, aby recipient a donor nemeli positivni hla crossmatch? Protoze scorer i pro pary ktere positivni crossmatch nemaji nekdy vypocte -1 (TRANSPLANT_IMPOSSIBLE_SCORE) kvuli jinym kriteriim. Mam tohle brat v potaz pri vypoctu tech kompatibilnich donoru? cPRA dle definice v documentation bych stale pocital jenom na zaklade hla crossmatch.

**Ano, berte to v potaz a ano cpra bychom pocitali jen na zaklade crossmatche zatim**

> Logovani ze je tam moc HLA kodu
**Zkuste prosim zjednodusit tu hlasku (zni to ze je zbytecne bloated a to zbytecne zpomaluje) + prosim v populate large db by ty multiple hla code warningy se dit nemely, nema to tam zadne opodstatneni, tak se prosim mrknete v jakych pripadech se to deje a zkuste to jeste v ramci tohoto issue opravit (pripadne se ptejte). To bude nejspravnejsi reseni.**

uvidime, jak to bude po tetchto upravach, pripadne pak se mrkneme na ty jine upravy, ktere navrhujete.

2023-03-10 16:42 UTC, kubantjan requested changes
viz komentar

2023-03-10 19:18 UTC, abragtim requested changes

2023-03-10 19:18 UTC, abragtim commented on txmatching/patients/recipient_compatibility.py
> +                compatible_donors_details.append(recipient_donor_compatibility_details)
@kubantjan , takhle představujeme informaci o kompatibilitě donoru a recipientů? Když jsem četl toto issue, tak se mi zdálo, že možná nepotřebujeme tolik informaci v tom endpointu , jen ty donory chceme nějak číselně porovnávat přes scorer nebo možná i přes compatibility index (pokud je to docela validní kriterium pro imunology). Jak by to chtěli v IKEM?

2023-03-10 19:18 UTC, abragtim commented on txmatching/patients/recipient_compatibility.py
> +    Calculates cPRA for recipient (which part of donors [as decimal] is compatible) for txm_event and returns list of
```suggestion
    Calculates cPRA for recipient (which part of donors [as decimal] is incompatible) for txm_event and returns list of
```

2023-03-13 22:12 UTC, jakubmonhart commented
@kubantjan 

> > Logovani ze je tam moc HLA kodu
> > **Zkuste prosim zjednodusit tu hlasku (zni to ze je zbytecne bloated a to zbytecne zpomaluje) + prosim v populate large db by ty multiple hla code warningy se dit nemely, nema to tam zadne opodstatneni, tak se prosim mrknete v jakych pripadech se to deje a zkuste to jeste v ramci tohoto issue opravit (pripadne se ptejte). To bude nejspravnejsi reseni.**
> 
> uvidime, jak to bude po tetchto upravach, pripadne pak se mrkneme na ty jine upravy, ktere navrhujete.

Ten error je vždy odtud: https://github.com/mild-blue/txmatching/blob/5afabae3a603030602341fb517168de8068f7045/txmatching/utils/hla_system/compatibility_index.py#L313-L318

Ten check tam vyžaduje aby hla_typing obsahoval alespoň jednu sekvenci typu DPA i DPB (a stejně pro DQ). Podle txmatching/documentation by to sedělo, ale ta data nahraná přes populate_large_db (koukám se teď konkrétně na high_res_example_data) tomu často neodpovídají: 
Pacient má například DPB1\*509:01, DPB1\*388:01, DQA1\*03:03, DQA1\*06:02, což checkem neprojde. 

Výše jsem zmiňoval, že tato část checku byla přidáná v nedávném PR, kde je asi relevantní tento komentář (?): https://github.com/mild-blue/txmatching/pull/1142#issuecomment-1413849651 
Nebyl ten komentář myšlen tak, že skupina DP/DQ prostě musí obsahovat minimálně 2 sekvence (což v některých případech může být jenom typ A nebo B)? Takový případ by totiž před změnami v tom PR prošel.

2023-03-14 16:30 UTC, jakubmonhart commented on txmatching/data_transfer_objects/patients/out_dtos/conversions.py
> +            compatible_donors_details=compatibilities_details
Přemýšlel jsem jestli dát cpra a compatible_donors_details rovnou do Recipient, ale nakonec jsem se rozhodl po vzoru DonorDTOOut dát tyto informace do RecipientDTOOut. Pokud ty informace budou v budoucnu používané i v nějaké jiné části backendu, dávalo by asi smysl to dát spíš do Recipient no. Takhle teda nevím co je lepší řešení.

2023-03-14 16:38 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +                compatible_donors_details.append(recipient_donor_compatibility_details)
> Tento task je o tom, aby se na FE zobrazoval na strance patients u kazdeho recipienta seznam kompatibilnich donoru. **Tzn jak tam je ted videt jen overview compatibility originalniho donora, tak ted pod tim, kdyz bude uzivatel scrolovat tak uplne stejne bude videt i ty potencialni donory).**

Chápu to tak že na FE má být pro každý kompatibilní pár recipient-donor stejná tabulka jako teď pro donora a related recipienta. Takže vlastně posílám to stejné co se počítá v donor_to_donor_dto_out().

2023-03-14 18:12 UTC, abragtim commented on txmatching/data_transfer_objects/patients/out_dtos/conversions.py
> +            compatible_donors_details=compatibilities_details
Myslím si, že Recipient je opravdu dobrá volba pro tuto metodu. Už je to druhý endpoint, který používá tuto funkci. 
Pokud tohle moc nezabere (neobjeví se nějaké problémy jako cyklické importy), tak bych to udělal. Jestli se tam něco takového divného objeví, že to bude potřebovat ne jenom migraci této metody s drobnými úpravy, tak bych to zatím nechal jak to je

2023-03-15 10:57 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +                compatible_donors_details.append(recipient_donor_compatibility_details)
@abragtim nn chceme tam mit fakt vsechno info,

@jakubmonhart  to pise spravne, chceme tam ty informace mit komplet.

2023-03-15 11:18 UTC, kubantjan commented
> Ten check tam vyžaduje aby hla_typing obsahoval alespoň jednu sekvenci typu DPA i DPB (a stejně pro DQ). Podle txmatching/documentation by to sedělo, ale ta data nahraná přes populate_large_db (koukám se teď konkrétně na high_res_example_data) tomu často neodpovídají: Pacient má například DPB1*509:01, DPB1*388:01, DQA1*03:03, DQA1*06:02, což checkem neprojde.
> 
> Výše jsem zmiňoval, že tato část checku byla přidáná v nedávném PR, kde je asi relevantní tento komentář (?): [#1142 (comment)](https://github.com/mild-blue/txmatching/pull/1142#issuecomment-1413849651) Nebyl ten komentář myšlen tak, že skupina DP/DQ prostě musí obsahovat minimálně 2 sekvence (což v některých případech může být jenom typ A nebo B)? Takový případ by totiž před změnami v tom PR prošel.


@jakubmonhart super, je to presne tak jak pisete, mame tam chybu v tomto checku. Na toto udelame rovnou nove issue, kde to opravime

Timto bych povazoval toto tema rychlosti temer za vyresene. Jeste vas poprosim o jednu vec: muzete zkontrolovat, zda ve 100% je ta error hlaska zpusobena timto (tzn ze chybi chain A k B ci naopak? Zetam neni zadny jiny duvod?

2023-03-15 11:21 UTC, kubantjan commented on txmatching/data_transfer_objects/patients/out_dtos/conversions.py
> +            compatible_donors_details=compatibilities_details
@abragtim  @jakubmonhart  nechcme to zatim takto. tzn ze to neni v objektu recipienta ale az v tom DTO. Ono nekdy to vracet nebude treba a zbytecne tim zas objekt recipienta narusta.

2023-03-15 11:28 UTC, kubantjan requested changes
Jeste par malych komentaru ale jsme temer hotovi:
- [x] prosim rebase na nejnovejsi master
- [x] prosim uklidit text commitu. Vzdy velke pismeno, na konci tecka, fakt aby to byla veta. (vzdy to na 100% v nasich historickych commitech nemame ale chceme se o to snazit)
- [x] overeni toho, ze ty error hlasky, ktere zpomaluji jsou opravdu vsechny zpusobeny jen tim spatnym checkem jak tam resime v komentarich
- [x] Jeste dnes finalne kod jednou projdu a pripadne jeste napisu nejaky komentar.

2023-03-15 12:15 UTC, jakubmonhart commented
> - [ ] overeni toho, ze ty error hlasky, ktere zpomaluji jsou opravdu vsechny zpusobeny jen tim spatnym checkem jak tam resime v komentarich

Kontroloval jsem to, error je jenom z toho spatneho checku.

>> Mam jeste doplnujici dotaz k tomu co je v tomto issue chapano jako kompatibilni par. Staci, aby recipient a donor nemeli positivni hla crossmatch? Protoze scorer i pro pary ktere positivni crossmatch nemaji nekdy vypocte -1 (TRANSPLANT_IMPOSSIBLE_SCORE) kvuli jinym kriteriim. Mam tohle brat v potaz pri vypoctu tech kompatibilnich donoru? cPRA dle definice v documentation bych stale pocital jenom na zaklade hla crossmatch.
>
> Ano, berte to v potaz a ano cpra bychom pocitali jen na zaklade crossmatche zatim

K tomuto mám vlastně další dotaz: funkce `calculate_cpra_and_get_compatible_donors_for_recipient` je využívána i v tom endpointu `CalculateRecipientCPRA`. Tam stále vracet kompatibilní donory jenom na základě hla crossmatche, nebo brát ohled i na ty další podmínky tak jak to budu dělat v endpointu `AllPatients`? Funkce `calculate_cpra_and_get_compatible_donors_for_recipient` má tedy vracet:
- cpra (podle crossmatch), compatible_donors (Set[int]; podle crossmatch), compatible_donors_details (List[RecipientDonorCompatibilityDetails]]; podle celkoveho score)

nebo:
- cpra (podle crossmatch), compatible_donors (Set[int]; podle celkoveho score), compatible_donors_details (List[RecipientDonorCompatibilityDetails]]; podle celkoveho score) ?

2023-03-15 14:31 UTC, kubantjan commented
> > * [ ]  overeni toho, ze ty error hlasky, ktere zpomaluji jsou opravdu vsechny zpusobeny jen tim spatnym checkem jak tam resime v komentarich
> 
> Kontroloval jsem to, error je jenom z toho spatneho checku.
> 
> > > Mam jeste doplnujici dotaz k tomu co je v tomto issue chapano jako kompatibilni par. Staci, aby recipient a donor nemeli positivni hla crossmatch? Protoze scorer i pro pary ktere positivni crossmatch nemaji nekdy vypocte -1 (TRANSPLANT_IMPOSSIBLE_SCORE) kvuli jinym kriteriim. Mam tohle brat v potaz pri vypoctu tech kompatibilnich donoru? cPRA dle definice v documentation bych stale pocital jenom na zaklade hla crossmatch.
> > 
> > 
> > Ano, berte to v potaz a ano cpra bychom pocitali jen na zaklade crossmatche zatim
> 
> K tomuto mám vlastně další dotaz: funkce `calculate_cpra_and_get_compatible_donors_for_recipient` je využívána i v tom endpointu `CalculateRecipientCPRA`. Tam stále vracet kompatibilní donory jenom na základě hla crossmatche, nebo brát ohled i na ty další podmínky tak jak to budu dělat v endpointu `AllPatients`? Funkce `calculate_cpra_and_get_compatible_donors_for_recipient` má tedy vracet:
> 
> * cpra (podle crossmatch), compatible_donors (Set[int]; podle crossmatch), compatible_donors_details (List[RecipientDonorCompatibilityDetails]]; podle celkoveho score)
> 
> nebo:
> 
> * cpra (podle crossmatch), compatible_donors (Set[int]; podle celkoveho score), compatible_donors_details (List[RecipientDonorCompatibilityDetails]]; podle celkoveho score) ?

b) podle celkoveho skore bude davat smysl. jedine CPRA ponechme ciste podle crossmatche

2023-03-15 22:36 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +        if len(common_codes) == 0: # donor is compatible with the recipient
Přemýšlím jak tu duplicitu vyřešit. `antibodies` totiž později využívám k výpočtu `detailed_score`, takže nahradit celou tu logiku funkcí `is_positive_hla_crossmatch` (což by bylo nejpřehlednější) by znamenalo pak znovu počítat už vypočtené `antibodies`.  Napadá mě vyjmout ten výpočet `common_codes` z  `is_positive_hla_crossmatch` do samostatné funkce kterou pak použít i tady, ale ta duplicita celkové logiky zůstane. Napadá vás nějaké řešení?

2023-03-16 11:28 UTC, kubantjan requested changes
Par komentaru. V zasade hlavni vystup z nich je:

prosim dopln za tebe co by se melo stat v https://github.com/mild-blue/txmatching/issues/1163 aby se vyresily ty problemy na ktery se odkazujes.

2023-03-16 11:28 UTC, kubantjan commented on txmatching/utils/hla_system/detailed_score.py
> +    assert len(antibodies) == len(compatibility_index_detailed)
assert je jen pro debuging a testing, nepatri do produkcniho kodu. TAdy se to da brat jako jakasi dokumentace.

spravny reseni by tady melo byt ze ty dva objekty budou jeste nejak zabaleny a nadefinovany, aby se tohle proste stat nemohlo. Coz ted ale neresme a tady to ted asi prozatim nechcme. 

Ale pridej sem hlasku, co se pokazilo. A co s tim (tzn hele jsou tady dva objekty co nemaji stejne hla groups i kdyz by mely asi mame bug, neco takovyho) at ta dokumentacni vlastnost je zrejmejsi

2023-03-16 11:28 UTC, kubantjan commented on txmatching/utils/hla_system/detailed_score.py
> +        assert antibody_group.hla_group == compatibility_index_detailed_group.hla_group
stejne tak tady (ze je spatny poradi asi) je ta hlaska

2023-03-16 11:28 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +        antibodies = crossmatch_logic(
jop, souhlas, to proste udleame do budoucna

2023-03-16 11:51 UTC, kubantjan commented
> > Ten check tam vyžaduje aby hla_typing obsahoval alespoň jednu sekvenci typu DPA i DPB (a stejně pro DQ). Podle txmatching/documentation by to sedělo, ale ta data nahraná přes populate_large_db (koukám se teď konkrétně na high_res_example_data) tomu často neodpovídají: Pacient má například DPB1_509:01, DPB1_388:01, DQA1_03:03, DQA1_06:02, což checkem neprojde.
> > Výše jsem zmiňoval, že tato část checku byla přidáná v nedávném PR, kde je asi relevantní tento komentář (?): [#1142 (comment)](https://github.com/mild-blue/txmatching/pull/1142#issuecomment-1413849651) Nebyl ten komentář myšlen tak, že skupina DP/DQ prostě musí obsahovat minimálně 2 sekvence (což v některých případech může být jenom typ A nebo B)? Takový případ by totiž před změnami v tom PR prošel.
> 
> @jakubmonhart super, je to presne tak jak pisete, mame tam chybu v tomto checku. Na toto udelame rovnou nove issue, kde to opravime
> 
> Timto bych povazoval toto tema rychlosti temer za vyresene. Jeste vas poprosim o jednu vec: muzete zkontrolovat, zda ve 100% je ta error hlaska zpusobena timto (tzn ze chybi chain A k B ci naopak? Zetam neni zadny jiny duvod?

Za chvili mergneme to co by tohle melo fixnout (https://github.com/mild-blue/txmatching/pull/1165) pak vas jeste poprosim o rebase a test toho, ze to skutecne pomohlo.

2023-03-16 13:30 UTC, jakubmonhart commented on tests/patients/test_cpra_calculation.py
> +        self.config_parameters_general = ConfigParameters(use_high_resolution=True, # TODO
To jsem tam nechal pro sebe (a zapoměl odstranit -> odstraním to v dalším commitu) abych se zeptal:
Tím že teď ten seznam kompatibilnich donoru bude počítán na základě score (a ne jenom podle crossmatche), vzniká tam zase závislost testů na config_parameters. Mám počítat s nějakými defaultními hodnotami (tedy SplitScorer) a testy udělat podle toho, nebo tady bude vhodnější nějaké jiné řešení které zahrnuje další možnosti?
Nejsem si celkově jistý kolik různých případů ideálně testovat tady, když je scorer i hla_crossmatch testovaný jinde samostatně (ať tedy nevytvářím redundantní testy).

2023-03-16 16:34 UTC, jakubmonhart commented
> > > Ten check tam vyžaduje aby hla_typing obsahoval alespoň jednu sekvenci typu DPA i DPB (a stejně pro DQ). Podle txmatching/documentation by to sedělo, ale ta data nahraná přes populate_large_db (koukám se teď konkrétně na high_res_example_data) tomu často neodpovídají: Pacient má například DPB1_509:01, DPB1_388:01, DQA1_03:03, DQA1_06:02, což checkem neprojde.
> > > Výše jsem zmiňoval, že tato část checku byla přidáná v nedávném PR, kde je asi relevantní tento komentář (?): [#1142 (comment)](https://github.com/mild-blue/txmatching/pull/1142#issuecomment-1413849651) Nebyl ten komentář myšlen tak, že skupina DP/DQ prostě musí obsahovat minimálně 2 sekvence (což v některých případech může být jenom typ A nebo B)? Takový případ by totiž před změnami v tom PR prošel.
> > 
> > 
> > @jakubmonhart super, je to presne tak jak pisete, mame tam chybu v tomto checku. Na toto udelame rovnou nove issue, kde to opravime
> > Timto bych povazoval toto tema rychlosti temer za vyresene. Jeste vas poprosim o jednu vec: muzete zkontrolovat, zda ve 100% je ta error hlaska zpusobena timto (tzn ze chybi chain A k B ci naopak? Zetam neni zadny jiny duvod?
> 
> Za chvili mergneme to co by tohle melo fixnout (#1165) pak vas jeste poprosim o rebase a test toho, ze to skutecne pomohlo.
> 
> EDIT tak uz merged :) @jakubmonhart

Od erroru to pomohlo.

Ale po rebase nad #1153 se podstatně zpomalil výpočet `do_crossmatch_in_type_a`. To postihuje jenom high_res_example_data. Načtení stránky patients ně teď trvá přes 3s. tady je kousek výstupu z profile funkce `to_lists_for_fe`:

 ```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      2/1    0.000    0.000    3.210    3.210 {built-in method builtins.exec}
        1    0.000    0.000    3.209    3.209 conversions.py:32(to_lists_for_fe)
       26    0.006    0.000    2.582    0.099 recipient_compatibility.py:19(calculate_cpra_and_get_compatible_donors_for_recipient)
      867    0.005    0.000    2.574    0.003 hla_crossmatch.py:32(get_crossmatched_antibodies)
      867    0.110    0.000    2.491    0.003 hla_crossmatch.py:176(do_crossmatch_in_type_a)
   229020    0.475    0.000    1.690    0.000 hla_crossmatch.py:317(_recipient_was_tested_for_donor_antigen)
    72828    0.061    0.000    1.623    0.000 hla_crossmatch.py:223(_do_crossmatch_for_hlas_recipient_was_not_tested_for)
    72828    0.220    0.000    0.580    0.000 hla_crossmatch.py:84(do_crossmatch_for_selected_antibodies)
       56    0.001    0.000    0.475    0.008 conversions.py:150(get_messages)
        1    0.000    0.000    0.412    0.412 conversions.py:51(<listcomp>)
       30    0.001    0.000    0.412    0.014 conversions.py:90(donor_to_donor_dto_out)
      168    0.002    0.000    0.370    0.002 session.py:1563(execute)
      168    0.000    0.000    0.330    0.002 base.py:1691(_execute_20)
      168    0.001    0.000    0.329    0.002 elements.py:329(_execute_on_connection)
      168    0.002    0.000    0.329    0.002 base.py:1523(_execute_clauseelement)
       56    0.002    0.000    0.301    0.005 parsing_issue_service.py:85(get_parsing_issues_for_patients)
      168    0.004    0.000    0.295    0.002 base.py:1768(_execute_context)
      159    0.000    0.000    0.271    0.002 additive_scorer.py:24(score_transplant)
      159    0.002    0.000    0.270    0.002 hla_additive_scorer.py:48(score_transplant_calculated)
      168    0.000    0.000    0.265    0.002 default.py:735(do_execute)
      168    0.262    0.002    0.265    0.002 {method 'execute' of 'psycopg2.extensions.cursor' objects}
      112    0.002    0.000    0.261    0.002 query.py:2756(all)
   229020    0.255    0.000    0.255    0.000 hla_crossmatch.py:318(<listcomp>)
      112    0.001    0.000    0.254    0.002 query.py:2910(_iter)
       26    0.000    0.000    0.214    0.008 conversions.py:65(recipient_to_recipient_dto_out)
       61    0.000    0.000    0.193    0.003 hla_crossmatch.py:55(is_positive_hla_crossmatch)
```

Při rebase na commit před #1153 dostávám:

```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
867    0.054    0.000    0.281    0.000 hla_crossmatch.py:80(do_crossmatch_in_type_a)
```

V #1163 je v plánu použít už vypočítáné score z compatibility matrix, ta ale nezahrnuje všechny recipient-donor kompatibilní páry na základě crossmatch, protože takový pár může mít z jiného důvodu score -1. Ale tyto páry potřebujeme pro výpočet cpra. Šlo by v rámci #1163 přepočítat i to cpra?

2023-03-16 19:05 UTC, kubantjan commented
> > > > Ten check tam vyžaduje aby hla_typing obsahoval alespoň jednu sekvenci typu DPA i DPB (a stejně pro DQ). Podle txmatching/documentation by to sedělo, ale ta data nahraná přes populate_large_db (koukám se teď konkrétně na high_res_example_data) tomu často neodpovídají: Pacient má například DPB1_509:01, DPB1_388:01, DQA1_03:03, DQA1_06:02, což checkem neprojde.
> > > > Výše jsem zmiňoval, že tato část checku byla přidáná v nedávném PR, kde je asi relevantní tento komentář (?): [#1142 (comment)](https://github.com/mild-blue/txmatching/pull/1142#issuecomment-1413849651) Nebyl ten komentář myšlen tak, že skupina DP/DQ prostě musí obsahovat minimálně 2 sekvence (což v některých případech může být jenom typ A nebo B)? Takový případ by totiž před změnami v tom PR prošel.
> > > 
> > > 
> > > @jakubmonhart super, je to presne tak jak pisete, mame tam chybu v tomto checku. Na toto udelame rovnou nove issue, kde to opravime
> > > Timto bych povazoval toto tema rychlosti temer za vyresene. Jeste vas poprosim o jednu vec: muzete zkontrolovat, zda ve 100% je ta error hlaska zpusobena timto (tzn ze chybi chain A k B ci naopak? Zetam neni zadny jiny duvod?
> > 
> > 
> > Za chvili mergneme to co by tohle melo fixnout (#1165) pak vas jeste poprosim o rebase a test toho, ze to skutecne pomohlo.
> > EDIT tak uz merged :) @jakubmonhart
> 
> @kubantjan Ano, od erroru to pomohlo.
> 
> Ale po rebase nad #1153 se podstatně zpomalil výpočet `do_crossmatch_in_type_a`. To postihuje jenom high_res_example_data. Načtení stránky patients ně teď trvá přes 3s. tady je kousek výstupu z profile funkce `to_lists_for_fe`:
> 
> ```
> ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>      2/1    0.000    0.000    3.210    3.210 {built-in method builtins.exec}
>        1    0.000    0.000    3.209    3.209 conversions.py:32(to_lists_for_fe)
>       26    0.006    0.000    2.582    0.099 recipient_compatibility.py:19(calculate_cpra_and_get_compatible_donors_for_recipient)
>      867    0.005    0.000    2.574    0.003 hla_crossmatch.py:32(get_crossmatched_antibodies)
>      867    0.110    0.000    2.491    0.003 hla_crossmatch.py:176(do_crossmatch_in_type_a)
>   229020    0.475    0.000    1.690    0.000 hla_crossmatch.py:317(_recipient_was_tested_for_donor_antigen)
>    72828    0.061    0.000    1.623    0.000 hla_crossmatch.py:223(_do_crossmatch_for_hlas_recipient_was_not_tested_for)
>    72828    0.220    0.000    0.580    0.000 hla_crossmatch.py:84(do_crossmatch_for_selected_antibodies)
>       56    0.001    0.000    0.475    0.008 conversions.py:150(get_messages)
>        1    0.000    0.000    0.412    0.412 conversions.py:51(<listcomp>)
>       30    0.001    0.000    0.412    0.014 conversions.py:90(donor_to_donor_dto_out)
>      168    0.002    0.000    0.370    0.002 session.py:1563(execute)
>      168    0.000    0.000    0.330    0.002 base.py:1691(_execute_20)
>      168    0.001    0.000    0.329    0.002 elements.py:329(_execute_on_connection)
>      168    0.002    0.000    0.329    0.002 base.py:1523(_execute_clauseelement)
>       56    0.002    0.000    0.301    0.005 parsing_issue_service.py:85(get_parsing_issues_for_patients)
>      168    0.004    0.000    0.295    0.002 base.py:1768(_execute_context)
>      159    0.000    0.000    0.271    0.002 additive_scorer.py:24(score_transplant)
>      159    0.002    0.000    0.270    0.002 hla_additive_scorer.py:48(score_transplant_calculated)
>      168    0.000    0.000    0.265    0.002 default.py:735(do_execute)
>      168    0.262    0.002    0.265    0.002 {method 'execute' of 'psycopg2.extensions.cursor' objects}
>      112    0.002    0.000    0.261    0.002 query.py:2756(all)
>   229020    0.255    0.000    0.255    0.000 hla_crossmatch.py:318(<listcomp>)
>      112    0.001    0.000    0.254    0.002 query.py:2910(_iter)
>       26    0.000    0.000    0.214    0.008 conversions.py:65(recipient_to_recipient_dto_out)
>       61    0.000    0.000    0.193    0.003 hla_crossmatch.py:55(is_positive_hla_crossmatch)
> ```
> 
> Při rebase na commit před #1153 dostávám:
> 
> ```
> ncalls  tottime  percall  cumtime  percall filename:lineno(function)
> 867    0.054    0.000    0.281    0.000 hla_crossmatch.py:80(do_crossmatch_in_type_a)
> ```
> 
> V #1163 je v plánu použít už vypočítáné score z compatibility matrix, ta ale nezahrnuje (dívám se do databáze na `compatibility_graph` v `pairing_result` ) všechny recipient-donor kompatibilní páry na základě crossmatch, protože takový pár může mít z jiného důvodu score -1. Ale tyto páry potřebujeme pro výpočet cpra. Šlo by v rámci #1163 předpočítat i to cpra?
> 
> Ještě se na ty změny podívám, jestli s tím nejde něco dělat.

hmm na optimalizaci toho vypoctu se do_crossmatch_in_type_a se pak take podivame. Zatim se budeme muset spolehnout na to #1163.

Co se tyka toho cpra, upravil jsem dle vasi poznamky 1163.

2023-03-16 21:56 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +        if len(common_codes) == 0: # donor is compatible with the recipient
Jelikož jsme řešili, že info o hla crossmatchi nepůjde z compatibility matrix vytáhnout, bude muset tahle část kódu zůstat a duplicita nebude vyřešena optimalizací. Možná bude vhodnější přidat TODO s odkazem na #1160 nebo to ještě dotáhnout v rámci tohoto PR.

2023-04-03 06:09 UTC, kubantjan commented
mreged blocked by #1163

2023-04-06 12:01 UTC, closed without merging