Add crossmatch api
mild-blue/txmatching pull request #1167
Opened 2023-03-17 10:55 UTC by krllstdn

2023-03-17 11:12 UTC, krllstdn commented
@kubantjan Jo mels pravdu, problem byl ne v swagger testeru. Tam byla malicka chyba, je jiz opravena.
Ale jsem se zasek na presouvani na novy path. Delam vsechno podle navodu, ale neco mi porak unika - namespace se nepridava do swaggeru a tim padem endpoint taky. Mohl bys prosim mrknout co delam spatne?

2023-03-17 16:12 UTC, krllstdn commented on txmatching/web/__init__.py
> +                                                 USER_NAMESPACE, enums_api, crossmatch_api, CROSSMATCH_NAMESPACE)
Ty kraso, dekuji! Takova malinkost...

2023-03-17 16:14 UTC, abragtim commented on txmatching/web/__init__.py
> +                                                 USER_NAMESPACE, enums_api, crossmatch_api, CROSSMATCH_NAMESPACE)
Náhodou to našel. Přidej tam určitě nějaký komentář do namespaces.py. To vůbec není triviální věc

2023-03-17 16:22 UTC, krllstdn commented on txmatching/web/__init__.py
> +                                                 USER_NAMESPACE, enums_api, crossmatch_api, CROSSMATCH_NAMESPACE)
Jo, dobry napad

2023-03-29 09:13 UTC, kubantjan requested changes
Jeste jeden koment plus podle toho komentare pridat nejaky testy na mix kde typizace donora je ve split a protilatky recipienta jsou high res a ze vse dobre funguje.

2023-03-29 09:13 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +                matched_hla = [hla for hla in antigen_to_antibody if hla.hla_code == match.hla_antibody.raw_code]
takhle to nemuze fungovat. To porovnani tady musi byt kdyz high res tak pres high res, kdyz split tak pres split atd.

2023-03-29 09:15 UTC, kubantjan commented
predavam na @abragtim

2023-03-29 11:13 UTC, kubantjan commented
@abragtim  je tu nejaky bordel v commitech ne? Jsou tu i nejaky co sem vubec nepatri?

2023-03-31 07:34 UTC, kubantjan requested changes
mini koment jinak ok

2023-03-31 07:34 UTC, kubantjan commented on tests/resources/sample_html_report.html
> -        <span>Mar 28, 2023 14:31:01</span>
tohle neni potreba delat ne?

2023-03-31 07:38 UTC, abragtim commented on tests/resources/sample_html_report.html
> -        <span>Mar 28, 2023 14:31:01</span>
Tohle nějak bylo vygenerováno automaticky. Teď smažu

2023-04-02 10:20 UTC, kubantjan approved these changes

2023-04-03 06:50 UTC, kubantjan requested changes
jeste testy nepatri do public_api slozky.

2023-04-05 06:36 UTC, kubantjan approved these changes

2023-04-05 06:36 UTC, merged