Add description of square bracket parsing algorithgm to README. Plus update the readme with description of how crossmatch is calculated in those cases.
mild-blue/txmatching pull request #1171
Opened 2023-03-28 20:50 UTC by abragtim

Closes #1169

2023-03-28 20:57 UTC, abragtim commented on documentation/double_antibodies_parsing/double_antibodies_parsing_algorithm.drawio
Tohle je soubor .drawio pro https://app.diagrams.net/ (tam jsem vytvořil to pdf dole)

2023-03-29 09:51 UTC, abragtim commented
V crossmatch už bylo popsáno o double antibodies z mastru

2023-03-30 22:10 UTC, kristinagalik requested changes
v tom pdf sa mi zda ze:

1. **Has antibody mfi under cutoff?** ma vymenene tie podmienky, plus idk je to pdf cize by som asi gramatiku nestresovala ale keby sa ti chce prepisat tak: does antibody have...?
2. also **Has antibody mfi under cutoff?** -> yes ta prva vec hore ma byt asi over cutoff
3. description **Has antibody mfi under cutoff?** -> yes v spodnej branchi co zacina slovami "Add this antibody..." je teda tiez zle (vid comment v kode)
4. tu chyba info o tom ze iba ak je jedna positive
![image](https://user-images.githubusercontent.com/56656359/228974988-9a21fd3f-34b5-46d3-9a46-b390b313c387.png)

2023-03-30 22:10 UTC, kristinagalik commented on documentation/README.md
> +3. parsing_issues - a list of parsing issues that occur during the algorithm running.
algorithm execution

2023-03-31 19:42 UTC, kristinagalik reviewed
tym padom aj pdf teda mozno treba upresnit v style:

is antibody parsed -> are both antibody chains parsed

plus teda zmenit aj podla commentov v kode tu logiku theoretical antibodies

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +3. parsing_issues - a list of parsing issues that occur during the algorithm running.
jaj toto som myslela ze "algorithm running" -> "algorithm execution"

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +already in the parsed list, we move on to the next antibody.
tu by som este highlightla ze if both chains are already parsed

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +First, we check if the antibody has a positive MFI.
tu by som tiez highlightla ze teda ak neni sparsovane, tak ideme sem

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +
tuto sa to riesi separatne pre chainy, v zmysle - ak je chaina len negative, tak ju pridam, ak je chaina aj positive tak ju nepridam. ale z tohto textu mam pocit akoby ked jedna chaina ma daky positive vyskyt tak skipujem cele antibody

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +
proste len ta posledna veta by ma asi zmiatla

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +with the arithmetic mean of the MFI from all antibodies with this chain in the list.
este stale nie tak. v tomto pripade sa deje toto:

if both chains have positive and negative mfis:
1. add double antibody of type NORMAL with THIS MFI
2. raise parsing issue
3. add both chains separately of type THEORETICAL with AVERAGED MFI

2023-03-31 19:42 UTC, kristinagalik commented on documentation/README.md
> +arithmetic mean of the MFI from all antibodies with this chain, as in the first case.</br>
If one of the chains has at least one negative MFI representation and the other chain has only positive MFI representation among other antibodies in the list, we add the chain with only positive MFI representation to the parsed list with the arithmetic mean of the MFI from all antibodies with this chain. For the chain with mixed MFI representation, if this is the only positive occurrence of this chain, we add it to the parsed list with the arithmetic mean of the MFI from all antibodies with negative MFI for this chain in the list. Otherwise, if there is another positive occurrence for this chain, we skip it for now.

taketo nieco, asi este treba highlightnut dake slova a ak sa to da napisat krajsie tak prepisat

2023-04-03 05:59 UTC, kubantjan commented on documentation/double_antibodies_parsing/double_antibodies_parsing_algorithm.drawio
pridej ho do gitu ne jako drawio ale jako xml. Pak to jde otvirat takto skrz github primo. 
![Screenshot from 2023-04-03 07-58-33](https://user-images.githubusercontent.com/24394374/229423656-2f49ff51-6a89-4268-83fd-950f15666da2.png)


mame to tak treba na breviary:

https://github.com/mild-blue/breviary-backend/blob/master/documentation/diagrams_en/heparin-flow-chart.drawio.xml

2023-04-06 07:15 UTC, kristinagalik approved these changes

2023-04-11 09:12 UTC, kubantjan requested changes
Je to dobre, jen na muj vkus az prilis algoritmicky, kdyz si to precte imunolog, tak se bojim ze mu to nebude jasne. Asi bych tam 
1) pridal nejaky priklady
2) nepsal to tak moc jako algoritmus ale proste co se stane. Tzn vsem double tak a tka priradim double kdyz to a to. Neni potreba jit do detailu toho jak je to naimplementovano a spis to zasumuje tu pdostatu.

2023-04-13 13:04 UTC, jakubmonhart commented
Bylo by možné do té dokumentace i napsat, v které funkci je ten algoritmus naimplementovaný? Pro imunologa to asi potřeba není, ale když na tom projektu začne dělat někdo nový (takže třeba já) a bude číst dokumentaci, je dobrý si k tomu ten kód otevřít. Mít tam přímo referenci na funkci `_add_double_hla_antibodies` tedy podle mě orientaci zjednoduší.

2023-04-14 10:19 UTC, kubantjan commented
> Bylo by možné do té dokumentace i napsat, v které funkci je ten algoritmus naimplementovaný? Pro imunologa to asi potřeba není, ale když na tom projektu začne dělat někdo nový (takže třeba já) a bude číst dokumentaci, je dobrý si k tomu ten kód otevřít. Mít tam přímo referenci na funkci `_add_double_hla_antibodies` tedy podle mě orientaci zjednoduší.

hmm tady zacinaji clashovat dve ruzna publika toho readme. Ja bych rad to mel tak, ze to budu moct potom ukazat imunogovi u kteryho zas tohle bude navic. A obecne tohle readme v doumentatnion je mysleny spis takto. To co pises tady tady do toho readme moc nepatri. 

Ale nekde by byt mohlo. Pripadne takovy veci prosim do nejakyho readme vedle ktery bych nazval technical readme nebo tak nejak (tam pripadne muzes i @abragtim  vykopirovat tenhelten vic algoritmickej popis).

2023-04-27 13:30 UTC, jakubmonhart commented on documentation/README.md
> +we add them to the `parsed` list as one double antibody with the provided MFI. Moreover, we add each chain **separately** to the `parsed` list, and we denote their type as "theoretical", with the ari
Tady se bere jenom mean pres positive mfi ne?

2023-04-27 13:36 UTC, abragtim commented on documentation/README.md
> +we add them to the `parsed` list as one double antibody with the provided MFI. Moreover, we add each chain **separately** to the `parsed` list, and we denote their type as "theoretical", with the ari
Jo, jen jsem ještě to neopravil. Pokud náhodou děláš review (zvlášť u toho nového readme netechnického), tak asi počkej, protože zatím je to draft. Hodně věcí se tam mohou změnit, abys to neprocházel dvakrát

2023-04-27 13:37 UTC, jakubmonhart commented on documentation/README.md
> +we add them to the `parsed` list as one double antibody with the provided MFI. Moreover, we add each chain **separately** to the `parsed` list, and we denote their type as "theoretical", with the ari
Procital jsem si to parsovani kvuli jinemu review, tak jsem si tohohle všiml a nechtěl jsem na to zapomenout :) . S review tohoto počkám na request.

2023-05-03 08:20 UTC, jakubmonhart reviewed
Ten popis v README (non technical) mi přijde skvělě vysvětlující skrze ty příklady. Přidal jsem pár poznámek, ale celkově dobrý!

2023-05-03 08:20 UTC, jakubmonhart commented on documentation/README_TECH.md
> +[file](double_antibodies_parsing/double_antibodies_parsing_algorithm.pdf).
Tohle ber jenom jako návrh k diskuzi: Je to zobrazení na šířku lepší než na výšku? Představuji si že to někdo otvírá na notebooku nebo menší obrazovce a musí scrollovat horizontálně, což si myslím není vždy úplně intuitivní pokud nemáš touchpad jak na macbooku :D . Prostě mám pocit že když by stačilo při pročítání toho schéma scrollovat vertikálně tak to přidá na uživatelské příjemnosti, jestli to je něco co nás zajímá.

2023-05-03 08:20 UTC, jakubmonhart commented on documentation/README_TECH.md
> +**P.S.** The last time this algorithm was in the `_add_double_hla_antibodies` function.
```suggestion
### Where is this algorithm implemented
Antibodies in generall are parsed in `create_hla_antibodies_per_groups_from_hla_antibodies` function. The antibodies raw codes are preprocessed and single and double antibodies are parsed separately afterwards. Double antibodies are parsed in `_add_double_hla_antibodies` function which uses the algorithm described above.
```

2023-05-09 06:30 UTC, abragtim commented on tests/utils/hla_system/test_code_parser.py
Nenašel jsem test pro tento case, tak jsem ho přidal sem

2023-05-09 06:32 UTC, abragtim commented on documentation/README.md
> +we expect to parse this mixed chain through other antibodies.
V tomhle případě ne, ale nejčastěji čekáme, že tu mixed s několika positive parsneme v mixed+mixed case.
Viz test, který jsme přidal, protože jsem nějak nenašel existující test pro tento case:
https://github.com/mild-blue/txmatching/blob/863842ec395f4be55f9b958102a74170c6255a19/tests/utils/hla_system/test_code_parser.py#L310-L351

2023-05-09 06:44 UTC, abragtim commented on documentation/README.md
> +In summary, if there are several positive representations in this positive + mixed case,
Tady to nese smysl, o kterém diskutujeme tady https://github.com/mild-blue/txmatching/pull/1171/files/16ff94cea7a8f074b86cb01af72ee6e1723a7cc6#r1183367165, tak korektní asi bude varianta vyplývající z našich dvou:
```suggestion
In summary, if we detect the mixed chain, which has several positive representations among all the antibodies, 
in the positive + mixed double antibody, 
```
Souhlas? Nebo vadí takový popis "positive + mixed" v non tech README?

2023-05-09 06:56 UTC, abragtim commented on documentation/README_TECH.md
> +[file](double_antibodies_parsing/double_antibodies_parsing_algorithm.pdf).
Jo. To určitě dává smysl. Udělal jsem reformat obou těch readme

2023-05-09 14:04 UTC, jakubmonhart commented on documentation/README.md
> +In summary, if there are several positive representations in this positive + mixed case,
Ten odkaz nefunguje :( . Nicméně koukám na tvůj návrh a stále mi to přijde matoucí kvůli pořadí těch vět. Mě to dává smysl třeba takhle:

```
In summary, if we encounter this positive and mixed chain case where the mixed chain has several positive 
representations among all the antibodies, we expect to parse the mixed chain through other antibodies.
```

2023-05-09 21:35 UTC, abragtim commented on documentation/README_TECH.md
> +[file](double_antibodies_parsing/double_antibodies_parsing_algorithm.pdf).
Jo, už chápu. Určitě příště na to budu myslet od začátku, ale asi to natolik navádí, že bych to teď úplně překléslil. Navíc není tak obrovské (docela v pohodě jej čtu i bez scrolingu na malé obrazovce macbooku)

2023-05-10 08:36 UTC, jakubmonhart reviewed
Ještě jsem našel nějaké malé typos.

2023-05-10 08:36 UTC, jakubmonhart commented on documentation/README_TECH.md
> +above.
```suggestion
Antibodies in general are parsed
in `parse_hla_antibodies_raw_and_return_parsing_issue_list` function. The antibodies' raw codes are preprocessed, and single and double antibodies are
parsed separately afterwards. Double antibodies are parsed
in `_add_double_hla_antibodies` function which uses the algorithm described
above.
```

2023-05-10 08:36 UTC, jakubmonhart commented on documentation/README_TECH.md
> +above.
Jenom typos

2023-05-10 08:36 UTC, jakubmonhart commented on documentation/README.md
> +either `DPA1*03:03` or `DPB1*02:02` have only positive MFIs among all
```suggestion
In this case, the antibody `DP*[03:03;02:02]` has both chains positive because
both `DPA1*03:03` and `DPB1*02:02` have only positive MFIs among all
```

2023-05-10 08:36 UTC, jakubmonhart commented on documentation/README.md
> +`DPA1*03:03`, and a mixed chain, `DPB1*02:02`, because `DPB1*02:02` has a
```suggestion
In this case, the antibody `DP*[03:03;02:02]` has an only positive chain,
`DPA1*03:03`, and a mixed chain, `DPB1*02:02`, because `DPB1*02:02` has a
```

2023-05-10 08:36 UTC, jakubmonhart commented on documentation/README.md
> +DPB1*02:02 MFI 100 (average negative MFI), cutoff 2000
Napadá mě tady ještě zmínit že to děláme protože předpokládáme že positive MFI je způsobeno tím druhým chainem, takže tuto positivni hodnotu pro ten mixed chain neuvažujeme.

2023-05-10 08:36 UTC, jakubmonhart commented on documentation/README.md
> +`DP*[03:03;04:01]` and `DP*[01:01;02:02]`, respectively.
```suggestion
`DP*[03:03;04:01]` and `DP*[01:01;02:02]` respectively.
```

2023-05-10 09:01 UTC, jakubmonhart submitted a review, later dismissed

2023-05-10 09:16 UTC, jakubmonhart commented
Teď koukám, že v názvu PR je je i 'update the readme with description of how crossmatch is calculate in those cases'. To se bude nakonec dělat někde jinde?

2023-05-11 06:58 UTC, jakubmonhart approved these changes

2023-05-22 14:10 UTC, abragtim commented
@kubantjan , ready for review. Provedl jsem úpravy, o kterých jsem diskutovali na SU. Z mého pohledu nic extra užitečného, co bychom nemohli vykoukat z kódu, v TECH README nebylo

2023-05-22 16:46 UTC, kubantjan approved these changes

2023-05-22 16:46 UTC, merged