Fix: generate_patients.py for python 3.11.
mild-blue/txmatching pull request #1178
Opened 2023-04-04 09:06 UTC by abragtim

Make generate_patients.py works.

2023-04-04 09:16 UTC, kubantjan requested changes

2023-04-04 09:16 UTC, kubantjan commented on local_testing_utilities/generate_patients.py
> +    acceptable = random.sample(sorted(blood_groups), num_of_acceptable)
[random.sample()](https://docs.python.org/3/library/random.html#random.sample) must be a sequence, and automatic conversion of [set](https://docs.python.org/3/library/stdtypes.html#set)s to [list](https://docs.python.org/3/library/stdtypes.html#list)s is no longer supported.

je matouci ze sem davas sorted, kdyz by stacilo list(

2023-04-08 16:52 UTC, abragtim commented on local_testing_utilities/generate_patients.py
> +GENERATED_TXM_EVENT_NAME = 'high_res_example_data'  # generated with generate_patients.py
Chceme ještě mít tento txm_event, který byl předtím nebo chceme jen nový?

2023-04-11 09:08 UTC, kubantjan approved these changes

2023-04-24 06:27 UTC, kubantjan requested changes
Jen maly dotaz, jinak fajn

2023-04-24 06:27 UTC, kubantjan commented on local_testing_utilities/remove_inconsistent_patients.sql
> +/*
tohle prosim vysvetli.

2023-04-24 06:27 UTC, kubantjan commented on local_testing_utilities/remove_inconsistent_patients.sql
> +/*
v jakym pripade tohle nastane a je potreba to pustit?

2023-04-24 06:50 UTC, kubantjan commented on local_testing_utilities/remove_inconsistent_patients.sql
> +/*
takze jen pridej prosim vetu do README

2023-05-09 05:32 UTC, kubantjan commented
potrebuje rebase @abragtim

2023-05-09 05:33 UTC, kubantjan approved these changes

2023-05-09 05:33 UTC, kubantjan approved these changes

2023-05-09 05:43 UTC, merged