Show cpra and compatible donors in patients list FE
mild-blue/txmatching pull request #1180
Opened 2023-04-05 11:13 UTC by kristinagalik

Closes #1174

2023-04-05 20:42 UTC, kristinagalik commented
![image](https://user-images.githubusercontent.com/56656359/230206721-829e8ffa-5267-49f8-9388-cee4476ff4cf.png)

![image](https://user-images.githubusercontent.com/56656359/230206754-99752b35-4020-4555-abd8-aa0107e3bf62.png)

![image](https://user-images.githubusercontent.com/56656359/230206786-dcf5927d-608e-4196-9add-f84aeba4ffb8.png)

2023-04-13 10:38 UTC, NotLubo requested changes
Skvelá práca! Jenom nějaké blbůstky.

2023-04-13 10:38 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/patient-pair-detail/patient-pair-detail.component.ts
> +    }
```
    if (this.item?.r && this.defaultTxmEvent && this.configuration && this.patients) {
      this.getRecipientCompatibilityInfo(
        this.item.r.dbId,
        this.defaultTxmEvent.id,
        this.configuration,
        this.patients.donors
      );
    }
```

2023-04-13 10:38 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/patient/patient.service.ts
> +    const configIdStr = configId !== undefined ? configId.toString() : "default";
magic string `default`

Vytvořit asi nejaký enum který bude ve swagger, nebo nějaké lepší řešení pokud tě napadá

2023-04-13 10:38 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/patient/patient.service.ts
> +    configId: number | undefined,
`configId: number | undefined `-> `configId?: number`

2023-04-13 10:38 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/patient/patient.service.ts
> +    const configIdStr = configId !== undefined ? configId.toString() : "default";
A na number na string je snad implicitní. Takže `toString()` je zbytečné

2023-04-17 08:10 UTC, kubantjan commented
@kristinagalik  jakmile @NotLubo  schvali, prosim merge

2023-04-17 08:26 UTC, NotLubo approved these changes

2023-04-18 10:39 UTC, merged