Speed up recipient compatibility details computation by loading compatibility graph.
mild-blue/txmatching pull request #1184
Opened 2023-04-06 12:21 UTC by jakubmonhart

Closes #1163 .

2023-04-06 12:30 UTC, jakubmonhart commented
Rychlost jsem zase zkoušel na datech z populate_large_db.py.
AllPatients endpoint teď na tomto branch trvá ~2s pro mock data a ~4s pro high_res data.
Na master branch trvá ~1.6 s pro mock data a ~3s pro high_res data.

2023-04-07 13:12 UTC, kristinagalik requested changes
prevazne len par style komentov :)

2023-04-07 13:12 UTC, kristinagalik commented on txmatching/patients/recipient_compatibility.py
> +                score = compatibility_graph[d_r_id_pair]['hla_compatibility_score']
HLA_SCORE miesto "hla_compatibility_score"

2023-04-07 18:10 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +            if not is_positive_hla_crossmatch(donor_hla_typing=donor.parameters.hla_typing,
To prave bohuzel nejde. V `compatibility_graph` je ulozene score ktere je pocitane na zaklade vice kriterii (hla crossmatch, ale i compatibility index, blood group, atd - viz `HLAAdditiveScorer.score_transplant_calculated`) . Z compatibility matrix proto beru jenom info na to, ktere donory vracet k recipientovy jako kompatibilni.

2023-04-07 18:55 UTC, jakubmonhart commented on txmatching/web/api/patient_api.py
> +        lists_for_fe = to_lists_for_fe(txm_event, configuration, compute_cpra)
Tohle je takovy nesikovny no. To je ten problem co jsem zminoval na standupu. Ona totiz fce `get_configuration_from_db_id_or_default` vraci None, pokud jeste v databazi neni ulozena ta configuration odpovidajici config_id, a defaultem tam je mysleno to, ze to zkusi z db nahrat configuration s id `txm_event.default_config_id`, coz je v nejakych pripadech None. Ve vysledku to pak pada na testech a po setupnuti db. 

Pokud ale neni ulozena dana configuration, tak ani neni napocitan `compatibility_graph` a pocita se pak cely matching v patient_api  ve funkci `lists_for_fe` (coz taky neni asi uplne expected).  Ted me napada resit to tak, ze pokud configurace (a tim padem i compatibility_graph) neexistuje v db, tak nic nepocitat a neukladat a udelat vsechno bez compatibility_graph, coz bude pomalejsi ale pouze do te doby nez se to nekde napocita.

2023-04-08 11:07 UTC, kristinagalik commented on txmatching/web/api/patient_api.py
> +        lists_for_fe = to_lists_for_fe(txm_event, configuration, compute_cpra)
a keby sa v danych testoch najprv robil config a potom az sa s nim pocitalo? ako napr v `test_get_matchings`:

```
        with self.app.test_client() as client:
            conf_dto = dataclasses.asdict(configuration_parameters)
            res = client.post(f'{API_VERSION}/{TXM_EVENT_NAMESPACE}/{txm_event_db_id}/'
                              f'{CONFIGURATION_NAMESPACE}/find-or-create-config',
                              json=conf_dto,
                              headers=self.auth_headers)

            config_id = res.json['config_id']
            res = client.get(
                f'{API_VERSION}/{TXM_EVENT_NAMESPACE}/{txm_event_db_id}/'
                f'{MATCHING_NAMESPACE}/calculate-for-config/{config_id}',
                headers=self.auth_headers
            )
```

2023-04-08 11:12 UTC, kristinagalik commented on txmatching/web/api/patient_api.py
> +        lists_for_fe = to_lists_for_fe(txm_event, configuration, compute_cpra)
a keby sa v danych testoch najprv robil config a potom az sa s nim pocitalo? ako napr v `test_get_matchings`:

```
        with self.app.test_client() as client:
            conf_dto = dataclasses.asdict(configuration_parameters)
            res = client.post(f'{API_VERSION}/{TXM_EVENT_NAMESPACE}/{txm_event_db_id}/'
                              f'{CONFIGURATION_NAMESPACE}/find-or-create-config',
                              json=conf_dto,
                              headers=self.auth_headers)

            config_id = res.json['config_id']
            res = client.get(
                f'{API_VERSION}/{TXM_EVENT_NAMESPACE}/{txm_event_db_id}/'
                f'{MATCHING_NAMESPACE}/calculate-for-config/{config_id}',
                headers=self.auth_headers
            )
```

plus tam by to nemalo padat po setupnuti db lebo v oboch `patient_api` endpointoch ultimatne dostavas z fe len config id a nie config contents a mas to oguardene s `require_valid_config_id`

2023-04-08 11:34 UTC, kristinagalik commented on txmatching/patients/recipient_compatibility.py
> +            if not is_positive_hla_crossmatch(donor_hla_typing=donor.parameters.hla_typing,
noo ak to je naozaj pomala cast tak by nebolo lepsie (ak je niekde pocitana cisto hla compatibility vramci tej funkcie) vracat tuple (kompletne score, hla score)? a potom by boli 2 values ukladane do toho comp graph dictionary a dala by sa retrievnut tato tabulka stale za lacnejsie?

2023-04-10 07:50 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +            if not is_positive_hla_crossmatch(donor_hla_typing=donor.parameters.hla_typing,
Tam se počítá ten HLA crossmatch a ovlivňuje score takhle: https://github.com/mild-blue/txmatching/blob/dbce8ecaa792343714324462c61084eb58e9ca6a/txmatching/scorers/hla_additive_scorer.py#L73-L79 . Zasahovat do toho a vracet ke score i bool is_positive_hla_crossmatch už by asi zahrnovalo moc změn ne?

2023-04-11 06:56 UTC, kubantjan commented
- pridat flag ze me nezajimaji pacienti detailni kdyz oteviram matching stranku
- prpojit s FE
- nepocitat a posilat prazdny listy kdyz to jeste neni v databazi

2023-04-12 13:18 UTC, kristinagalik requested changes

2023-04-12 13:19 UTC, kristinagalik commented on txmatching/patients/recipient_compatibility.py
> +            if not is_positive_hla_crossmatch(donor_hla_typing=donor.parameters.hla_typing,
hmm neviem... zalezi asi ako velmi pomale to je, lebo ak to je privelmi pomale to imo za ten refactoring stoji, lebo nemyslim ze bude az taky velky. asi nechcem robit ale claims, @kubantjan asi by si toto vedel lepsie povedat, pozrel by si sa na to prosim?

2023-04-12 15:25 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +            if not is_positive_hla_crossmatch(donor_hla_typing=donor.parameters.hla_typing,
compute cpra je neco co se bude pocitat malo a vubec bych se tim ted nezabyval a nechal to takto schovany a neoptimalni

2023-04-14 11:43 UTC, kristinagalik approved these changes
za mna fajn:)

2023-04-17 08:21 UTC, kubantjan requested changes

2023-04-17 08:21 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +                -> Tuple[Optional[int], Set[int], Optional[List[RecipientDonorCompatibilityDetails]]]:
tadyto uz je celkem komplexni objekt, vytvor na to dataclassu prosim.

2023-04-17 08:21 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +            d_r_id_pair = (donor.db_id, recipient.db_id)
kdyz je par v compatibility grafu automaticky to znamena ze jsou compatible, tzn neni tady potreba cela ta logika s tim score > Transplant impossilb atp/.

2023-04-17 08:21 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +                                                           compute_compatibility_details: bool = False,
jestli tomu spravne rozumim tak tady compute details je false v pripade ze jdu z matchings stranky, jeneze v tom pripade celou tuhle fci vubec volat nemusim, protoze me nezajima ani ten list tech compatibilnich ne?

2023-04-18 08:47 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +            d_r_id_pair = (donor.db_id, recipient.db_id)
Mám to tam kvůli `CalculateRecipientCPRA` endpointu v `patient_api` . Tam se nechci spolehat na to, ze compatibility graph je uz spocteny a zaroven tam nestaci pocitat jenom hla_crossmatch, protoze list compatibilnich donoru tam posilame podle celkoveho score.

2023-04-18 08:49 UTC, jakubmonhart commented on txmatching/patients/recipient_compatibility.py
> +                                                           compute_compatibility_details: bool = False,
Kdyz jdu z matching stranky tak tu funkci nevolam. Tenhle argument tam je zase kvuli `CalculateRecipientCPRA` endpointu, kde nechci pocitat detaily ale jenom list compatibilnich donoru.

2023-04-24 06:22 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +            d_r_id_pair = (donor.db_id, recipient.db_id)
ok, vidim.

2023-04-24 06:22 UTC, kubantjan commented on txmatching/patients/recipient_compatibility.py
> +                                                           compute_compatibility_details: bool = False,
ok, rozumim.

2023-04-24 06:23 UTC, kubantjan commented
rebase, pak merge uz do te vetve je to dobre. (necekej na approve a rebasni a mergni, jeste to neni do mastra :)

2023-04-24 06:23 UTC, kubantjan approved these changes

2023-04-27 06:58 UTC, kubantjan requested changes
cekam na updates

2023-05-04 05:38 UTC, kubantjan requested changes

2023-05-04 05:38 UTC, kubantjan commented on txmatching/web/api/patient_api.py
>          txm_event = get_txm_event_complete(txm_event_id)
mno tady mozna tak desne dlouho trva ze se tady loaduje ten txm event complete ne? a to mozna neni nutny, protoze realne to k nicemu neni potreba, pokud tomu spravne rozumim?

2023-05-04 06:56 UTC, jakubmonhart commented on txmatching/web/api/patient_api.py
>          txm_event = get_txm_event_complete(txm_event_id)
Je potřeba txm_event_complete? Lze loadovat i jinou funkcí s méně informacemi.

2023-05-04 10:05 UTC, jakubmonhart commented on txmatching/web/api/patient_api.py
>          txm_event = get_txm_event_complete(txm_event_id)
Máš pravdu že načítání toho txm_eventu zabírá asi nejvíce času z toho api callu, ale jinou možnost při použití tohoto endpointu nevidím. Potřebuji nahrát txm_event se všemi donory abych mohl počítat kompatibilní donory, cpra, atd ... . Je tam vypnuté načítání raw antibodies pro recipienty, to už šetří nějaký čas. Ale zbytek načítat musím.

2023-05-04 11:03 UTC, kubantjan commented on txmatching/web/api/patient_api.py
>          txm_event = get_txm_event_complete(txm_event_id)
ok

2023-05-09 07:15 UTC, merged