Add support for theoretical and double antibodies in crossmatch api
mild-blue/txmatching pull request #1187
Opened 2023-04-11 21:06 UTC by kristinagalik

Closes #1168

- theoretical sa pridava aj ked neni double crossmatch, proste ako zvysne
- double antibody sa pridava len ak ma double crossmatch

2023-04-12 15:28 UTC, kubantjan commented
@kristinagalik  davam se pryc, na prvni kolo prosim davat @abragtim  a @jakubmonhart

2023-04-14 16:05 UTC, jakubmonhart reviewed
Podle mě to funguje tak jak má, takže ok. Mám jenom pár poznámek/dotazů:

1. `test_theoretical_and_double_antibodies_not_implemented` bych přejmenoval, protože double už je naimplementovany a theoretical antibody tady v žádném match nefiguruje (a tedy se tady ani netestuje).
2. Teď se tedy nikde netestuje jestli crossmatch api vrací správně theoretical antibody match že?  (testuje se jenom že to správně dělá `get_crossmatched_antibodies_per_group`, tak je možná redundantní to testovat znovu jako výstup api když se theoretical match zpracovává stejně jako ostatní).
3. Je potřeba u všech těch parsing issue specifikovat v assert tu value? (viz třeba `ParsingIssueDetail.INSUFFICIENT_NUMBER_OF_ANTIBODIES_IN_HIGH_RES.value`) Funguje to stejně když dáš jenom `ParsingIssueDetail.INSUFFICIENT_NUMBER_OF_ANTIBODIES_IN_HIGH_RES` a možná je to lehce lépe čitelné (to je asi fakt detail, ale když už jsem si toho všiml tak to radši píšu :) )
4. viz comment u kódu

2023-04-14 16:05 UTC, jakubmonhart commented on txmatching/web/api/crossmatch_api.py
> +                    if not (common_matches_alpha and common_matches_beta):
Není tohle duplicitní? v `get_crossmatched_antibodies_per_group` to přeci antibody s dvěma kódy nepustí, pokud oba kódy nemají crossmatch. (viz tento kód https://github.com/mild-blue/txmatching/blob/d7a543f9b7a6157b78318099dac577e94ed8131d/txmatching/utils/hla_system/hla_crossmatch.py#L209-L212)

2023-04-22 11:28 UTC, jakubmonhart reviewed
Už jenom jedna poznámka v kódu, jinak ok.

2023-04-22 11:28 UTC, jakubmonhart commented on tests/web/test_do_crossmatch_api.py
> +            self.assertCountEqual([ParsingIssueDetail.CREATED_THEORETICAL_ANTIBODY,
Tady je možný kontrolovat (možná udělat z těch listů set a porovnat), že jsou ty parsing issue opravdu tato (ne jenom že sedí počet).

2023-04-24 07:15 UTC, jakubmonhart commented on tests/web/test_do_crossmatch_api.py
> +            self.assertCountEqual([ParsingIssueDetail.CREATED_THEORETICAL_ANTIBODY,
assertCountEqual dělá přesně to co jsem navrhoval, takže tohle uzavírám a vše ok.

2023-05-03 14:07 UTC, kubantjan requested changes

2023-05-03 14:07 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +                                      if antibody_hla_match.hla_type.code in (antibody_group_match.hla_antibody.code,
tohle je blbost ne? Kdyz jsou tam dva kody tak to ma byt tak ze musi OBA mit donor, jinak to nesmi projit. @kristinagalik  @jakubmonhart ? Pridat do testu tenhle case taky prosim

2023-05-03 15:18 UTC, kubantjan approved these changes

2023-05-03 15:22 UTC, merged