Handle special HLAType format in crossmatch API
mild-blue/txmatching pull request #1188
Opened 2023-04-12 09:12 UTC by abragtim

Closes #1139

2023-04-12 09:15 UTC, abragtim commented
# PR Checklist

- [ ] Update swagger and approve with @kubantjan .
- [ ] ...

2023-04-13 07:16 UTC, kubantjan requested changes

2023-04-13 07:16 UTC, kubantjan commented on txmatching/web/swagger/swagger.json
> +                        "example": [
ten exaple je blbe ne? To ma byt prave list listu

2023-04-13 07:19 UTC, kubantjan requested changes
nevidim ten display code? Ten uz se posilal i predtim? Pokud jo tak to napis, ze to v issue bylo redundantne

2023-04-13 07:20 UTC, kubantjan commented
+ To summary ma mit domplet informace (tzn i hla kod) jen proste ne list protilatek ale jen jednu. Tzn ted to neni dobre jak to tam mas.

2023-04-13 08:19 UTC, abragtim commented
> * To summary ma mit domplet informace (tzn i hla kod) jen proste ne list protilatek ale jen jednu. Tzn ted to neni dobre jak to tam mas.

@kubantjan 
Podle mě v tom summary je jen jedna HLAAntibody, ne? Žádný list tam není
<img width="240" alt="Snímek obrazovky 2023-04-13 v 10 16 50" src="https://user-images.githubusercontent.com/25512296/231698445-330f35ff-3d93-46e2-b6f6-69b0e1d5e9dd.png">

2023-04-14 08:32 UTC, kubantjan reviewed
Jo takhle dobre, jdu to poslat do ikemu :)

2023-04-22 12:15 UTC, jakubmonhart commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        pass
Ten AttributeError to hází při AntibodyMatchForHLAType.__init__ že? Pak mě nenapadá (což neznamená že neexistuje :D) jiné řešení než nastavit ten setter, nebo napsat custom __init__ kde se nenastavuje self.summary_antibody.

2023-04-26 13:34 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        pass
úpravil jsem to tak, jak řekl Jakub. Ale pořád si myslím, že by to mohlo jít nějak líp. Jsem otevřen k novým návrhům

2023-04-26 17:20 UTC, jakubmonhart reviewed
Vypadá to dobře, jenom pár poznámek.

2023-04-26 17:20 UTC, jakubmonhart commented on txmatching/web/api/crossmatch_api.py
> +                donor_hla_typing=create_hla_typing([match.get_low_res_code_from_assumed()
Tady už není potřeba `get_low_res_code_from assumed`, protože to děláš na řádku 116 ne?

2023-04-26 17:20 UTC, jakubmonhart commented on txmatching/web/api/crossmatch_api.py
> +        typing_parsing_issues = get_parsing_issues_for_hla_typing(antibody_matches_for_hla_type)
Chceme ty `typing_parsing_issues` jenom pro ty zjistene hla kody nebo pro vsechny ktere prijdou?

2023-04-26 19:44 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +            return list(dict.fromkeys(lst).keys())
set() změní pořadí prvků v listu. Bohužel, na tom máme příliš závislé testy u TestDoCrossmatchApi. 
Určitě jde je změnit, ale to může docela zabrat času. Tak jsem vyřešil spíš takovým způsobem dostat unikátní elementy.
list(set()) je rychlejší, ale pro takové množství elementu jako počet HLA typů u člověka to nebude tak podstatné

2023-04-26 20:12 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +                donor_hla_typing=create_hla_typing([match.get_low_res_code_from_assumed()
Jo, mohlo by tady být match.hla_type[0].code.display_code, ale s tou funkci to vypadá, podle mě, nějak hezčí. Je to matoucí, že dostávám low_res pomocí metody get_low_res_code_from_assumed, i když ten hla type už fakticky není assumed?

2023-04-26 20:17 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +        typing_parsing_issues = get_parsing_issues_for_hla_typing(antibody_matches_for_hla_type)
Podle mě dává smysl ukazovat jen pro zjištěné. Nevím, proč by lékař měl zájem o HLA, která jsme vyhodili, když zadával assumed právě s cílem, abychom ukázali jen relevantní. 
Možná je to jinak, než si myslím, proto nechám tuhle otázku na @kubantjan

2023-04-26 20:55 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        return len({hla_type.code.get_low_res_code() for hla_type in self.hla_type}) > 1
Co si myslíš o názvu is_hla_type_uniquely_defined_in_low_res? Podle mě je čitelnější a předává smysl tohoto checku

2023-04-26 21:14 UTC, jakubmonhart commented on txmatching/web/api/crossmatch_api.py
> +            return list(dict.fromkeys(lst).keys())
Aha, neuvědomil jsem si to pořadí. Tím pádem takhle ok. Mě by u toho možná pomohl komentář, protože je to na první pohled docela exotický způsob jak získat unikátní hodnoty z listu :D .

2023-04-26 21:18 UTC, jakubmonhart commented on txmatching/web/api/crossmatch_api.py
> +                donor_hla_typing=create_hla_typing([match.get_low_res_code_from_assumed()
Teď s těmi změnami je to myslím dobrý. Mě tam jenom přišla matoucí ta duplicita transformace na low_res code. Teď je to dobrý,

2023-04-27 06:50 UTC, jakubmonhart approved these changes

2023-05-03 15:46 UTC, kubantjan requested changes
privedlo me to review na jeden pripad: pokud pacient ma typizaci a pro ni nejsou protilatky ani ve splitu tak co ted delas? mam pocit ze to prevedes na split a nechas to tak, je to tak?

2023-05-03 15:46 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "recipient_antibodies": [{'mfi': 2350,
recipient antibodies budou vzdy v podasdtate v high res a ne ultra, tak bych to tak i testoval

2023-05-03 15:46 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
tohle je dost hloupej pripad, to by se nikdy nemelo prekryvat to DPA1*01:04 jak je tam dvakrat tak to je nevalidni. Len assumed_donor_hla_typing a len  expected_assumed_hla_typing by melo byt vzdycky stejny (jen delka tech vnitrnich listu by mela byt kratsi a taky NIKDY prazdna)

2023-05-03 15:46 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +                                           [asdict(create_hla_type('DPA1*01:08'))],
jaktoze je tady DPA1*01:08, to tady byt nema? vzdy to mezi protilatkama neni?

2023-05-03 15:49 UTC, kubantjan requested changes
jeste pridej check na konzistenci, ze kazdy z tech hla typu ma jiny split kod (tzn v ramci jednoho listu je to jeden a ten samy a mezi listy zas ruzny)

2023-05-03 15:52 UTC, kubantjan requested changes

2023-05-03 15:52 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +        expected_summary_antibody = {'hla_antibody':
tadyto otestuj komplet ten objekt ze to ty protilatky fakt naslo vsechny

2023-05-03 15:52 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +                                     'match_type': 'UNDECIDABLE'}
tohle nema byt undecidable? To preci ma byt match high res!

2023-05-03 19:36 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +                                           [asdict(create_hla_type('DPA1*01:08'))],
@kubantjan ,to je protilátka, která je z assumed ['DPA1*01:08'] (řádek 271), což je jediný HLA typ v tom assumed, a proto ho rovnou bereme. Ale máš pravdu, že tento HLA typ nemá crossmatch s žádnou z těch protilátek

2023-05-03 19:41 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +                                           [asdict(create_hla_type('DPA1*01:08'))],
Jasný ok dává smysl

2023-05-03 21:20 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +                                     'match_type': 'UNDECIDABLE'}
@kubantjan 
Tak to vyšlo kvůli tomu, že počítáme crossmatch pro více hla typů, než je povoleno obecně (protože některé jsou assumed), což jsem nějak přehlédl. Vyřešil jsem to tak, že jsem přidal vlajku ignore_max_number_hla_types. 
Má to jediný háček, že zahodíme i skutečné undecidable, které by neměli projít checkem. Můžu to parsovani zpustit ještě jednou pro low res a zkontrolovat, které jsou skutečné undecidable. Ale přijde mi to zbytečně dělat jenom kvůli tomu, abychom napsali UNDECIDABLE v match_type místo HIGH RES. Potenciálně tohle může ovlivnit tento kus kódu:

```python
def _add_theoretical_crossmatch_type(positive_matches: Set[AntibodyMatch]):
    for match in positive_matches:
        if match.hla_antibody.type == HLAAntibodyType.THEORETICAL and match.match_type != AntibodyMatchTypes.UNDECIDABLE:
            positive_matches.remove(match)
            positive_matches.add(AntibodyMatch(match.hla_antibody, AntibodyMatchTypes.THEORETICAL))
``` 

Co si o tom myslíš?  Bude lepší na to undecidable zapomenout pro takový special endpoint nebo spočítat to 
 důsledně zvlášť?

2023-05-04 05:21 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +        typing_parsing_issues = get_parsing_issues_for_hla_typing(antibody_matches_for_hla_type)
jop dava smysl takto

2023-05-04 05:23 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        pass
ted mi to prijde vyreseny ok @abragtim

2023-05-04 05:26 UTC, kubantjan requested changes
jeste v tedstech mas vlastne ted 3x v donorove typizaci DPA1 coz je nesmysl, to tam vzdy by melo byt jen max 2x. to bych opravil (v jednom typu tech moznych typizaci muze byt milion, ale typy furt max 2x.. 

idealne tohle bychom meli nekde zkontrolovany, ale ted to asi neni nutny (pridej issue) ted to obejiti toho kdy se flatne ten list v to summary_antibody je ok.

2023-05-04 05:48 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +                                     'match_type': 'UNDECIDABLE'}
udelej nove issue. Uz to pisu jinde v komentari, Pokud spravne rozumim tomu co pises, resis pripad kdy mame prilis mnoho typizaci od jednoho genu a v realu je dany gen  nevalidni 

tady bych predpokladal, ze nam poslou validni pacienty prozatim proste.

2023-05-04 08:42 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
> jeste pridej check na konzistenci, ze kazdy z tech hla typu ma jiny split kod (tzn v ramci jednoho listu je to jeden a ten samy a mezi listy zas ruzny)

@kubantjan 
Myslím si, že se to stává u reálných pacientů, dokonce i v high res. Tady je příklad z posledního txm eventu:
<img width="169" alt="Snímek obrazovky 2023-05-04 v 10 38 22" src="https://user-images.githubusercontent.com/25512296/236153965-f0b61f1f-81ce-4f4c-88f3-f23e4e10ce20.png">

2023-05-04 08:44 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
A ten test je špatně určitě. Jenom teď nevím, jak to máme řešit z těch dvou variant:

1. Povolujeme stejné codes, ale len assumed a len expected má být stejná
2. Zakazujeme to, jak jsi to navrhoval

2023-05-04 09:00 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
> > jeste pridej check na konzistenci, ze kazdy z tech hla typu ma jiny split kod (tzn v ramci jednoho listu je to jeden a ten samy a mezi listy zas ruzny)
> 
> @kubantjan Myslím si, že se to stává u reálných pacientů, dokonce i v high res. Tady je příklad z posledního txm eventu: <img alt="Snímek obrazovky 2023-05-04 v 10 38 22" width="169" src="https://user-images.githubusercontent.com/25512296/236153965-f0b61f1f-81ce-4f4c-88f3-f23e4e10ce20.png">

Možná celkově na TXM to neřešíme, protože v takovém případě
<img width="305" alt="Snímek obrazovky 2023-05-04 v 10 52 56" src="https://user-images.githubusercontent.com/25512296/236157316-32df12d8-0248-4b86-ab17-acf821f9b407.png">
(nalevo jsou antigeny donora, napravo - recipienta)
by asi měl být match pro oba antigeny recipienta, když je teď zeleně označen jenom jeden. To je drobný bug asi, pokud neovlivňuje score tohoto match (myslím si, že ne)

2023-05-04 09:17 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +        expected_summary_antibody = {'hla_antibody':
Máme zkontrolovat všechny protilátky nebo jenom summaries (tj. i pro ostatní hla typy, pro které v tomhle případě bude summary_antibody None)?

Zatím jsem udělal jen pro summary. V tomhle případě asi chceme testovat jenom to summary, na všechny protilátky jsou jiné testy:
```python
        expected_summary_antibodies = [{'hla_antibody':
                                         {'code': {'broad': 'DPA1',
                                                   'high_res': 'DPA1*01:04',
                                                   'split': 'DPA1'},
                                          'cutoff': 2000,
                                          'mfi': 2100,
                                          'raw_code': 'DPA1*01:04',
                                          'second_code': None,
                                          'second_raw_code': None,
                                          'type': 'NORMAL'},
                                        'match_type': 'HIGH_RES'},
                                       None,
                                       None]
        for antibody_match, expected_summary_antibody in zip(res.json['hla_to_antibody'],
                                                             expected_summary_antibodies):
            self.assertEqual(expected_summary_antibody,
                             antibody_match['summary_antibody'])
```
Je to ok?

2023-05-04 09:32 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
Máš pravdu 2x stejný teoreticky být může a to že je to 2x zelený je ok.

2023-05-04 09:53 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
Myslím si, že u recipienta to taky má být 2x zelený, když je teď jen jednou. Ne?

2023-05-04 10:05 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "assumed_donor_hla_typing": [['DPA1*01:03', 'DPA1*01:04', 'DPA1*01:06'],
Ah jasný no asi jo ale to je fakt jedno

2023-05-05 09:43 UTC, abragtim commented on txmatching/data_transfer_objects/hla/hla_swagger.py
> +    'display_code': fields.String(required=False)
@kubantjan 
Existuje tam jako property, tj. flask ho nevidí a na výstupu nebude. Pokud to přidám to dataclass jako attr některé testy spadou a hlavně nastává problém s tím, že v `test_direct_conversion_to_dataclass_works_and_is_faster_than_dacite`
`recipient_model = RecipientModel.query.filter_by(txm_event_id=txm_event_id).first()` bude taky mít display code v tomto dict. Poté v této části
```python
hla_typing_dacite: HLATypingDTO = dacite.from_dict(
            data_class=HLATypingDTO, data=recipient_model.hla_typing,
            config=dacite.Config(cast=[Enum]))
```
to spadne s errorem 
`TypeError: HLACode.__init__() got an unexpected keyword argument 'display_code'.`
Nevím, jak zařídit, aby SQLAlchemy to display_code nebrala z dataclass HLACode. Zkoušel jsem dataclass.field(init=False). Možná víš, jak na to?
</br>
Přišlo mi do hlavy jen přizpůsobit této situaci HLACode.__init__()
```python

    def __init__(self, high_res: Optional[str], split: Optional[str], broad: Optional[str],
                 display_code = None):
        assert high_res is not None or broad is not None
        if display_code is not None:
            logger.warning(f'The specified value "{display_code}" will be ignored during HLACode initialization. '
                           f'display_code is readonly property.')
        self.high_res = high_res
        self.split = split
        self.broad = broad
```
Ale nepřipadá mi to jako dobrý nápad pro této účely

2023-05-05 13:16 UTC, kubantjan requested changes
Asi porad nerozumim proc je potreba ten display code pridat..

2023-05-05 18:11 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +                                     'match_type': 'UNDECIDABLE'}
https://github.com/mild-blue/txmatching/issues/1204

2023-05-06 14:42 UTC, kubantjan requested changes
asi to dela co ma, ale fakt tezko se ten kod cte, dal jsem tam par poznamek.

zasadni sdeleni za me je:

snazit se to neprehanet se zanorenou strukturou kodu,

za me je lepsi projdu vsechny hla
a jeden po druhym k nim priradim protilatky proste a ne tohleto cykly a vnoreny cykly a fuknce ve fukncich kde hrozi ze tam doje k chybe a fakt tezko se to cte.

Plus nazvy. To jak tam mas hla_type a pritom je to list a to jak davas hla_types=hla_type, to je hodne matouci.

No mrkni na komentare a pripadne se ptej..

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +        def distribute_antibody_matches_solved_unsolved(matches):
tyhle taky dat pryc

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +                    common_matched_hla_types: List[HLAType] = get_hla_types_correspond_antibody(
proc tady explicitne pises ten typ? To k nicemu neni ne?

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +        antibody_matches_for_hla_type = [AntibodyMatchForHLAType(
tohle mi nedava smysl vytvaret tady s prazdny listem, to uz bych rovnou vytvarel ten objekt jako celek.

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +        antibody_matches_for_hla_type = [AntibodyMatchForHLAType(
obecne veci co pak clovek hnedka mutuje nekdy dava smysl vytvaret, ale chces k tomu mit dobry duvod..

2023-05-06 14:42 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    def __init__(self, hla_type: List[HLAType],
tady rozdil mezi hla_type a hla_types je fakt tezko pochopitelnej a srozumitelnej. To bych takto urcite nedeal. Jestli to chapu spravne tak hla_types ma byt assumed_hla_types ne? a hla_type neco jako potential_hla_types?

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +            if solved_hla_types:
tohle se fakt tezko cte ok if tohle tak tohle a co kdyz to neni pravda? Clovek desne tezko hleda kde je schovany to else.

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +    def __fulfill_with_common_matches(antibody_matches, crossmatched_antibodies):
typ!

2023-05-06 14:42 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        self.hla_types = hla_type
tohle ne, tady dokonce hla_types ma dva ruzny vyznamy, jednoou tady je to vlastne vsechny potential.

2023-05-06 14:42 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +                antibody_hla_match.hla_types = list(solved_hla_types)
a pak tady jsou to jen ty assumed.

2023-05-07 15:31 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    def __init__(self, hla_type: List[HLAType],
@kubantjan 
> tady rozdil mezi hla_type a hla_types je fakt tezko pochopitelnej a srozumitelnej. To bych takto urcite nedeal. Jestli to chapu spravne tak hla_types ma byt assumed_hla_types ne? a hla_type neco jako potential_hla_types?

> tohle ne, tady dokonce hla_types ma dva ruzny vyznamy, jednoou tady je to vlastne vsechny potential. (https://github.com/mild-blue/txmatching/pull/1188#discussion_r1186705821)

> a pak tady jsou to jen ty assumed. (https://github.com/mild-blue/txmatching/pull/1188#discussion_r1186705858)

Konkrétně tady je to chyba po refactoringu, ale to je matoucí s tím, že je to assumed/potential/hla_type/hla_types, ale biologicky nese smysl jenom jednoho HLAType.
Tak když to upravím následujícím způsobem:

_Pokud budeme mít List[HLAType], který biologicky nese smysl jenom jednoho HLA Type (prostě nemůžeme zvolit, který z těch je ten správný), tak ten object nazýváme `assumed_hla_type` a ten má tyto vlastnosti:_

- _nesmí být prazdný_
- _musí mít jednotný HLA code v low res_
-  _nesmí mít několik kódu v low res, tj. nepovolujeme situaci ['A1', 'A1']_

Přičemž jak ['A1'], tak i ['DPA1*01:01'] budou taky assumed, jenom s tou vlastnosti, že tyto assumed jsou jednoznačně určeny, tj. teoreticky by mohli být i převedeny jenom na typ HLAType místo List[HLAType].


Stačí taková konvence, kterou popíšu v komentářích v kódu, aby bylo jasné, že se nejedná o nějakou biologickou interpretaci ve skutečném světě, jenom to řeší určité nejistoty v typingu pro tento endpoint?

2023-05-09 05:22 UTC, kubantjan requested changes

2023-05-09 05:22 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    def from_crossmatched_antibodies(cls, hla_types: List[HLAType],
porad tady mas hla_types ve vyznamu all possible hla types a pak v tom ojbektu ty class mas hla_types v jinem vyznamu. To prosim jeste pojmenovat jinak at je to jasne odliseny.

2023-05-09 05:27 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    def from_crossmatched_antibodies(cls, hla_types: List[HLAType],
obecne to hla_types je pouzity na mnoha mistech a fakt bych strikne ty dva typy pojmenoval ruzne (ani jeden z nich jen hla_types, ale s nejakym privlastkem at je to srozumitelny_

2023-05-09 05:32 UTC, kubantjan requested changes

2023-05-09 05:32 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +def _get_parsing_issues_for_hla_typing(antibody_matches_for_hla_type: List[AntibodyMatchForHLAType])\
proc je tahle fce potreba? Nevis ty parsing issues uz z predtim?

2023-05-17 15:02 UTC, kubantjan requested changes

2023-05-17 15:02 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +                                     (has all the same limitations, viz AntibodyMatchForHLAType),
Here all potential hla_typing codes that were derived from a lab test (likely PCR) of patient are stored. 

this is then processed to assumed hla_typing that contains only the typing that has a match with antibodies and therefore is meaningul for crossmatch computation.

2023-05-17 15:02 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +def _solve_potential_hla_typing(potential_hla_typing_raw: List[List[str]],
tohle bych nazval get_assumed_hla_typing

2023-05-17 15:02 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +        -> Tuple[List[List[HLAType]], List[ParsingIssueBase]]:
klidne bych zas nedelal tuple ale dataclassu, citelnost to zlepsuje a ty tuply obcas delaji neplechu

2023-05-18 07:28 UTC, jakubmonhart submitted a review, later dismissed
Změnám rozumím. Ten kod v crossmatch_api mi teď přijde podstatně přehlednější.

2023-05-20 20:07 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +def _solve_potential_hla_typing(potential_hla_typing_raw: List[List[str]],
Sejde se na `get_assumed_hla_typing_and_return_parsing_issue_list`?

2023-05-24 22:03 UTC, kubantjan approved these changes

2023-05-24 22:03 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +def _solve_potential_hla_typing(potential_hla_typing_raw: List[List[str]],
`get_assumed_hla_typing_and_parsing_issues` to return je tam navic. jedno reknes get a jednou return kdyz get a return jsou v tomto pripade synonyma

2023-05-24 22:03 UTC, kubantjan requested changes
jen ten jeden malej komentar jinak ok

2023-05-24 22:03 UTC, kubantjan requested changes
jen ten jeden malej komentar jinak ok

2023-05-24 22:04 UTC, kubantjan requested changes

2023-05-24 22:04 UTC, kubantjan commented on txmatching/web/api/crossmatch_api.py
> +    antibodies_codes = antibodies_to_solve_hla_typing.get_antibodies_codes_as_list()
solve hla typing je pojem ktery podle me nezname mame potential a assumed to je vsechno. Tak tak bych u toho i zustal. tzn solve tady nikde by nemelo byt.

2023-05-25 10:40 UTC, merged