Handle theoretical double antibodies equivalent to the some donors HLAs
mild-blue/txmatching pull request #1196
Opened 2023-04-14 16:56 UTC by abragtim

2023-04-14 16:58 UTC, abragtim commented
@kubantjan , mohl bys, prosím, schválit ten unittest pro jistotu, že správně rozumím tohle issue. Po tomto PR ten test by měl proběhnout

2023-04-17 08:07 UTC, kubantjan requested changes

2023-04-17 08:07 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +    def test_theoretical_and_double_antibodies_equal_hlas_below_cutoff(self):
Ten unittest je urcite blbe ted ted endpoint vraci 501 a mel by vracet success a jen jinou sadu protilatek.

Plus:

Cekal bych ze v tom testu budes resit zda recipientovi jsme nalezli crossmatch s DQA1*01:01 (coz by ted najit melo a va budoucnu ne a ty tam resit crossmatch s A

P.S. jsou urcite vsechy ty dq kody existujici? Uplne jsem si je vymyslel a bal bych se ze nejaky nesparsujeme?

2023-04-17 08:18 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +    def test_theoretical_and_double_antibodies_equal_hlas_below_cutoff(self):
Ale vrací 501, protože teď nemáme povolené pro tento endpoint double protilátky. Po tomto PR to bude 200, protože už nebude match s DQ[01:01, 03:03], ne?
```python
if antibody_group_match.hla_antibody.type == HLAAntibodyType.THEORETICAL or \
                        antibody_group_match.hla_antibody.second_raw_code:
                    raise TXMNotImplementedFeatureException(
                        'This functionality is not currently available for dual antibodies. '
                        'We apologize and will try to change this in future versions.')
```

2023-04-17 08:31 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +    def test_theoretical_and_double_antibodies_equal_hlas_below_cutoff(self):
Aha! rebasni se nad https://github.com/mild-blue/txmatching/pull/1187 kde se tohle resi. 

Tohle PR nema resit aby se nevracela 501 ale jen upravovat chovani. 

Tzn ok, 501 se vyresit tim rebasem ale ty druhy dva komenty stale plati

2023-04-27 14:41 UTC, jakubmonhart reviewed
Myslím že je to vpohodě. Mám tam jen jednu poznámku abych si ověřil že všemu správně rozumím.

2023-04-27 14:41 UTC, jakubmonhart commented on txmatching/web/api/crossmatch_api.py
> +                if antibody.type == HLAAntibodyType.THEORETICAL \
Chápu to správně tak, že by neměla nastat situace 
` antibody.type != HLAAntibodyType.THEORETICAL and antibody.raw_code in exclusive_raw_codes` ? I pokud to tak je, je dobře tam ten check na theoretical nechat kvůli čitelnosti, chci si jen ověřit že tomu správně rozumím.

2023-04-27 15:22 UTC, jakubmonhart approved these changes

2023-04-30 15:11 UTC, abragtim commented
@kubantjan , teď jsem si uvědomil o tom, že se mohou na vstup dostat ultra high res codes. Zda se mi, že double antibodies typu DP[01:02:03:02, 02:01:03:01] při parsingu nepřivádíme do DP[01:02, 02:01] (nejen v tomto endpointu, ale celkově na TXM). Je to špatně?

2023-05-04 05:34 UTC, kubantjan requested changes
chtel jsem delat review ale zda se ze jsou tu ted zmeny co tu byt nemaji, tak pockam az se to vytribi

2023-05-04 05:34 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "recipient_antibodies": [{'mfi': 2350,
typicky muzou prijit typizace v ultra high res ale ne protilatky. Tak by to mel i ten test testovat.

2023-05-04 05:34 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "recipient_antibodies": [{'mfi': 2350,
ale obecne tenhleten test sem nepatri, chces mit co nejmensi change set a v tomhle testu resis jiny veci. Uz tak je ten PR mega, takze tohle prostim pripadne separatni PR jestli ti tento test chybel.

2023-05-04 05:34 UTC, kubantjan commented on txmatching/data_transfer_objects/crossmatch/crossmatch_dto.py
> +    assumed_donor_hla_typing: List[List[str]]
hmm asi pockam na rebase, tohleto vypada, ze tu jsou zmeny co tu byt nemaji obecne

2023-05-04 08:26 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +            "recipient_antibodies": [{'mfi': 2350,
Aha. Tak to je stejně test z jiného PR. To, o čem jsem mluvil je jiný test

2023-05-29 07:05 UTC, kubantjan requested changes
Doresit jak s readme, aby bylo up to date

2023-05-29 07:05 UTC, kubantjan requested changes
Doresit jak s readme, aby bylo up to date

2023-05-31 09:39 UTC, kubantjan commented
cekam na popis v readme v tom druhym PR,  pak muzeme mergovat

2023-05-31 09:40 UTC, kubantjan requested changes
cekam na finalizaci readme v tom druhym pr

2023-05-31 09:40 UTC, kubantjan requested changes
cekam na finalizaci readme v tom druhym pr

2023-05-31 09:57 UTC, kubantjan approved these changes

2023-05-31 09:58 UTC, merged