Theoretical antibody ukazovat mene vyrazne
mild-blue/txmatching pull request #1200
Opened 2023-04-18 13:25 UTC by kristinagalik

Closes #1195

2023-05-08 09:45 UTC, NotLubo requested changes

2023-05-08 09:45 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/matching-transplant/matching-transplant.component.ts
> +    var classes = "";
Nepoužívaj var. Nerespektuje scope tak jak očekáváš.

https://medium.com/@codingsam/awesome-javascript-no-more-var-working-title-999428999994

2023-05-08 09:45 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/code/code.component.scss
>      color: $code-color--bad-matching !important;
Tady ty 3 imporatnt to přepisují

2023-05-08 13:02 UTC, NotLubo approved these changes
Super :)

2023-05-09 07:04 UTC, kubantjan commented
mrknout na report jeste prosim

2023-05-14 09:06 UTC, closed without merging