feat: parse also the probability of HLA
mild-blue/txmatching pull request #1215
Opened 2023-05-28 12:07 UTC by kristinagalik

2023-05-28 14:51 UTC, abragtim commented
> Aj ked je to vela riadkov, zmeny su detailne
> 
> 1. dala som tie frequencies ako dictionary, pretoze swagger nema rad tuples
> 2. idk ako velmi maju byt 1/0 realisticke, nasla som stranku ktora zhruba hovori frequency allel ale neviem co to znamena vlastne "casto sa vyskytujuca alela"
> 
> http://www.allelefrequencies.net/hla6006a.asp?hla_locus_type=Classical&hla_locus=&hla_allele1=A*01%3A02&hla_allele2=A*01%3A02&hla_selection=&hla_pop_selection=&hla_population=&hla_country=&hla_dataset=&hla_region=&hla_ethnic=&hla_study=&hla_order=order_1&hla_sample_size_pattern=equal&hla_sample_size=&hla_sample_year_pattern=equal&hla_sample_year=&hla_level_pattern=equal&hla_level=&standard=a&hla_show=
> 
> 3. zatial to tam je teda tak ze logika crossmatchu sa nemeni (beru sa tie codes bez 1/0)

1. Udělal bych na to dataclassu
2. Zatím IKEM bude sám posílat binární informaci, jestli je to rare alela či ne. Ale máš pravdu, dělají to na základě takových různých databází, kterou jsi našla. Jednu z nich, kterou obvykle používá jak Matěj Roder, tak i francouzy z EasyHLA, budeme nejspíš napojovat v rámci tohoto issue https://github.com/mild-blue/txmatching/issues/1214 pro predikci High res ze SPLIT, ale taky budeme moct využívat i pro toto crossmatch API. IKEM to má v hlavě, ale zatím to budeme mít takhle

2023-05-28 15:12 UTC, abragtim reviewed
Přidal jsem komentáře, které by měli navést k tomu, co vlastně chceme

2023-05-28 15:12 UTC, abragtim commented on txmatching/web/swagger/swagger.json
1. V HLA typing chceme mít pro každou grupu x2 hla type, v našem případě jako asssumed hla type. Pro každou grupu dva listy. Tj. x2 hla typy pro A, x2 pro B, atd.
2. Chceme mít i příklad double protilátky
3. Tam vidím u A1 vs A1*01:01 match_type NONE. Nemá tam být SPLIT? Možná špatně na to koukám. Dostala jsi to na výstupu tohoto endpointu?

2023-05-28 16:55 UTC, kristinagalik commented on txmatching/web/swagger/swagger.json
jop ale uz to je outdated, pardon zabudla som updatnut tie antibodies... tym padom tam je teraz vela parsing issues tak tie proste ignorujem nech tym nezaplavim ten example output

2023-05-29 07:32 UTC, abragtim commented on txmatching/web/swagger/swagger.yaml
Ještě asi chybí warning, který budeme posílat v případě rare u AntibodyMatchForHLAType

2023-05-29 08:03 UTC, abragtim commented on documentation/README.md
> +#### Evaluating crossmatch
```suggestion
#### Evaluating crossmatch with cadaverous donors
```

2023-05-29 08:27 UTC, abragtim commented on documentation/README.md
> +**If some codes are 0 and some are 1**, we consider all the codes, and we calculate the crossmatch as usual. The only
Vlastně odhad potential hla typing, což v naši terminologii kódu znamená převod z potential do assumed, děláme trochu jinak. Tohle, co popisuješ, platí jenom v kontextu hodnocení summary, což je úplně OK. Jenom tohle i chceme v rámci tohoto issue, ale musím udělat README na minulé PRs spojené s crossmatch API.
Navrhuju pro úpravu README udělat toto, protože potřebujeme upravit to README současně, aby bylo správné:
_Timur Abragimovich, Teď
@Kristína Gáliková , teď jsem si uvědomil, že vůbec nemáme popsáno v README, jak funguje crossmatch API. Navrhnul bych udělat na to separátní issue a cherry picknout tvé commity s README do nové branche, nad kterou bychom pracovali společně. Už jsi napsala v rámci svého PR hodně užitečných věcí, tak bych asi chtěl vnořit v tvůj text detaily, které už máme. Co si o tom myslíš? Jinak bychom museli pořád řešit konflikty, protože chci někde upravovat i věty, nejen přidávat odstavce_

2023-05-29 08:53 UTC, abragtim commented on documentation/README.md
Přidal jsem nové issue na README a udělal jsem cherry pick tvého commitu, tak můžeš postupně přecházet s README do té branch. Zatím jsem tady ten commit nemazal, aby zůstali moje komentáře

2023-05-29 15:14 UTC, kristinagalik commented
@abragtim dala som readme zmeny odtialto prec, a podla vojho review som pomenila veci v https://github.com/mild-blue/txmatching/pull/1218

2023-05-29 16:38 UTC, abragtim requested changes

2023-05-29 16:38 UTC, abragtim commented on txmatching/web/swagger/swagger.json
Pro toto API chceme mít ten warning ne v parsing issues, ale v AntibodyMatchForHLAType.
Viz text issue
> tohle upozrneni pridat do AntibodyMatchForHLAType jako novou propertu. Nejaky warning textik

Nejsem si na 100% jistý proč. Myslel jsem si, že je to kvůli tomu, že na to nebudeme mít FE nějakou dobu nebo napořád. Těžko se bude vyhledávat ten warning mezi všechny parsing issues. Jistotu v tom nemám, tak nechám vysvětlení na @kubantjan

2023-05-29 16:43 UTC, abragtim commented on txmatching/web/swagger/swagger.json
Nebo tohle issue nevzniklo během parsingu, tak třeba nemá tam patřit

2023-05-30 14:13 UTC, abragtim submitted a review, later dismissed

2023-05-31 09:41 UTC, kubantjan requested changes
nevidim zadny test specificky testujici tu novou fukncionalitu

2023-05-31 09:42 UTC, kubantjan requested changes

2023-05-31 09:42 UTC, kubantjan commented on tests/web/test_do_crossmatch_api.py
> +            "potential_donor_hla_typing": [[{"hla_code": 'DPA1*01:03', "is_frequent": True},
vidim ze tady nejak pridavas true a fals, takze se to mozna testovat nejak snazis, ale pak musis nazvat test tak aby bylo jasny co testujes

ted ty testy dle nazvu testuji furt to co testovaly predtim. 

a teda neni takhle jasny ze tim ze takhle prepisujes ty testy tak neco co se testovalo driv se uz ted treba netestuje..

2023-06-01 17:01 UTC, abragtim requested changes
+ Chceme mít na výstupu i frequencies, včetně swaggeru

2023-06-01 17:09 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +        code_frequencies = {hla.hla_code: hla.is_frequent for hla in potential_hla_type_raw}
Ohledně názvu:

assumed hla type: List[HLATypeWithFrequency]
assumed hla typing: List[List[HLATypeWithFrequency]]

Nic lepšího mi zatím nenapadá, ale možná se dá vymyslet i lepší název pro toto

2023-06-01 17:14 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +            potential_hla_type = _convert_potential_hla_type_to_low_res(potential_hla_type)
Chceme, aby ta nová magie s frequent/infrequent byla tady:

https://github.com/mild-blue/txmatching/blob/f012208e2e94bcb1663c5f21ae90dd14d402d833/txmatching/utils/hla_system/hla_crossmatch.py#L50C1-L53

2023-06-02 08:00 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +            potential_hla_type = _convert_potential_hla_type_to_low_res(potential_hla_type)
Tak jsme měli call. A takový přechod do split v případě 0 tam chceme mít a vypočítávat parsing issues pro 1/0 e taky ok, jenom nechceme v případě 1/0 rozdělovat do separate lists

2023-06-02 08:18 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +            potential_hla_type = _convert_potential_hla_type_to_low_res(potential_hla_type)
Jenom co se tyče těch parsing issues, tak ten warning posíláme jen v případě, že nenastal crossmatch s 1, tj. pro warning nestačí jenom mít rare antigen v tom listu assumed hla type, ale chceme, aby byl crossmatch pro tento assumed hla type jenom na 0

2023-06-02 08:58 UTC, kristinagalik reviewed
@abragtim

2023-06-02 08:58 UTC, kristinagalik commented on txmatching/web/api/crossmatch_api.py
> +    return parsing_issues
toto uz je dobre? pridavam to teda len vtedy, ked su celkovo v `AntibodyMatchForHLAType` len infrequent codes v `assumed_hla_type`

2023-06-02 08:58 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
>                     key=lambda match: match.hla_antibody.mfi) if self.antibody_matches else None
tu som stale zmatena ci tu mam znova akoze extractnut len frequent codes a z nich sa spytat na to ze ake su tam antibodies a z tych vybrat max mfi antibody

2023-06-02 09:28 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +    return parsing_issues
Neskončí tahle podmínka _all_codes_infrequent teď vždy False? Už jsi _all_codes_infrequent převedla na SPLIT.
Tady ale chceš mít _is_unlikely_crossmatch
Unlikely crossmatch with assumed hla type = crossmatch just with infrequent HLATypes inside one assumed hla type + len(assumed hla type > 1) + exists mininalne jedna frequent hla type inside assumed hla type (coz jsi zarucila uz tim prevodem na split pro same 0)

2023-06-02 09:32 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
>                     key=lambda match: match.hla_antibody.mfi) if self.antibody_matches else None
```suggestion
    def summary_antibody(self) -> Optional[AntibodyMatch]:
        # extract only frequent codes
        frequent_codes = [hla_type.hla_code for hla_type in self.assumed_hla_type if hla_type.is_frequent == True]
        # if there is crossmatch only with infrequent codes, don't return anything

        return max(self.antibody_matches,  # TODO: + podminka, ze match.hla_antibody.hla_code in frequent_codes
                   key=lambda match: match.hla_antibody.mfi) if self.antibody_matches else None
```

2023-06-02 09:36 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
>                     key=lambda match: match.hla_antibody.mfi) if self.antibody_matches else None
Nějak tak má vypadat ta logika. Tady jen pro kontrolu:
1. Bereme informaci o frequent codes od donora
2. Pak bereme antibody s max MFI, který má frequent code. Pokud takový není, tak vracíme None

2023-06-02 12:12 UTC, kristinagalik commented on txmatching/web/api/crossmatch_api.py
> +    return parsing_issues
noo na split sa to prevadza ak vsetky codes su na vstupe 0. ale toto je situacia ze kody na vstupe boli mix 1/0 ale pozitivny crossmatch prebehol len so subsetom kde kazdy kod je 0.

2023-06-02 12:20 UTC, kristinagalik commented on txmatching/web/api/crossmatch_api.py
> +    return parsing_issues
ano ale v `AntibodyMatchForHLAType` mi ostava v `hla_type` uz len to co ma crossmatch. cize ja som v situacii ze na vstupe sice boli 0/1 mix, ale tu uz by som mala mat len situaciu ze "crossmatch prebehol len s nejakymi infrequent codes". tym padom ak sa pozriem do `hla_type` a su vsetky 0, tak pridam warning. ci?

2023-06-02 12:44 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +    return parsing_issues
V AntibodyMatchForHLAType v assumed hla type nevšichni antigeny mají crossmatch. Všichni budou mít stejný kód s nějakou z antibodies, které byly na vstupu tohoto endpointu, ale crossmatch mít nemusejí (třeba MFI < cutoff).

To znamená, že situace
recipient antibodies na vstupu endpointu = [A:01:02 mfi 3000, A:01:01 mfi 100, A:01:03 mfi 100]
pak
AntibobyMatchForHLAType:
assumed hla type = [A:01:02, A:01:01, A:01:03]
antibody_matches = [A:01:02 mfi 3000]
je celkem běžná

2023-06-02 12:59 UTC, abragtim requested changes
Tak se už  bližíme :) Z důležitého zbývá jen ta logika s novým warningem

2023-06-02 12:59 UTC, abragtim commented on txmatching/data_transfer_objects/crossmatch/crossmatch_dto.py
> +    potential_donor_hla_typing: List[List[AssumedHLATypeRaw]]
```suggestion
    potential_donor_hla_typing: List[List[PotentialHLATypeRaw]]
```

2023-06-02 12:59 UTC, abragtim commented on txmatching/data_transfer_objects/crossmatch/crossmatch_dto.py
> +    potential_donor_hla_typing: List[List[AssumedHLATypeRaw]]
Potential je pred vyhodnocenim, assumed po

2023-06-02 12:59 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                   key=lambda match: match.hla_antibody.mfi) if antibodies_against_frequent_codes else None
```suggestion
        antibody_matches_with_frequent_codes = [
                antibody_match 
                for antibody_match in self.antibody_matches 
                if antibody_match.hla_antibody.code in frequent_codes
                ]
        return max(antibody_matches_with_frequent_codes,
                   key=lambda match: match.hla_antibody.mfi) if antibody_matches_with_frequent_codes else None
```

2023-06-02 12:59 UTC, abragtim commented on txmatching/web/api/crossmatch_api.py
> +        if hla_type.is_frequent is True:
Dokonce stačí i
```
if hla_type.is_frequent:
    ...
```

2023-06-03 10:02 UTC, abragtim requested changes
Jo, celkově je to dobře, dořešíme drobnosti + chce to nové testy

2023-06-03 10:37 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    assumed_hla_type: List[AssumedHLAType]
Nebo možná ten jeden kód by byl AssumedHLAType a list by byl prostě assumed hla type list (nebo jednoduše assumed hla types). List listu bez změn: assumed hla typing)
Logika by byla docela jednoduchá, že assumed hla type list je prostě list těch předpokládaných hla types (assumed hla types), který reprezentuje biologicky jen jeden hla type

2023-06-03 10:39 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    assumed_hla_type: List[AssumedHLAType]
Co si o tom myslíte, @kristinagalik, @kubantjan , @jakubmonhart ?

2023-06-05 17:05 UTC, abragtim requested changes
1. Napadl mi ještě jeden edge case: assumed hla type má jediný kód a je infrequent, například donor má [{'A*01:04', is_frequent: False}] a máme crossmatch s tímto antigenem. Myslím si, že to budeme hodnotit jako pravděpodobný crossmatch, tj. summary != None a warning nebudeme posílat. @kubantjan , správně to chápu? Nepamatuju, jestli to bylo explicitně řečeno na schůzce, ale z kontextu mi to přijde správným


2. Tady je bug, že vyhodnotíme antibody ve split jako infrequent:
```json
"antibody_matches": [
        {
          "hla_antibody": {
            "code": {
              "broad": "DR2",
              "high_res": null,
              "split": "DR15"
            },
            "cutoff": 2000,
            "mfi": 3000,
            "raw_code": "DR15",
            "second_code": null,
            "second_raw_code": null,
            "type": "NORMAL"
          },
          "match_type": "SPLIT"
        }
      ],
      "assumed_hla_type": [
        {
          "hla_type": {
            "code": {
              "broad": "DR2",
              "high_res": "DRB1*15:03",
              "split": "DR15"
            },
            "display_code": "DRB1*15:03",
            "raw_code": "DRB1*15:03"
          },
          "is_frequent": false
        },
        {
          "hla_type": {
            "code": {
              "broad": "DR2",
              "high_res": "DRB1*15:112",
              "split": "DR15"
            },
            "display_code": "DRB1*15:112",
            "raw_code": "DRB1*15:112"
          },
          "is_frequent": true
        },
        {
          "hla_type": {
            "code": {
              "broad": "DR2",
              "high_res": "DRB1*15:07",
              "split": "DR15"
            },
            "display_code": "DRB1*15:07",
            "raw_code": "DRB1*15:07"
          },
          "is_frequent": true
        }
      ],
      "summary_antibody": null
```

- [ ] + test na tento bug

2023-06-06 07:36 UTC, kristinagalik commented on txmatching/data_transfer_objects/base_patient_swagger.py
> +]
mas pravdu, zabudla som asi niekde po novej logike updatnut nove parsing issues

2023-06-06 08:42 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +        # CASE: only infrequent codes
Jo, když máš split, tak by neměl být match type HIGH RES. Ale to je docela divný, protože přechod do SLIT bychom měli dělat před počítáním crossmatch

2023-06-06 10:04 UTC, abragtim requested changes

2023-06-06 10:04 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
Přidej, prosím, ještě testy

- [ ]  na ten bug, který jsme našli
- [ ] na summary, které má protilátku s MFI, které je maximální ze všech frequent, ale existuje i infrequent s větším MFI. Navíc by tuhle situaci s upozorněním na nutné protilátky bylo taky vhodné vysvětlit přes komentáře, aby bylo jasné, proč to testujeme

2023-06-06 10:12 UTC, abragtim requested changes

2023-06-06 10:12 UTC, abragtim commented on txmatching/data_transfer_objects/base_patient_swagger.py
> +]
Tady máš příklad z tím bugem, který jsme našli, minimálně u "DRB1*15:03, DRB1*15:112, DRB1*15:07"

2023-06-08 08:23 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return False
jaj lebo __eq__ overriduje == a __contains__ overriduje "in" len ma uprimne v tom bode nenapadlo napisat __contains__ co by asi bolo lepsie...

2023-06-08 09:21 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return False
Ale použivali bychom 
```python
antibody_match.hla_antibody.code in frequent_codes
```

Tj. máme situaci HLACode in List[HLACode], kde list (ne HLACode) použivá __contains__. V dokumentaci je napsano _"For container types such as **list**, tuple, set, frozenset, dict, or collections.deque, the expression x in y is equivalent to any(x is e or x == e for e in y)."_. Myslím si, že list.__contains__ už používá "==" v sobě

2023-06-08 09:24 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return False
jaj no ja som to tak originalne mala ako to pises, ale z dakeho dovodu to nefungovalo.. a je tiez true ze ak by to tak malo fungovat tak by bola funkcia `__contains__` nepodstatna

2023-06-08 09:36 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return False
Hmm tak to mas pravdu to by malo ist, neviem preco mi to predtym neslo, mozno som tam mala ine zmeny co to sposobovali… ci skusal si to uz prepisat naspat a nefunguje to?

2023-06-08 09:48 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    return False
Našel jsem, v čem je problém. I když v této funkci je napsán type u frequent_codes: List[HLACode], ale fakticky jsme posílali Set[HLACode]. U Set[HLACode] ale funguje trochu jinak to "in", i když to v dokumentaci explicitně nepíšou, ale zkratka používají ne __eq__, ale __hash__, což v případě HLACode(None, A1, A1) vs HLACode(A01:01, A1, A1) __eq__ = True, ale __hash__ mají různý (https://stackoverflow.com/questions/7549709/unexpected-behavior-for-python-set-contains)

Stačí jenom používat List a všechno bude fungovat

2023-06-12 07:20 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    assumed_hla_type: List[AssumedHLAType]
Tak jsme shodli na
assumed_hla_types: List[HLATypeWithFrequency]

2023-06-14 14:37 UTC, kubantjan approved these changes

2023-06-14 14:38 UTC, merged