Popsat v README, jak funguje crossmatch API pro kadaverózní dárce
mild-blue/txmatching pull request #1218
Opened 2023-05-29 08:50 UTC by abragtim

Closes #1216

2023-05-29 20:33 UTC, kristinagalik commented on documentation/README.md
> +In the last case, with only one HLA code, `A*02:01`, in the potential HLA type, it will remain unchanged.
hmm mozno by som vymenila len poradie v akom o tom hovoris, teraz preskakujes A0201 a vracias sa k tomu na koniec a v tom snippete to je v inom poradi.. akoze asi no big deal anyway

2023-05-29 20:34 UTC, kristinagalik commented on documentation/README.md
> +is the fact that if we have a double antibody that has both it chains among the donor's antigens
"...both it..." asi preklep

2023-05-29 20:35 UTC, kristinagalik commented on documentation/README.md
> +      hla_code: "A*01:02", is_frequest: True
is_frequest -> is_frequent

2023-05-30 09:06 UTC, abragtim commented
Poprosil jsem review od @jakubmonhart . Ale pokud to README spěchá a chceme to mít co nejdřív, tak dávám rovnou i na @kubantjan

2023-05-30 13:04 UTC, kubantjan requested changes
chtelo by to tady nejka jasne vyjadrit kde se kadaveri lisi od zivych darcu priklad jak se to vyhodnoti pro ne a jak pro zivy darce, to tady ted nevidim

2023-05-30 13:05 UTC, kubantjan requested changes

2023-05-30 13:05 UTC, kubantjan commented on documentation/README.md
> +One more distinguishing feature of this API compared to the classical TXM virtual crossmatch
vidim ze to resis tady ale rekl bych to vice na prikladu

2023-05-30 13:05 UTC, kubantjan commented on documentation/README.md
> +One more distinguishing feature of this API compared to the classical TXM virtual crossmatch
ten text mi neprijde dobre srozumitelnej

2023-05-31 09:55 UTC, kubantjan approved these changes
Super, takto je to dobre

2023-05-31 09:58 UTC, merged