Převádět na začátku do assumed jen pak kontrolovat frequent/infrequent
mild-blue/txmatching pull request #1231
Opened 2023-06-20 09:31 UTC by abragtim

Closes #1227

2023-06-20 10:45 UTC, abragtim commented
## Tak bylo před PR
```json
"antibody_matches": [
        {
          "hla_antibody": {
            "code": {
              "broad": "A2",
              "high_res": "A*02:01",
              "split": "A2"
            },
            "cutoff": 2000,
            "mfi": 20464,
            "raw_code": "A*02:01",
            "second_code": null,
            "second_raw_code": null,
            "type": "NORMAL"
          },
          "match_type": "HIGH_RES"
        }
      ],
      "assumed_hla_types": [
        {
          "hla_type": {
            "code": {
              "broad": "A2",
              "high_res": "A*02:01",
              "split": "A2"
            },
            "display_code": "A*02:01",
            "raw_code": "A*02:01"
          },
          "is_frequent": false
        }
      ],
      "summary_antibody": null

 "parsing_issues": [
    {
      "hla_code_or_group": "DPA1*01:03, DPB1*11:01",
      "message": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains. Other antibodies with alpha: DP[01:03,28:01] mfi: 111, DP[01:03,23:01] mfi: 212, DP[01:03,19:01] mfi: 3226, DP[01:03,06:01] mfi: 4689, DP[01:03,04:02] mfi: 214, DP[01:03,04:01] mfi: 123, DP[01:03,03:01] mfi: 5810, DP[01:03,02:01] mfi: 161, DP[01:03,01:01] mfi: 4593. Other antibodies with beta: DP[02:02,11:01] mfi: 1993.",
      "parsing_issue_detail": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains."
    },
    {
      "hla_code_or_group": "DPA1*02:02, DPB1*13:01",
      "message": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains. Other antibodies with alpha: DP[02:02,11:01] mfi: 1993, DP[02:02,10:01] mfi: 2770, DP[02:02,05:01] mfi: 2028. Other antibodies with beta: DP[03:01,13:01] mfi: 2184, DP[02:01,13:01] mfi: 1711.",
      "parsing_issue_detail": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains."
    },
    {
      "hla_code_or_group": "A*02:01",
      "message": "There is most likely no crossmatch, but there is a small chance that a crossmatch could occur. Therefore, this case requires further investigation.",
      "parsing_issue_detail": "There is most likely no crossmatch, but there is a small chance that a crossmatch could occur. Therefore, this case requires further investigation."
    }
  ]
```

## Tak stane po PR
```json
{
    {
      "antibody_matches": [
        {
          "hla_antibody": {
            "code": {
              "broad": "A2",
              "high_res": "A*02:01",
              "split": "A2"
            },
            "cutoff": 2000,
            "mfi": 20464,
            "raw_code": "A*02:01",
            "second_code": null,
            "second_raw_code": null,
            "type": "NORMAL"
          },
          "match_type": "HIGH_RES"
        },
        {
          "hla_antibody": {
            "code": {
              "broad": "A2",
              "high_res": "A*02:06",
              "split": "A2"
            },
            "cutoff": 2000,
            "mfi": 18408,
            "raw_code": "A*02:06",
            "second_code": null,
            "second_raw_code": null,
            "type": "NORMAL"
          },
          "match_type": "HIGH_RES"
        }
      ],
      "assumed_hla_types": [
        {
          "hla_type": {
            "code": {
              "broad": "A2",
              "high_res": null,
              "split": "A2"
            },
            "display_code": "A2",
            "raw_code": "A2"
          },
          "is_frequent": true
        }
      ],
      "summary_antibody": {
        "hla_antibody": {
          "code": {
            "broad": "A2",
            "high_res": "A*02:01",
            "split": "A2"
          },
          "cutoff": 2000,
          "mfi": 20464,
          "raw_code": "A*02:01",
          "second_code": null,
          "second_raw_code": null,
          "type": "NORMAL"
        },
        "match_type": "HIGH_RES"
      }
    },

"parsing_issues": [
    {
      "hla_code_or_group": "DPA1*01:03, DPB1*11:01",
      "message": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains. Other antibodies with alpha: DP[01:03,28:01] mfi: 111, DP[01:03,23:01] mfi: 212, DP[01:03,19:01] mfi: 3226, DP[01:03,06:01] mfi: 4689, DP[01:03,04:02] mfi: 214, DP[01:03,04:01] mfi: 123, DP[01:03,03:01] mfi: 5810, DP[01:03,02:01] mfi: 161, DP[01:03,01:01] mfi: 4593. Other antibodies with beta: DP[02:02,11:01] mfi: 1993.",
      "parsing_issue_detail": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains."
    },
    {
      "hla_code_or_group": "DPA1*02:02, DPB1*13:01",
      "message": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains. Other antibodies with alpha: DP[02:02,11:01] mfi: 1993, DP[02:02,10:01] mfi: 2770, DP[02:02,05:01] mfi: 2028. Other antibodies with beta: DP[03:01,13:01] mfi: 2184, DP[02:01,13:01] mfi: 1711.",
      "parsing_issue_detail": "Theoretical antibody was created, because double antibody had mixed MFI values for both chains."
    }
  ]
```

2023-06-20 10:51 UTC, abragtim commented
@kubantjan , posílám na review bez big data testu v případě, že už na této stadii mám chybu v logice, abych testy neopravoval na hodně místech

2023-06-20 13:31 UTC, kubantjan requested changes
takto ok, pridej test

2023-06-21 13:37 UTC, abragtim commented
Tady je porovnání výstupu oproti tomu, co máme na STG:
[json_compare.html.zip](https://github.com/mild-blue/txmatching/files/11818096/json_compare.html.zip)

2023-06-21 13:40 UTC, closed without merging