Split in summary (crossmatch-api).
mild-blue/txmatching pull request #1235
Opened 2023-06-23 10:38 UTC by abragtim

Closes #1230

2023-06-26 13:36 UTC, jakubmonhart commented on documentation/README.md
> +crossmatch issue `Antibodies against this HLA Type might not be DSA, for more see detailed section`.
Ja jsem na dnesnim standupu pochopil, ze v takovem to pripade bude mfi=3000 , protoze uvazujeme mfi hodnoty pouze od toho kodu (B1) s max mfi (pokud by bylo vice B1 kodu, delal by se prumer z jejich mfi). ... viz tento koment  https://github.com/mild-blue/txmatching/issues/1230#issuecomment-1606851229

2023-06-26 13:42 UTC, jakubmonhart commented on documentation/README.md
> +crossmatch issue `Antibodies against this HLA Type might not be DSA, for more see detailed section`.
Ted ale koukam ze to readme je konzistenti s tou odpovedi od mateje (https://github.com/mild-blue/txmatching/issues/1230#issuecomment-1602164572), tak mozna ok.

2023-06-26 14:02 UTC, jakubmonhart commented on documentation/README.md
> +For summary, we would like to take into account just frequent codes among all assumed HLA types.
Takhle jsme se na tom dnes rano domluvili? Pochopil jsem to tak, ze kdyz mame jenom infrequent codes, tak prevedem na SPLIT s mean mfi a dame warning.

2023-06-26 15:14 UTC, kubantjan commented on documentation/README.md
> +In this case the summary HLA code is `A1`, because it has the highest MFI among antibodies (viz `A*01:01, mfi 3000`).
viz -> see

2023-06-26 15:16 UTC, kubantjan commented on documentation/README.md
> +So the summary HLA code is `B1`, because it has the highest MFI among antibodies (viz `B*07:02, mfi 3000`).
viz. neni anglicky, vsude zmenit

2023-06-26 15:17 UTC, kubantjan commented on documentation/README.md
> +the same as the summary match type. We consider all the rest codes as less important for the summary section.
We consider all the rest codes as less important for the summary section. tohleto by melo byt uvedeny rovnou nahore asi?

2023-06-26 15:19 UTC, kubantjan commented on documentation/README.md
> +The summary MFI in this case will be `3500`, because we just calculated the arithmetic mean MFI values for frequent
nepatri sem warning: Ambiguity in HLA typization, for more see detailed section?

2023-06-26 15:29 UTC, kubantjan commented on documentation/README.md
> +crossmatch issue `Antibodies against this HLA Type might not be DSA, for more see detailed section`.
no v zasade je to jedno, protoze je to vsechno tak nejak cca ale z toho co psal matej podle me naopak plyne konzistentnost s tim co pisu ja, ze chceme to prumer mfi od toho kodu ktery ma max. mfi. Tzn v tomto pripade 3000. (protoze je tam jen jedna tahodnota).

2023-06-26 15:43 UTC, kubantjan requested changes

2023-06-26 15:43 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        summary_match_type = max(antibodies_matched_types)
tady bych rekl ze summary match type se tyka jen frequent kodu.

2023-06-26 15:43 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    def _calculate_crossmatch_summary(self):
tady to mas takovy napreskacku

2023-06-26 23:08 UTC, abragtim commented on documentation/README.md
> +The summary MFI in this case will be `3500`, because we just calculated the arithmetic mean MFI values for frequent
Jo, patří, ale v této sekci dělám fokus na logiku výpočtu summary MFI, aby ostatní věcí nerušili, když čtenář chce zatím pochopit jen MFI. Různé crossmatch issues vysvětluju dál na příkladech

2023-06-27 07:16 UTC, kubantjan requested changes
jop, tohle uz mi prijde fajn, nahodim to na staging.

2023-06-27 07:16 UTC, kubantjan commented on documentation/README.md
> +The summary MFI in this case will be `3500`, because we just calculated the arithmetic mean MFI values for frequent
nekde zmin ze i v tomhle pripade bude ten warning, prijde mi to matouci, ze to vubec uvedeny neni.

2023-06-27 07:16 UTC, kubantjan commented on documentation/README.md
> +The summary MFI in this case will be `3500`, because we just calculated the arithmetic mean MFI values for frequent
at uz tady rovnou, nebo to niz zminis

2023-06-27 07:16 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            # there are not any antibody matches with frequent codes,
ted kdyz to vidim, tak vlastne tady to TODO neni potreba, takto je to ok podle me.

2023-06-27 09:11 UTC, kubantjan commented
Jeste prosim upravit aby se summary mfi pocitalo jen z te sady kodu ktere patri k tomu kodu ktery je v summary

2023-06-27 14:28 UTC, jakubmonhart commented on txmatching/data_transfer_objects/crossmatch/crossmatch_in_swagger.py
> +                                                      in CadaverousCrossmatchIssueDetail])
```suggestion
        'issues': fields.List(required=False, cls_or_instance=fields.String(
            required=False, enum=[issue.value for issue in CadaverousCrossmatchIssueDetail]))
```

2023-06-28 14:50 UTC, jakubmonhart commented on documentation/README.md
> +the same as the summary match type. We consider all the rest codes as less important for the summary section.
Tohle je takova zvlastni formulace. Napsal bych neco ve stylu: `For summary HLA code, we consider only the the matches with frequent HLA codes (up to some edge cases described later in this text). From those matches, we filter out those with highest severity (based on match type). Rest of the codes are less important and not considered for the summary.`

2023-06-28 14:50 UTC, jakubmonhart commented on documentation/README.md
> +In case there are not any MFI values above cutoff for the frequent HLA code, we use `null` value for the summary MFI.
Tady by to chtelo lepe popsat co je to za pripad. V tomhle pripade totiz upoustime od toho ze uvazujeme jenom frequent code.

2023-06-28 14:50 UTC, jakubmonhart commented on documentation/README.md
> +The summary MFI in this case will be `3500`, because we just calculated the arithmetic mean MFI values for frequent
```suggestion
The summary MFI in this case will be `4000`, because we just calculated the arithmetic mean MFI values for frequent
```

2023-06-28 14:50 UTC, jakubmonhart commented on documentation/README.md
> +We just send `null` value in this situation.
```suggestion
We just send `None` value in this situation.
```

2023-06-28 14:50 UTC, jakubmonhart commented on documentation/README.md
> +So we just take their SPLIT `B1` as summary HLA code. The summary MFI is calculated via `= (3000 + 4000) / 2 = 3500`
```suggestion
So we just take their SPLIT `B7` as summary HLA code. The summary MFI is calculated via `= (3000 + 4000) / 2 = 3500`
```

2023-06-28 15:05 UTC, jakubmonhart commented
@abragtim Chceme tohle tedy uz mergovat do vetve `honza-vacation`? At necekame na honzovo review a muzeme pokracovat s dalsima taskama.

2023-06-28 19:34 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            else frequent_codes[0]
Myslím si, že zatím to problém nezpůsobí kvůli tomu, že při vícero frequent převede stejně na split, ale v budoucnu by mohlo, tak docela dává smysl. Opravím

2023-06-28 20:32 UTC, abragtim commented on documentation/README.md
> +In case there are not any MFI values above cutoff for the frequent HLA code, we use `null` value for the summary MFI.
Mohl bys, prosím, trochu víc rozepsat, co tady vadí? Zatím nechápu

2023-06-28 20:34 UTC, abragtim commented
> @abragtim Chceme tohle tedy uz mergovat do vetve `honza-vacation`? At necekame na honzovo review a muzeme pokracovat s dalsima taskama.

Jo, nemusíme asi už čekat na Honzu. Po approve od tebe to dám do `honza-vacation`.

2023-06-28 21:43 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                mfi=None,
```suggestion
                mfi= summary_match.hla_antibody.mfi,
```

2023-06-28 21:44 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            # there are not any antibody matches with frequent codes,
Když jsem teď dělal review na #1236, tak si myslím, že k nové logice víc zapadá, abychom tady poslali i summary MFI. @jakubmonhart , souhlasíš?

2023-06-29 08:06 UTC, jakubmonhart reviewed
Tak uz jen posledni drobnosti, stale kolem toho edge case s RARE hla.

2023-06-29 08:06 UTC, jakubmonhart commented on documentation/README.md
> +In case there are not any MFI values above cutoff for the frequent HLA code, we use the highest MFI value among infrequent
Tady se myslim ty dva negativy perou mezi sebou. Napsal bych jenom `In case there are no MFI values above ... `

2023-06-29 08:06 UTC, jakubmonhart commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    RARE_ALLELE_POSITIVE_CROSSMATCH = 'There is most likely no crossmatch, but there is a small chance that a ' \
Tady me napada i napsat ze v tom summary davame split toho infrequent kodu, at je to uplne jasny. At tam neni prostor pro to to pochopit tak ze tam mame nejaky match ktery ukazujeme v summary a do toho existuje nejaky dalsi RARE match.

2023-06-29 08:28 UTC, jakubmonhart reviewed
SPLIT je vzdy frequent, tak at tady nezanasime zmatky.

2023-06-29 08:28 UTC, jakubmonhart commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                                      'crossmatch.'
```suggestion
                                      'In summary we send SPLIT resolution of an infrequent code with the highest ' \
                                      'MFI value among antibodies that have rare positive ' \
                                      'crossmatch.'
```

2023-06-29 08:50 UTC, jakubmonhart approved these changes

2023-06-29 08:52 UTC, merged