Summary antibody is never null.
mild-blue/txmatching pull request #1236
Opened 2023-06-26 19:54 UTC by jakubmonhart

2023-06-26 20:12 UTC, jakubmonhart commented on documentation/README.md
> +                        {"hla_code": "B*07:05", "mfi": 1000, "cutoff": 2000}]
Pokud tady bude `assumed_hla_types = [{"hla_code": "B7", "is_frequent": True}]`, tak stale budeme vracet ten antibody s max mfi v high res, ok?

2023-06-27 07:31 UTC, kubantjan commented on documentation/README.md
> +                        {"hla_code": "B*07:05", "mfi": 1000, "cutoff": 2000}]
ujistime se dnes na callu.

2023-06-27 07:31 UTC, kubantjan commented on documentation/README.md
> +                        {"hla_code": "B*07:05", "mfi": 1000, "cutoff": 2000}]
spis ale tady chceme ukazovat ten split si myslim.

2023-06-27 07:46 UTC, jakubmonhart commented on documentation/README.md
> +                        {"hla_code": "B*07:05", "mfi": 1000, "cutoff": 2000}]
+ Co budeme chtit davat do match type? Bude nam stacit to v tomto pripade nespecifikovat a dat tam None? Jinak bychom museli nejak snizovat cutoff a pocitat crossmatch s nejakou casti antibodies .. vlastne nevim co by davalo smysl.

2023-06-27 09:13 UTC, jakubmonhart commented on documentation/README.md
> +                        {"hla_code": "B*07:05", "mfi": 1000, "cutoff": 2000}]
Tady vzdy do summary davat split resolution

2023-06-27 09:15 UTC, jakubmonhart commented on documentation/README.md
> +                        {"hla_code": "B*07:05", "mfi": 1000, "cutoff": 2000}]
Pridat hlasku ze kod jsme vzali z antibodies mfi<cutoff (crossmatched antibodies je ale prazdny list)

2023-06-28 21:45 UTC, abragtim requested changes
Super, tak jen drobnosti

2023-06-28 21:45 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        self.summary = self._calculate_crossmatch_summary(all_antibodies=all_antibodies)
```suggestion
        self.summary = self._calculate_crossmatch_summary(all_antibodies=all_antibodies or [])
```

2023-06-28 21:45 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                    hla_code=self.assumed_hla_types[0].hla_type.code,
přidej komentář o tom, jak obvykle vypadají kódy, které jsou v assumed a zároveň nemají ani negative match + že víme, že ztratíme všechny mimo první kód, pokud jsou jich tam víc, ale je to natolik vzácná situace, že ji neřešíme (nenese za sebou žádné rozhodovací důsledky pro uživatele)

2023-06-28 21:45 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +            'potential_donor_hla_typing': [[{'hla_code': 'A*01:01N', 'is_frequent': True}]],
```suggestion
            'potential_donor_hla_typing': [[{'hla_code': 'A*01:01N', 'is_frequent': False}]],
```
jak v README

2023-06-29 07:38 UTC, jakubmonhart commented on documentation/README.md
> +#### Summary in case of no crossmatch
Muze ale nastat ten case s pismenkem, a to uz neni ani negative crossmatch, tak dam `Summary in case of no positive crossmatch`, at je to presny i oficialni :)

2023-06-29 07:44 UTC, jakubmonhart commented on documentation/README.md
> +assumed_hla_types = [{"hla_code": "A*01:01N", "is_frequent": True}]
Jasny, dava smysl, opravim.

2023-06-29 08:37 UTC, abragtim approved these changes

2023-06-29 08:37 UTC, jakubmonhart commented
Jeste rebasnu

2023-06-29 09:05 UTC, merged