zrusit match type v summary a doplnit nejaky issues
mild-blue/txmatching pull request #1245
Opened 2023-07-02 12:10 UTC by jakubmonhart

2023-07-03 06:43 UTC, abragtim requested changes
a ještě update README

2023-07-03 06:43 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        match_type = matches_with_frequent_codes_and_summary_type[0].match_type
přidej, prosím, komentář, proč lze vzít jen první kvůli tomu, že mají stejný summary match type

2023-07-03 06:43 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            pass
Chceme ještě vyřešit case THEORETICAL a NONE, jo? Undecidable zatím nevadí, když spadne do else: AssertionError, jen by bylo dobré o tom komentář přidat

2023-07-03 06:43 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +                issues=[CadaverousCrossmatchIssueDetail.HIGH_RES_MATCH_ON_SPLIT_LEVEL]
Proveď tento case přes komentáře, tj. upozorní na nutné aspekty vstupu, a pak napiš jaký očekáváme výsledek a proč

2023-07-03 06:43 UTC, abragtim commented on tests/web/test_do_crossmatch_api.py
> +                                      'cutoff': 2000}] + type_A_antibodies
Proč bylo potřeba měnit existující kódy? Nestačilo jen přidat type_A_antibodies? To nevadí, jenom abych správně pochopil změny

2023-07-03 07:12 UTC, jakubmonhart commented
prejmenovat issues na neco obecnejsiho

2023-07-04 09:25 UTC, abragtim requested changes
Skvěle! Tak tuto verzi můžeme nasadit na STG. Myslím si, že by šlo zlepšit README, ale STG už můžeme ukázat IKEM :)

2023-07-04 09:25 UTC, abragtim commented on documentation/README.md
> +
Vůbec bych nezmiňoval summary match type, protože už neexistuje na output, tj. na místě, kde je v README napsáno HIGH RES, tak je lepší napsat hlášku. A tak pro různé HIGH RES, SPLIT a ostatní typy a všechno na příkladech.
A dělal bych to v nové samostatné sekci, abychom nepletli ty různé cases pro crossmatch issues, summary MFI, summyry code. Jen bych tam zmiňoval o jakou novou hlášku se jedná. Už bych popis úplně všech dal do separátní sekci

2023-07-04 09:25 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        elif match_type == AntibodyMatchTypes.UNDECIDABLE:
```suggestion
        else:
```

2023-07-04 09:25 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        elif match_type == AntibodyMatchTypes.UNDECIDABLE:
přidání v budoucnu nového typu (nejspíš ne, ale teoreticky ano) by mělo taky způsobit AssertionError

2023-07-04 09:25 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            pass
Tady bych rovnou dělal return z toho důvodu, že se už nic nestane, tak není třeba ten kód číst dál do return až na konci, můžeme rovnou out z této funkce.

Na ostatních místech taky

2023-07-04 14:27 UTC, jakubmonhart commented on documentation/README.md
> +
@abragtim na summary match type se snazim neodkazovat, ale dava smysl prece vyuzit definici tech typu crossmatche co uz v dokumentaci mame. Tak se mrkni jestli je to ted ok.

2023-07-04 14:32 UTC, abragtim approved these changes

2023-07-04 14:46 UTC, merged