Add 'is_crossmatch' property for each hla type in crossmatch api output
mild-blue/txmatching pull request #1246
Opened 2023-07-04 11:23 UTC by jakubmonhart

2023-07-04 11:32 UTC, abragtim requested changes
Yes, tento boolean stačí

2023-07-04 11:32 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if match.match_type in (AntibodyMatchTypes.UNDECIDABLE, AntibodyMatchTypes.NONE):
To se změní, když začneme řešit undecidable, jo? Udělej ještě komentář s TODO na to issue s undecidable, které je na mě

2023-07-04 11:38 UTC, jakubmonhart commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if match.match_type in (AntibodyMatchTypes.UNDECIDABLE, AntibodyMatchTypes.NONE):
Tomu moc nerozumim. Nasel jsem tohle issue #1243 kde ale jeste neni doplneno o co jde.

Kdyz jsem se nad tim ted znovu zamyslel, UNDECIDABLE by se tady objevit nemelo vubec. Mas k tomu vic info?

2023-07-04 14:39 UTC, abragtim requested changes

2023-07-04 14:39 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    is_crossmatch: bool
```suggestion
    is_pozitive_crossmatch: bool
```

2023-07-04 14:39 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if match.match_type in (AntibodyMatchTypes.UNDECIDABLE, AntibodyMatchTypes.NONE):
Myslím si, že undecidable je pozitive crossmatch. Ale pokud se v tom neshodujeme, tak to nevadí. Vyřešíme to pak v issue, o kterém zmiňuješ #1243. Zatím jen '#TODO: link na issue'

2023-07-06 06:20 UTC, abragtim requested changes
cool. Jenom drobný refactoring

2023-07-06 06:20 UTC, abragtim commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    def check_if_positive_crossmatch(self):
```suggestion
    def is_positive_crossmatch(self):
```

Jinak lze chápat jako "udělat nějaký check, pokud je positivní crossmatch"

2023-07-06 19:45 UTC, merged