Parse antibodies from luminex output and update recipient.
mild-blue/txmatching pull request #1263
Opened 2023-08-16 11:15 UTC by jakubmonhart

2023-08-16 13:01 UTC, jakubmonhart commented
+ uprava hlasky:
<img width="748" alt="image" src="https://github.com/mild-blue/txmatching/assets/23408949/3bf480a6-3d74-442c-b3c5-7dae12c67def">

2023-08-16 14:21 UTC, kubantjan requested changes
jeste si nainstaluj pre-commit co mame v readme nebo v make, aby se ti ten notebook vycistil

2023-08-17 07:31 UTC, jakubmonhart commented
Ten precommit co mame tam teda chce delat docela dost zmen (poradi importu, cisteni trailing whitespace, ... ). To znamena ze to pri tech commitech moc lidi nepouziva a dostalo se nam tam spoustu neporadku?

2023-08-17 08:04 UTC, kubantjan commented
zni to tak, vsiml jsem si toho ted u toho tvyho notebooku, ale je mozny ze to nema nahozeny ani @abragtim  a me to nedoslo. Asi to proved prosim komplet.

2023-08-21 13:10 UTC, kubantjan approved these changes

2023-08-21 19:44 UTC, merged