Add severity split to different parsing issue types
mild-blue/txmatching pull request #793
Opened 2022-03-15 19:36 UTC by kristinagalik

Closes #791

2022-03-15 20:13 UTC, kristinagalik commented
Toto riesenie je skor proposal, tym ze uz v `hla_code_processing_result_detail.py` existuje ekvivalent "info severity", namely OK_PROCESSING_RESULTS, a issue popisuje rozlisovanie medzi info, error a warning, tak som len pridala dalsie dva typy severity. Rozlisovala som podla toho ako su vnimane napr v testoch: MFI_PROBLEM bol porovnavany v testoch s errormi, preto je zaradeny do errorov a pod... 

Tymto riesenim sa vzdy vieme spytat do akej kategorie severity parsing issue patri, ako sa to uz napr robi s OK_PROCESSING_RESULTS v `hla_transformation_store.py`.

2022-03-18 16:54 UTC, kubantjan commented
jo, to dava smysl, takto mi to prijde dobre

2022-03-18 16:54 UTC, kubantjan submitted a review, later dismissed

2022-03-20 18:24 UTC, kubantjan requested changes
Akorat bych pridal nejaky test, ktery zajisti, ze kazdy ten processing result detail je prave v jedne z eroor, warning, nebo ok kategorri,

Je mozny, ze to pujde nejak pekneji mozna uz rovnou v tom enumu (ale to si nejsem jistej) nebo proste unittestem to zkontrolovat :)

2022-03-21 07:34 UTC, kubantjan requested changes
Jeste maly komment

2022-03-21 07:34 UTC, kubantjan commented on tests/utils/hla_system/test_code_parser.py
> +    def test_parsing_errors_exactly_in_one_severity_category(self):
zkontroluje tohle, ze je ten processing result alespon v jedne z tech kategorii? Podle me ne, to bych jeste cheknul (tzn ze tam neni dira, ze by v jedny ani z tech kategorii nebyl)

2022-03-21 20:22 UTC, kubantjan approved these changes

2022-03-21 21:01 UTC, merged