Add sanity check that we have meaninful antibodies for patient
mild-blue/txmatching pull request #794
Opened 2022-03-15 21:53 UTC by kristinagalik

Closes #784

2022-03-18 10:25 UTC, kristinagalik commented
@kubantjan nie som si tu uplne ista kde by sa ten check mal diat, asi to pozeram moc skoro ale zaroven je to posledna nejaka funkcia aku som nasla z ktorej sa da vybrat aj info o tom ci si user vybral high resolution option aj pozriet tie antigeny. 

Zaroven sa to takto vola len ked sa pocita nieco nove, tak neviem ci to dat este "vyssie" aby ked sa user vrati ku konfiguracii pre ktoru uz vysledok ma, mu to ma vyhodit error znova, ale zaroven vsade "vyssie/skorej" mi to prislo odveci.

Plus este som sa chcela spytat na severitu tych errorov - staci ze o tom je info v debuggeri?

A testy este k tomu niesu, tie prirobim ked bude toto dobre:)

2022-03-18 16:57 UTC, kubantjan commented
Ja myslel, ze toto bude fungovat stejne, jako to, co kontroluje treba pocet hla_kodu v group, tam ze se zkontorluje i tohle a pripadne se zase ulozi dalsi typ parsing erroru.

2022-03-18 17:01 UTC, kubantjan requested changes
Maly technicky koment, ale hlavni je ten obecny. Tzn ze to bude potreba tenhle check presunout jinam a nebudeme vubec chtit resit logger.error, ale zase ukladani parsing erroru do db :)

2022-03-19 12:36 UTC, kristinagalik commented
Lenze to nie je parsing error ci? Pretoze ak nepocitame v high res tak to neni error. Preto som myslela ze ten check treba urobit az ked sa zacne pocitat, lebo tam treba tu informaciu z configu. Ci to bolo myslene tak ze pokial uz sa davaju tie HLACodes v high_res verzii uz na zaciatku vsetky? @kubantjan

2022-03-20 18:16 UTC, kubantjan commented
> Lenze to nie je parsing error ci? Pretoze ak nepocitame v high res tak to neni error. Preto som myslela ze ten check treba urobit az ked sa zacne pocitat, lebo tam treba tu informaciu z configu. Ci to bolo myslene tak ze pokial uz sa davaju tie HLACodes v high_res verzii uz na zaciatku vsetky? @kubantjan
> 
> Edit: uz som to zmenila :) je to takto v pohode?

k tomu doplneni:

mozna parsing neni spravny slovicko, ale jedna se o error ktery se tyka dat, ktere nahrali k pacientovi. Tzn mel by se odhalit uz v momente, kdy toho pacienta zadavaji. 

Kazdopadne bych to strcil to teto skatulky erroru..

2022-03-20 18:19 UTC, kubantjan approved these changes

2022-03-20 20:54 UTC, merged