Remove from parsing error table and add there patient id and patient type
mild-blue/txmatching pull request #798
Opened 2022-03-20 10:16 UTC by kristinagalik

Closes #788

2022-03-30 08:10 UTC, kubantjan commented
@nikola-svobodova na to jeste koukne a zkusi ten erorr 500 dofixovat, zaroven na tom uz pracuje i @kristinagalik , ktera uz to skoro ma a dotahuje nejaky testy plus jeste to, aby se ten list erroru ukladal rovnou spolecne s objektem pacienta.

2022-04-01 10:11 UTC, kristinagalik commented
@nikola-svobodova cize co sa zhruba vsetko deje:
* ParsingError uz nema medical_id stlpec ktory by ho spajal s pacientom, ale ma donor/recipient id, z coho je jeden None
* Donor/Recipient teraz maju novy column - parsing_errors ktory ma byt list vsetkych parsing errorov ktore sa s danym pacientom spajaju 
* dal sa prec ParsingInfo objekt, a co sa dialo doteraz je ze v tom ParsingInfo sa vzdy do nizsich funkcii posielalo info o pacient id a event id, a v najspodnejsich funkciach sa potom toto info pouzilo na to, aby sa pridavali errory do databazy. Co sa deje teraz je uplny opak - ak sa v nizsich funkciach pride na daky parsing error, tak sa len urobi list ParsingError-ov a ten list sa posuva vyssie a vyssie az kym nenarazi na funkcie kde sa uploaduje vlastne aj zvysok pacienta, a tam sa prida parsing_errorom prislusne pacient/event id a ulozia sa do databazy

2022-04-02 12:52 UTC, kubantjan commented
@kristinagalik  @nikola-svobodova  ted jsme to s nikolou resili a co se tyka migrace starych dat v parsing_error tabulce, je ok ty data proste dropnout. V pripade potreby pujde lehce ty data zase doplnit.

2022-04-02 14:05 UTC, kristinagalik commented
@nikola-svobodova @kubantjan 
cize podarilo sa mi este urobit zmeny ktore sa zbavili par errorov a failov, no este tam nejake su, a to su nasledovne: 

error v `test_recompute_hla_and_antibodies_parsing` ktory sa stazuje ze : `AttributeError: 'InstrumentedList' object has no attribute 'hla_types_list'` comu moc nreozumiem lebo tej casti kodu som sa moc nechytala

fail v `test_txm_event_patient_successful_upload` ktory teda hovori o tom ze nie vsetky errory co sa mali uploadnut sa uploadli (`self.assertEqual(expected_count, len(errors)) -> AssertionError: 26 != 22`)... presla som este raz vsetky funkcie ktore sa pouzivaju/pouzivali na to aby sa pridali pocas uploadu pacientov errory do databazy, no neviem najst dieru...

2022-04-02 14:40 UTC, nikola-svobodova commented
@kristinagalik ten test: `test_recompute_hla_and_antibodies_parsing` pada podle me jen protoze v patient_service.py ma byt na 307 radku parse_hla_antibodies_raw_and_add_parsing_error_to_db_session, ted je tam parse_hla_typing_raw_and_add_parsing_error_to_db_session

2022-04-02 21:42 UTC, kristinagalik commented
@kubantjan
tak som pomenila ten patient upload, zistila ze parsing errorov ma byt v tom teste co failuje naozaj len 22 cize to som prepisala (vsetky su vypisane par riadkov skor), testy by uz mali tym padom vsetky prechadzat a pocistila som v uploade tie parametre co sa passuju do `add_ids_to_parsing_errors_and_return_parsing_errors_models` co si spominal ze by to nemuselo brat donor/recipient id.. inde to este robim (v update donor/recipient) lebo v `update_donor` a `update_recipient` (a rovnez aj v `_create_patient_update_dict_base`) to bez toho pada, ked parsing errory vkladam do dictionary... zajtra sa na to este skusim pozriet, ale worst case scenario to uz funguje either way 🙂

2022-04-03 14:56 UTC, kubantjan requested changes
Prubezne davam komentare

2022-04-03 14:56 UTC, kubantjan commented on tests/web/public_api/test_public_patient_upload_data_validation.py
>          # three errors from the real processing and 2 from get_hla_typing above
tady neni spravne 3 plus 2 ale jiny pocet, vysvetli to tady prosim

2022-04-03 16:14 UTC, kubantjan commented
(obecne pro @Kristína Gáliková :

- formatting mas obcas blbej, v necem mame ten linter jeste hloupej

treba:

```
a = 1 //spravne
a=1 //spatne

function(x=1) //spravne
function(x = 1) //sptane
```

je to nejakej codestyle, kterje je standard. Intellij umi automaticky reformat kodu, tak jsem to tam obcas volal

- bacha kdyz menis apicka, co vraci, aby to nerozbilo FE, co jiny navaznosti: zmenily se tu 2 veci:
- public apicko ktere prijima novy pacienty, opravil jsem
- apicka na editaci pacientu pro FE - nechal jsem, FE stale funguje, i kdyz ne uplne dobre a to neva, stejne to bude lubos upravovat, ale je potreba na takovy veci v review upozornit a uvedomit si je :)

2022-04-03 16:14 UTC, kubantjan commented
jinak super, diky!

2022-04-04 06:08 UTC, merged