#818 divide enviroments files to local and stg, add enviroments.ts to .gitignore
mild-blue/txmatching pull request #819
Opened 2022-04-06 11:26 UTC by NotLubo

2022-04-06 12:27 UTC, misslecter requested changes
Trochu se mi nelíbí, že v gitu máme něco, co má v názvu `.local.`

Co to udělat takhle:

- V gitu mít defaultní `environment.ts` a produkční `environment.prod.ts` (jak to bylo do teď)
- Mít lokálně `environment.local.ts`, který bude v `.gitignore`
- Do `angular.json` přidat nový config `"dev"`, který při spuštění použije `environment.local.ts`:

```
 "dev": {
      "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.local.ts"
        }
      ],
     ...
}
```
Tady je když tak rozepsané, co se má upravit v `angular.json` https://www.itsolutionstuff.com/post/how-to-use-environment-variable-in-angularexample.html (ten `"dev"` config je na více místech).

Nejspíš to povede k tomu, že po novém stažení projektu bude potřeba vytvořit `environment.local.ts`, což ale je dost běžná practice, takže to nevadí.

Obdobně se může udělat config pro `"stg"`.

2022-04-06 12:34 UTC, NotLubo commented
Tak jo souhlas :)

2022-04-06 12:37 UTC, NotLubo commented
Local ale v podstate nepotrebujeme lebo to bol doteraz default enviroment.ts.

2022-04-06 12:57 UTC, NotLubo commented
Myslím si že tak ako si to napísala to stačí. Do local si potom človek dá čo chce. Teda zvlášť stg netreba

2022-04-08 06:54 UTC, NotLubo commented
Doplnené :)

2022-04-25 11:53 UTC, misslecter approved these changes

2022-04-25 11:54 UTC, merged