Prevention of overriding patients
mild-blue/txmatching pull request #820
Opened 2022-04-06 13:10 UTC by kristinagalik

Closes #774

2022-04-08 07:07 UTC, kubantjan commented
* pacienti uz nemozu byt overridovani
* ak sa niekto snazi overridnut pacienta vyhodi to warning message
Co chyba/je este asi zle:
1) testy som este vobec neriesila lebo najprv treba vyriesit following veci
2) neviem co sa ma stat v pripade ze clovek stlaci save - ci mam proste urobit nieco ako mock pacienta ktory bude vlastne reprezentovat to co tam je zatial nahodene (cize zo strany pouzivatela to bude vyzerat ze sa nic nestalo len ze mu vyskocil warning message) alebo to vyhodi toho pacienta co tam je aktualne? (lebo aj tak je clovek nuteny stratit ten progres ak to manualne nahadzuje...) <- toto tam aj zatial robim
3) myslim ze aj ked to funguje, je to trochu konceptualne zle.. co sa teraz deje je, ze response je ok, tvari sa to ako by sa ten pacient ulozil, no neuklada sa a hadze to warning message.. a keby sa vyriesi toto, tak sa podla mna vyriesi aj predosly bod.

Zatial som pushla vsetky zmeny ale este sa na to asi skusim pozriet dnes, ak daco este pomenim tak dam vediet :)

2022-04-08 07:10 UTC, kubantjan commented
2+3. 
- Udelej to prosim tak, ze API kdyz se nepodari ulozit kvuli overridu, tak vrati error. (tzn ne ok a toho predchoziho pacienta)
- kdyz se vrati ten error tak FE proste necha toho rozdelanyho pacienta jak je 
- error hlaska co se napise je: nemuzu ulozit pacienta, nekdo jiny ho uz editoval, musite si pacienta znovu nacist a tam ho upravit. (tzn ty zmeny co mate ted ztratite a musite si je ulozit nekam bokem)

Neni to uplne krasny ale mela by to bejt minimal change, ktera neni silene narocna a bude si myslim dobre srozumitelna pro uzivatele (ted jsme to resili s @NotLubo )

2022-04-10 21:19 UTC, kristinagalik commented
@kubantjan 
@NotLubo so mnou pozeral na FE, a navrhol tuto issue riesit spolu s #674 
Dalsie updates: na backende by to malo byt uz fajn, testy su opravene/pridane, este teda chyba nejak krajsie urobit ten error handling na frontende :) ale fungovat to funguje

2022-04-13 19:16 UTC, kristinagalik commented on txmatching/web/frontend/src/app/components/patient-donor-detail/patient-donor-detail.component.ts
> +      this._alertService.infoPatientIsBeingOverriden();
Toto je nieco co by chcelo asi samostatnu issue este, idealne high priority, lebo to neni idealne riesenie.. hlavne ak by sa malo este na zaklade typu erroru rozlisovat v tom aky alert sa ma uzivatelovi zobrazit, asi by bolo fajn odchytavat errory uz v saveDonor a saveRecipient funkciach nez az tu

2022-04-14 07:24 UTC, NotLubo commented
Za mňa FE okej s tým že to čo kristína označila sa ide dorobiť v rámci #674

2022-04-14 07:53 UTC, kubantjan requested changes
Par komentaru na vylepseni logiky

2022-04-14 07:53 UTC, kubantjan commented on txmatching/database/db_migrations/0029.add-etag-to-patient-models.sql
> +-- file: txmatching/database/db_migrations/0029.add-etag-to-patient-models.sql
bacha, 29 uz mame, chces uz 30.

2022-04-14 07:53 UTC, kubantjan commented on txmatching/database/services/patient_service.py
>      if txm_event_db_id != old_recipient_model.txm_event_id:
tady koukam ze ten error nerika, to co realne znamena, opravis to prosim?

2022-04-14 07:53 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +def update_recipient(recipient_update_dto: RecipientUpdateDTO, txm_event_db_id: int) -> (Recipient, bool):
obecne bych se snazil vyvarovat vraceni tuples, je pak tezko citelny, co ty tuples znamenaji. Nejlepsi je vracet dataclassu, nebo se tomu vyhnout uplne

2022-04-14 07:53 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +    if recipient_update_dict['etag'] - 1 == old_recipient_model.etag:
tady bych tu condition prehodil, nejdriv ten error, pak to druhy, takhle se to fakt blbe hleda.

2022-04-14 07:53 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +    if donor_update_dict['etag'] - 1 == old_donor_model.etag:
taky prehozeni condition

2022-04-14 07:53 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +def update_recipient(recipient_update_dto: RecipientUpdateDTO, txm_event_db_id: int) -> (Recipient, bool):
v tomto pripade chces tady rovnou reaisova eroro, ktery pak chytis pres

error_handler.py (podivej se na jine errory, ktere tam jsou a jak to funguje)

tzn tady zadny tuple vracet nebudes ale primo v miste, kde zjistis, ze overridujes pacienta vyhodis error

2022-04-14 07:53 UTC, kubantjan commented on txmatching/web/web_utils/namespace.py
> +    def overriding_error(self):
tohle zmizi (viz jiny komentar, a soubor errror_handler

2022-04-14 07:53 UTC, kubantjan commented on txmatching/web/web_utils/route_utils.py
> +def overriding_error(code=406):
ohle zmizi (viz jiny komentar, a soubor errror_handler

2022-04-14 07:53 UTC, kubantjan commented on txmatching/web/api/patient_api.py
> +    @patient_api.overriding_error()
ohle zmizi (viz jiny komentar, a soubor errror_handler

2022-04-14 07:53 UTC, kubantjan commented on txmatching/web/api/patient_api.py
> +    @patient_api.overriding_error()
ohle zmizi (viz jiny komentar, a soubor errror_handler

2022-04-14 09:20 UTC, kristinagalik commented on txmatching/database/services/patient_service.py
>      if txm_event_db_id != old_recipient_model.txm_event_id:
prepac nerozumiem co presne mas namysli.. ze uz tie `parsing_errors` mam rovno prepisat na parsing issues?

2022-04-14 10:29 UTC, kubantjan commented on txmatching/database/services/patient_service.py
>      if txm_event_db_id != old_recipient_model.txm_event_id:
Nene jen ten error co je tady raisnutej má nějaký divný text ne? Podle mě neodpovídá tomu co se tu stalo

2022-04-19 07:52 UTC, kubantjan requested changes
Dva male komentare

2022-04-19 07:52 UTC, kubantjan commented on txmatching/web/api/patient_api.py
> -                parsing_errors=get_parsing_errors_for_patients(recipient_ids=[updated_recipient.db_id], txm_event_id=txm_event_id)
tady delas z nejakyho duvodu jen formatovaci zmeny, takovym vecem je dobry se vyhybat, pak je to pri review matouci. zda se ze mas nastaveny nejak jinak sirku stranky, proto ti to pri upravach takhle upravuje. Ja mam 120, kolik ty?
![Screenshot from 2022-04-19 09-49-29](https://user-images.githubusercontent.com/24394374/163952834-978e2ec5-fd2c-46bc-932f-80381c7fa23d.png)

2022-04-19 07:52 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +    else:
tohle bych dal zase nahoru, fakt se to lip cte

https://softwareengineering.stackexchange.com/questions/431529/is-error-first-better-than-if-else-why

2022-04-19 10:23 UTC, NotLubo commented
FE v poriadku. Možno by som namiesto etag použil errorType príde mi to výstižnejšie ale je to len špŕtanie :)

2022-04-20 06:42 UTC, kubantjan commented on txmatching/web/api/patient_api.py
> -                parsing_errors=get_parsing_errors_for_patients(recipient_ids=[updated_recipient.db_id], txm_event_id=txm_event_id)
ahh tak pardon, zda se ze tohle konkretne byl fakt moc dlouhej radek

2022-04-20 06:44 UTC, kubantjan commented
jeste prosim toto
![Screenshot from 2022-04-20 08-44-16](https://user-images.githubusercontent.com/24394374/164166939-a38d1719-742c-4ba6-b927-88a20365dc4c.png)

2022-04-20 06:45 UTC, kubantjan commented on txmatching/web/api/patient_api.py
> -                parsing_errors=get_parsing_errors_for_patients(recipient_ids=[updated_recipient.db_id], txm_event_id=txm_event_id)
tzn ze autoformat mame fakt nastavenej stejne, ale z nejakyho duvodu jsme tam uz nejakou dobu meli moc dlouhej ten radek

2022-04-20 06:47 UTC, kubantjan commented on txmatching/web/api/patient_api.py
> -                parsing_errors=get_parsing_errors_for_patients(recipient_ids=[updated_recipient.db_id], txm_event_id=txm_event_id)
takze ok i kdyz obecne menit fily jen kvuli formatovani je obecne v pohode, ale pak je dobry to zminit v PR a upozornit na to, ze clovek ma treba nejaky commity brat zvlast, ze jsou jen formatovani a ze realny zmeny se dejou jen nekde nebo tak. 

Kazdopadne ted to takto nech :)

2022-04-20 06:49 UTC, kubantjan approved these changes

2022-04-20 06:49 UTC, merged