Multiple donors per patient
mild-blue/txmatching pull request #834
Opened 2022-04-13 13:17 UTC by kristinagalik

Closes #822

2022-04-22 23:12 UTC, kristinagalik commented
@kubantjan 
este chyba:
* testy
* poriesit duplicitu vysledkov niekde na urovni ILP solveru
* este sa neskor teda pridaju nove FE issues

2022-04-22 23:14 UTC, kristinagalik commented on txmatching/database/services/txm_event_service.py
> +    all_recipients = sorted([get_recipient_from_recipient_model(donor.recipient)
tu mam skor otazku - ci neni lepsie sa tu niekde priebezne pytat nieco v zmysle - bol tento recipient uz pridany? nech sa zbytocne ten isty nepridava napr 3x, alebo je to zbytocne?

2022-04-25 07:10 UTC, kubantjan commented on txmatching/database/services/txm_event_service.py
> +    all_recipients = sorted([get_recipient_from_recipient_model(donor.recipient)
no myslim, ze v listu all recipients by mel byt kazdy recipent prave jednou, pokud mi neunika neco, takze ano.

2022-04-26 10:24 UTC, kristinagalik commented
@kubantjan 
este tam su 2 veci TODO:
1. v ILP solveri to duplicitu odignoruje, no for loop to aj tak berie do uvahy ako legit loop cize tomu este treba povedat "pocitaj dalej" (mam to ako lowercase todo, aby som si vedela na docasnych todos rozlisit ktore su moje a ktore longterm)
2. testy este niesu

Predtym nez budem riesit tieto veci ^^ by som rada dostala feedback na to co robim v tom ILP solveri, ci to je v pohode :)

2022-04-26 10:32 UTC, kubantjan commented
> @kubantjan este tam su 2 veci TODO:
> 
> 1. v ILP solveri to duplicitu odignoruje, no for loop to aj tak berie do uvahy ako legit loop cize tomu este treba povedat "pocitaj dalej" (mam to ako lowercase todo, aby som si vedela na docasnych todos rozlisit ktore su moje a ktore longterm)
> 2. testy este niesu
> 
> Predtym nez budem riesit tieto veci ^^ by som rada dostala feedback na to co robim v tom ILP solveri, ci to je v pohode :)

Meta poznamka jen:
v tomto pripade mi dava smysl udelat testy, nez budu delat review, ty ti to dobre otestuji a overis si ze vsechno funguje navic me to taky doda duvery, ze to vypada dobre a taky i kdyz reknu ze mas neco predelat, tak testy zustanou.

2022-04-26 12:29 UTC, kubantjan commented
@kristinagalik  plus jeste vidim, ze tam jsou nejaky konflikty, tak na to mrkni rovnou :)

2022-04-27 14:33 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +
@kubantjan 
tieto constraints by tu mali byt inak sa deje toto: (-1 je donor bez recipienta)
![image](https://user-images.githubusercontent.com/56656359/165537765-400a8ff5-7255-47c9-ac31-c53719a86c9c.png)
resp ta druha, ta prva je ak to spravne chapem nepotrebna, ale rovnat sa tie cisla nemusia (rozdiel je v tom ked to je bud chain alebo cycle)

2022-04-30 09:08 UTC, kubantjan commented
@kristinagalik  see PR #846 but please update this PR, not the other one,

2022-04-30 09:08 UTC, kubantjan requested changes
updates needed shown in #846

2022-05-01 13:49 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +    # convert solution_edges to set where there are donors represented as their recipients or as negative number
![image](https://user-images.githubusercontent.com/56656359/166148806-34ab2da7-659f-4086-b8dd-fe496979e512.png)
v situaciach ako tato treba vytriedit vsetky kombinacie

2022-05-01 13:50 UTC, kristinagalik commented
Plus po tomto PR vznikaju nove issues:
- [ ]  nejaky napr dropdown treba pridat na FE ked robime noveho donora a chceme ho priradit k existujucemu recipientovi
- [ ]  terat sa kazda dvojica nanovo ukazuje a tym aj duplikatni recipienti - toto treba asi spravit tak ze bude existovat box s recipientom a vsetkymi jeho donormi?
- [ ]  delete pair teraz vymaze vsetkych donorov k danemu recipientovi

2022-05-02 08:29 UTC, kubantjan commented
> Plus po tomto PR vznikaju nove issues:
> 
> * nejaky napr dropdown treba pridat na FE ked robime noveho donora a chceme ho priradit k existujucemu recipientovi
> * teraz sa kazda dvojica nanovo ukazuje a tym aj duplikatni recipienti - toto treba asi spravit tak ze bude existovat box s recipientom a vsetkymi jeho donormi?
> * delete pair teraz vymaze vsetkych donorov k danemu recipientovi

udelal jsem nove issue #848

2022-05-02 08:37 UTC, kubantjan requested changes
prijde mi ok, permutace davaji smysl, akorat neslo by ten kod nejak zprehlednit v tom pridavani jeste? Hodne tezko se to cte, jsou i nejaky interni python funkce na hledani permutaci treba. 

Kdyz ti to nepujde, zkusim se nad tim zamyslet.

plus nevim jestli v tom testu se fakt testuje, ze ti funguje cely to permutovani. Klidne bych pridal jeden test, kde budes testovat, ze ciste to permutovani fakt funguje tak jak cekas. 

ze bys videlila tu fci co dela permutace a na tu mela fakt low level test s par prikladama

2022-05-02 11:02 UTC, kristinagalik commented
@kubantjan staci tak ci este mam nieco zjednodusit? lebo uz neviem co ale mozem este dopisat komenty?
plus nasla som python itertools vec na tie permutacie - treba tym padom test alebo staci verit tej python funkcii

2022-05-03 14:06 UTC, kubantjan requested changes
Tak jeste zmeny
- mas nejaky uplne spatny ten rebase. Nevim asi si musime callnout, fakt pak chces mit linearni historii, ted je to velikansky zmatek, kde mas i zmeny ktery sem vubec nepatri (napriklad to REQUIRE_2FA na USE_2FA)

- nakonec podle me permutace nejsou potreba. Staci zajistit, ze to dalsi solution bude mit alespon jednu hranu, ktera:
1) neni mezi temi v reseni
2) neni ani mezi hranami, ktere by vedly od konce nejakyho chainu k libovolnemu jinemu donorovi, co ma stejnyho recpienta.

Tzn melo by stacit pridat jen jednu podminku, ne spoustu.

2022-05-06 06:57 UTC, kubantjan requested changes
Rebase great,

but I have added an extra test that is failing. It seems that the conditions for ILP solver are not enough to ensure everything.

Plus the _add_constraints_removing_solution needs rewrite, at the moment its really hard to read and its not clear what is happening there. And I am very sure it can be rewritten to be much simpler.

2022-05-06 06:57 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +    recipient_to_recipient_solution_edges = set()
This is quite hard to read. What I though will be the steps
0) find all edges that are at the end of chains (maybe write a function to do that)
1) Iterate through all edges that are at the end of chains (**d1** -> **d**)
2) For each **d** find all donors  that have the same recipient (denoted **dr1** .. **drn**
 3) For each such donor add the edge **d1** -> "dri" to sol_edges_set

continue the code as is

Maybe you are doing it here, but I cannot folow it. For eample # remember all donoring counterparts expressed as their recipients is quite confusing comment honestly.

2022-05-09 06:47 UTC, kubantjan requested changes
Couple of comments

2022-05-09 06:47 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +    sol_edges_set = set()
I would renemae this variable the name is not really intuitive.

2022-05-09 06:47 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +    sol_edges_set = set()
I am unable to find the proper name really. 

What would be maybe even better is to have here already:
```
edges_in_alternative_solution = set(data_and_configuration.graph.edges) - set(solution_edges)
```

a pak uz jenom:
```
end_of_chain_edges = _find_all_end_of_chain_edges(solution_edges, data_and_configuration)
for edge in end_of_chain_edges:
  recipient_at_the_end_of_chain = data_and_configuration.donor_enum_to_related_recipient[solution_edge[1]]
              all_donors_of_recipient = data_and_configuration.recipient_to_donors_enum_dict[
                  recipient_at_the_end_of_chain]
              for donor_enum in all_donors_of_recipient:
                  edges_in_alternative_solution.remove((solution_edge[0], donor_enum))
ilp_model.add_constr(mip.xsum([mapping.edge_to_var[edge] for edge in edges_in_alternative_solution]) >= 0.5)
return edges_in_alternative_solution
```

2022-05-09 06:47 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +        print(solution_edge[0], data_and_configuration.donor_enum_to_related_recipient[solution_edge[0]])
No print please, either delete or use logger (but here I think it should be deleted)

2022-05-09 06:47 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +        if solution_edge[0] in data_and_configuration.donor_enum_to_related_recipient:
In which case is the solution_edge[0] not in data_and_configuration.donor_enum_to_related_recipient its hard for me to understand?

2022-05-09 06:47 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +            set_of_donors.add(data_and_configuration.donor_enum_to_related_recipient[solution_edge[0]])
Here are two confusing things:

1) you have set of donors BUT you are putting data_and_configuration.donor_enum_to_related_recipient[solution_edge[0]] which looks like you are putting there releated RECIPIENT and not donor

2) why do you need to do this in the first place? Cannot you simple have set_of_donors.add(solution_edge[0])?

and then 

if solution_edge[1] not in set_of_donors?

2022-05-09 10:22 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +        if solution_edge[0] in data_and_configuration.donor_enum_to_related_recipient:
jaj pardon, to bol dlho dictionary len pre donorov typu DONOR a nie BRIDGING alebo NON_DIRECTED, a zabudla som ze som tu podmienku odstranila

2022-05-10 07:03 UTC, kubantjan requested changes
Couple of comments

2022-05-10 07:03 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
>      for solution_edge in solution_edges:
tohle jde taky udelat jako set comprehension

2022-05-10 07:03 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +            if (solution_edge[0], donor_enum) in edges_in_alternative_solution:
tohle if by nemel byt potreba, staci proste remove

2022-05-10 07:03 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
>      # create set to be removed
tenhle comment neni up to date

2022-05-10 07:03 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
>      # find all donors from the end of chains to exclude
tenhle comment neni up to date

2022-05-10 14:54 UTC, kubantjan requested changes
Use discard comment

2022-05-10 14:54 UTC, kubantjan commented on txmatching/solvers/ilp_solver/solve_ilp.py
> +            if (solution_edge[0], donor_enum) in edges_in_alternative_solution:
tak je treba pouzit druhou fci discard:

https://www.geeksforgeeks.org/python-remove-discard-sets/#:~:text=The%20built%2Din%20method%2C%20discard,the%20original%20set%20is%20printed.

2022-05-10 16:43 UTC, kubantjan reviewed
Vypada dobre, jeste prolitnu zitra rano, ale myslim, ze to rovnou mergnu, diky!

2022-05-11 07:08 UTC, kubantjan commented
@kristinagalik jeste tim squashem jsou ted spatny jmena tech commitu, v tom prvni se toho deje spousta, ne jen refactor

2022-05-11 07:12 UTC, merged