#842 badge added to flag in reports
mild-blue/txmatching pull request #843
Opened 2022-04-25 12:25 UTC by NotLubo

2022-04-26 05:18 UTC, NotLubo commented
@kubantjan prosím o pretestovanie

2022-04-26 07:44 UTC, kubantjan requested changes
Opravil jsem spatne improty a chybejici flag component na spouste mist, ted uz to facha, ale furt je to nekde hnusne. Viz prilozene pdf.

[report_2022_04_26_09_41_56.pdf](https://github.com/mild-blue/txmatching/files/8560936/report_2022_04_26_09_41_56.pdf)

2022-04-26 08:53 UTC, kubantjan commented
[report_2022_04_26_10_51_14.pdf](https://github.com/mild-blue/txmatching/files/8561440/report_2022_04_26_10_51_14.pdf)

jeste to neni ono a bacha force pushnul jsem, pullni si to nacisto, byl tam zas bordel v oommitech, tak jsem to rovnou procistoval.

2022-04-27 06:35 UTC, kubantjan approved these changes

2022-04-27 06:43 UTC, merged