Added endpoint TxmEventCopyBetweenEvents
mild-blue/txmatching pull request #847
Opened 2022-05-01 17:59 UTC by krllstdn

Added endpoint TxmEventCopyBetweenEvents with tests.
It copies the given list of donors (and related recipients) from one txm_event to the other

2022-05-03 14:12 UTC, kubantjan commented
Great thank you! I will look into that.

2022-05-04 19:57 UTC, krllstdn commented
Looking forward to hear your critique.

2022-05-06 07:16 UTC, kubantjan commented
As we have sent by email, please fix the tests first, before we look into it more deeply.

Otherwise I have one high level comment: in all our other endpoint we use json objects to send data to the api, not the url path itself. Please use this approach also in the case of the new endpoint.

2022-05-06 07:16 UTC, kubantjan requested changes
As we have sent by email, please fix the tests first, before we look into it more deeply.

Otherwise I have one high level comment: in all our other endpoint we use json objects to send data to the api, not the url path itself. Please use this approach also in the case of the new endpoint.

2022-05-08 13:35 UTC, krllstdn commented
Okay, thanks. I'll correct the input. For some reason on my machine tests fail even on the stable version. Some "import errors" even though the app works fine. Probably a problem with the environment. I'm working on that.

2022-06-03 14:59 UTC, krllstdn commented
As mentioned in the commit, the endpoint tests seem to work but showed up the error from the swagger part. Everything was generated as mentioned in README.md using `make generate-swagger-all` command.  The error has the following description:

FAIL: test_server_logged_in (web.test_swagger_endpoint.TestSwaggerEndpoints)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/krllstdn-txmatching/txmatching/tests/web/test_swagger_endpoint.py", line 58, in test_server_logged_in
    swagger_test(swagger_yaml_path=PATH_TO_SWAGGER_YAML,
  File "/home/kirill/anaconda3/envs/txmatching/lib/python3.8/site-packages/swagger_unittest/swagger_tester/swagger_tester.py", line 228, in swagger_test
    for _ in swagger_test_yield(swagger_yaml_path=swagger_yaml_path,
  File "/home/kirill/anaconda3/envs/txmatching/lib/python3.8/site-packages/swagger_unittest/swagger_tester/swagger_tester.py", line 322, in swagger_test_yield
    validate_definition(swagger_parser, response_spec[response.status_code], response_json)
  File "/home/kirill/anaconda3/envs/txmatching/lib/python3.8/site-packages/swagger_unittest/swagger_tester/swagger_tester.py", line 82, in validate_definition
    assert type(response) == type(valid_response)
AssertionError

2022-06-07 14:59 UTC, kristinagalik commented
hi @krllstdn :)
try looking at the format of the responses of other endpoints. In your code, on line 172 in `txmatching/web/api/txm_event_api.py` you are specifying `CopyPatientsJson` as the output format, but its not the same as what you are returning on line 188. Also, its better to use List[int] rather than list. Hope this helped :)

2022-06-07 15:00 UTC, kristinagalik commented on txmatching/web/api/txm_event_api.py
> +        CopyPatientsJson,
here is the specified format

2022-06-07 15:00 UTC, kristinagalik commented on txmatching/web/api/txm_event_api.py
> +        return response_ok(new_patients_ids)
here is the response in the wrong format

2022-06-08 14:12 UTC, krllstdn commented
@kristinagalik Thank you! I corrected it and now I at least see what type of error it is. (500 internal server error)

2022-06-09 18:33 UTC, kristinagalik requested changes
if you have any questions, don't hesitate to ask :)

2022-06-09 18:33 UTC, kristinagalik commented on tests/web/test_txm_event_api.py
> +            self.assertEqual('application/json', res.content_type)
also, there is no actual checking whether the new txm event contains the patients in question

2022-06-09 18:33 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +def copy_patients_between_events(txm_event_id_from: int, txm_event_id_to:int, donor_ids: list) -> List[int]:
i think this function should be in one of the files in services

2022-06-09 18:33 UTC, kristinagalik commented on txmatching/web/api/txm_event_api.py
> +        donor_ids = [int(donor_id) for donor_id in copy_dto.donor_ids]
the converting function isn't necessary since you enforce the type in TxmEventCopyDTOIn

2022-06-09 18:33 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +            )
for this, and for recipients, it would be better if you wrote separate functions that create DonorUploadDTO from DonorModel (the same for Recipient). because like this, someone could assume there is no such function and create one if needed, which would lead to duplicate code

2022-06-10 06:37 UTC, kristinagalik commented on txmatching/data_transfer_objects/patients/txm_event_dto_in.py
> +class TxmEventCopyDTOIn:
just a suggestion - wouldn't it be better if you had TxmEventCopyPatientsDTOOut and TxmEventCopyPatientsDTOIn? TxmEventCopyDTO looks as if you were copying also other parameters, such as config... and its a little inconsistent with the other class that you made

2022-06-10 07:10 UTC, kubantjan commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +    txm_event_from = get_txm_event_complete(txm_event_id_from, load_antibodies_raw=True)
I would say it is as without this flag the raw antibodies would not be loaded and they are needed to create the RecipientUploadDTO

2022-06-10 13:26 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +            DonorModel.id==donor_id).first().country
the Donor class extends the Patient class that has attribute parameters (PatientParameters) that already includes the country code, so you don't need to retrieve it from the database

2022-06-10 16:39 UTC, krllstdn commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +def copy_patients_between_events(txm_event_id_from: int, txm_event_id_to:int, donor_ids: list) -> List[int]:
@kristinagalik In services (txm_event_service and patient_service) this function creates a circular import error.

  File "/mnt/d/krllstdn-txmatching/txmatching/txmatching/database/services/patient_service.py", line 31, in <module>
    from txmatching.database.services.patient_upload_service import add_donor_recipient_pair
ImportError: cannot import name 'add_donor_recipient_pair' from partially initialized module 'txmatching.database.services.patient_upload_service' (most likely due to a circular import) (/mnt/d/krllstdn-txmatching/txmatching/txmatching/database/services/patient_upload_service.py)

2022-06-11 22:10 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +def copy_patients_between_events(txm_event_id_from: int, txm_event_id_to:int, donor_ids: list) -> List[int]:
since you don't need to access the database (because of the donor_country on line 30), it makes sense to me to keep it in this file for now. sorry I didn't update this comment yesterday with the country code one

2022-06-13 19:59 UTC, kristinagalik requested changes

2022-06-13 19:59 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +from txmatching.patients.patient import Donor, TxmEvent
this is not alphabetically ordered

2022-06-13 19:59 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +def copy_patients_between_events(txm_event_id_from: int, txm_event_id_to:int, donor_ids: list) -> List[int]:
here you should have a blank space after `txm_event_id_to:`

2022-06-13 19:59 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +            recipient=recipient_upload_dto
if related_recipient_id is None, i dont think this should work, because you are referencing a nonexisting variable

2022-06-13 19:59 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +from txmatching.patients.patient import Donor, TxmEvent
there are other instances in the rest of the code, please check it

2022-06-13 19:59 UTC, kristinagalik commented on txmatching/web/api/txm_event_api.py
> +from flask import request
this import is unused

2022-06-13 19:59 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +def copy_patients_between_events(txm_event_id_from: int, txm_event_id_to:int, donor_ids: list) -> List[int]:
if you dont want to check for such code formatting details all the time, i recommend getting a formatter! :)

2022-06-13 20:01 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +            recipient=recipient_upload_dto
(lines 29-31)

2022-06-14 07:45 UTC, krllstdn commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +def copy_patients_between_events(txm_event_id_from: int, txm_event_id_to:int, donor_ids: list) -> List[int]:
Good hint, thanks)

2022-06-14 08:40 UTC, krllstdn commented
@kristinagalik Hi, I have installed the formatter so I hope there won't be any formatting errors this time) Also, I've  added an assertion to tests, I hope that it is what was expected

2022-06-14 09:20 UTC, kristinagalik commented
hi @krllstdn ur right, I completely overlooked the previous assertion in tests - sorry about that! I think the code is ok now :) I'm going to run the tests and @kubantjan will give you a review too :)

2022-06-21 08:38 UTC, kubantjan requested changes
Hello!

thank you for the PR. I think its almost ready now. Well done. 

I have written couple of small comments. Please have a look. After they are updated we can close the PR.

Apart from the comments in code, please also do a rebase on current master.

2022-06-21 08:38 UTC, kubantjan commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +        copied_donor = add_donor_recipient_pair(donor_recipient_pair, txm_event_id_to)
Here be careful. function add_donor_recipient_pair directly commits the changes to database.

this would mean that if first few donors succeeds and then some not some would be in the database and some not.

We do not want that. We want the copy operation to be either completely successfull or not at all..

you can do that by creating helper function add_donor_recipient_pair_uncommitted what would not have commit in it and add db.commit here at the end

(and also use the add_donor_recipient_pair_uncommitted inside of add_donor_recipient_pair function

2022-06-21 19:57 UTC, krllstdn commented
Thank you for the review! 

I'm working on add_donor_recipient_pair_uncommitted.

2022-06-29 09:27 UTC, kubantjan requested changes
Seems ok, after you rebase and the tests run successfully we are ready to merge and finalize the task! 

Great job :).

2022-06-29 11:41 UTC, krllstdn commented
@kubantjan Thank you a lot!

I think I've done the rebase

2022-06-30 12:40 UTC, merged