User parsing issues instead of parsing errors everywhere
mild-blue/txmatching pull request #853
Opened 2022-05-24 10:02 UTC by kristinagalik

Closes #832

2022-05-24 15:56 UTC, kristinagalik commented
@kubantjan premenovavala som na parsing issues a nie results, lebo results znie ako ze tam su included aj OK_PROCESSING_RESULTS, ale afaik sa tam ukladaju len warningy a errory, cize mi pride lepsie to oznacit ako issues.

2022-05-31 06:21 UTC, kubantjan requested changes
Jedno misto ma mit parsing errors, jinak ok.

2022-05-31 06:21 UTC, kubantjan commented on txmatching/patients/patient.py
> +def _filter_patients_that_dont_have_parsing_issues(
tady prave ma zustat errors, jako jediny misto.

2022-06-02 11:04 UTC, kubantjan approved these changes

2022-06-02 11:11 UTC, merged