Set color and logo template in .env
mild-blue/txmatching pull request #854
Opened 2022-05-24 16:01 UTC by kristinagalik

Closes #845

2022-06-02 11:05 UTC, kubantjan requested changes

2022-06-02 11:05 UTC, kubantjan commented on .env.pub
> +COLOUR_SCHEME = DEVELOPMENT
color scheme bych dal Mild Blue a IKEM ne production a development :)

2022-06-03 05:21 UTC, kubantjan approved these changes

2022-06-03 05:22 UTC, kubantjan commented
@kristinagalik  jen pro jistotu, vyzkousela jsi to lokalne nastaveni tech ruznych themes? Na tohle nejdou napsat testy, tak abychom vedeli ze to dobre funguje :)
Az udelas/jestli jsi udelala, mergnul bych :)

2022-06-03 13:01 UTC, kristinagalik commented
> 

hej poskusala som aj v reportoch :)

2022-06-03 13:05 UTC, merged