Allow immunologist to confirm that a warning was checked and is ok
mild-blue/txmatching pull request #859
Opened 2022-06-02 13:07 UTC by kristinagalik

Closes #827

2022-06-04 13:14 UTC, kristinagalik commented on txmatching/database/services/patient_service.py
> +    parsing_issue.confirmed_at = datetime.now()
@kubantjan je toto v poriadku sposob updatovania instances of models?

2022-06-04 13:16 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_transformations/parsing_issue.py
> +# todo
@kubantjan a este tuto som sa chcela spytat ci je lepsie napisat tu funkciu co updatuje parsing issue a odkazat na nu v patient_service.py alebo je ok ju nechat iba tam?

2022-06-06 07:27 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +    parsing_issue.confirmed_at = datetime.now()
Ano, ivz https://www.tutorialspoint.com/sqlalchemy/sqlalchemy_orm_updating_objects.htm

akorat ty zmeny musi byut commitnuty. 

idealne vsechny commitnuti chceme delat v servisach.

2022-06-06 07:30 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +    parsing_issue.confirmed_at = datetime.now()
ale vzhledem k tomu, ze tady resis veci kolem parsing issue asi bych to nedelal v patient service ale udelal parsing issue service, at nam tohleto moc nebobtna

2022-06-06 07:30 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/parsing_issue.py
> +# todo
nerozumim presne otazce.

2022-06-06 07:35 UTC, kubantjan requested changes
Odpovedi na otazky, jedna extra otazka

2022-06-06 07:35 UTC, kubantjan commented on txmatching/utils/hla_system/hla_transformations/parsing_issue.py
> +# todo
kazdopadne idealne vsechny veci co pracuji s databazi primo by meli byt v nejake service. To ze tady mame ty fce co deletuji je vlastne spatne, ty taky patri do parsing issue service.

(idealni bude to tam vsechno presunout)

Zodpovedel jsem otazku?

2022-06-06 07:35 UTC, kubantjan commented on tests/web/public_api/test_public_patient_upload_data_validation.py
> +        self.assertEqual(2, len(txm_event.active_and_valid_recipients_dict))
proc se tyhle cisla meni? Tenhle task by s tim nemel souviset ne?

2022-06-06 11:25 UTC, kristinagalik commented on tests/web/public_api/test_public_patient_upload_data_validation.py
> +        self.assertEqual(2, len(txm_event.active_and_valid_recipients_dict))
v issue je odrazka:
* do not allow issues with issues without confirmation to go into matching run (before now it was that errors are not allowed to go into the matching run)

a ten test berie z file `test_public_patient_upload_valid_example_data.py`, kde jeden donor a jeden recipient maju warning parsing issue (line 10 - BW4 je irrelevant code, lines 69, 74 - tam je problem ze to droppuje jeden antibody)

2022-06-06 11:37 UTC, kubantjan commented on tests/web/public_api/test_public_patient_upload_data_validation.py
> +        self.assertEqual(2, len(txm_event.active_and_valid_recipients_dict))
ah jasne

hmm tak to musime dat bacha a tohle nemergnout do te doby, nez bude FE ready. Nebo zatim tady jeste tyto poustet i do matchovani a az udelame FE tak tuhle podminku teprve pridat.

Ten fe bude docela narocny ne? Asi bych radeji to udelal tak, ze tu podminku zatim vypustime. Co myslis?

2022-06-06 11:49 UTC, kristinagalik commented on tests/web/public_api/test_public_patient_upload_data_validation.py
> +        self.assertEqual(2, len(txm_event.active_and_valid_recipients_dict))
tak zatial ju mozem zakomentovat a dat tam dake TODO?

2022-06-06 11:57 UTC, kristinagalik commented on tests/web/public_api/test_public_patient_upload_data_validation.py
> +        self.assertEqual(2, len(txm_event.active_and_valid_recipients_dict))
davam tu funkciu celu prec, aj tak je to par riadkov, a urobila som novu issue  https://github.com/mild-blue/txmatching/issues/860

2022-06-08 12:55 UTC, kubantjan approved these changes

2022-06-08 13:59 UTC, merged