Send also parsing issue id and confirmation attributes to FE
mild-blue/txmatching pull request #870
Opened 2022-06-12 09:38 UTC by kristinagalik

Closes #865

2022-06-13 14:10 UTC, kubantjan submitted a review, later dismissed

2022-06-13 15:25 UTC, NotLubo requested changes

2022-06-13 15:25 UTC, NotLubo commented on txmatching/web/frontend/src/app/parsers/patient.parsers.ts
> +  });
Skôr než tu by som jednoducho pridal tento jeden riadok do componenty kde sa message vypisuje
`warning.hla_code_or_group + ": " + warning.message` a tým pádem nepotřebujeme tyhle 3 loops.

Príde mi to lepšie pretože si nechávame možnosť `hla code` nastylovať (možno by bolo přehlednejší dát ho boldem), zároveň možná v budoucnu budeme chtít nekdy ukazovat jenom `hla code` při kterém warning nastal? I když ne dveře jsou otevřené :)

2022-06-13 20:24 UTC, kristinagalik commented on txmatching/web/frontend/src/app/parsers/patient.parsers.ts
> +  });
hej, toto je len docasne, tym ze ta issue je rozdelena na 2 casti tak toto je len predpriprava. ale dalsia zmena co urobim bude vlastne aj tak vyzerat takto:
![image](https://user-images.githubusercontent.com/56656359/173438592-4692ad71-f198-47ee-80ca-fd68b718f530.png)
len som si nebola ista ci sa tie loopy nedaju napisat nejak kompaktnejsie alebo ci proste nieco nemissujem

2022-06-13 20:37 UTC, NotLubo commented on txmatching/web/frontend/src/app/parsers/patient.parsers.ts
> +  });
Jasné tak potom v pohode :) V premenných zmaž medzeru pred dvojbodkou a za mňa je to ok teda.

2022-06-13 20:37 UTC, NotLubo approved these changes

2022-06-14 04:47 UTC, NotLubo approved these changes

2022-06-14 07:16 UTC, merged