Better how transplant errors are shown in tranplant detail
mild-blue/txmatching pull request #876
Opened 2022-06-17 22:02 UTC by kristinagalik

Closes #873

2022-06-20 16:14 UTC, NotLubo requested changes
Za mňa super len pôvodný kód čo si upravovala je trochu zbytočne dlhý tak návrh na skrátenie. Plus v tom jednom súbore je trochu bordel na to asi spraviť issue.

2022-06-20 16:14 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/recipient-settings/recipient-settings.component.ts
> +    switch (inputValue.name) {
switch sa dá zjednodušiť na `this.recipient[inputValue.name] = formatNumberForPatient(inputValue, this.recipient);`

2022-06-20 16:14 UTC, NotLubo commented on txmatching/web/frontend/src/app/directives/validators/form.directive.ts
>  export function formatNumberForPatient(
v celom súbore by sa zišlo upratať
- funkcie na arrow
- nepoužívať null
- správne natypovať premenné namiesto any

to ale asi nechaj na iné issue. možno sem aspoň pridať TODO?

2022-06-20 16:14 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/recipient-settings/recipient-settings.component.ts
>      }
zmazať nepoužité ngOninit a jeho implementaci a import

2022-06-21 08:49 UTC, kubantjan approved these changes
Za me ok, takze jen poznamky od @NotLubo

2022-06-21 10:21 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/recipient-settings/recipient-settings.component.ts
> +    switch (inputValue.name) {
aha áno to je jednoduché v JS ale TS s tým mám celkom problém :D tak to nechaj tak ako je :)

2022-06-21 10:22 UTC, NotLubo approved these changes

2022-06-21 11:21 UTC, kubantjan requested changes

2022-06-21 11:21 UTC, kubantjan commented on txmatching/data_transfer_objects/patients/update_dtos/recipient_update_dto.py
> +        if self.year_of_birth and (self.year_of_birth < 1900 or self.year_of_birth > date.today().year):
no magic number, dej to do konstanty prosim :) idealne cele do funkce is_year_of_birth_valid

2022-06-21 11:23 UTC, kristinagalik commented on txmatching/data_transfer_objects/patients/update_dtos/recipient_update_dto.py
> +        if self.year_of_birth and (self.year_of_birth < 1900 or self.year_of_birth > date.today().year):
to nemam potom radsej urobit 4 funckie (aj na height, weight a pod) a budem len tie prevolavat v update/upload pacientoch?

2022-06-21 14:00 UTC, kubantjan commented on txmatching/data_transfer_objects/patients/update_dtos/recipient_update_dto.py
> +        if self.year_of_birth and (self.year_of_birth < 1900 or self.year_of_birth > date.today().year):
jop, to nebude spatne.

2022-06-26 19:20 UTC, kubantjan approved these changes
Za me ok

2022-06-26 21:14 UTC, merged