More match type logic
mild-blue/txmatching pull request #878
Opened 2022-06-27 18:07 UTC by kristinagalik

Closes #531

2022-06-29 11:35 UTC, kubantjan requested changes
Few comments, questions answered

2022-06-29 11:35 UTC, kubantjan commented on txmatching/database/services/matching_service.py
> +    # todo
what is this todo?

2022-06-29 11:35 UTC, kubantjan commented on txmatching/utils/transplantation_warning.py
> +    # todo: should I add warning messages also for missing antibodies and missing typization?
Yep that would be cool

2022-06-29 11:35 UTC, kubantjan commented on txmatching/utils/enums.py
>                  crossmatch_level == HLACrossmatchLevel.SPLIT_AND_BROAD and self == self.HIGH_RES
Here should be not only high_Res but also high res with split

2022-06-29 11:36 UTC, kristinagalik commented on txmatching/database/services/matching_service.py
> +    # todo
its a reminder for me, if i have to add custom warning messages

2022-07-04 13:52 UTC, kubantjan requested changes
vypada dobre, hodis sem jeste screenshot jak vypadaji matchingy, kde jsou tyhlety novy kategorie prosim?

2022-07-05 12:54 UTC, kristinagalik commented
UNDECIDABLE:
![image](https://user-images.githubusercontent.com/56656359/177289223-362ddb6b-3566-4306-9fd1-b63e9320ef5a.png)
![image](https://user-images.githubusercontent.com/56656359/177289292-ca8e6dbc-9971-42fa-b1a3-7a6c1ff5f9ad.png)
HIGH_RES_WITH_SPLIT:
not allowed anywhere
HIGH_RES_WITH_BROAD:
![image](https://user-images.githubusercontent.com/56656359/177326664-15af1409-7a58-4d85-bc70-e59b55add080.png)
ANTIBODIES_MISSING:
![image](https://user-images.githubusercontent.com/56656359/177323857-fc3fe2eb-a57d-4e01-939a-639460376a49.png)
![image](https://user-images.githubusercontent.com/56656359/177323890-7cc33a80-86fd-4467-a4d1-fc595a64ecc9.png)

2022-07-06 14:40 UTC, kubantjan commented
Groups can be recognized by the code in high res
A -> A
B -> B
CW -> C
DR -> DRB1
DP -> DPB
DQ -> DQB
DP -> DPB
DQA -> DQA
DPA -> DPA

DRB51, DRB52, DRB53 -> DRB_other

Ale vsechny skupiny krom A,B,DRB1 davat porad to other.

2022-07-07 10:44 UTC, kristinagalik commented
@kubantjan i think i solved "Use the group names (not just other) in found antibodies for group the donor has no typization for." in `matching_service.py`. is that what you meant?

2022-07-11 06:48 UTC, kubantjan requested changes

2022-07-11 07:00 UTC, kubantjan requested changes

2022-07-11 07:01 UTC, kubantjan commented
> @kubantjan i think i solved "2. Use the group names (not just other) in found antibodies for group the donor has no typization for." in `matching_service.py`. is that what you meant?
> 
> ![image](https://user-images.githubusercontent.com/56656359/177755779-17abd85d-ae61-4ded-abe8-a83ce9fb4467.png) ![image](https://user-images.githubusercontent.com/56656359/177755817-567c8b48-e36d-4ae9-9e22-966ae2bd756b.png)

yes, this is it

2022-07-11 07:41 UTC, kubantjan requested changes
Looks good overall,

2022-07-11 07:41 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +        if hla_per_group.hla_types == []:
This is not the way to test whether a list i empty. It is quite controversial topic overall. (sse https://stackoverflow.com/questions/53513/how-do-i-check-if-a-list-is-empty)

I personally prefer 

if len(list) == 0

other approach can be (which is according to official python style guide)

if not list

but surely not this.

2022-07-11 07:41 UTC, kubantjan commented on txmatching/database/services/matching_service.py
> +    undecidable_crossmatches = {_group_from_raw_code(possible_crossmatch.hla_antibody.raw_code) for possible_crossmatch
moreover, we have a duplicit logic here,_split_hla_types_to_groups does kind of the same thing as the stuff happening here, the logic as a whole should be in one place. But for that it will be better to do an issue (can be easily assinged to someone from the students) 

Please just move the function group_from_raw_code into the hlacode object and add todo to unify the logic and create a new issue for that.

2022-07-11 11:39 UTC, kristinagalik commented
okay, ill make new issue for the duplicity.. meanwhile for https://github.com/mild-blue/txmatching/pull/877#pullrequestreview-1013094154 the number 1 stopped being relevant with new changes in `is_positive_for_level` function, so i deleted that logic.

2022-07-11 12:23 UTC, kubantjan requested changes

2022-07-11 12:23 UTC, kubantjan commented on tests/solvers/ilp_solver/test_ilp_solver.py
> -    def test_solver_too_many_solutions(self):
This test was here just for the purpose of the raised exception at the end? Then the name was a bit confusing

I think we should have some test that tries to find solution and fails because of too low dynamic constraints bound

2022-07-12 10:12 UTC, kristinagalik commented on tests/solvers/ilp_solver/test_ilp_solver.py
> -    def test_solver_too_many_solutions(self):
added

2022-07-12 14:50 UTC, kubantjan submitted a review, later dismissed

2022-07-12 14:54 UTC, kubantjan approved these changes

2022-07-12 15:01 UTC, merged