Investiate the use of graphql library and possibility of its removal
mild-blue/txmatching pull request #885
Opened 2022-07-01 08:18 UTC by kristinagalik

Closes #884

2022-07-01 10:34 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/result.py
> +# this is not used anywhere, do I keep it for future possibilities or not
@kubantjan

2022-07-01 10:34 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/logging_utils.py
> +# this is not used anywhere too
@kubantjan

2022-07-01 10:42 UTC, kristinagalik commented
@kubantjan 

* deleted AllSolutionSolver
* things that were used in both solvers were moved from AllSolutionSolver to ILPSolver
* functions and classes from ILPSolver arent used anywhere else in the code (apart from sensible ones, `solver_base` and `solver_from_config`)
* only essential things are imported from the rest of the code into the `ilp_solver` files, and thats too only into `txm_configuration_for_ilp` and `solve_ilp`
* there are 2 classes that arent used anywhere, should i delete them or do they seem like we could use them in the future?

2022-07-04 13:48 UTC, kubantjan requested changes
1) Klidne odeber i ty nepouzity knihovny.
2) myslim si, ze takto to odebrat tu zavislost nestaci, ze je jeste potreba ji dat pryc z conda.yml -> to je to dulezity misto, kde se vyskytuji dependencies.
3) to bude asi chtit pak updatnout base image (neco je v readme, pokud si nebudes vedet rady, rekni si)
4) to by melo zajistit, ze uz to beha jak  na windows a M1 -> updatnout readme (zkontrolvoat, jestli jeste nejaky dalsi updates nejsou potreba)

2022-07-06 10:16 UTC, kristinagalik commented
@kubantjan 
skusala som to rozbehat na windowse a aj tak treba wsl2 kvoli gunicornu

2022-07-06 11:22 UTC, kubantjan commented
> @kubantjan skusala som to rozbehat na windowse a aj tak treba wsl2 kvoli gunicornu

Lets keep english everywhere :). I forget sometimes as well but we have to remind each other 

Ok but gunicorn is used just in production setup, when runnning locally we are running flask only. So this should not be a problem. The only issue is that we have gunicorn in even in the conda.yml that is meant for local run.

could you try to remove gunicorn from conda yml and run it locally?

if it does not help, we wont deal with it further but if it did it would be cool.

2022-07-06 12:52 UTC, kubantjan commented
I will have couple more comments in the end, but lets do it via a call, I have sent you a message

2022-07-06 15:27 UTC, kubantjan commented
1) check with @NotLubo  whether it works for him with graph tool only in docker or no
2) check whether graph tool is the best thing we can use (from this https://graph-tool.skewed.de/performance it seems that it is, but it is quite old)
3) do not delete the solver in the end, but maybe use some refactoring if it was reasonable
4) study the handbook of kepsoft and understand the inputs and outputs of the solver that is used there
5) select an option from the two below, depending on which one would be easier
a) create an issue to replace topology.max_cliques(path_intersections_graph) with ILP
b) create an issue that woud replace   topology.max_cliques(path_intersections_graph) with kepsoft optimizer

2022-07-11 08:21 UTC, closed without merging