#879 authentic added to docker composer
mild-blue/txmatching pull request #887
Opened 2022-07-04 21:14 UTC by NotLubo

2022-07-11 08:24 UTC, kubantjan requested changes

2022-07-11 08:24 UTC, kubantjan commented on README.md
> +7. Input TXM as name
where is this TXM taken from? Is it somewhere in code as well?

2022-07-11 08:24 UTC, kubantjan commented on README.md
> +8. Client ID: `f5c6b6a72ff4f7bbdde383a26bdac192b2200707`
Where is client id a nd secret taken from? from .env? Then I would not write the exact ids and secrets here, but say to take them from .env

2022-07-11 08:24 UTC, kubantjan commented on README.md
> +13. Set name as TXM and slug as txm
where is this TXM and txm taken from? Is it somewhere in code as well?

2022-07-11 08:24 UTC, kubantjan commented on README.md
> +14. From providers select TXM
Where are this providers taken from?

2022-07-11 09:11 UTC, NotLubo commented on README.md
> +7. Input TXM as name
Its just label used in authentic you could put anything there

2022-07-11 09:11 UTC, kubantjan requested changes

2022-07-11 09:11 UTC, kubantjan commented on txmatching/web/api/user_api.py
> +        # todo redirect to homepage instead of showing access token after testing is finished
add link to an issue

2022-07-11 09:13 UTC, NotLubo commented on README.md
> +8. Client ID: `f5c6b6a72ff4f7bbdde383a26bdac192b2200707`
Yes its from env. Corrected

2022-07-11 09:19 UTC, NotLubo commented on README.md
> +14. From providers select TXM
You create provider in steps 4 -> 10. I added subheadings to make it more clear

2022-07-11 09:24 UTC, NotLubo commented on txmatching/web/api/user_api.py
> +        # todo redirect to homepage instead of showing access token after testing is finished
Done

2022-07-11 10:21 UTC, NotLubo commented on README.md
> +7. Input TXM as name
Done

2022-07-11 14:17 UTC, kristinagalik commented
@NotLubo 

potom pre info: 
```
    ports:
      - "9000:9000"
      - "9443:9443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

toto mi tiez neslo:
![image](https://user-images.githubusercontent.com/56656359/178285597-17464561-4ffc-48f4-b9b2-2dd475b648d2.png)

2022-07-12 10:03 UTC, kubantjan requested changes

2022-07-12 10:10 UTC, kubantjan requested changes
you are missing depends_on in the docker-compose services. Use that. to clarify which service is needed for which other service

2022-07-12 10:10 UTC, kubantjan commented on README.md
> +After you run `make docker-build` you must setup Authentik. You will do this only once.
there is no need for docker-build you need only docker-compose up! and make docker-build does not even do that it just build txmatch image that is not related at all

2022-07-12 10:10 UTC, kubantjan commented on docker-compose.yml
> +  postgresql:
authentik-db or some clear name like that

2022-07-12 10:10 UTC, kubantjan commented on docker-compose.yml
> +  redis:
authentik-redis?

2022-07-12 10:10 UTC, kubantjan commented on docker-compose.yml
> +  server:
authentik-server?

2022-07-12 10:10 UTC, kubantjan commented on docker-compose.yml
> +  worker:
authentik-worker?

2022-07-12 10:19 UTC, kubantjan requested changes

2022-07-12 10:19 UTC, kubantjan commented on docker-compose.yml
> +    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.4.1}
k cemu je tady ten AUTHENTIK_IMAGE env?  to asi k nicemu nikdy neni ne?

2022-07-12 10:19 UTC, kubantjan commented on docker-compose.yml
> +    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.4.1}
Klidne bych tady smazal i ten ENV AUTHENTIK_TAG

2022-07-12 11:02 UTC, NotLubo commented on docker-compose.yml
> +    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.4.1}
Myslel jsem si, že pak držíš verzi authentiku v env ale mohu zmazat

2022-07-12 11:04 UTC, NotLubo commented on docker-compose.yml
> +    # This is optional, and can be removed. If you remove this, the following will happen
I think the comment belongs to something that is already removed. I asked Honza.

2022-07-12 11:14 UTC, NotLubo commented on docker-compose.yml
> +    # This is optional, and can be removed. If you remove this, the following will happen
the comment is meant for `user: root`. I've corrected it

2022-07-12 14:38 UTC, kubantjan commented on docker-compose.yml
> +    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.4.1}
Asi bych to smazal v dohledné době to nepoužijeme přes ten env

2022-07-12 14:38 UTC, NotLubo commented on docker-compose.yml
> +    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.4.1}
Je to zmazane

2022-07-12 14:45 UTC, kubantjan approved these changes

2022-07-12 14:45 UTC, merged