Fix #886 issue
mild-blue/txmatching pull request #904
Opened 2022-07-08 15:08 UTC by jogobeny

2022-07-10 18:51 UTC, kristinagalik commented
hi @jogobeny :)

there was a small typo that i overlooked when editing the issue description - it should have been "in case we delete the only donor of a recipient, delete also the recipient, otherwise delete only the **donor**". i apologize.

2022-07-14 20:33 UTC, kristinagalik requested changes
just a small comment, and also please add/fix tests and rebase :)

2022-07-14 20:33 UTC, kristinagalik commented on txmatching/database/services/patient_service.py
>      donor, maybe_recipient = get_donor_recipient_pair(donor_id, txm_event_id)
here is an unused variable `donor`, either i would access the id of the donor through this variable, or get only the `maybe_recipient` object from the function :)

2022-07-15 13:19 UTC, kristinagalik reviewed
well done, the code is fine by me :) @kubantjan could you please review the changes too :)?

2022-07-21 10:02 UTC, kubantjan approved these changes

2022-07-25 07:10 UTC, kristinagalik approved these changes

2022-07-25 07:10 UTC, merged