Issue#748 fixed:in binary mode only binary scores are shown
mild-blue/txmatching pull request #905
Opened 2022-07-08 16:56 UTC by rimmakam

Closes #748

2022-07-11 12:00 UTC, kristinagalik requested changes
hi @rimmakam :)

just a few things: 
1. what happens if you set the manual score of a pair to a negative value?
2. you could rather create a function that will be called on line 31 (for instance from the same place as `score_transplant_calculated` so you wouldn't need to deal with `ConfigParameters` in the `additive_scorer.py` file) 
3. please also add/fix tests so we can be sure it works :)

2022-07-11 18:18 UTC, rimmakam commented
> hi @rimmakam :)
> 
> just a few things:
> 
> 1. what happens if you set the manual score of a pair to a negative value?
> 2. you could rather create a function that will be called on line 31 (for instance from the same place as `score_transplant_calculated` so you wouldn't need to deal with `ConfigParameters` in the `additive_scorer.py` file)
> 3. please also add/fix tests so we can be sure it works :)

Hello, @kristinagalik :)

I wanted to ensure if I understand that correctly: if a negative manual score is set for some pair, should that pair be excluded from the results or should it be kept but with binary score "-1" or "0"?

And also I wanted to ask if there are already some tests for the situation when we have manual scores with binary mode chosen (I haven't found it yet).

Thank you!

2022-07-11 19:36 UTC, kristinagalik commented
@rimmakam 

if a negative value is set (or is negative by default) it means that a pair is not compatible. so by setting a negative manual value, you are forcing the pair to be incompatible (regardless of their initial level of compatibility), so it shouldn't display such a pair in the matchings.

so it essentially doesn't matter whether for incompatible manual scores you return a custom negative value or the inital or the set manual negative value, but for consistency i suggest -1 or something for everything negative in binary scoring? 

for this and maybe also for compatible pairs in binary scoring i would also suggest making new constants in scorer_constants.py. so 2 constants in total - negative and positive in binary matchings.

and for tests: i can't seem to find any, could you please add some tests :)?

2022-07-15 15:07 UTC, kubantjan requested changes
Waiting for the review be finished by kristina, then please rerequest my review :)

2022-07-17 14:45 UTC, rimmakam commented
Hello, @kristinagalik,

I'm working on tests right now, but I'm a little bit lost - should I write them in test_hla_scorer or somewhere else? 

Thank you :)

2022-07-18 09:16 UTC, kristinagalik commented
@rimmakam hmm maybe its better to write them in `test_configuration.py` :)

2022-07-23 09:31 UTC, rimmakam commented
Hi, @kristinagalik. 

I would like to ask why the configuration parameters should be tested. It seemed to me that I should test whether the scoring works correctly given binary mode(on/off). For example when the manual score is negative and the binary mode is on, I would test if it results in overall score == "-1". Or I would test whether the score == "1" for a positive manual score given binary mode.

Thank you :)

2022-07-25 11:25 UTC, kristinagalik commented
@rimmakam

so you could do it for instance in `test_ilp_solver.py`, that would be the best probably.

2022-07-27 19:21 UTC, rimmakam commented
Hello, @kristinagalik,

I've written some tests, could you please take a look? :)

2022-07-27 21:29 UTC, kristinagalik requested changes
looks good, just some very small comments from me :) also please rebase. 

^ after this im approving :)

2022-07-27 21:29 UTC, kristinagalik commented on txmatching/scorers/hla_additive_scorer.py
> +            elif manual_score < 0:
maybe here is sufficient only `else`

2022-07-27 21:29 UTC, kristinagalik commented on tests/solvers/ilp_solver/test_ilp_solver.py
> +
redundant blank spaces between tests (functions in tests are for some reason only surrounded by 1 blank space)

2022-07-27 21:29 UTC, kristinagalik commented on tests/solvers/ilp_solver/test_ilp_solver.py
> +
also if you dont use a formatter, it would be good to use one :)

2022-07-28 14:11 UTC, rimmakam commented
Hello, @kristinagalik,

changes have been added. I also wanted to ensure if I should rebase to master branch.

2022-07-29 08:37 UTC, kristinagalik requested changes
hi @rimmakam, yes, please rebase to master. 

also sorry, one last change request. 

@kubantjan after this one change and rebase the code is fine by me, ready for your review :)

2022-07-29 08:37 UTC, kristinagalik commented on txmatching/scorers/hla_additive_scorer.py
> +    NEGATIVE_SCORE_BINARY_MODE
sorry overlooked this, but imports should be alphabetically ordered, so is thould be `... import NEGATIVE_SCORE_BINARY_MODE, POSITIVE_SCORE_BINARY_MODE, TRANSPLANT_IMPOSSIBLE_SCORE`

2022-07-29 12:06 UTC, kristinagalik approved these changes
@kubantjan za mna zmeny fajn :)

2022-07-29 12:32 UTC, kubantjan commented
@kristinagalik use rerequest please :)

2022-07-29 12:34 UTC, kubantjan submitted a review, later dismissed

2022-07-31 17:18 UTC, rimmakam commented
Hello, @kristinagalik,

I'm facing some problems with rebase. I've never done it before and I'm not sure about how to do it correctly. I've tried just "git rebase master" and few other things, but it seems that nothing has changed. Could you please have a look if you see some changes? I would also appreciate any advice.

Thank you :)

2022-08-01 09:43 UTC, kristinagalik commented
@rimmakam 
hmm after you did `git rebase master` did you also push? if yes, what IDE do you use? if you struggle further, maybe we can have a quick call?

2022-08-01 19:57 UTC, rimmakam commented
Hello, @kristinagalik,

I didn't push, because I wasn't sure that I did the rebase correctly. I'm using PyCharm. I've tried to do it according to the official documentation, but unfortunately I'm still stuck, so if you had time to have a look, it would be great.

2022-08-02 08:38 UTC, kristinagalik commented
Okay so there are multiple ways to do a rebase, 2 of those are: 
1. when you do a rebase through a console (on your branch just write `git rebase master`) you see stuff like 
```
First, rewinding head to replay your work on top of it...
Applying: Issue#748 fixed:in binary mode only binary scores are shown
Applying: Added function that deals with manual scores depending on whether the binary mode is set
Applying: Issue#748: tests added
Applying: Issue#748: last changes added
Applying: Issue#748: imports fixed
``` 
(If you didnt see anything like that, make sure to do to master branch, `git pull` and then checkout to your branch again and rebase.)
If you dont see any warnings, conflicts or anything, you can just do `git push -f` and the branch is rebased also remotely. 

2. when you are using pycharm, you can go to the master branch, at the bottom of the IDE go to "Git" 
![image](https://user-images.githubusercontent.com/56656359/182329484-8eee5ed4-6ed7-485f-8008-1a04c411757c.png)
and then right-click your branch, and pick the option to "checkout and rebase onto master". If you see no warnings and there was a pop up at the right bottom side of the screen saying something like "checked out and rebased onto master" you are good to `git push -f`

if you arent sure if you did the right thing and you are stuck between steps "rebase" and "push" just rebase again and it will tell you whether its up to date - if it is, you should be good to push.

if you worry that you did something along the way, i would just delete the branch, then create new one from the remote (`git switch Iss...`) and rebase again, but i dont think this should be needed

2022-08-02 09:42 UTC, rimmakam commented
@kristinagalik, 

so I tried to do it by deleting the branch and creating new one, because nothing else worked, but I'm sure I did it the wrong way. I'm sorry :(

2022-08-02 09:44 UTC, kristinagalik commented
oh sorry, it was meant to be deleted only locally, and then again restored from the remote. no worries,

2022-08-02 11:02 UTC, rimmakam commented
Thank you very much, I hope it will be easier next time :) So we can leave it as it is?

2022-08-09 14:41 UTC, kubantjan approved these changes

2022-08-09 14:41 UTC, merged