do not allow patients with warning issues without confirmation to go into matching run (before now it was that errors are not allowed to go into the matching run)
mild-blue/txmatching pull request #909
Opened 2022-07-11 10:21 UTC by krllstdn

Closes #860

2022-07-11 13:14 UTC, kristinagalik requested changes

2022-07-11 13:14 UTC, kristinagalik commented on tests/web/test_patient_api.py
>              # TODO https://github.com/mild-blue/txmatching/issues/860
this can be deleted

2022-07-11 13:14 UTC, kristinagalik commented on txmatching/database/services/pairing_result_service.py
> +    return solve_from_configuration_and_save(configuration, txm_event)
this shouldnt be commented out, its just a tip for if you quickly need to recompute matchings every time you open matchings page :)

2022-07-11 13:14 UTC, kristinagalik commented on txmatching/patients/patient.py
> +# from txmatching.database.sql_alchemy_schema import ParsingIssueModel
if you comment something out it can be deleted

2022-07-11 13:14 UTC, kristinagalik commented on txmatching/patients/patient.py
> +def _filter_patients_that_dont_have_parsing_errors_or_they_are_confirmed(
here pay attention to the difference between WARNING_PROCESSING_RESULTS and ERROR_PROCESSING_RESULTS. because what you wrote is basically asking whether the errors are confirmed or not

2022-07-11 13:43 UTC, kristinagalik requested changes

2022-07-11 13:43 UTC, kristinagalik commented on txmatching/patients/patient.py
> +def _filter_patients_that_dont_have_parsing_errors_and_have_confirmed_warnings(
sorry, here i meant not only the name of the function, but also the body.

there are 3 types of severities: info, warning and error.

right now, what your code is doing, is asking: are there any errors for this patient? and if yes, it checks whether they are approved.

but this is not correct, patients with errors should never go into matching run. what you wan to ask is - does this patient have any unconfirmed warnings? if yes, dont include him in active_and_valid_patients_dict.

2022-07-12 12:26 UTC, kristinagalik requested changes

2022-07-12 12:26 UTC, kristinagalik commented on tests/web/test_patient_api.py
> +            self.assertFalse(recipient_db_id in txm_event.active_and_valid_recipients_dict)
this is great, you check that without confirmed warning the patient is not in the dictionary, but it would be also great to check after the confirmation of the warning the patient is in the active and valid patients dict :) please add that assert after the warning confirmation endpoint call

2022-07-12 12:26 UTC, kristinagalik commented on txmatching/patients/patient.py
> +    return False
i would suggest rather making function `_parsing_issue_list_contains_unconfirmed_warnings` so you dont have to basically check the list twice, and its not the most correct approach on lines 207-210 and 219-224, because if you would have some **info** parsing issues, they should not affect the patient going into matching run regardless of whether they are confirmed, but since you iterate through all the parsing issues (which might include **infos**) it might block the patient from being included in the run

2022-07-12 14:00 UTC, kristinagalik requested changes

2022-07-13 09:22 UTC, kristinagalik requested changes
good job, just a few styling requests from me, otherwise looks great :)! 

also please rebase :)

2022-07-13 09:22 UTC, kristinagalik commented on tests/web/test_patient_api.py
> +            self.assertEqual(None, error_issue.confirmed_by)
here is a redundant white space

2022-07-13 09:22 UTC, kristinagalik commented on tests/web/test_patient_api.py
> +    def  test_confirming_error_issue(self):
here are two spaces after `def`, should be one

2022-07-13 09:22 UTC, kristinagalik commented on tests/web/test_patient_api.py
> +
this is redundant

2022-07-13 09:22 UTC, kristinagalik commented on txmatching/patients/patient.py
> +        if (_parsing_issue_list_contains_errors(patient.parsing_issues) or
here and on line 203 there is a trailing whitespace at the end of the line

2022-07-13 09:36 UTC, kristinagalik commented on txmatching/patients/patient.py
> +def _filter_patients_that_dont_have_parsing_errors_or_have_confirmed_warnings(
`_filter_patients_that_dont_have_parsing_errors_and_have_confirmed_warnings`

or

`_filter_patients_that_dont_have_parsing_errors_or_unconfirmed_warnings`

2022-07-13 11:51 UTC, kristinagalik commented on txmatching/web/error_handler.py
changes to this file probably shouldnt be here

2022-07-13 12:00 UTC, krllstdn commented on txmatching/web/error_handler.py
yes, they shouldn't. I committed them by mistake and couldn't delete that commit

2022-07-13 12:39 UTC, kristinagalik commented
@kubantjan za mna fajn :)

2022-07-15 07:35 UTC, kubantjan approved these changes
Super, @krllstdn  merguj a @kristinagalik  diky za super poctivy review :)

2022-07-15 14:15 UTC, merged