Cleanup parsing issue objects
mild-blue/txmatching pull request #916
Opened 2022-07-14 14:47 UTC by krllstdn

Closes #621

2022-07-14 15:26 UTC, kristinagalik requested changes

2022-07-14 15:26 UTC, kristinagalik commented on txmatching/database/db_migrations/0033.make-txm-event-id-required-in-parsing-issue.sql
> +ALTER TABLE parsing_issue ALTER column txm_event_id SET NOT NULL;
newline and comments at the beginning of the file are missing - please check other sql files.. 

@kubantjan i dont suppose there are any parsing_issues without a txm_event_id value, but just to be precautious, shouldnt we set a default value here to overcome any problems? (more precisely i am asking - which value)

2022-07-14 21:20 UTC, kristinagalik requested changes

2022-07-14 21:20 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
> +    confirmed_at: Optional[datetime] = None
i dont think these attributes should actually be here ("This is not good, split it in two objects, one with all fields required, other with just the fields that are required now, that will be used as the temporary object."), and also there should be another another problem - that you arent creating actual ParsingIssues from these temp objects that will go into database (for reference check `parsing_issues_to_models` and where it is used for better understanding) pls also try to check for other such instances

2022-07-14 21:20 UTC, kristinagalik commented on txmatching/database/sql_alchemy_schema.py
>      updated_at = Column(
also here - pls also check which attributes are required, because its not only txm_event_id

2022-07-14 21:23 UTC, kristinagalik commented on txmatching/database/db_migrations/0033.make-txm-event-id-required-in-parsing-issue.sql
> +ALTER TABLE parsing_issue ALTER column txm_event_id SET NOT NULL;
maybe there can be smth like `clean` django function that says "have at least one of these attributes set"?

2022-07-15 07:28 UTC, kubantjan commented on txmatching/database/db_migrations/0033.make-txm-event-id-required-in-parsing-issue.sql
> +ALTER TABLE parsing_issue ALTER column txm_event_id SET NOT NULL;
So there is couple of things:
1) Check please the stg and demo servers but I think there should be no parsing issues without txm event. I will check production after that. I would not put any default and rather let the migration fail
2) yes not all should be required .and this is the case now, donor_id and recipient id are not required. Quick search found smth like that: https://stackoverflow.com/questions/5447880/adding-an-one-out-of-two-not-null-constraint-in-postgresql we can add this condition

2022-07-15 11:59 UTC, kristinagalik commented on txmatching/database/db_migrations/0033.make-txm-event-id-required-in-parsing-issue.sql
> +ALTER TABLE parsing_issue ALTER column txm_event_id SET NOT NULL;
staging and demo checked, should have no parsing issues with txm_event_id null @kubantjan

2022-07-15 15:08 UTC, kubantjan requested changes
Waiting for the review to be approved by kristina, then please re request my reviwe

2022-07-16 14:22 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
>      hla_code_or_group: Optional[str]
@kubantjan tento field by mohol byt tiez required kedze vzdy sa tie DTOs robia z parsing issues, co by znamenalo ze vsetky parsing issue dataclasses zdielaju 3 identicke fields a mozno by sa mohol urobit daky base class (napr z toho tempu?)

2022-07-16 14:22 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
>      hla_code_or_group: Optional[str]
plus `ParsingIssueConfirmationDTO` by mohlo mat vsetky fields required kedze je to nieco co sa vzdy robi z `ParsingIssue`, no to by znamenalo ze `ParsingIssue` a `ParsingIssueConfirmationDTO` by mohli byt rovno ta ista classa a tym padom by boli len 3 classy a nie 4 :)

2022-07-16 14:22 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
>      hla_code_or_group: Optional[str]
(asi zatial @krllstdn nejdem davat plne review kym sa toto neporiesi lebo by to znamenalo viac zmien)

2022-07-18 07:53 UTC, kubantjan commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
>      hla_code_or_group: Optional[str]
@kristinagalik  it sounds it makes sense, just to be sure to summarize what can be in hla_code_or_group:

- in case there is some nonsense code it contains the raw string
- in case the issue relates to some whole group it contains the name of the group
- in case there is some meaningful code that has some weirdness it contains the raw string of the code

nothing else can happen? There is always raw string of the code or name of the group.

if this is the case I aggree.

2022-07-18 09:27 UTC, kristinagalik requested changes
* there should be a base class (like the ParsingIssueTemp) from which other classes just inherit and add other fields
* unify ParsingIssueConfirmationDTO and ParsingIssue into one class

2022-07-25 14:27 UTC, kristinagalik requested changes

2022-07-25 14:27 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_swagger.py
>  })
maybe also solve the TODO on line 9 :)? and make it consistent with the dataclass

2022-07-25 14:27 UTC, kristinagalik commented on txmatching/database/services/patient_upload_service.py
> +        parsing_issues_temp=parsing_issues,
missing argument

2022-07-25 14:27 UTC, kristinagalik commented on txmatching/database/services/patient_upload_service.py
> +        parsing_issues_temp=parsing_issues,
missing argument

2022-07-25 14:27 UTC, kristinagalik commented on txmatching/data_transfer_objects/patients/utils.py
> +def parsing_issue_model_to_parsing_issue(parsing_issue: ParsingIssueModel,
`parsing_issue_model_to_parsing_issue` and `convert_parsing_issue_models_to_dataclasses` duplicate logic

2022-07-25 14:27 UTC, kristinagalik commented on txmatching/database/services/parsing_issue_service.py
> +
use list comprehension

2022-07-25 14:27 UTC, kristinagalik commented on txmatching/database/services/parsing_issue_service.py
> +def get_parsing_issues_for_patients(txm_event_id: int, donor_ids: List[int] = None,
this function can be deleted, there already is one right above it

2022-07-27 15:19 UTC, kubantjan requested changes
after kristina approves, let me know

2022-07-27 21:13 UTC, kristinagalik requested changes

2022-07-27 21:13 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_swagger.py
>      'parsing_issue_detail': fields.String(required=True),
maybe overthinking (should work like this too) but parsing_issue_detail should be enum no?

2022-07-27 21:13 UTC, kristinagalik commented on txmatching/database/services/parsing_issue_service.py
> +    parsing_issue_models = []
this doesnt have to be here if you declare it anyway later :)

2022-07-29 18:48 UTC, kristinagalik requested changes
sorry i also forgot to mention - it probably happened during a rebase, but the commit history in this pr doesnt seem correct.

also `memory.sqlite` file is here too

2022-07-29 18:48 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_dto.py
>  # It is reasonable to have many attributes here
these comments shouldnt be relevant - if they are, please correct me

2022-08-01 13:41 UTC, krllstdn commented
Because of the mess in commits caused by bad rebase this PR is closed and the solution to the issue is in #953

2022-08-01 13:41 UTC, closed without merging