Different warning flag if all warnings confirmed
mild-blue/txmatching pull request #927
Opened 2022-07-18 14:21 UTC by kristinagalik

Closes #923

2022-07-19 12:19 UTC, kubantjan requested changes
One general point. I really thing we need to have something that would distinguish the patients that are included in the matching, Something that on the first glance shows which patients are included and which not. 
I would do two things:
1) In the list of patients sent to FE first send the patients that are included and then the ones that are not (including the inactive patients). 
2) As we have the inactive label than have similar label in case the patient is not inactive but is not included (in this current case it is patients with errors and patients with unconfirmed warnings) The lable could be simply  something like "excluded"

The confirmed/unconfirmed warning distinction is ok, but maybe i would prefer something more clear (making the confirmed warnings less threatening - maybe green even? as they are not of concern at all)

I would skip senindg patient_has_Confirmed_warnings to FE you could simply check there if all warnings are confirmed or not..

2022-07-20 08:32 UTC, kubantjan approved these changes
za me ok, jeste @NotLubo

2022-07-20 09:01 UTC, NotLubo requested changes
Komentáře

2022-07-20 09:01 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/patient-pair-item/patient-pair-item.component.ts
> +    if (patientHasConfirmedWarnings(this.item?.d?.allMessages) && patientHasConfirmedWarnings(this.item?.r?.allMessages)){
if není potřeba
` this.allWarningsConfirmed = patientHasConfirmedWarnings(this.item?.d?.allMessages) && patientHasConfirmedWarnings(this.item?.r?.allMessages);`

2022-07-20 09:40 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/patient-pair-item/patient-pair-item.component.ts
> +
2 prázdne řádky. jeden odstranit

2022-07-20 09:50 UTC, NotLubo requested changes
Formátování. Zišlo by se do projektu přidat prettier

2022-07-20 09:50 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/patient-pair-item/patient-pair-item.component.ts
> +
2 prázdne řádky jeden odstranit

2022-07-20 09:50 UTC, NotLubo commented on txmatching/web/frontend/src/app/parsers/parsingIssueConfirmation.parsers.ts
> +    txmEventId: data.txm_event_id,
ESLint hlási trailing comma

2022-07-20 09:58 UTC, NotLubo approved these changes
Super za mňa ok :)

2022-07-20 10:58 UTC, merged