Try to get all the different types of crossmatches in the app
mild-blue/txmatching pull request #939
Opened 2022-07-21 08:10 UTC by krllstdn

Closes #921

2022-07-21 09:55 UTC, krllstdn commented
I'm not sure about README.md - who is the target audience? So probably further changes will be needed.
@kubantjan

2022-07-22 08:57 UTC, kubantjan requested changes

2022-07-22 08:57 UTC, kubantjan commented on README.md
> +1. Donor doesn't have any typization for a group.
This is not true it is something like:
1. Recipient has antibody against and antigen from a group that donor is not typized for.

2022-07-22 08:57 UTC, kubantjan commented on local_testing_utilities/generate_patients.py
> +                      crossmatch: bool = False) -> List[PatientUploadDTOIn]:
The name crossmatch is wrong. It should be more like "randomly assign high or split resolution to country"

2022-07-22 08:57 UTC, kubantjan commented on local_testing_utilities/generate_patients.py
> +    CROSSMATCH = True
This setup will generate just one country that has either low of high res typization. I thing better would be to generate here one country with high and one with split for example

2022-07-25 11:11 UTC, kristinagalik requested changes
so just an update from me:
cant populate database with the generated file 
```
dacite.exceptions.WrongTypeError: wrong value type for field "donors.hla_typing" - should be "typing.List[str]" instead of value "[['A*26:01'], ['A*23:18'], ['B*44:04'], ['B*44:09'], ['DRB1*15:02'], ['DRB1*03:06'], ['DPA1*03:03'], ['DPA1*01:24'], ['DPB1*962:01'], ['DPB1*190:01'], ['DQA1*03:16'], ['DQA1*05:03'], ['DQB1*03:10'], ['DQB1*04:02']]" of type "list"
```

2022-07-27 10:43 UTC, krllstdn commented
Patient generation with crossmatches in the separate event works, but for some reason, high res patients that were generated previously are not added to the main event `high_res_example_data`. I have no idea why.
@kubantjan @kristinagalik Could you please take a look?

2022-07-28 08:52 UTC, kristinagalik requested changes

2022-07-28 08:52 UTC, kristinagalik commented on local_testing_utilities/generate_patients.py
> +            [generate_patient(country, i, has_hla_letter_at_the_end, high_res)
reminder true false

2022-07-28 16:02 UTC, krllstdn commented on local_testing_utilities/generate_patients.py
> +            [generate_patient(country, i, has_hla_letter_at_the_end, high_res)
@kristinagalik sorry, but I don't understand what you mean) could you be more specific?

2022-07-29 08:01 UTC, kristinagalik commented on local_testing_utilities/generate_patients.py
> +            [generate_patient(country, i, has_hla_letter_at_the_end, high_res)
oh sorry i rewrote the message but maybe i forgot to update the comment... i mean, till now, there were both options for `has_hla_letter_at_the_end` covered - `generate_patients` was called with both values, true and false, but now, you dont really pass that value, just at some point (`generate_patients_for_one_country`) you set it to a default value "false", so now you will never reach functions like `get_sample_of_codes_with_letter` if you dont make further changes to the code. and i just wanted to ask if this was intended?

2022-07-29 09:26 UTC, krllstdn commented on local_testing_utilities/generate_patients.py
> +            [generate_patient(country, i, has_hla_letter_at_the_end, high_res)
yeah, you're right, I didn't intend to do that. thx

2022-07-29 10:11 UTC, kubantjan reviewed
still waiting for update, then rerequest me please

2022-08-01 19:13 UTC, kristinagalik requested changes
just some small comments :)

2022-08-01 19:13 UTC, kristinagalik commented on README.md
> +2. Recipient has an antigene of level high res (of the same broad as in 1.)
also just realised this but isnt it antigen instead of antigene?

2022-08-01 19:13 UTC, kristinagalik commented on README.md
> +There are three types of crossmatches: Undecidable, High Res. With Split, High Res. With Broad.
pls check in with @kubantjan if this is a sufficient description, but crossmatch isnt just a warning that happens because of *different* resolution levels (it can happen also on the same level) so idk if this is good enough

2022-08-02 05:39 UTC, kubantjan commented on README.md
> +There are three types of crossmatches: Undecidable, High Res. With Split, High Res. With Broad.
Yep it's not just a warning so I would rewrite this. If you are not sure how ask us

2022-08-05 08:02 UTC, kubantjan requested changes

2022-08-05 08:02 UTC, kubantjan commented on README.md
> +Antigens have three levels of resolution: broad, split, and high res. Crossmatch is a warning or an error that happens because of different resolution levels of the same antigen in patients (or no an
I would not use warning and error. 

I would write something like
Crossmatch happens because of match of antibody of a recipient and antigen of a donor. (We consider also one special type of crossmatch (undecidable) that is explained later and works differently)

2022-08-05 08:02 UTC, kubantjan commented on README.md
> +Antigens have three levels of resolution: broad, split, and high res. Crossmatch is a warning or an error that happens because of different resolution levels of the same antigen in patients (or no an
According to seriousness of a crossmatch either the transplant between donor and recipient is forbiden, or the transplant is allowed but a warning is shown.

2022-08-05 08:02 UTC, kubantjan commented on README.md
> +There are three types of crossmatches: Undecidable, High Res. With Split, High Res. With Broad.
there are also high_res, split and broad crossmatches.

2022-08-08 10:32 UTC, kubantjan requested changes

2022-08-08 10:32 UTC, kubantjan commented on README.md
> +2. Recipient has an antigen of level high res (the same split as in 1.)
has an ANTIBODY

+ at least one antibody positive and one negative

2022-08-08 10:32 UTC, kubantjan commented on README.md
> +2. Recipient has an antigen of level high res (of the same broad as in 1.)
has an ANTIBODY

at least one antibody positive and one negative

2022-08-08 11:43 UTC, krllstdn commented on README.md
> +2. Recipient has an antigen of level high res (of the same broad as in 1.)
@kubantjan I'm not sure if I understand it correctly. A positive antibody is an antibody that responds to a donor's antigen, and a negative is the one that does not. Is that correct?

2022-08-08 14:28 UTC, krllstdn commented
The readme was updated with respect to Knowledge base which was not yet added to master branch. So further rebase will be needed with probable link correction.

2022-08-10 06:42 UTC, merged