929 add soft cutoff
mild-blue/txmatching pull request #944
Opened 2022-07-25 12:51 UTC by jogobeny

Closes #929.

I am still not sure about difference between `hla_antibodies_raw_list` and `hla_antibodies_per_groups`.
Should I filter
https://github.com/mild-blue/txmatching/blob/7e21936e54d35090de0112db12f7cc2545564feb/txmatching/database/services/matching_service.py#L112
as well?

2022-07-26 08:15 UTC, kristinagalik reviewed
there was a small update on this issue https://github.com/mild-blue/txmatching/issues/929#issuecomment-1194125634

2022-07-26 13:04 UTC, kristinagalik reviewed
okay, i will probably need a confirmation from @kubantjan because maybe i am not updated on the issue well, but i took a look at your code and what i think the only changes should be are:

* add soft_cutoff parameter to config
* add attribute is_soft (or smth like that) to `AntibodyMatch` with default to false
* modify `get_crossmatched_antibodies` function such that it will find crossmatches for antibodies also in range cutoff > mfi >= soft_cutoff (or maybe try to refactor the function such that it can be used either for normal range or for soft range?)
* modify `is_positive_hla_crossmatch` logic such that it will raise positive crossmatch only for antibody matches that arent soft (we just want to highlight them, not actually forbid them)
* add tests

2022-07-26 14:30 UTC, kubantjan commented
@kristinagalik  yes agreed!

2022-07-27 15:13 UTC, kubantjan requested changes
waiting for updates that kristina mentioned

2022-08-02 15:44 UTC, kristinagalik requested changes

2022-08-02 15:44 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
>          # Construct antibody matches set
instead of lines 175-213 why not just do 
```
        # Construct antibody matches set
        antibodies_in_pos_matches = { match.hla_antibody for match in positive_matches }
        for antibody in _get_antibodies_over_cutoff(antibodies):
            if antibody not in antibodies_in_pos_matches:
                positive_matches.add(AntibodyMatch(antibody, AntibodyMatchTypes.NONE))

        if soft_cutoff is not None:
            for antibody in _get_antibodies_in_soft_range(antibodies, soft_cutoff):
                if antibody not in antibodies_in_pos_matches:
                    positive_matches.add(AntibodyMatch(antibody, AntibodyMatchTypes.NONE, True))

        antibody_matches_for_groups.append(AntibodyMatchForHLAGroup(
            hla_per_group.hla_group,
            list(positive_matches)
        ))
```

pls @kubantjan does this violate any logic? i think this is more comprehensible ^ than a lot of ifs

2022-08-02 15:44 UTC, kristinagalik commented on txmatching/web/frontend/src/app/generated/model/configurationGenerated.ts
> +    soft_cutoff: number;
also pls add `softCutoff` to `interface AntibodyMatch` and to `parseAntibodyMatch`

2022-08-03 09:03 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                                positive_matches.add(AntibodyMatch(antibody, AntibodyMatchTypes.SPLIT, True))
@kubantjan is it sufficient like this or should we differentiate between `HIGH_RES` `HIGH_RES_WITH_SPLIT` and `SPLIT` also in soft cutoff (and if yes it will probably have to be with respect to antibodies over cutoff right? like ask - are all antibodies over cutoff in high res so i can add high res antibodies from soft cutoff also to `HIGH_RES`?

2022-08-03 09:40 UTC, kubantjan requested changes

2022-08-03 09:40 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    soft_cutoff: bool=False
(again use IDE configuration)

2022-08-03 09:40 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
>          # Construct antibody matches set
overall the function get_crossmatched_antibodies is extremely complicated. We have an issue to improve it significantly.  Surely this task should not add any extra lines to the function. (which is happening now) preferably  the opposite simplify the function a bit.

So definitely @jogobeny  should create some helper functions. 

and this logic improvement sounds legit, but maybe even more can be done

2022-08-03 10:17 UTC, kubantjan requested changes
Based on my discussion with @kristinagalik  I have made some updates to the issue description. Please have a look. 

overalll 

important part of this issue will be improving the get_crossmatched_antibodies function.

2022-10-11 08:49 UTC, kubantjan commented
Zmeny:
1) nove kdy je use_high_Resolution false, jdeme VZDY na type b
2) upravit testy, dke je ted high resolution false a jde se do type a na type b a ocekavat tam kde bylo high_res_with_split jen split (mozna podobne high_res_with_Broad na broad..)

2022-10-11 10:31 UTC, kubantjan commented
@jogobeny  dava smysl co pises, split se nikdy nehitne, podobne to bude i u broad.

2022-10-12 05:43 UTC, kubantjan commented
je to ok, zmen ho. Bylo to chybne predtim

2023-01-04 08:23 UTC, kubantjan commented
Pro ted zaviram, zda se ze @jogobeny  se k tomu v nejblizsi dobe nedostane a ze strany ikemu byla uzitecnost tohohle rozporovana, takze to vypustime pro ted.

2023-01-04 08:23 UTC, closed without merging