Propose schema for optimizer module
mild-blue/txmatching pull request #948
Opened 2022-07-26 10:36 UTC by kristinagalik

Closes #918

2022-07-27 09:42 UTC, kristinagalik reviewed
@kubantjan please when you have a minute, i have a few questions

2022-07-27 09:42 UTC, kristinagalik commented on txmatching/optimizer/compatibility_graph.py
> +    scoring_column_to_index: Dict[str, int] # todo pripadne miesto str dat enum z score_columns.py
(pls dont mind my comments in the code for now)

here we could already use smth like i started making in `score_columns.py`, but i dont know if there should be some custom keywords, or if i can rely on the fact that there will be finite set of attributes/keywords which will not change without a notice so i can use an enum?

2022-07-27 09:42 UTC, kristinagalik commented on txmatching/web/api/optimizer_api.py
> +        # todo ma tu vobec byt ze maju mat konkretne mena ci sa mam skusit pozriet na koncovky a podla toho?
do you know how exactly will the files be provided? will there be a common name under which the file will be passed? like file1 or configuration etc.. or do i have to check if there are 2 files, which has which extension and so on?

2022-07-28 08:38 UTC, kubantjan requested changes
overall try to make the swagger that is shown for this endpoint to be as nice as possible so one can easily see how it works and upload easily data through the swagger endpoint and get a response that looks real.

2022-07-28 08:38 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +    csv_f = csv_file.read().decode("utf-8")
parsoval bych csv pomoci pandas, nepis vlastni parser.

2022-07-28 08:38 UTC, kubantjan commented on txmatching/web/api/optimizer_api.py
> +class Optimize(Resource):
ten config bych posilal v body jako json (jak to mame v jinych filech, v souborech bych posilal jen ty csvcka :)

2022-07-28 08:38 UTC, kubantjan commented on txmatching/web/api/optimizer_api.py
> +    @optimizer_api.response_ok(description='Matching run, stats')  # todo better description
as in the todo better description and as part of this PR try to already directly send some dummy response files according to the schema.

2022-07-28 09:10 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +    csv_f = csv_file.read().decode("utf-8")
okej, ale neterbalo by potom ukladat tie csv fles na to aby som ich vedela zmysluplne citat? ked som sa to snazila citat takto cez pandas tak to kricalo ze to chce source k filu. to by potom bolo treba mat dake generovane files v zmysle timestamp_2132443513 ktory obsahuje tieto files a potom to mazat a to mi pride ako zbytocne overcomplicated? alebo je to tak lepsie a mam to tak spravit?

2022-07-28 09:58 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +    csv_f = csv_file.read().decode("utf-8")
https://stackoverflow.com/questions/56393747/pandas-read-csv-from-filestorage-in-flask

2022-08-02 12:12 UTC, kubantjan commented on txmatching/web/api/optimizer_api.py
> +# todo question: does pairs.csv start with column names original_donor_index, original_recipient_index or with numbers?
I guess it is not agreed yet, but I would go with a)

2022-08-02 13:04 UTC, kubantjan requested changes
Couple of comments.

2022-08-02 13:04 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +                "Invalid \'compatibility_graph\' file contents. Length of line not equal to number of columns.")
this is exactly somethins that pandas takes care of

2022-08-02 13:04 UTC, kubantjan commented on txmatching/optimizer/compatibility_graph.py
> +    # todo: use int or float? also to post_init add check that compatibility_graph has 3 dimensions?
1. Int values. Yes we should, 
2, I  think what they said during the call makes sens, better than array that is quite sparse will be Dict[Tuple[int,int], List[int]]
where first is id of donor and second id of recipient. From this we can easily create a graph or anything else we might need. 

I do not understand the exact meaning of the other to index dicts. 

what i think we need is after all csvs are processed is something like:


@dataclass
class OptimizationData:
     scoring_column_to_index: Dict[str, int]
     possible_transplants: Dict[Tuple[int,int], List[int]]
     original_pairs: Dict[Tuple[int, int]]
     non_directed_donors: Iterable[int]

2022-08-02 13:08 UTC, kubantjan reviewed
Btw i just realised, the all solutions solver does not work with mutliple donors right? It allows now for cycles that have multiple donors from the same recipient in one round.

2022-08-08 08:13 UTC, kristinagalik commented on txmatching/optimizer/compatibility_graph.py
> +    # todo: use int or float? also to post_init add check that compatibility_graph has 3 dimensions?
original_pairs and non_directed_donors here means that i should exrtact data from both pairs.csv and comp_graph.csv and merge all the info to just one object right?

2022-08-08 08:44 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +def parse_csv_to_comp_graph(csv_file: FileStorage) -> CompatibilityGraph:
which line do you mean? because i use pandas to read the file at line 17

2022-08-08 15:55 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +                "Invalid \'compatibility_graph\' file contents. Length of line not equal to number of columns.")
or differently: this will never happen as the data is parsed to dataframe already. And number of columns will be the same..

2022-08-08 15:55 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +        raise ValueError("No score columns provided for compatibility graph.")
this is legit, there might be no score columns also. and only the default can be used.

2022-08-08 15:55 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +def parse_csv_to_comp_graph(csv_file: FileStorage) -> CompatibilityGraph:
you are right, sorry, I got confused.

2022-08-08 19:25 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +        # todo how to check for non directed donors? recipient is set to -1 or is it line of length 1?
@kubantjan

2022-08-09 08:43 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +def export_return_data() -> Response:
tu mam este otazku - zatial je response zip v ktorom su 2 csvcka - no nebolo by lepsie to mat ako json s 2ma csv stringami pre lepsie parsovanie? ci to chcu byt fakt ze csv **files**

2022-08-09 10:22 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +        # todo how to check for non directed donors? recipient is set to -1 or is it line of length 1?
recipient is not filled (null)

2022-08-09 10:22 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +        # todo how to check for non directed donors? recipient is set to -1 or is it line of length 1?
or that is what i propose in the schema

2022-08-09 10:22 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +        # todo how to check for non directed donors? recipient is set to -1 or is it line of length 1?
you should write a test testing how it works :)

2022-08-09 10:28 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +def export_return_data() -> Response:
tady je dulezity, ze to vymyslime za behu jak presne to vypada. U vsech domluv a callu jsi byla take, ja nemam zadne informace navic. 

pokud vyhodnotime, ze neco nejak bude lepsi, tak fajn. 

kdyz to takhle pises mozna bude lepsi proste json, zadne csvcka

a v tom jsonu budou proste vsechno dokopy

a treba tam jako return bude vzdy:

rounds: [{donor_id:1, recpient_id:2}, {donor_id:2, recpient_id:1}]

to mozna bude prehlednejsi a lepsi.

2022-08-09 10:29 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +def export_return_data() -> Response:
co je vubec v tech files ted? Odkud jsi vzala ze chteji 2 csv files vlastne? v tomhle dokumentu nic takoveho zatim neni: https://docs.google.com/document/d/1Ymsb9j61uo3Fo7Dq0V724FUukhvpBGgJU7eDDUb7NI4/edit#heading=h.4i6bwjlaa2im

2022-08-09 10:37 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +        # todo how to check for non directed donors? recipient is set to -1 or is it line of length 1?
tim schematem myslim v https://docs.google.com/document/d/1Ymsb9j61uo3Fo7Dq0V724FUukhvpBGgJU7eDDUb7NI4/edit#heading=h.4i6bwjlaa2im

tam je explicitne napsany jak to ma vypadat pro non directed. Tak ted nevim jestli jsi to necetla, nebo jaktoze to tam nevidis? Nebo to neni srozumitelny?

2022-08-09 10:45 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +def export_return_data() -> Response:
https://docs.google.com/document/d/1oG7jSf9548IKaWH3tVxv20s_eJFNlpHJxXkZ47Wrn4g/edit

tu je to ^ ja som myslela ze to ma prejst najprv tvojim suhlasom aby sa to vedelo pridat do external

2022-08-09 14:59 UTC, kubantjan commented on txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
> +class DictItem(fields.Raw):
I would not use here generic dictItime

I would simply have a dataclass with some fields and add more upon demand..

2022-08-15 09:58 UTC, closed without merging