589 validate objects coming via api
mild-blue/txmatching pull request #952
Opened 2022-08-01 12:06 UTC by krllstdn

Closes #589

2022-08-01 18:02 UTC, kristinagalik requested changes

2022-08-02 14:36 UTC, krllstdn commented on txmatching/configuration/configuration.py
> +    return ConfigModel.query.filter_by(id=configuration_id).first() is not None
@kristinagalik It has to be, but if it is placed there the _circular import_ occurs

2022-08-03 15:09 UTC, kristinagalik commented on txmatching/configuration/configuration.py
> +def raise_error_if_configuration_does_not_exist(configuration_id):
duplicate definition of this function

2022-08-05 09:20 UTC, kubantjan requested changes
overall ok, small comments

2022-08-05 09:20 UTC, kubantjan commented on txmatching/configuration/config_parameters.py
> +    def __post_init__(self):
I would add non negativnes as a property of the field (such as COMPARISON_MODE property, so we do not have to do this repetitive code here and simply iterate through the fields)

2022-08-05 09:20 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +def raise_error_if_donor_in_txm_event_doesnt_exist(txm_event_id: int, donor_id: int):
I do not see here how you check that the donor is in the txm_event

2022-08-05 13:59 UTC, krllstdn commented on txmatching/database/services/patient_service.py
> +def raise_error_if_donor_in_txm_event_doesnt_exist(txm_event_id: int, donor_id: int):
Hmm, interesting, the check disappeared. WIll be corrected

2022-08-09 10:43 UTC, kristinagalik submitted a review, later dismissed

2022-08-09 14:30 UTC, krllstdn commented on tests/database/services/test_configuration.py
> +            ConfigParameters(minimum_total_score=-1)
@kristinagalik So you mean that it makes sense to leave only one check of the first parameter?

2022-08-09 14:56 UTC, kubantjan requested changes
tiny comment otherwise alright

2022-08-09 14:56 UTC, kubantjan commented on tests/database/services/test_configuration.py
> +            ConfigParameters(minimum_total_score=-1)
@kristinagalik  is right. 

I would say that better is to check for all (as you have it here ready already) but do the chceck for valueerrro separately)

2022-08-09 15:09 UTC, krllstdn commented on tests/database/services/test_configuration.py
> +            ConfigParameters(minimum_total_score=-1)
thanks for the quick reply

2022-08-09 16:00 UTC, kubantjan approved these changes

2022-08-09 16:00 UTC, merged