621 parsing issue objects cleanup
mild-blue/txmatching pull request #953
Opened 2022-08-01 13:36 UTC by krllstdn

Closes #621

2022-08-01 19:28 UTC, kristinagalik requested changes
maybe you copied contents of some files but most of them are missing newlines at the end

other thing is that you are at this point unable to build frontend - i know its frontend but it shouldnt be too complicated, so if you want you can try to fix it by yourself :) if you struggle, just message me or i can do it

2022-08-01 19:28 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_transformations/get_mfi_from_multiple_hla_codes.py
> +    return parsing_issues_temp, relevant_mean
missing newline at the end of the file

2022-08-01 19:28 UTC, kristinagalik commented on txmatching/patients/hla_functions.py
> +    return False
missing newline

2022-08-01 19:28 UTC, kristinagalik commented on txmatching/database/sql_alchemy_schema.py
> +    deleted_at = Column(DATETIME(timezone=True), nullable=True)
missing newline(pls check all the modified files)

2022-08-01 19:28 UTC, kristinagalik commented on txmatching/data_transfer_objects/hla/parsing_issue_swagger.py
> +
this empty line shouldnt be here

2022-08-02 14:12 UTC, kristinagalik requested changes
just a small comment, plus there are some formatting imperfections, but for frontend, ask @NotLubo for reviews rather than me

2022-08-02 14:12 UTC, kristinagalik commented on txmatching/web/frontend/src/app/generated/model/patientUploadSuccessResponseGenerated.ts
> +    // parsing_issues: Array<ParsingIssuePublicGenerated>;
this looks hard coded... maybe regenerate swagger files?

2022-08-03 09:02 UTC, NotLubo requested changes
Minor formatting issues and unremoved leftover code. Good job :)

2022-08-03 09:02 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/patient/patient.service.ts
> +// import { parseParsingIssue } from '@app/parsers/parsingIssueConfirmation.parsers';
remove comment

2022-08-03 09:02 UTC, NotLubo commented on txmatching/web/frontend/src/app/services/patient/patient.service.ts
> +import {parseParsingIssuePublic} from '@app/parsers/parsingIssuePublic.parsers';
lines 28 and 27 formatting

2022-08-03 12:19 UTC, kristinagalik requested changes
just small be changes, otherwise backend ok :)

2022-08-03 12:19 UTC, kristinagalik commented on txmatching/database/db_migrations/0033.make-txm-event-id-required-in-parsing-issue.sql
> +ALTER TABLE parsing_issue ADD CHECK ((donor_id IS NOT NULL) OR (recipient_id IS NOT NULL));
newline missing

2022-08-03 12:19 UTC, kristinagalik commented on txmatching/database/sql_alchemy_schema.py
> +from sqlalchemy.schema import Column, ForeignKey, UniqueConstraint, CheckConstraint
alphabetical order

2022-08-03 12:51 UTC, NotLubo approved these changes

2022-08-05 09:08 UTC, kubantjan approved these changes

2022-08-05 09:20 UTC, merged