Copy patients between txm events not working
mild-blue/txmatching pull request #957
Opened 2022-08-04 13:11 UTC by krllstdn

Closes #956

2022-08-19 09:25 UTC, kristinagalik requested changes
`memory.sqlite` shouldnt be there

also idk if this should be handled (probably yes)

but when a recipient A has donors for instance B, C, D

if i first add B, C, then realize i wanted to add D also but i do it in separate endpoint call, i get an error.

2022-08-19 09:25 UTC, kristinagalik commented on txmatching/data_transfer_objects/patients/utils.py
> +def donor_to_donor_upload_dto(donor: Donor, related_recipient_medical_id:str) -> DonorUploadDTO: # , related_recipient_medical_id:str
check formatting, plus the comment might be redundant

2022-08-19 09:25 UTC, kristinagalik commented on txmatching/database/services/parsing_utils.py
> +        raise InvalidArgumentException(f'There were the same recipient in current data and in the data for upload:'
recipients*

2022-08-19 09:25 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +    txm_event_to_name = get_txm_event_complete(txm_event_id_to).name
if you just want the name, rather do `get_txm_event_base` because the `get_txm_event_complete` function is quite expenisve

2022-08-19 09:25 UTC, kristinagalik commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +    get_id_or_none,
unused import

2022-08-22 08:22 UTC, kristinagalik requested changes
the situation i described above still doesnt work

2022-08-22 08:22 UTC, kristinagalik commented on txmatching/data_transfer_objects/patients/utils.py
> +def donor_to_donor_upload_dto(donor: Donor, related_recipient_medical_id: str) -> DonorUploadDTO:
when are actually `donor_to_donor_upload_dto` and `recipient_to_recipient_upload_dto` used?

2022-08-22 08:59 UTC, krllstdn commented on txmatching/data_transfer_objects/patients/utils.py
> +def donor_to_donor_upload_dto(donor: Donor, related_recipient_medical_id: str) -> DonorUploadDTO:
Never) So you suggest deleting them? I left them there just in case they might be needed in the future

2022-08-22 12:00 UTC, krllstdn commented on txmatching/data_transfer_objects/patients/utils.py
> +def donor_to_donor_upload_dto(donor: Donor, related_recipient_medical_id: str) -> DonorUploadDTO:
@kristinagalik

2022-08-22 12:52 UTC, kristinagalik commented on txmatching/data_transfer_objects/patients/utils.py
> +def donor_to_donor_upload_dto(donor: Donor, related_recipient_medical_id: str) -> DonorUploadDTO:
hmm probably let them be there, i was just confused why to alter them then, but it probably doesnt matter for now :)

2022-08-22 12:58 UTC, krllstdn commented on txmatching/data_transfer_objects/patients/utils.py
> +def donor_to_donor_upload_dto(donor: Donor, related_recipient_medical_id: str) -> DonorUploadDTO:
I used a couple of approaches already, these are just leftovers. I'll leave them the way they are. Thanks

2022-08-26 08:51 UTC, krllstdn commented
@kristinagalik In that case with multiple donors with the same recipient that you've described above, I still have a problem solving it. The problem was copying the remaining donor/donors with the same recipient in another endpoint call. I tried to solve it by getting the needed `RecipientModel` from the DB (now those lines in `_donor_upload_dto_to_donor_model` are commented) but this removed reference to the recipient in donors that were already copied, probably due to ForeignKey. Could you have a look?

2022-08-26 11:00 UTC, kristinagalik reviewed
still not sure whether its necessary, (although i still think its a good idea) but after looking at your code, id rather suggest something like this:
create a.. idk either some global variable or rather something like a database model? that holds these information:

CopyPatientsDictionaries:
from: txmeventid
to: txmeventid
patients: Dict[oldid, newid]

idk if it should be just for donors and then you would retrieve recipient ids from that, (and also it should be updated every time an event gets deleted) or you want to have a separate dict for recipients too (probably better to avoid obscure retrieval), but i would probably do smth like htat (because i didnt find a way to retrieve recipient id from "to" txm event correctly in your code, correct me if im wrong tho, i just skimmed it)

2022-08-26 11:52 UTC, krllstdn commented on txmatching/database/services/patient_upload_service.py
> +            recipients.remove(next(recipient for recipient in recipients if recipient.medical_id == medical_id))
@kristinagalik but the medical id doesn't change, the code checks them in medical ids. This part works as expected

2022-08-26 11:53 UTC, kristinagalik commented on txmatching/database/services/patient_upload_service.py
> +            recipients.remove(next(recipient for recipient in recipients if recipient.medical_id == medical_id))
oh sorry its medical id, ill go look at it again then, dont mind my comment (not even the longer one) for now

2022-08-26 12:34 UTC, krllstdn commented
It also came to my mind but adding the variable `initial_recipient` that copies `recipient` didn't help

2022-08-26 12:57 UTC, kristinagalik commented
@krllstdn 

je to trochu neintuitivne, ale python funguje takto

![image](https://user-images.githubusercontent.com/56656359/186908461-87f31265-77ff-4cba-9b0f-314719a7905a.png)

2022-08-26 13:14 UTC, krllstdn commented
@kristinagalik Wow, `initial_recipients = recipients.copy()` worked! Thanks!
I'll clean it up, test and send it for review

2022-09-19 13:15 UTC, krllstdn commented
Just a small comment: it works if we copy patients to empty txm event. But in case in the db is already a recipient related to the donor we want to copy, it crashes. I didn't manage to fix it. But the probable solution might be creating db table or global variable with the list of copied donor recipient pairs with old and new ids and checking from there, as it was suggested by @kristinagalik. @kubantjan, please look into that. Thanks.

2022-09-27 16:39 UTC, krllstdn commented
@kristinagalik yes it shouldn't copy the donor that is already, and it doesn't. As was mentioned he problem was with linking the donor we are copying with the recipient that is already in the database. In code the linking donor and recipient is made by passing the object of related recipient model to the donor that wasn't in the db yet (if we got it from the db and passed it to donor it didn't work. and just passing an id of related recipient didn't work as well)

2022-10-11 09:51 UTC, kubantjan requested changes

2022-10-11 09:51 UTC, kubantjan commented on tests/web/test_txm_event_api.py
> +            self.assertEqual(200, res.status_code)
tady by preci nemel byt error code 200, pokud je to fail ne?

2022-10-11 09:55 UTC, kubantjan requested changes

2022-10-11 09:55 UTC, kubantjan commented on txmatching/database/services/patient_upload_service.py
> +    if not is_copy:
tohle vysvetlit prosim, proc v copy to takhle muze byt?

2022-11-02 11:38 UTC, krllstdn commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +    donor_related_recipient_medical_ids = [
proc se tohle jmenuje `donor_related_recipient_medical_ids` pokud neobsahuje zadne medical ids? to je seznam Recipient objectu

2022-11-02 11:41 UTC, krllstdn commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
>      for medical_id in donor_related_recipient_medical_ids:
opet. tohle neni medical id

2022-11-02 11:46 UTC, krllstdn commented on txmatching/database/services/patient_upload_service.py
> +    List[DonorModel], List[RecipientModel]]:
nejaky divny indentation

2022-11-02 15:57 UTC, kubantjan commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
>      for medical_id in donor_related_recipient_medical_ids:
dobry postreh, mrkni ale na to, ze test testujici na error byl uplne spatne, vubec to netestoval tu situaci. self.assertEqual co tam bylo predtim nedelalo vubec nic!

2022-11-02 15:57 UTC, kubantjan commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
>      for medical_id in donor_related_recipient_medical_ids:
kdyby to testoval spravne, tak testy v tomto pripade vubec neprojdou a tu chybu bych neudelal, ale takhle test prochazel, i kdyz to vubec nefungovalo.

2022-11-02 16:04 UTC, kubantjan commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
> +    donor_related_recipient_medical_ids = [
good catch

2022-11-02 16:05 UTC, kubantjan commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
>      for medical_id in donor_related_recipient_medical_ids:
mrkni na to. Tohle je zas priklad toho, jak rikam, ze nekdy delas hodne neco neopatrne, ten test jsem uznavam prehlidl, ze vlastne vubec nic netestuje. Ale kdyz tam pridas self.assertRaises tak bys mel presne rozumet tomu co to dela, nebo si vyzkouset ze to dela to co chces..

2022-11-02 17:23 UTC, krllstdn commented on txmatching/utils/copy/copy_patients_from_event_to_event.py
>      for medical_id in donor_related_recipient_medical_ids:
Jo, uz chapu svu chybu. Budu se snazit ji nezopakovat. Dik za vysvetleni

2022-11-11 08:59 UTC, kubantjan commented
as soon as this finishes running it can be merged.

2022-11-29 08:16 UTC, kubantjan approved these changes

2022-11-29 08:17 UTC, merged