Txm knowledge base
mild-blue/txmatching pull request #959
Opened 2022-08-08 12:27 UTC by kristinagalik

2022-08-08 12:32 UTC, kristinagalik reviewed
@kubantjan tym ze som len zbierala material z internetu, tak neni problem ak to nereferencnem hej?

2022-08-08 12:32 UTC, kristinagalik commented on documentation/README.md
> +## Types of crossmatches in TXM
@kubantjan you wrote: 
...
3) you should explain here how we require the information about all antibodies that the recipient is tested for (positive and negative) for high res, but not for split, this will help the understanding of the logic I think.

but im not sure i understand properly. does it mean that we want to have the high res for antibodies if possible?

2022-08-08 12:32 UTC, kristinagalik commented on documentation/README.md
> +**NONE** - antibody is over cutoff, but there is no crossmatch.
tu je moj confusion ten ze to je vlastne undecidable ci?
resp este moze nastat ze su dake antibodies pre SPLIT antigen aj v split aj v high res, a tie high res sa pridaju bud do HIGH RES alebo HIGH RES WITH SPLIT a tie split sa odignoruju, ale to by mala byt asi skor podmienka ze ak je tam aspon jeden split antibody tak to hod vsetko do SPLIT miesto HIGH RES WITH SPLIT ci? (myslim ze toto sa tam teraz necheckuje)

2022-08-09 14:33 UTC, kubantjan commented on documentation/README.md
> +## Types of crossmatches in TXM
no it does not. (even though what you write is true)

I am not sure whether you know that what I will write below. But it is extremely important and I think:
when we get antibodies in high res, we assume that we are getting all antibodies the patient was tested fore. I.e. both with MFI below and above cutoff

in the case of split/broad resolution we do not assume that. i.e. we expect that only the positive mfi values are send (and if some negative it is no problem), but we do not expect the lab to send all.

2022-08-09 14:36 UTC, kubantjan commented on documentation/README.md
> +**NONE** - antibody is over cutoff, but there is no crossmatch.
tady furt zminujes ze mame najednou protilatky pro jednoho pacienta ve split i high res. Jako tohle obecne by vubec se dit nemelo. Rozhodne by se nemelo stat, ze budeme mit u jednoho pacienta pro jeden split protilatku ve split resolution i high res. To je dost nesmysl na to bychom klidne mohli mit tst.

tvuj confusion furt nechapu. NONE je ze proste ma protilatku proti necemu co donor nema, co na tom neni jasne?

2022-08-09 14:38 UTC, kubantjan requested changes
viz odpovedi na otazky

2022-08-09 14:39 UTC, kubantjan commented on README.md
> +### Crossmatches
here is category of crossmatches so there is duplicity

2022-08-09 14:39 UTC, kubantjan commented on README.md
> +### Crossmatches
and here are some levels missing even

2022-08-09 14:54 UTC, kristinagalik commented on documentation/README.md
> +**NONE** - antibody is over cutoff, but there is no crossmatch.
no ale potom ak to je takto tak NONE == UNDECIDABLE

NONE = "ze proste ma protilatku proti necemu co donor nema"
UNDECIDABLE = "antibody exists against a typization group that the donor was not typizised for" (z tej match logic issue)

a tym padom by NONE ani nemusel existovat a ani tych vela ifov v `get_crossmatched_antibodies` ktore su tam len kvoli NONE

2022-08-09 14:55 UTC, kristinagalik commented on README.md
> +### Crossmatches
thats kirils code, we agreed that we will merge the information

2022-08-10 06:50 UTC, kubantjan requested changes
Jeste pridat teda to vysvetleni ze predpokladame na high res vsechny protilatky

2022-08-10 06:50 UTC, kubantjan commented on documentation/README.md
> +E.g.: donor has antigens in group “Other”: DPB1\*512:01, DQA1\*02:05, and recipient has antibodies: DQB1\*03:10,
here you are wrongly using example of group other. We are not grouping this by group other, but by dqa dqb etc.

2022-08-10 10:51 UTC, kubantjan requested changes

2022-08-10 10:51 UTC, kubantjan commented on documentation/README.md
> +IMPORTANT: When we get antibodies in high res, we assume that we are getting all antibodies the patient was tested for. Meaning, both with MFI below and above cutoff. In the case of split or broad re
Jeste bych to tady dovysvetlil ten pripad split. Ze predpokladame ze pacient byl testovany na vsechny relevantni split protilatky. Takze neni potreba negativni posilat, ale poslat je klidne muzou, nic to nerozbije.

2022-08-12 12:43 UTC, kristinagalik commented on documentation/README.md
> +IMPORTANT: When we get antibodies in high res, we assume that we are getting all antibodies the patient was tested for. Meaning, both with MFI below and above cutoff. In the case of split or broad re
assumujem ze mas namysli split aj broad, zatial tie zmeny robim tak, prosim oprav ma ak to je len split

2022-08-13 14:21 UTC, kubantjan approved these changes

2022-08-13 14:21 UTC, merged