#669 default configuration not working when patients change
mild-blue/txmatching pull request #960
Opened 2022-08-11 09:31 UTC by krllstdn

2022-08-11 09:34 UTC, krllstdn commented
This PR is still a work in progress and is paused for some time. Some tests that modulate the problem were made, though I'm not sure how well they do their work.

2022-09-09 14:53 UTC, kubantjan requested changes
ten problem nastava nejen kdyz se pacient smaze ale i kdyz se jen pacient stane nevalidnim. 

je to potreba jeste dotahnout. Prijde mi ze mozna bude lepsi, nez to handlovat na urovni mist, kde se to muze zmenit ten pacient (delete donor nebo modify) to delat na miste, kde se config aplikuje a proste nevalidni veci z configu ignorovat.

2022-09-22 21:42 UTC, kristinagalik requested changes
few small comments :) otherwise ok

2022-09-22 21:42 UTC, kristinagalik commented on Makefile
> +rerun: setup-non-empty-db run
missing endline

2022-09-22 21:42 UTC, kristinagalik commented on txmatching/configuration/configuration.py
> +from txmatching.database.services.txm_event_service import get_txm_event_complete, raise_error_if_txm_event_does_not_exist
why import `get_txm_event_complete`? i think its not used anywhere

2022-09-22 21:42 UTC, kristinagalik commented on txmatching/configuration/configuration.py
> +from txmatching.database.services.txm_event_service import get_txm_event_complete, raise_error_if_txm_event_does_not_exist
same goes for `RecipientModel`

2022-09-22 21:42 UTC, kristinagalik commented on txmatching/solve_service/solve_from_configuration.py
> +            and pair.recipient_db_id not in txm_event.active_and_valid_recipients_dict:
it should be probably `or` rather than `and`

2022-10-01 15:30 UTC, kristinagalik submitted a review, later dismissed

2022-11-01 16:08 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +    for config in ConfigModel.query.all():
tady bych minimalne bral jen ty z relevantniho txm eventu.

2022-11-01 16:14 UTC, kubantjan commented on txmatching/database/services/patient_service.py
> +        if maybe_recipient is not None and maybe_recipient.db_id in config.parameters["required_patient_db_ids"]:
proc tady nekontrolujes i jestli to id neni mezi manual recipient donor scores?

2022-11-01 16:19 UTC, kubantjan commented on txmatching/solve_service/solve_from_configuration.py
> +    for patient_db_id in config_parameters.required_patient_db_ids:
tady bych spis udelal list comprehension nez pouzival remove, to je docela draha operace, tady ji vyuzivas podle me zbytecne.

2022-11-01 16:20 UTC, kubantjan commented on txmatching/solve_service/solve_from_configuration.py
> +    for patient_db_id in config_parameters.required_patient_db_ids:
neco jako config_parameters.required_patient_db_ids = [db_id for db_id in config_parameters.required_patient_db_ids if db_id in active_and_valid_recipients_dict]

2022-11-01 16:20 UTC, kubantjan commented on txmatching/solve_service/solve_from_configuration.py
> +    for patient_db_id in config_parameters.required_patient_db_ids:
a podobne o radek niz

2022-11-03 10:23 UTC, krllstdn commented on tests/web/test_patient_api.py
> +        configuration = ConfigParameters(
Zde jsem si vsimnul ze my filtrujeme nevalidni pacienty z `manual_donor_recipient_score`, ale netestujeme zda to funguje nebo ne.

2022-11-03 16:45 UTC, kubantjan approved these changes

2022-11-03 21:20 UTC, merged