UI Improvements #740 testový úkol
mild-blue/txmatching pull request #965
Opened 2022-08-12 20:16 UTC by anhelina-sadovnikova

Vyřešen problém s pop-upem "Add new patient pair" při přidání nových pacientu a posouvatkem u okna Generate report. Zasekla jsem se u problému s rohy.

2022-08-25 11:04 UTC, misslecter requested changes
jen drobnost

2022-08-25 11:04 UTC, misslecter commented on txmatching/web/frontend/src/app/components/template-popup/template-popup.component.scss
> +    overflow: hidden;
posun `overflow: hidden;` do parenta a odsud odstran

2022-08-25 11:04 UTC, misslecter commented on txmatching/web/frontend/src/app/components/template-popup/template-popup.component.scss
> +    overflow: hidden;
odsud taky odstran, podedi to od parenta

2022-08-26 11:57 UTC, anhelina-sadovnikova reviewed
Poslední část testového zadání (lícování rohů)

2022-09-06 15:01 UTC, merged