Send statistics about the matching run to FE; swagger regenerated
mild-blue/txmatching pull request #966
Opened 2022-08-15 07:51 UTC by NguyenAdela

2022-08-16 05:32 UTC, kubantjan requested changes
jeste pridat do nejaky test

2022-08-16 05:32 UTC, kubantjan commented on txmatching/scorers/hla_additive_scorer.py
> +    #pylint: disable=too-many-return-statements
proc je tohle tadz potreba najednou? muze to souviset s https://github.com/mild-blue/txmatching/issues/814?

2022-08-16 05:32 UTC, kubantjan commented on txmatching/web/frontend/src/app/generated/model/calculatedMatchingsGenerated.ts
> + *
?

2022-08-16 05:32 UTC, kubantjan commented on txmatching/web/frontend/src/app/generated/model/patientModelToUpdateGenerated.ts
> +    hla_typing?: PatientModelToUpdateHlaTypingGenerated;
co se to tady stalo?

2022-08-16 05:32 UTC, kubantjan commented on txmatching/web/frontend/src/app/generated/model/calculatedMatchingsGenerated.ts
> +    number_of_possible_recipients?: number;
kdyz uz to pridavas na fe, umela bys to i nekde ukazat ty cisla?

2022-08-16 11:30 UTC, NguyenAdela commented on txmatching/web/frontend/src/app/generated/model/patientModelToUpdateGenerated.ts
> +    hla_typing?: PatientModelToUpdateHlaTypingGenerated;
Vypada to, ze se menily nejaky apicka a nevygeneroval se swagger a ts

2022-08-16 11:33 UTC, NguyenAdela commented on txmatching/scorers/hla_additive_scorer.py
> +    #pylint: disable=too-many-return-statements
ahaa, asi ano

2022-08-16 11:34 UTC, NguyenAdela commented on txmatching/web/frontend/src/app/generated/model/calculatedMatchingsGenerated.ts
> + *
Jak jsem pregenerovala ts frontendove, tak se tam nevypsala ta mezera (asi ji tam nekdo omylem pripsal)

2022-08-16 11:35 UTC, NguyenAdela commented on txmatching/web/frontend/src/app/generated/model/calculatedMatchingsGenerated.ts
> +    number_of_possible_recipients?: number;
yop, tak pridam rovnou k tomuhle PR

2022-08-19 08:55 UTC, kristinagalik commented on txmatching/database/services/matching_service.py
> +    number_of_possible_recipients = sum(
just guessing but
if this calculates recipients that have at least one *compatible* donor, i tihnk this isnt accurate because the 
```
[
            score_dict[(donor_db_id, recipient_db_id)] >= 0
            for donor_db_id in txm_event.active_and_valid_donors_dict.keys()
        ]
```
part outputs boolean array, so the length will be always greater than zero as long as there is at least one valid donor. maybe just make a `set` of recipients from the `score_dict` and return length?

but if i misunderstood the issue please correct me

2022-08-21 10:47 UTC, NguyenAdela commented on txmatching/database/services/matching_service.py
> +    number_of_possible_recipients = sum(
Yeah, thanks, you're right. Instead of len I meant to use sum

2022-09-19 06:34 UTC, kubantjan requested changes

2022-09-19 06:34 UTC, kubantjan commented on txmatching/database/services/matching_service.py
> +        if sum([
co se stane, kdyz tento set donoru bude prazdny? asi by mi tady spis daval smysl len i to bude vic nazorncy co se deje

2022-09-19 06:34 UTC, kubantjan commented on txmatching/database/services/matching_service.py
> +    number_of_possible_recipients = sum(
proc sum a ne len?

2022-09-19 14:11 UTC, NguyenAdela commented on txmatching/database/services/matching_service.py
> +    number_of_possible_recipients = sum(
Jo, mas pravdu, opravila jsem na sum v obou pripadech.

2022-09-19 14:14 UTC, kubantjan requested changes

2022-09-19 14:14 UTC, kubantjan commented on txmatching/database/services/matching_service.py
> +        if sum([
tady vidim porad sum!

2022-09-19 14:17 UTC, NguyenAdela commented on txmatching/database/services/matching_service.py
> +        if sum([
V tomto pripade tam mam list boolean hodnot a chci zjistit, kolik jich je true, mam predelat i tohle?
`[          score_dict[(donor_db_id, recipient_db_id)] >= 0
            for donor_db_id in txm_event.active_and_valid_donors_dict.keys()
        ]`

2022-09-19 14:35 UTC, kubantjan requested changes

2022-09-19 14:35 UTC, kubantjan commented on txmatching/database/services/matching_service.py
> +        if sum([
ah uz vidim. Tak jo logika je ok, ale zlepsil bych citelnost.

1) nepotrebujes ten list, sum umi iterovat rovnou.
2) mozna bych to hodil do nejaky fce at je jasny co se tam deje (inspirace zde: https://stackoverflow.com/questions/2643850/what-is-a-good-way-to-do-countif-in-python

2022-09-20 15:34 UTC, kubantjan requested changes
jeste poznamky k citelnosti, uz to nic na logice nemeni, ale prijde mi to fakt uzitecny, je fakt dobry se zamyslet jak to psat tak aby se kod hezky cetl a ted ta konstrukce co tam je je divna.. To co pisu jsou navrhy, klidne rozporuj :)

2022-10-11 10:43 UTC, kubantjan approved these changes

2022-10-13 14:43 UTC, kubantjan approved these changes

2022-10-13 14:43 UTC, merged