feat: add optimizer endpoint
mild-blue/txmatching pull request #969
Opened 2022-08-15 09:55 UTC by kristinagalik

2022-08-15 09:56 UTC, kristinagalik commented on txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
> +class DictItem(fields.Raw):
zrazu uz niekolko veci pouziva tento dict item.. mam sa snazit kazdu z nich nahradit optional fields z toho setu keywords co su provided v dropbox dokumente?

2022-08-15 09:57 UTC, kristinagalik commented on txmatching/web/api/optimizer_api.py
> +# todo toto asi netreba a staci dat do swaggeru examples
@kubantjan ?

2022-08-15 15:16 UTC, kubantjan commented on txmatching/web/api/optimizer_api.py
> +# todo toto asi netreba a staci dat do swaggeru examples
jop, melo by to bejt v examples dostatecny

2022-08-15 15:19 UTC, kubantjan requested changes

2022-08-15 15:21 UTC, kubantjan requested changes
Urcite bych pridal jeden test :)

2022-08-15 15:21 UTC, kubantjan commented on tests/web/test_swagger_endpoint.py
> +                f'{API_VERSION[1:]}/optimizer': [400]
tahle 400 je kvuli tomu ze nefunguje spravne ten example asi? To mozna se spravi prave..

2022-08-16 08:08 UTC, kristinagalik commented on txmatching/web/api/optimizer_api.py
> +# todo toto asi netreba a staci dat do swaggeru examples
ide, tak dam to ako examples miesto toho popisku

2022-08-16 08:23 UTC, kristinagalik commented on txmatching/web/api/optimizer_api.py
> +# todo toto asi netreba a staci dat do swaggeru examples
```
{
  "compatibility_graph": [
    {
      "donor_index": 1,
      "recipient_index": 2,
      "hla_compatibility_score": 17,
      "donor_age_difference": 1
    }
  ],
  "pairs": [
    {
      "donor_id": 1,
      "recipient_id": 4
    }
  ],
  "configuration": {
    "limitations": {
      "max_cycle_length": 3,
      "max_chain_length": 4,
      "custom_algorithm_settings": {
        "max_number_of_iterations": 200
      }
    },
    "scoring": [
      [
        {
          "transplant_count": 1
        }
      ],
      [
        {
          "hla_compatibility_score": 3
        },
        {
          "donor_age_difference": 20
        }
      ]
    ]
  }
}
```
toto je teda v examples a ten popis davam prec

2022-08-16 12:06 UTC, kristinagalik commented
```
AssertionError: Responses are not compatible. Definition of valid response is ['OptimizerReturn'] which is different than definition of actual response which is []. 
Valid response: {'cycles_and_chains': [], 'statistics': {'number_of_found_cycles': 1, 'number_of_found_transplants': 1}} 
Actual response: {'cycles_and_chains': [[{'donor_id': 1, 'recipient_id': 2, 'score': [6, 5, 4, 7]}, {'donor_id': 2, 'recipient_id': 1, 'score': [3, 2, 1, 4]}]], 'statistics': {'number_of_found_cycles': 1, 'number_of_found_transplants': 2}}
```
hadze mi to tento error, uz nad tym sedim niekolko hodin a neviem co premeskavam, nenapada ta prosim @kubantjan cim by to mohlo byt?

2022-08-22 09:57 UTC, kubantjan approved these changes

2022-08-22 10:29 UTC, merged