Simplify `get_crossmatchted_antibodies`
mild-blue/txmatching pull request #971
Opened 2022-08-18 12:19 UTC by jogobeny

Hello there, I've
1. divided the crossmatching into seperated types
2. added https://github.com/mild-blue/txmatching/blob/4f4dcb0b00f258405084d7837628d3aaac648b0f/txmatching/utils/hla_system/hla_crossmatch.py#L125 because of not getting antibodies below cutoff in https://github.com/mild-blue/txmatching/blob/4f4dcb0b00f258405084d7837628d3aaac648b0f/txmatching/utils/hla_system/hla_crossmatch.py#L142-L145
3. removed https://github.com/mild-blue/txmatching/blob/06f545e00f9eb31fb0c46a79b73d87cf0c6584cf/txmatching/utils/hla_system/hla_crossmatch.py#L82 from the logic code and modified https://github.com/mild-blue/txmatching/blob/06f545e00f9eb31fb0c46a79b73d87cf0c6584cf/tests/web/test_patient_api.py#L523 to https://github.com/mild-blue/txmatching/blob/4f4dcb0b00f258405084d7837628d3aaac648b0f/tests/web/test_patient_api.py#L523 to check the uniqueness of antibodies.

What are you thoughts?

2022-08-23 18:41 UTC, kristinagalik submitted a review, later dismissed
fine by me :) so when @kubantjan is back he can check it too 

(also rebase)

2022-09-06 11:59 UTC, kubantjan requested changes
jeste in progress

2022-09-06 11:59 UTC, kubantjan commented on tests/web/test_patient_api.py
> +        # Because there is a uniqueness between antibodies in high resolution and
https://stackoverflow.com/questions/480214/how-do-i-remove-duplicates-from-a-list-while-preserving-order

podle toho co tam pisou dava smysl list(dict.fromkeys(items))

a tim bych i zjednodusil ten komentar na neco jako

using code from link to get unique elements from list while preserving order.

2022-09-06 11:59 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +def _do_crossmatch(matching_antibodies: List[HLAAntibody], positive_matches: Set[AntibodyMatch],
co maji znamenat ty podrzitka ve jmenech tech parametru metody?

2022-09-07 10:02 UTC, kubantjan requested changes
par komentaru

2022-09-07 10:02 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    elif len(_get_antibodies_over_cutoff(antibodies_with_high_res)) > 0:
tohle je takovy divny, kdyz bude nejaky antibody high res a nejaky ne, tak tady udelas to ze vsem das to high_res_with_broad, coz bude spatne.

tady spis bys mel projet ten seznam tech matchu a u kazdyho z nich se rozhodnout, podle toho, jestli je to high res nebo ne.

2022-09-12 12:45 UTC, kubantjan commented
Mrkni v ramci tohoto na:

https://github.com/mild-blue/txmatching/pull/984

asi by bylo idealni v ramci toho upravit tu logiku, aby to odpovidalo presne tomuhle (+ pridat testy) 

tim se ozkousi, jestli je to napsane srozumitelne 

v  zasade by to cca takto uz ted melo fungovat, ale ted je to hezceji shrnute a asi mi i dava smysl aby ten kod mel takovouhle vyhybku. Tzn ten mode A a mode B

2022-09-21 10:17 UTC, kubantjan commented
Lepsi ty komentare nedavat do todo ale rovou do toho PR, pak se na ne lip odpovida

2022-09-21 10:24 UTC, kubantjan requested changes
komentare

obecne bych jeste udelal 2 3 testy na _is_recipient_type_a

2022-09-21 10:24 UTC, kubantjan commented on tests/utils/hla_system/test_crossmatch.py
> +        # TODO: Je toto potřeba? `create_antibodies` stejně volá nějaké parsování,
neni potreba, mas pravdu muzes smazat

2022-09-21 10:24 UTC, kubantjan commented on tests/utils/hla_system/test_crossmatch.py
> +        # TODO: Tohle už je taky podle mě zbytečné, protože to, že se správně počítá průměr mfi jsme zjistili už nahoře
jop, smaz

2022-09-21 10:24 UTC, kubantjan commented on tests/utils/hla_system/test_crossmatch.py
> +        # TODO: Tohle mi podle té logicky odpovídá pro type B typizací BROAD, podle BROAD_2.
Pro obe varianty to ma byt NONE. A podle me to i odpovida popisu v textu.

Pro "b" , aby to byl broad, muselo by byt bud donoruv antiben, nebo recipientovo antibody v broad, coz v tomto pripade neni.

Pro "a" aby to byl HIGH_2, muselo by jit o shodu na urovni split a ne broad.

2022-09-21 10:24 UTC, kubantjan commented on tests/utils/hla_system/test_crossmatch.py
> +        # antibodies duplicity should not raise duplicity assert, because the antibodies are joined before creating
tohleto s tim duplicity assertem nevim proc tady pises?

2022-09-21 10:26 UTC, kubantjan requested changes

2022-09-21 10:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    if total_antibodies < 5:
tuhle konstantu dej nahoru do filu pojmenovanou. Nikdy nechces mit v kodu magic numbers. a ma byt 20 a ne 5 :)

2022-09-21 10:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +def _is_recipient_type_a(recipient_antibodies: HLAAntibodies) -> bool:
logika ok

2022-09-21 22:42 UTC, kristinagalik requested changes
(ill finish review tomorrow in the afternoon)

2022-09-21 22:42 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
>      return [antibody for antibody in antibodies if antibody.code.high_res]
this function is no longer used

2022-09-21 22:42 UTC, kristinagalik commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    if is_at_least_one_antibody_below_cutoff:
shouldnt this be `if not is_at_least_one_antibody_below_cutoff`?

2022-09-27 11:29 UTC, kubantjan commented
> Okay, I've
> 
> 1. fixed mistakes in the logic in `get_crossmatched_antibodies`: [Simplify `get_crossmatchted_antibodies` #971 (comment)](https://github.com/mild-blue/txmatching/pull/971#discussion_r978343515)
> 2. added `test_is_recipient_type_a`
> 3. made to pass all tests for `get_crossmatched_antibodies` function
> 
> I have a question about `test_virtual_crossmatch_if_all_antibodies_positive_in_high_res`. I am not sure about determining whether a crossmatch is positive or negative. For example `self._assert_negative_crossmatch('A9', high_res_antibodies_not_all_positive, True, HLACrossmatchLevel.BROAD)` should have negative crossmatch on `BROAD` level. This assert calls `is_positive_hla_crossmatch` -> `get_crossmatched_antibodies`, but in lack of antibodies, it always does logic type B (and I don't even know if it should be type B or type A). For type B, this crossmatch is positive, because antibodies has `BROAD` match type and `BROAD` is accepted in `BROAD` crossmatch level. For type A, the crossmatch is negative, because antibodies has `HIGH_RES_WITH_BROAD` match type and it is not accepted by `BROAD` crossmatch level. I mean, I've shown you that it is determinable if it's type A or type B by more analyzing, but I'd like to have it approved by you. I might have missed some text in documentation.

cely ten test ma byt pro logiku type A

2022-09-27 14:17 UTC, kubantjan requested changes
Crossmatch by mel vracet rozhodne vzdy a za kazdych okolnosti jen list protilatek over cutoff. Ty pod cutoff slouzi jen jako doprovodna informace pro rozhodnuti do ktery kategorie ta dana protilatka nad cutoff spada. Coz ted tak uplne mi neprijde (treba u toho add_undecidable)

2022-09-27 14:17 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +                    for match in _get_antibodies_over_cutoff(tested_antibodies_that_match):
v celym antibodies type b te zajimaji jen over cutoff, tak bych to udelal rovnou na zacatku.

2022-09-27 14:17 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +def _add_undecidable_typization(antibodies: List[HLAAntibody], hla_per_group: HLAPerGroup,
sem by mely vstupovat jen pozitivni protilatky. coz se ted nedeje

2022-09-27 14:19 UTC, kubantjan reviewed
Jinak celkove vypada dobre

2022-09-29 14:05 UTC, kubantjan commented
> 

None urcite nikdy nic matchnout nemuze

2022-09-30 14:40 UTC, kubantjan requested changes
Tady porad cekam na tebe ne?

2022-10-03 17:11 UTC, kristinagalik reviewed
odomna len maly dotaz

2022-10-05 05:56 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +    if hla_per_group.hla_group == HLAGroup.Other:
https://www.quora.com/Are-function-calls-expensive-in-Python

myslim ze tohle je naprosto ok, kdyz bys delal nejakou hlubokou rekurzi, tak to dava asmysl resit, tady v tomto pripade ne.

2022-10-05 06:26 UTC, kubantjan requested changes
Pridej vysvetleni vyznam co to znamena (tzn HIGH_RES_1 ze odkazuje na bod 1. z toho atp. Asi to dej tohle vysvetleni do readme..

2022-10-05 06:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
>  def is_positive_hla_crossmatch(donor_hla_typing: HLATyping,
tohle je druha hlavni, hned pod ni.

2022-10-05 06:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +def _add_all_tested_antibodies_are_positive(tested_antibodies_that_match: List[HLAAntibody],
tenhle nazev mi prijde blbe srozumitelny.

co to presne dela? Z nazvu tomu uprimne nerozumim a zkodu si taky nejsem jisty.

2022-10-05 06:26 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.split is not None:
odkaz na readme

2022-10-05 06:28 UTC, kubantjan commented on txmatching/utils/hla_system/hla_crossmatch.py
> +            if hla_type.code.split is not None:
SPLIT_1 asi ne?

2022-10-05 06:37 UTC, kubantjan commented
Uvedomil jsem si chybu.

V pripade SPLIT_2 a BROAD_2 kdyz je antigen v high res, tak ten bod jeplatny jen pro type B. Pro type A se tohle resi uz jinde (bud to bude HIGH_RES, nebo to bude HIGH_RES_WITH_SPLIT/BROAD

mrkni na to prosim, pripadne pridej test a fix.

2022-10-07 06:15 UTC, kubantjan approved these changes

2022-10-07 06:25 UTC, merged