Optimize the size of report
mild-blue/txmatching pull request #972
Opened 2022-08-18 16:56 UTC by krllstdn

Closes #964

2022-09-07 08:29 UTC, kubantjan requested changes
and add test

2022-09-07 08:29 UTC, kubantjan commented on txmatching/database/services/report_service.py
> +            '--dpi': ' 60'
please attach an example report, so we can see that the dpi is not too low for print

2022-09-07 08:29 UTC, krllstdn commented on txmatching/database/services/report_service.py
> +            '--dpi': ' 60'
[report_2022_09_07_07_31_05.pdf](https://github.com/mild-blue/txmatching/files/9504213/report_2022_09_07_07_31_05.pdf)

2022-09-07 08:32 UTC, krllstdn commented
with lowered dpi : [report_2022_09_07_07_31_05.pdf](https://github.com/mild-blue/txmatching/files/9504193/report_2022_09_07_07_31_05.pdf)
with original dpi: [report_2022_09_07_10_30_30.pdf](https://github.com/mild-blue/txmatching/files/9504229/report_2022_09_07_10_30_30.pdf)

Personally, I don't see any difference in how they look, but the one with the original dpi is 25% bigger

2022-09-07 09:26 UTC, kubantjan commented
> @kubantjan with lowered dpi : [report_2022_09_07_07_31_05.pdf](https://github.com/mild-blue/txmatching/files/9504193/report_2022_09_07_07_31_05.pdf) with original dpi: [report_2022_09_07_10_30_30.pdf](https://github.com/mild-blue/txmatching/files/9504229/report_2022_09_07_10_30_30.pdf)
> 
> Personally, I don't see any difference in how they look, but the one with the original dpi is 25% bigger

@krllstdn  have you tried then dpi 30? or even dpi 1? maybe the setting does not matter and will only decrese the size of the report then?

2022-09-09 10:09 UTC, krllstdn commented
@kubantjan Yes I did. Dpi 1 ruined everything, dpi 30 some elements were too pixelated, dpi 60 looked optimal to me. But now I rechecked everything and I decided to stop on dpi 300. Because it doesn't increase size of the file significantly, while it's optimal for printing

2022-09-09 11:57 UTC, kubantjan approved these changes

2022-09-09 11:59 UTC, kubantjan requested changes
dopsat vysvetleni proc se tam dela ten magic

2022-09-09 14:06 UTC, kubantjan approved these changes

2022-09-09 14:06 UTC, merged