Add export for optimization module
mild-blue/txmatching pull request #975
Opened 2022-08-22 08:31 UTC by kristinagalik

Closes #963

2022-08-24 16:47 UTC, kristinagalik commented
Output from `high_res_example_data`
```
{
    "compatibility_graph": [
        {
            "donor_id": 1,
            "hla_compatibility_score": -2.0,
            "recipient_id": 1
        },
        {
            "donor_id": 1,
            "hla_compatibility_score": -1.0,
            "recipient_id": 2
        },
        {
            "donor_id": 2,
            "hla_compatibility_score": -1.0,
            "recipient_id": 1
        },
        {
            "donor_id": 2,
            "hla_compatibility_score": -2.0,
            "recipient_id": 2
        },
        {
            "donor_id": 3,
            "hla_compatibility_score": -1.0,
            "recipient_id": 1
        },
        {
            "donor_id": 3,
            "hla_compatibility_score": 0.0,
            "recipient_id": 2
        }
    ],
    "configuration": {
        "limitations": {
            "custom_algorithm_settings": {},
            "max_chain_length": 4,
            "max_cycle_length": 4
        },
        "scoring": [
            [
                {
                    "hla_compatibility_score": 1
                }
            ]
        ]
    },
    "pairs": [
        {
            "donor_id": 1,
            "recipient_id": 1
        },
        {
            "donor_id": 2,
            "recipient_id": 2
        },
        {
            "donor_id": 3,
            "recipient_id": null
        }
    ]
}
```

2022-08-24 19:49 UTC, kristinagalik reviewed
@kubantjan nejake otazky

2022-08-24 19:49 UTC, kristinagalik commented on txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
> +    'compatibility_graph': fields.List(required=True, cls_or_instance=fields.Nested(CompatibilityGraphRowJson)),
toto som musela prepisat lebo testom na swagger sa nepacil DictItem, problem ale je, ze je to este pre "scoring" a pre "custom_algorithm_settings" pouzivane... ako sa tomu vyhnut? mam tam proste dat keywords ktore sa budu rozsirovat neskor? (resp idem to tam zatial takto dat ale neviem ci mi to pride ako fajn napad)

2022-08-24 19:49 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +    # todo: I don't actually know what the number represents? this is a temporary scoring
niesom si ista ci uplne chapem ako tie cisla presne vplyvaju.. resp chapem rozdiel medzi vplyvom zaporneho a kladneho cisla ale neviem co *presne* toto znamena? nejaka importance? ci zalezi od implementacie?

2022-08-24 23:20 UTC, kristinagalik commented on txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
> +    # 'scoring': fields.List(required=False, cls_or_instance=fields.Nested(ScoringJson), example=[[{"transplant_count": 1}], [{"hla_compatibility_score": 3}, {"donor_age_difference": 20}]])
je tu mensi problem, swagger uplne nepodporuje nested lists a tym padom padaju testy.. co s tym? mam proste urobit daku vynimku v testoch?

2022-08-25 09:01 UTC, kristinagalik commented on txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
> +    # 'scoring': fields.List(required=False, cls_or_instance=fields.Nested(ScoringJson), example=[[{"transplant_count": 1}], [{"hla_compatibility_score": 3}, {"donor_age_difference": 20}]])
https://github.com/mild-blue/swagger-unittest/issues/10 
je to blokovane tymto co sme sa bavili asi tyzden dozadu

2022-08-25 09:36 UTC, kristinagalik commented
works but blocked by https://github.com/mild-blue/swagger-unittest/issues/10

2022-09-09 13:48 UTC, kubantjan requested changes

2022-09-09 13:48 UTC, kubantjan commented on tests/web/test_optimizer_api.py
>                          "hla_compatibility_score": -1,
tady teda nakonec nema byt ten par s  -1 viz ten muj komentar.

2022-09-09 13:48 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +    scoring = [[{"hla_compatibility_score": 1}]]
tohle cislo je vaha toho score v tom danem score, pokud je taom jen hla_compatibility_score a nic jineho, tak je uplne jedno co to je, pokud je to pozitivni. Pokud bys tam dala neco zaporneho, najednou by to melo minimalizovat to score a ne maximalizovat. je to proste koeficient kterym to skore pronasobit.

2022-09-09 13:48 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +    # todo: I don't actually know what the number represents? this is a temporary scoring
odpovedel jsem snad k tomu todo

2022-09-09 13:48 UTC, kubantjan commented on txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
> +    # 'scoring': fields.List(required=False, cls_or_instance=fields.Nested(ScoringJson), example=[[{"transplant_count": 1}], [{"hla_compatibility_score": 3}, {"donor_age_difference": 20}]])
udelam ten fix.

2022-09-09 14:05 UTC, kubantjan commented
udelal jsem fix ve swagger tester https://github.com/mild-blue/swagger-unittest/pull/11 verze 0.3.5 uz je nasazena na pypi, melo by stacit jen zvednout verzi.

2022-09-11 11:15 UTC, kristinagalik commented on tests/web/test_optimizer_api.py
>                          "hla_compatibility_score": -1,
ah okay cize v compatibility graph ma byt len to co mi vyjde v txm ako normalne score ale davam do compatibility graph len tie co su actually compatible...

2022-09-12 12:42 UTC, kubantjan requested changes
pridal bych test, kde bude nejaky poradny output toho exportu a porovna se to jestli je to spravny, aby byl hezky videt ten example output (ted si myslim ze je to furt asi spatne, kdyz to vraci to skore -1?

2022-09-12 12:42 UTC, kubantjan commented on tests/web/test_optimizer_api.py
>                          "hla_compatibility_score": -1,
tady to HLA compatibility score -1 nedava smysl

2022-09-12 13:31 UTC, kubantjan commented on tests/web/test_optimizer_api.py
>                          "hla_compatibility_score": -1,
jop, -1 a -2 neni nromalni score, to je jen nejaky custom, co jsme si vymysleli pro nase ucely. to je ta vyhoda proc delame compatibility graph, ze jak je to ridky, neni potreba tam davat vsechny incompatible

2022-09-12 13:55 UTC, kristinagalik commented on tests/web/test_optimizer_api.py
>                          "hla_compatibility_score": -1,
jaj to je input, tak to je take ze "automaticky necompatibilne" ale dam to kludne prec, aj tak to nerobi rozdiel

2022-09-14 07:46 UTC, merged