Add functionality to optimizer module
mild-blue/txmatching pull request #976
Opened 2022-08-22 12:49 UTC by kristinagalik

Closes #962

2022-09-15 15:10 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +        max_number_of_matchings=1
toto chapem dobre ze to hcce len jeden solution hej

2022-09-15 15:22 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +def get_optimizer_configuration(config: ConfigParameters) -> OptimizerConfiguration:
este mensia otazka k exportu - ten compatibility graph mam brat aj z manualnych skore z konkretneho configu ci zatial mam brat normalne len to score co je vypocitane?

2022-09-15 17:40 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +def get_optimizer_configuration(config: ConfigParameters) -> OptimizerConfiguration:
Stačí to co je spočtený

2022-09-17 16:18 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +        number_of_found_cycles=len(cycles) + len(chains),
asi som sa uz pytala ale neviem to spatne dohladat ci si mi na ot aj odpovedal: ale tuto mam dat este jeden `Statistics` atribut separatne na number of found chains alebo mam radsej premenovat tento na `number_of_found_cycles_and_chains`?

2022-09-18 10:39 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +        number_of_found_cycles=len(cycles) + len(chains),
rename :)

2022-09-18 10:45 UTC, kubantjan requested changes
koment k testu,

v zasade vypada dobre. asi bych udelal ty tasky dalsi, ktery to jeste vic uklidi a tohle po tech mini fixes a tmu ze sem pridas ty dalsi issues zavrel :)

2022-09-18 10:45 UTC, kubantjan commented on tests/web/test_optimizer_api.py
> +        self.assertEqual(solutions[0].score, total_score)
mozna jeste testni, ze to naslo nejaky realny reseni, ze to neni jen nulovy vsechno. Jinak good

2022-09-21 09:11 UTC, kristinagalik commented
#990 
#994 
#995 

@kubantjan staci tak?

2022-09-21 09:49 UTC, kubantjan commented
@kristinagalik  predstav si, ze by ty tasky delal nekdo jiny nez ty, kyryl, nebo ondra, me prijde ze to neni dostatecny teda. A chtelo by to promyslet poradi v jakem je delat. Mozna prvni ten #995 ?

2022-09-21 09:49 UTC, kubantjan requested changes
viz komentar

2022-09-27 14:24 UTC, kubantjan approved these changes

2022-09-28 08:05 UTC, merged