Make AllSolutionsSolver handle correctly mutliple donors
mild-blue/txmatching pull request #979
Opened 2022-08-29 14:55 UTC by krllstdn

Closes #961

2022-09-06 14:58 UTC, kubantjan commented
@krllstdn  prosim doplnit test

2022-09-07 13:10 UTC, kubantjan requested changes

2022-09-07 13:10 UTC, kubantjan commented on tests/solvers/all_solutions_solver/test_all_solutions_solver.py
> +        txm_event = get_txm_event_complete(get_txm_event_db_id_by_name(GENERATED_TXM_EVENT_NAME))
tohle nepridava donory se stejnym recipientem! tohle jen pridava moznost, aby ti tri donori darovali v parovani stejnemu recipientovi, ale neznamena to ze jejich original donor je donor 1..

2022-09-09 14:41 UTC, kubantjan commented
![PXL_20220909_142725141.jpg](https://user-images.githubusercontent.com/24394374/189376181-485f60ca-247b-4260-8edb-644b61712f26.jpg)

2022-09-09 14:42 UTC, kubantjan requested changes
viz fotka tabule, jsem presvedcen ze pro ten pripad co tam je to nefunguje ted spravne.\

prvni napis prosim test, ktery to co tam je zreprodukuje a pak fixnout..

2022-09-13 09:34 UTC, krllstdn commented
Overil jsem tento pripad, vypada snad v pohode. AllSolutionSolveru neco podobneho jak na obrazku
![image](https://user-images.githubusercontent.com/50211831/189866883-1989b99f-d975-497d-b013-f7296910da3f.jpeg)

2022-09-13 10:48 UTC, krllstdn commented
@kubantjan

2022-09-14 12:11 UTC, kubantjan commented
Napis tento test

d1a -> r1
d1b -> r1
d2 -> r2

compatibilita:
d2 -> r1
d1a -> r2

spravne reseni
d2 -> r1 + d1a -> r2

ale ted to podle me nenajde nic.

zkus napsat takovej test (zas pomoci ty compatibility matrix)

pak ho fixni a pak by mel prestat prochazet ten test

2022-09-14 12:44 UTC, kubantjan requested changes
Viz komentar

2022-09-17 15:58 UTC, kristinagalik approved these changes

2022-09-19 06:30 UTC, kubantjan requested changes
no ale ted resis tedy jen tu prvni cast, ted jeste vyresit tu puvodni cast z te tabule

2022-09-19 06:30 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/score_matrix_utils.py
> +        donor_idx: [d_idx for d_idx, r_idx in donor_idx_to_recipient_idx.items() for recipient_idx in recipient_idxs
d_index a r_index idealne priejmenuj, nebal bych se delsich nazvu.

2022-09-27 18:50 UTC, krllstdn commented
@kubantjan @kristinagalik takze cekam na merge tech ostatnich PRs a pak budu schopen removnout pouziti compatibility matrix z tohoto PR

2022-09-28 07:52 UTC, kubantjan requested changes

2022-09-28 07:52 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/score_matrix_solver.py
> +    valid_cycles = []
tohle bych dal do zvlastni pomocny fce.

2022-10-07 08:09 UTC, kubantjan requested changes
je to ted spatne, to filtrovani cos tam pridal vubec nesmi byt.

2022-10-07 08:09 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/score_matrix_solver.py
> +    # remove pairs from donor_idx_to_recipient_idx
odsud by se urcite odebirat nemel. tady ma byt 2x tohle je prevodnik donoru na jejich recipienty..

2022-10-07 08:23 UTC, kubantjan commented on txmatching/solvers/all_solutions_solver/score_matrix_utils.py
> +    pairs = _get_pairs_from_paths(circuit_list, donor_idx_to_recipient_idx)
prave ze je nutne resit to co jsem rikal tzn ze tam neni hrana mezi tema dvema cykly se stejnym recipientem.

Pripadne si nad timto muzeme zavolat, to ze jsi to resil takto znamena, ze tam jeste je ti podle me neco dost nejasnyho, protoze, tohle fakt nedava smysl.

2022-10-12 17:06 UTC, kubantjan commented
Pravdepodobne vyreseno  v https://github.com/mild-blue/txmatching/pull/1026 muzeme zavrit asi. prosim o review tam..

2022-10-16 12:29 UTC, closed without merging