solving issue #590
mild-blue/txmatching pull request #982
Opened 2022-09-08 11:37 UTC by abragtim

Error responses v swaggeru jsou teď závislé na error handlers v error_handler.py.

2022-09-14 12:55 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Je zajímavý nápad vytahovat description z doc, ale nebylo by přehlednější přidat místo toho nový parametr do dekorátoru, který dokumentaci handler funkcí zároveň nahradil (viz kód níže)? Nebo vnímáte, že má Váš přístup nějakou výhodu?

```
@_namespace_error_response(code=500, description="Internal error.")
    def handle_invalid_auth_call_exception(error: InvalidAuthCallException):
        """Invalid auth call exception"""
```

2022-09-14 12:56 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        Namespace.ERROR_CODE_DESCRIPTION[code] = splitted_doc[1].strip() if len(splitted_doc) > 1 \
Nebylo by jistější vzít první neprázdný splitted_doc?

2022-09-14 12:57 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> -    def response_error_matching_not_found(self):
Jaký je důvod pro přesunutí těchto dekorátorů z `namespace.py` do `error_handler.py`?

2022-09-14 13:01 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +# noinspection PyProtectedMember
Pro code inspection používáme **Pylint**

2022-09-14 13:02 UTC, tomaspavlin requested changes
Napsal jsem Vám ke kódu několik technických připomínek. Co se týče splnění zadání úkolu, cílem bylo sjednotit logiku errorů tak, aby tam nebyly redundantní informace. Issue bylo popsáno velmi stručně a očkávali jsme, že se kdyžtak doptáte. Pěkně jste použil dokumentaci handlerů k tomu, abyste nastavil descriptions errorů ve swaggeru, avšak pořád tam je redundance v response codes a vůbec v tom, že je pro jeden error třeba definovat zvlášť jak handler, tak dekorátor pro swagger dokumentaci endpointu. Pokud potřebujete více upřesnit zadání nebo něco není jasné, rád případné otázky zodpovím. Prosím o zapracování.

2022-09-15 10:51 UTC, abragtim commented
> Napsal jsem Vám ke kódu několik technických připomínek. Co se týče splnění zadání úkolu, cílem bylo sjednotit logiku errorů tak, aby tam nebyly redundantní informace. Issue bylo popsáno velmi stručně a očkávali jsme, že se kdyžtak doptáte. Pěkně jste použil dokumentaci handlerů k tomu, abyste nastavil descriptions errorů ve swaggeru, avšak pořád tam je redundance v response codes a vůbec v tom, že je pro jeden error třeba definovat zvlášť jak handler, tak dekorátor pro swagger dokumentaci endpointu. Pokud potřebujete více upřesnit zadání nebo něco není jasné, rád případné otázky zodpovím. Prosím o zapracování.

@tomaspavlin , děkuji za připomínky, ale chtěl bych upřesnit zadání. 
Pro různé API jsou různé responses v dokumentaci a některé errory neodpovídají responses. Například OverridingException s kódem 406 není v dokumentaci pro žádné API. A když budeme muset označovat, který error je v dokumentaci pro určitý API, tak je to ekvivalentní k používání těch error responses v Namespace. Nebo lze udělat pro všechny API stejné responses v dokumentaci?

Zatím vidím možnost udělat obecný dekorátor, který nahradí všechny error responses dekorátory a budeme definovat jako argumenty, které kódy aktivovat pro určité API:
Tzn. místo toho:
`@service_api.response_ok(status, description='Returns ok if the service is healthy.')`
    `@service_api.response_error_unexpected()`
    `@service_api.response_error_services_failing()`
    `def get(self): ...`
bude vypadat nějak takhle
`@service_api.response_ok(status, description='Returns ok if the service is healthy.')`
`@service_api.response_errors(codes=[500, 503])`
`def get(self): ...`, 
kde self.response_errors dekorátor bude tvořit responses pro určité kódy, které naskenuje pomocí @_namespace_error_response dekorátoru v handle-funkcích.
Výhodou je, že při tvoření nového erroru, budeme muset jen definovat jej jako handle funkci, označit dekorátorem @_namespace_error_response, že chceme ten error použit jako response pro určitý kód a nemusíme tvořit novou self.response_error_... funkci v Namespace, jen označit pak dekorátorem, pro které API ten response je platný (jako v tom příkladu pro service_api)

Ale možná znovu nechápu, co je cílem. Nebo musím udělat, aby program sam chápal, které handlery jsou platné pro určité API (což ještě nevím jak udělat, ale možná to nějak půjde)? 

Předem moc děkuji za odpověď a přeji hezký den.

2022-09-15 14:11 UTC, tomaspavlin commented
@abragtim 
> děkuji za připomínky, ale chtěl bych upřesnit zadání. Pro různé API jsou různé responses v dokumentaci a některé errory neodpovídají responses. Například OverridingException s kódem 406 není v dokumentaci pro žádné API.

Ano, máte pravdu, to se děje a není ve scope tohoto issue to opravit. Pokud se ale zlepší díky tomuto issue návrh, mohlo by být snažší podobné případy později najít a upravit dokumentaci.

> A když budeme muset označovat, který error je v dokumentaci pro určitý API, tak je to ekvivalentní k používání těch error responses v Namespace. Nebo lze udělat pro všechny API stejné responses v dokumentaci?

Chceme dále označovat errory v dokumentaci. Teď to ale není úplně pohodlné, když to chci dekorovat, musím jako vývojář:

1. podívat se které exceptions se v kódu endpointu vyhazují (pokud bychom neměli nějakou super automatizaci, tak se tomuhle asi nevyhneme)
2. najít pro error odpovídající handler, případně ho vytvořit
3. pro handler najít odpovídající response dekorátor (zřejmě podle code nebo podle sémanticky podle názvu), případně ho vytvořit (tak, že zkopíruji code a description) z handleru.
4. dekorovat endpoint

Je to docela dost kroků a při velkém množství endpointů se v tom udělá chyba. Kroků 1 a 4 se asi jentak nezbavíme, ale kroky 2 a 3 by v lepším návrhu se měly dát zjednodušit nebo je úplně vynechat. 

> Zatím vidím možnost udělat obecný dekorátor, který nahradí všechny error responses dekorátory a budeme definovat jako argumenty, které kódy aktivovat pro určité API: Tzn. místo toho: `@service_api.response_ok(status, description='Returns ok if the service is healthy.')` `@service_api.response_error_unexpected()` `@service_api.response_error_services_failing()` `def get(self): ...` bude vypadat nějak takhle `@service_api.response_ok(status, description='Returns ok if the service is healthy.')` `@service_api.response_errors(codes=[500, 503])` `def get(self): ...`, kde self.response_errors dekorátor bude tvořit responses pro určité kódy, které naskenuje pomocí @_namespace_error_response dekorátoru v handle-funkcích. Výhodou je, že při tvoření nového erroru, budeme muset jen definovat jej jako handle funkci, označit dekorátorem @_namespace_error_response, že chceme ten error použit jako response pro určitý kód a nemusíme tvořit novou self.response_error_... funkci v Namespace, jen označit pak dekorátorem, pro které API ten response je platný (jako v tom příkladu pro service_api)

Tohle zní jako cesta dobrým směrem. Nešlo by v `@service_api.response_errors(codes=[500, 503])` mapovat přes něco jiného než codes? Bez znalosti kontextu (třeba v code review) v seznamu integerů najdu těžko chybu.

> Ale možná znovu nechápu, co je cílem. Nebo musím udělat, aby program sam chápal, které handlery jsou platné pro určité API (což ještě nevím jak udělat, ale možná to nějak půjde)?

Tohle by bylo cool, ale bylo by to dost netriviální a není potřeba.

> Předem moc děkuji za odpověď a přeji hezký den.

Je to teď jasnější?

2022-09-16 23:51 UTC, abragtim commented on txmatching/web/error_handler.py
> +        """
Přemýšlel jsem, že by v takovém případě nebylo nutným psat description zvlášť, byla v doc, alespoň v jeho prvním neprázdném řádku. 
Ale určitě máte pravdu, že napsat description v dekorátoru není tak těžké, když už i píšeme tam kód + v takovém případě jsou víc prostoru pro tvoření response.

2022-09-19 16:02 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +    responses = {NotImplementedError: (f'This response is not implemented by error-handler. '
Proč tu vlastně musíš mít NotImplementedError? Neobešel by ses bez něj s tím, že bys případ, že exception nenastavíš, nějak hadloval v response_errors()?

2022-09-19 16:06 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +    __ERROR_INFO: Dict[type, Tuple[str, int]] = generate_namespace_error_info()
trošku se ztrácím v tom indexování tuplů. Co místo toho použít named tuple https://docs.python.org/3/library/collections.html#collections.namedtuple ?

2022-09-19 16:07 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +        for exception, ex_idx in zip(exceptions, range(len(exceptions))):
`for ex_idx, exception in enumerate(exceptions):`

2022-09-19 16:08 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +                exception = NotImplementedError
Nechceme tady spíš hned vyraisovat error? Pak by se asi vůbec nemusel používat NotImplementedError

2022-09-19 16:10 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +        if len(duplicates) > 1:
Tuhle podmínku tu nemusíš mít a bude ti to pak vracet pro neduplikát description

2022-09-19 16:11 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +            description = combined_description if combined_description else \
Když v `_create_combined_description_for_duplicates` nebudeš mít podmínku `if len(duplicates) > 1:` viz comment, tohle tu nebudeš muset mít

2022-09-19 16:13 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +                      error in exceptions[exception_idx:] and
Proč vlastně `exceptions` potřebuješ řadit podle code a indexuješ tu od `exception_idx` a ne od `0`?

2022-09-19 16:16 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +    def _create_combined_description_for_duplicates(cls, exceptions: List[type], exception_idx: int) -> str:
Jestli to chápu dobře, tady handluješ případ, že v `response_errors` uvedu dvě různé exceptions se stejným code? Děje se to někde?

Nebylo  by v takovém případě více safe vyhodit vysvětlující error, a vyřešit to (třeba změnou codes)?

2022-09-19 16:17 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +    def response_errors(self, exceptions: List[type]):
Co použít Set `exceptions: Set[type]`?

2022-09-19 16:22 UTC, tomaspavlin commented on txmatching/web/api/optimizer_api.py
> +                                               InvalidAuthCallException])
Vidím, že se skoro ve všech endpointech opakují tyhle 4 errory. Nešlo by to udělat nějak lépe?

2022-09-19 16:24 UTC, tomaspavlin requested changes
Pěkné, tohle už zadání dost odpovídá. Ještě jsem napsal komentáře.

2022-09-20 10:17 UTC, abragtim commented on txmatching/web/swagger/swagger_public.json
> +                        "description": "Service(s) is unavailable.",
Původně bylo vlastně dvě responses, které byly se stejným kódem response_error_services_failing(self) a response_error_sms_gate(self). Správně chápu z errorů, že response_error_servise_failing je pro případ error CouldNotSendOtpUsingSmsServiceException taky? Protože když změním jen hlášku, tak bude platná i pro services_failing. Je to v pořádku nebo servise_failing je pro handlování jiné chyby?

2022-09-20 10:29 UTC, abragtim commented on txmatching/web/web_utils/namespace.py
> +    def _create_combined_description_for_duplicates(cls, exceptions: List[type], exception_idx: int) -> str:
To se v kódu ještě neděje, ale taková situace by mohla nastát při handlování nových chyb, které mají stejný response code. 
Pokud dál v projektu nebudou handlovány různé responses se stejným response code, tak opravdu můžeme klidně smazat s combined description.
Pokud tohle chceme nechat pro budoucnost, ale to může způsobit nečekané problémy, tak vidím možnost udělat v dekorátoru namespace_error_response ještě volitelný bool argument duplites duplicates_allowed, který jako default bude False a když budeme chtít povolit duplicitu pro description s jiným errorem, tak bude možné to nechat na True.
Jak by bylo lepší?

2022-09-20 22:27 UTC, abragtim commented on txmatching/web/web_utils/namespace.py
> +                      error in exceptions[exception_idx:] and
Řadím exceptions jen kvůli přehlednosti. Orientuje se líp ve swagger.json při velkém počtu responses, když jsou seřazené podle code. Je to zbytečné? Měl bych to řazení odstranit pro zachování výkonnosti?

2022-09-20 22:29 UTC, abragtim commented on txmatching/web/web_utils/namespace.py
> +                      error in exceptions[exception_idx:] and
A indexoval jsem od exception_idx, protože jsem uviděl, že když jsou dvě různé responses se stejným code, tak se zapíše do swaggeru jen první vytvořeny response, tzn. nemá smysl hledat doplňkové descriptions z errorů, pro které už byl vytvořen response (protože aktuální error už je v combined description pro jiný error se stejným code). 
Ale teď uvažuju, že to není stabilní a snadno se může změnit v jiné verzi flask-restx. 
Napravil jsem to.

2022-09-21 13:22 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +_HANDLERS_CODE_DESCRIPTION = {}  # information about handler function: (description, code)
Pravda, to jsem si neuvědomil. V tom případě to můžete nechat jak to je. Případně se mrkněte do `txmatching/web/__init__.py - fce configure_apis`, kde se api inicializuje a je tam vidět souvislost mezi api a namespace. Ale nechávám to jako volitelné.

2022-09-21 13:59 UTC, tomaspavlin commented on txmatching/web/swagger/swagger_public.json
> +                        "description": "Service(s) is unavailable.",
Když se kouknu do txmatching/web/api/service_api.py, kde se pro `GET /status` endpoint využívalo `response_error_services_failing`, tak tam nejde o to, že failuje sms gate, ale že failuje připojení do db, tedy jde o jinou chybu.

Zvládl byste to vyřešit, aby se na tomto místě 503 dokumentovalo s hláškou "Service(s) is unavailable." (příp. rovnou "Database service is unavailable.") a na ostatních místech s hláškou "It was not possible to reach the SMS gate, thus the one time password could not be send."?

2022-09-21 14:06 UTC, tomaspavlin commented on txmatching/web/web_utils/namespace.py
> +    def _create_combined_description_for_duplicates(cls, exceptions: List[type], exception_idx: int) -> str:
Díky za odpověď. Nápad s duplicates_allowed zní dobře.

2022-09-22 12:02 UTC, abragtim commented
Zamyslím si ještě nad tou volitelnou části s přesunutí dekorátoru namespace_error_response z error_handler.py do namespace.py, ale nechci zdržovat celý ten PR. Když na to přijdu, tak udělám nový.

2022-09-22 20:33 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description

2022-09-22 20:33 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description. Případně upravit description.

2022-09-22 20:34 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description

2022-09-22 20:35 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description

2022-09-22 20:35 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description. Příp. upravit description

2022-09-22 20:35 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description

2022-09-22 20:36 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description

2022-09-22 20:36 UTC, tomaspavlin commented on txmatching/web/error_handler.py
> +        """
Dokumentace tu být nemusí, když je definován ten description

2022-09-22 20:38 UTC, tomaspavlin commented on txmatching/web/swagger/swagger.json
> +                        "description": "Database service is unavailable.",
Super

2022-09-22 20:42 UTC, tomaspavlin requested changes
Už jen drobnosti

2022-09-23 13:57 UTC, tomaspavlin approved these changes
Super!

2022-09-23 15:26 UTC, merged