Improve documentation
mild-blue/txmatching pull request #984
Opened 2022-09-09 13:19 UTC by kubantjan

Closes #983

2022-09-09 13:45 UTC, krllstdn commented on documentation/README.md
> +Antibodies of a patient are found by a special lab test. This tests does not find the antibodies directly but tests which antigens (from a limited set) the patient has the antibodies against. The lab
typo: this test**s**

2022-09-09 13:50 UTC, krllstdn commented on documentation/README.md
> +Antibodies of a patient are found by a special lab test. This tests does not find the antibodies directly but tests which antigens (from a limited set) the patient has the antibodies against. The lab
probably typo: "The lab test**s** can differ..."

2022-09-09 13:55 UTC, krllstdn commented on documentation/README.md
> +For each antigen the test reports MFI value and the higher the MFI value is the stronger was the immunological response. The lab then uses some cutoff value to distinguish which antibodies the patien
I am not sure if the reader knows what MFI is, but it might be obvious from the context. Maybe it is reasonable to define it somewhere?

2022-09-09 19:23 UTC, kristinagalik requested changes

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +Antibodies of a patient are found by a special lab test. This test does not find the antibodies directly but tests which antigens (from a limited set) the patient has the antibodies against. The lab
"The lab test can differ from lab to lab, each can use a bit different set of antibodies in the test." 
neni to skor
"The lab test can differ from lab to lab, each can use a bit different set of antigens in the test."
? 
tym ze (ak to spravne chapem) sa zoberu dake antigeny a pyta sa ze "na ktore z tohto ma pacient antibodies?"

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +For each antigen the test reports MFI value and the higher the MFI value is the stronger was the immunological response. The lab then uses some cutoff value to distinguish which antibodies the patien
it is defined at the bottom.. which maybe leads to duplicate information? 

moreover i thought that it tests for effectiveness rather than whether the antibody exists or not
"The lab then uses some cutoff value to distinguish which antibodies the patient has and which not. " -> 
"The lab then uses some cutoff value to distinguish which antibodies of he patient are effective/strong enough/idk and which not. "

viem ze neskor to definujes inak ale nejak sa mi to asi nepaci/nerozumiem tomu hlavne ak sa da ten cutoff menit. a aj lebo ten antibody tam je ale je proste len slaby.

tak toto je mozno take ze len otazka do plena

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +### Processing logic of type A
different heading type than on line 97

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +The parsing is done in two modes. In case we receive about the patient all antibodies, positive and negative in high resolution we use processing logic of type A. This is the better, more precise cas
missing dot at the end of the sentence

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +The parsing is done in two modes. In case we receive about the patient all antibodies, positive and negative in high resolution we use processing logic of type A. This is the better, more precise cas
also
"In case we receive about the patient all antibodies," -> "In case we receive all antibodies of the patient"

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +2. donor antigen is in high resolution and recipient is type A parsed and was not tested for donors antigen. But all antibodies that match donors antigen in split resolution are positive (and there i
missing dot at the end of the sentence

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +3. donor antigen is in low resolution and recipient is type A parsed and all antibodies that match donors antigen in low resolution are positive (and there is at least one such antibody).
tu ma trosku skrie ze sa hovori "low resolution" ale neni to napr spomenute v nomenclature ako vyraz. ze ludi ktori netusia, tak mozno nie hned vedia ako spada do toho rozdelenia broad, split, high res zrazu low res

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +Example: donor has antigen DQ8 and recipient has antibody DRB1\*08:01 or donor has antigen DQ8 and recipient has antibody DQ8
missing dot, "Example" -> "Example for case 1."

2022-09-09 19:23 UTC, kristinagalik commented on documentation/README.md
> +Example: donor has antigen DQ8 and recipient has antibody DRB1\*08:01 or donor has antigen DQ8 and recipient has antibody DQ8
resp aj v 1. a 2. su, neviem ci aj taketo veci sme mali komentovat

2022-09-12 09:15 UTC, krllstdn commented on documentation/README.md
> +For each antigen the test reports MFI value and the higher the MFI value is the stronger was the immunological response. The lab then uses some cutoff value to distinguish which antibodies the patien
yes, I see it. then I'll make a link to where this is defined

2022-09-12 09:51 UTC, krllstdn commented on documentation/README.md
> +In this case we assume we have received ALL antibodies in high resolution the antibody test was done for, with MFI values and required cutoff (the cutoff is sometimes then changed later in case it is
maybe `"... it is found useful" -> "... it is found reasonable"` ?

2022-09-12 10:20 UTC, kubantjan commented on documentation/README.md
> +In this case we assume we have received ALL antibodies in high resolution the antibody test was done for, with MFI values and required cutoff (the cutoff is sometimes then changed later in case it is
I have updated the description

2022-09-12 10:21 UTC, kubantjan commented on documentation/README.md
> +Example: donor has antigen DQ8 and recipient has antibody DRB1\*08:01 or donor has antigen DQ8 and recipient has antibody DQ8
updated

2022-09-12 10:21 UTC, kubantjan commented on documentation/README.md
> +Example: donor has antigen DQ8 and recipient has antibody DRB1\*08:01 or donor has antigen DQ8 and recipient has antibody DQ8
mrkni jestli je to ted srozumitelny

2022-09-12 10:22 UTC, kubantjan commented on documentation/README.md
> +3. donor antigen is in low resolution and recipient is type A parsed and all antibodies that match donors antigen in low resolution are positive (and there is at least one such antibody).
prepsano

2022-09-12 10:30 UTC, kubantjan commented on documentation/README.md
> +The parsing is done in two modes. In case we receive about the patient all antibodies, positive and negative in high resolution we use processing logic of type A. This is the better, more precise cas
updated

2022-09-12 10:34 UTC, kristinagalik commented on documentation/README.md
> +Example: donor has antigen DQ8 and recipient has antibody DRB1\*08:01 or donor has antigen DQ8 and recipient has antibody DQ8
este mam cakat na update hej

2022-09-12 10:40 UTC, kristinagalik reviewed
za mna len mala vizualna vec :)

2022-09-12 10:40 UTC, kristinagalik commented on documentation/README.md
> +### Processing logic of type A
tu som myslela aj pocet # 
![image](https://user-images.githubusercontent.com/56656359/189633357-321c6da0-f277-4ce4-af97-7ef332b6328a.png)

2022-09-12 12:39 UTC, krllstdn submitted a review, later dismissed

2022-09-12 12:40 UTC, kristinagalik submitted a review, later dismissed

2022-09-13 10:45 UTC, kubantjan commented on documentation/README.md
> +In this case, we assume we have received all tested antibodies in high resolution with MFI values and the required cutoff (The cutoff is configurable. In some cases the user can decide to change it f
good point upravim

2022-09-13 10:51 UTC, kubantjan commented on documentation/README.md
> +In this case, we assume we have received all tested antibodies in high resolution with MFI values and the required cutoff (The cutoff is configurable. In some cases the user can decide to change it f
mrkni, jak se ti to zda.

2022-09-13 10:56 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
bod 2. se resi:
https://github.com/mild-blue/txmatching/blob/6dd3b4698f693455e2e37f04353520b3d24f9e1c/txmatching/utils/hla_system/hla_crossmatch.py#L78-L85

2022-09-13 10:57 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
A taky vlastne tady (tzn tam ted chybelo pridat i slovicko split, to pridam):

https://github.com/mild-blue/txmatching/blob/6dd3b4698f693455e2e37f04353520b3d24f9e1c/txmatching/utils/hla_system/hla_crossmatch.py#L110-L116

2022-09-13 11:12 UTC, kubantjan commented on documentation/README.md
> +#### HIGH_RES_WITH_SPLIT
Type A ted v kodu explicitne nemame, takze nejaky casy skutecne ted proklouznou.

tzn ten test co rikas if set(matching_antibodies) == set(antibodies_with_high_res): dava smysl Obecne asi budeme chtit v kodu to explicitneji rozdelit na ty dva casy. 

ta druha cast otazky mi neni uplne jasna. Trosku jsem upravil ten text. a pridal example. mrkni

2022-09-13 11:16 UTC, kubantjan commented on documentation/README.md
> +Donor antigen is in broad resolution and the recipient is type A parsed. Some antibodies that match donors' antigen in broad resolution are positive and some are negative.
vylepsil jsem text kolem podminky, rekni jestli ted jasne.

2022-09-13 12:07 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
**Otazka 1**

ano kontrola tam dobre neni, jak rikas.

2022-09-13 12:10 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
**Otazka 2**

no tim ignored myslim, ze nejsou ty negativni pro split a broad zahozeny rovnou ale k nicemu se realne uvnitr v tom algoritmu ty negativni nepouzijou

2022-09-14 07:20 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
@jogobeny  dal jsem tam v bode dve spatnej link na radky, sry. Viz EDITEd. mrkni, jestli je to ted srozumitelnejsi.

2022-09-14 07:21 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
ted kod co tam mas ted je podle me spatne, rekneme si na standupu

2022-09-14 13:02 UTC, kubantjan commented on documentation/README.md
> +2. donor antigen is in high resolution and the recipient is type A parsed and was not tested for donor's antigen. But all tested antibodies that match the donor's antigen in split resolution are posi
no ted kod je fakt zmatenej, tohle si nemyslim ze tohle je dobrej pristup, me zabere desne casu se v tom kodu vyznat, a tim spis ze je zprasenej. To neni efektivne stravenej cas.

Pripada mi to ramcove ok.

2022-09-14 13:32 UTC, kubantjan commented on documentation/README.md
> +- Positive antibody of a patient: antibody of the patient was in a lab test over cutoff.
jop, makes sense, upresnime ty nerovnosti

2022-09-14 23:02 UTC, kubantjan commented on documentation/README.md
> +Type A requires that all antibodies are in high resolution and having all tested antibodies of a patient. We assume that if the criteria below are fullfiled this holds.
vzdy hned tady pod tim mas tri body, ktery jsou ty kriteria. Co na nich neni pochopitelny?
- All antibodies we receive are in high resolution.
- There is at least 20 antibodies provided.
- There is at least 1 antibody below cutoff.

2022-09-19 12:49 UTC, NguyenAdela reviewed
Just few little remarks (recommendations).

2022-09-20 14:58 UTC, kubantjan commented on documentation/README.md
>  Finally, we also specify high resolution, which is the most specific, specifying also things like specific HLA protein,
:D mas pravdu to je docela desna veta

2022-09-20 14:58 UTC, kubantjan commented on documentation/README.md
>  Finally, we also specify high resolution, which is the most specific, specifying also things like specific HLA protein,
```suggestion
Last resolution type is high resolution. It defines specific HLA protein,
```

2022-09-20 15:06 UTC, kubantjan commented on documentation/README.md
> +In the case of split or broad resolution, we do not assume that. We assume that as there are less split antigens that the patient has been tested for all relevant ones. And therefore for the algorith
```suggestion
Some crossmatch levels or ways to find a crossmatch are meaningful only in the case of processing logic of type A, because with type B we have less information. 
```

2022-09-20 15:06 UTC, kubantjan commented on documentation/README.md
> +   4. Some antibodies that match donors' antigens in split resolution are positive and some are negative.
ne, ma tam byt apostrof pred s

2022-09-20 15:06 UTC, kubantjan commented on documentation/README.md
> +   3. Donors antigen is not in the set of all tested antibodies.
```suggestion
   3. Donor's antigen is not in the set of all tested antibodies.
```

2022-09-21 11:12 UTC, NguyenAdela approved these changes

2022-09-27 14:23 UTC, merged