Fix eslint errors
mild-blue/txmatching pull request #989
Opened 2022-09-13 21:34 UTC by kristinagalik

2022-09-13 22:10 UTC, kristinagalik commented
@NotLubo

zmena z flag na app-flag robi toto (squashne to flags k menam pacientov):
![image](https://user-images.githubusercontent.com/56656359/190018247-00a51227-4a19-4d16-942d-d56f571a2dc2.png)

a asi nerozumiem uplne ze v com je problem? ked som premenuvavala country a patient componenty tak sa nic pofiderne nedialo

2022-09-14 07:28 UTC, NotLubo commented
`patient.component.scss`, `country.component.scss`, `matching-item.component.scss` používajú `flag` selector

2022-09-14 07:35 UTC, NotLubo requested changes

2022-09-14 07:35 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/score-indicator/score-indicator.component.html
> +    matTooltip="Score: {{ score !== null ? score : '-' }}/{{ maxScore ? maxScore : '-' }}"
Teď tady nedochází k `type coercion` (tady je výnimočne žádaná) takže jestli se score někde nastaví na undefined tak to neprojde. Takže bych to opravil na `score ?? '-'`.
`maxScore` mužeš taky.

2022-09-14 07:35 UTC, NotLubo commented on txmatching/web/frontend/src/app/components/score-indicator/score-indicator.component.html
> +    {{ score !== null ? score : "-" }}
to samé

2022-09-15 15:43 UTC, NotLubo approved these changes

2022-09-18 10:37 UTC, merged