Dont use score matrix, just compatibility graph
mild-blue/txmatching pull request #996
Opened 2022-09-21 13:05 UTC by kristinagalik

Closes #995

2022-09-27 10:16 UTC, kristinagalik commented on txmatching/database/db_migrations/0034.add-comp-graph-to-pairing-result.sql
> +ALTER TABLE pairing_result ADD COLUMN compatibility_graph JSONB NOT NULL;
toto je problem lebo stare pairing_results ktore uz existuju budu kricat ze tam neni `compatibility_graph`, ale neviem ako to vyriesit. podla mna by to totiz malo byt `NOT NULL`

2022-09-27 10:16 UTC, kristinagalik commented on txmatching/database/db_migrations/0034.add-comp-graph-to-pairing-result.sql
> +ALTER TABLE pairing_result ADD COLUMN compatibility_graph JSONB NOT NULL;
@kubantjan

2022-09-27 10:16 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
@kubantjan

2022-09-27 14:25 UTC, kubantjan commented on txmatching/database/db_migrations/0034.add-comp-graph-to-pairing-result.sql
> +ALTER TABLE pairing_result ADD COLUMN compatibility_graph JSONB NOT NULL;
holt zahodime ty stary vysledky, to se neda svitit.

2022-09-27 14:25 UTC, kubantjan commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
jestli se to uz nikde nepouziva tak muzes mazat :)

2022-09-27 14:30 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
pouziva sa to v tomto file v `_create_graph` na retrievovanie scores co sa potom dava do weights pre arc, ale tym ze to je jedine miesto kde sa to puziva (a aj predtym pouzivalo) nijak sa to nebije s logikou vo zvysku kodu... mozem to prepisat na comp_graph len v tomto pripade si nejak neuvedomujem asi vyhody toho (tym ze sa to nikde neuklada ani nikde neposiela)

2022-09-27 15:19 UTC, kubantjan requested changes
Par komentu, muzes rovnou na ne mrknout ale urcite me pak jeste napadne neco. Ale asi mi dava smysl aby ses ted mrkla na tyhle a ja pak zas dodam dalsi

2022-09-27 15:19 UTC, kubantjan commented on txmatching/database/services/scorer_service.py
> +    compatibility_graph_dto: List[List[float]]
compatibility graph uz neni list list float ne

2022-09-29 14:15 UTC, kubantjan commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
vyhody ceho?

2022-09-29 14:20 UTC, kubantjan commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
no cely ten kod ted muzes dropnout ne? Protoze muzes pouzit primo compatibility graph? Ten uz stejne mas k dispozici.

2022-09-30 11:37 UTC, kristinagalik commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
noo tusim nie lebo vsade inde bol score_matrix donor_enum -> recipient_enum, a tento score_matrix je donor_enum -> donor_enum. co tiez je take ze mozem to prepisat na comp_graph[(donor_enum, donor2_eum), int] ale pride mi to zbytocne ked toto je jedine miesto

2022-09-30 13:30 UTC, kubantjan requested changes

2022-09-30 13:30 UTC, kubantjan commented on txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
>      def _get_donor_score_matrix(config_parameters: ConfigParameters,
udelej sem todocko teda, dava mi to smysl taky predelat na dict[donor_id, donor_id] -> score, ale je pravda, ze to neni must have ted.

2022-09-30 15:15 UTC, kubantjan requested changes

2022-09-30 15:15 UTC, kubantjan commented on txmatching/scorers/additive_scorer.py
> +    def get_score_dict(self, recipients_dict: Dict[RecipientDbId, Recipient], donors_dict: Dict[DonorDbId, Donor],
tomuhle nerozumim, neni score_dict a compatibility graph to same?

2022-09-30 15:15 UTC, kubantjan commented on txmatching/scorers/additive_scorer.py
> +    def get_score_dict(self, recipients_dict: Dict[RecipientDbId, Recipient], donors_dict: Dict[DonorDbId, Donor],
a pokud ne tak to bude fajn nejak jasneji odlisit a vysvetlit
mozna ze je to vlastne comp graph akorat tam jsou idcka co jsou v databazi jako klice?

2022-09-30 15:55 UTC, kubantjan commented
@kristinagalik  fajn, nn, assignul jsem ti jinou vec + jeste nejaky komenty jsem ti tady napsal

2022-10-01 15:38 UTC, kristinagalik commented on txmatching/scorers/additive_scorer.py
> +    def get_score_dict(self, recipients_dict: Dict[RecipientDbId, Recipient], donors_dict: Dict[DonorDbId, Donor],
hej tam je ten rozdiel toho ze to uz niesu enumy ale idcka.. tak premenujem

2022-10-05 12:45 UTC, kubantjan requested changes

2022-10-05 12:45 UTC, kubantjan commented on txmatching/database/db_migrations/0034.add-comp-graph-to-pairing-result.sql
> +ALTER TABLE pairing_result ADD COLUMN compatibility_graph JSONB NOT NULL;
takhle to cely spadne, protoze to nebude vedet jaky compatibility graph tam doplnit, je potreba dropnout cely obsah ty tabulky. (coz je ok, proste historicky vypocty bude potreba znovu prepocitat)

2022-10-06 07:57 UTC, kubantjan requested changes

2022-10-06 07:57 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +def get_compatibility_graph_to_return(donors_dict: Dict[DonorDbId, Donor],
co znamena to return? proc to tady nevraci objekt compatibility graph a jinde jo, tohle by chtelo nejak lip pojmenovat..

2022-10-06 14:08 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +def get_compatibility_graph_to_return(donors_dict: Dict[DonorDbId, Donor],
`CompatibilityGraph = Dict[Tuple[int, int], int]` <- toto je compatibility graph v txmatchingu ako takom
`compatibility_graph: List[Dict[str, int]]` <- toto je v optimizer module, plus sa to este bude menit na kristofovu verziu typu:
```
    compatibility_graph: List[CompatibilityGraphEntry]
    
    dataclass CompatibilityGraphEntry:
        recipient_id: int
        donor_id: int
        weights: Dict[str, int]

```

2022-10-07 06:25 UTC, kubantjan commented on txmatching/optimizer/optimizer_functions.py
> +def get_compatibility_graph_to_return(donors_dict: Dict[DonorDbId, Donor],
OK, ale ten kristofuv uz je extremen blizky tomu co mame v txmatchingu jako takom ne?
u nas akorat ten posledni int musime rozpadnout na Dict[str, int] ale zatim pozadovat ze ten dict musi obsahovat jen jednu polozku :). 

Tak takto bych to jeste v ramci tohoto PR mozna upravi, aby ty compatibility graph objekty byly v zasade totozny? 
Dict[Tuple[int, int], int]

2022-10-07 09:43 UTC, kubantjan requested changes
jen to nove issue, doplneni todos a tot vse

2022-10-10 10:01 UTC, kristinagalik commented on txmatching/optimizer/optimizer_functions.py
> +def get_compatibility_graph_to_return(donors_dict: Dict[DonorDbId, Donor],
https://github.com/mild-blue/txmatching/issues/998 done

2022-10-11 09:50 UTC, kubantjan approved these changes

2022-10-11 10:13 UTC, merged